graph [
  node [
    id 0
    label "GGTGGGATCCCACCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 1
    label "GGCAGATATCTGCCCCCGTGGGGCGGATCCGTGTAGGCCTAC"
  ]
  node [
    id 2
    label "GGGTCGATCGGCCCCCCGTGGGGCGGATCCGCGCTAGCTAGC"
  ]
  node [
    id 3
    label "GGAGGGGCCCCTCCCCC--GGGTCAGATCTGAGAAGGCCTTC"
  ]
  node [
    id 4
    label "GGGGGGATCCCCCCCCC--GGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 5
    label "GTCTTG--CAGGACGCGCGCGCTTTGGCCGGAGGTGGCCACC"
  ]
  node [
    id 6
    label "GGGTCGGCCGGCCCCCCGTGGGGCGGATCCGCGCTAGCTAGC"
  ]
  node [
    id 7
    label "GGAGGGGCTCCTCCCCC--GGGGCAGATCTGTGCTGGCCAGC"
  ]
  node [
    id 8
    label "GGTGGGATCCCACCCCC--GGGGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 9
    label "GGGGGG--CCCCCCCCC--GGGGCGGATCCGCGTAGGCCTAC"
  ]
  node [
    id 10
    label "GGGGGAGCTCCCCCGCG--CGCACGGTACCGTGGTGGCCACT"
  ]
  node [
    id 11
    label "GGCGGGTACCCGCCCCCGTGGGGCGGATCCGTAGAGGCCTCT"
  ]
  node [
    id 12
    label "GGCAGG--CCTGCCCCCGTGGGGCGGATCCGTGCAGGCCTGC"
  ]
  node [
    id 13
    label "GGGCAAGCTTGCCCCCA--TGGGCAGATCTGCGGTGGCCATC"
  ]
  node [
    id 14
    label "GGGGAGATCTCCCCCCC--GGGGCTGATCAGTGGTGGCCACC"
  ]
  node [
    id 15
    label "GGAGGAGCTCCTCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 16
    label "GGAGGGGCCCCTCCTCC--GGAGCAGATCTGTGTAGGCCTAC"
  ]
  node [
    id 17
    label "GGGTAGGCCTGCCCGCCGTGGCGCAGATCTGCGGGGGCCCTC"
  ]
  node [
    id 18
    label "GGCAGGTACCTGCCCCC--GGGACGGTACCGTGATGGCCATC"
  ]
  node [
    id 19
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 20
    label "GAGTTG--TGACTCGCC--GGCATGGATCCATGCAGGCCTGC"
  ]
  node [
    id 21
    label "GGGTCGGCCGGCCCCCG--CGGGCGGTATCGCGCAGGCCTGC"
  ]
  node [
    id 22
    label "GGATGGATCCATCCCCC--GGGGCAGATCTGTGGTGGCCACC"
  ]
  node [
    id 23
    label "GGAGGGGCCCCTCCCCC--GGGACAGATCTGTGGAGGCCTCC"
  ]
  node [
    id 24
    label "CCCGGCTAGCCGGGGCTCGAGCGCGGATCCGCGCCGGCCGGC"
  ]
  node [
    id 25
    label "TCCTAG--CTGGGAGCT--AGCTCTGCGCAGGCTAGGCCTGG"
  ]
  node [
    id 26
    label "GGGAAGATCTTCCCCTC--GAGGCAGATCTGCGCAGGCCTGC"
  ]
  node [
    id 27
    label "GGGGGAATTCCCCCCCA--TGGACGGATCCGTACAGGCCTGT"
  ]
  node [
    id 28
    label "GGAAGGGTCCTTCCGCG--CGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 29
    label "GGCAGGTACCTGCCCCC--GGGGCGGATCCGTGTAGGCCTAC"
  ]
  node [
    id 30
    label "GGACAGGCCTGTCCGCC--GGCGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 31
    label "GGGAGTGCGCTCCCCCC--GGGACGGGCCCGTCAAGGCCTTG"
  ]
  node [
    id 32
    label "GGAGGAATTCCTCCCCC--GGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 33
    label "GGGGAGATCTCCCCCTC--GAGACAGATCTGTGCAGGCCTGC"
  ]
  node [
    id 34
    label "GGAGAGGCCTCTCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 35
    label "GGCAGGTACCTGCCGCA--TGCTCTGATCAGAGGGGGCCCTC"
  ]
  node [
    id 36
    label "GGAGGAGCTCCTCCGCG--CGCGCGGATCCGTAAAGGCCTTT"
  ]
  node [
    id 37
    label "GGGGAGATCTCCCCCTC--GAGGCAGATCTGCACAGGCCTGT"
  ]
  node [
    id 38
    label "GGGTCGATCGGCCCCCCGTGGGACGGATTCGTGCTGGCCAGC"
  ]
  node [
    id 39
    label "GGAGGGATCCCTTCGCG--CGCGCAGTACTGTGGTGGCCACC"
  ]
  node [
    id 40
    label "GGAGAGGCCTCTCCCCC--GGGGCAGATCTGTGCAGGCCTGC"
  ]
  node [
    id 41
    label "GGCAGGTACCTGCCCCCGTGGGGCGGTACCGTGTTGGCCAAC"
  ]
  node [
    id 42
    label "GGTGAGATCTCACCCTC--GAGGCAGATCTGCCGTGGCCACG"
  ]
  node [
    id 43
    label "GGGGGTGCGCCCCCGCA--TGCAGGGATCCCTGCTGGCCAGC"
  ]
  node [
    id 44
    label "GGTGAGGCCTCACCCCC--GGGGCGGATCCGCGAAGGCCTTC"
  ]
  node [
    id 45
    label "GGCAGGTACCTGCCCCCGTGGGGCGGATCCGTCAAGGCCTTG"
  ]
  node [
    id 46
    label "GGAGGAGCTCCTCCGCC--GGCACAGATCTGTGTAGGCCTAC"
  ]
  node [
    id 47
    label "GGGGGTGCGCCCCCGCA--TGCTCGGATCCGAGTTGGCCAGC"
  ]
  node [
    id 48
    label "GGGCGGATCCGCCCTCC--GGAACGGGCCCGTGCAGGCCTGC"
  ]
  node [
    id 49
    label "GGCGAGTACTCGCCCCCTAGGGTCTGATCAGAGGGGGCCCTC"
  ]
  node [
    id 50
    label "GGAAGT--ACTTTCGCTCGAGCATGGGCCCATATAGGCCTAT"
  ]
  node [
    id 51
    label "GGGAGTGCGCTCCCGCG--CGCGCGGATCCGCGTAGGCCTAC"
  ]
  node [
    id 52
    label "GGGTAGGCCTGCCCGCC--GGCGCAGATCTGTGGTGGCCATT"
  ]
  node [
    id 53
    label "CCGGCCGCGGCCGGGCTCGAGCCGGGATCCCGCCGGGCCCGG"
  ]
  node [
    id 54
    label "GGGTCGGCCGGCCCCCG--CGGCCTGGCCAGGGGAGGCCTTC"
  ]
  node [
    id 55
    label "GGTGGGGCCCCACCCTC--GAGTCAGATCTGAGAAGGCCTTC"
  ]
  node [
    id 56
    label "GGAGGAGCTCCTCCGCG--CGCGCGGATCCGCATAGGCCTAT"
  ]
  node [
    id 57
    label "GGGGAGATCTCCCCCCA--TGGACAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 58
    label "GGGCAGTACTGCCCCCA--TGGGCTGATCAGCGGTGGCCATC"
  ]
  node [
    id 59
    label "GGTGGGGCCCCACCGGG--CCCACAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 60
    label "GGAGGGGCCCCTCCGCCGTGGCGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 61
    label "GGAGGGGCCCCTCCGCG--CGCGCGGGTCCGCGGCAGCTGCC"
  ]
  node [
    id 62
    label "GGTGGGGTCCCACCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 63
    label "GGGGGGGCCCCCCCGCG--CGCGCGGATCCGCGGCGGCCGCC"
  ]
  node [
    id 64
    label "GGAGGGGCCCCTCCCCC--GGGGCGGATCCGTGTTGGCCAAC"
  ]
  node [
    id 65
    label "GGAGGAGCTCCTCCCCC--GGGACGGATCCGTAGTGGCCACT"
  ]
  node [
    id 66
    label "CCGCTCTAGAGCGGGCTCGAGCGCCGATCGGCCCCCGCGGGG"
  ]
  node [
    id 67
    label "GGAGAGATCTCTCCCCC--GGGACGGATCCGTGTTGGCCAAC"
  ]
  node [
    id 68
    label "GGAGGG--CCCTCCCCC--GGGGCAGATCTGTGTTGGCCAAC"
  ]
  node [
    id 69
    label "GGAGGGGCCCCTCCCCC--GGGTCAGATCTGAGGAGGCCTCC"
  ]
  node [
    id 70
    label "GGAAGT--ACTTTCGCTCGAGCATCGGCCGATGTAGGCCTAT"
  ]
  node [
    id 71
    label "GGGGAGATCTCCCCCTC--GAGACTGATCAGTGCAGGCCTGC"
  ]
  node [
    id 72
    label "GGGGGTGCGCCCCCCCA--TGGGCAGATCTGCGGTGGCCATC"
  ]
  node [
    id 73
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 74
    label "GGGTAGGCCTGCCCGCC--GGCGCAGATCTGTGGTGGCCATC"
  ]
  node [
    id 75
    label "GGAGGGGCCCCTCCGCG--CGCGCGGATCCGCGGCAGTTGCC"
  ]
  node [
    id 76
    label "GGTGGGGCCCCACCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 77
    label "TCCCTG--TGGGGAGCT--AGCTCTGTACAGGCTAGGCCTGG"
  ]
  node [
    id 78
    label "GGAGGGGCCCCTCCGTC--GGCCCGGATCCGGGCTGGCCAGC"
  ]
  node [
    id 79
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 80
    label "GGAGAGGCCTCTCCCCC--GGGTCGGGCCCGAGGAGGCCTCC"
  ]
  node [
    id 81
    label "GGAAGGGCCCTTCCGCG--CGCGCGGATTCGCGGGGGCCCTC"
  ]
  node [
    id 82
    label "GGAGGGGTCCCTCCCCC--GGGTCAGATCTGAGAAGGCCTTC"
  ]
  node [
    id 83
    label "GCCGGAGCTCCGGTGTC--GACGGAGATCTCCGTAGGCCTAC"
  ]
  node [
    id 84
    label "GGTGGGGCCCCACCGCC--GGCGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 85
    label "GGGTAGTACTGCCCGCC--GGCACAGATCTGTGGAGGCCTTC"
  ]
  node [
    id 86
    label "GGAGGGGCTCCTCCGCG--CGCGCGGATCCGCGGCAGCTGCC"
  ]
  node [
    id 87
    label "GGGAAGATCTTCCCCTC--GAGACGGATCCGTGCAGGCCTGC"
  ]
  node [
    id 88
    label "GGGGGAATTCCCCCCCA--TGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 89
    label "GGAGGGTACCCTCCGCG--CGCGGAGATCTCTGGTGGCCATC"
  ]
  node [
    id 90
    label "GGGGAG--CTCCCCGCG--CGCGCAGATCTGCGGTGGCCACC"
  ]
  node [
    id 91
    label "GGGGAGGTCTCCCCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 92
    label "GGTGAGGCCTCACCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 93
    label "GCCAGGTACCTGGCCCC--GGGGCGGATCCGCAAAGGCCTTT"
  ]
  node [
    id 94
    label "GGGTGGATCCACCCCCC--GGGCCAGATCTGGGCAGGCCTGC"
  ]
  node [
    id 95
    label "GGTGGGGCCCCACCGCG--CGCGCGGATCCGCGGCGGCCGTC"
  ]
  node [
    id 96
    label "GGGCAGATCTGCCCGCG--CGCACAGATCTGTGGAGGCCTCC"
  ]
  node [
    id 97
    label "TCCCTG--TAGGGAGCT--AGTTCTGCGCAGGCTGGGCCTAG"
  ]
  node [
    id 98
    label "GCAGGGGCCCCTGCGCCGTGGCGCAGATCTGCACAGGCCTGT"
  ]
  node [
    id 99
    label "GGGCGGGCCCGCCCCCC--GGGGCTGATCAGCGGTGGCCGCC"
  ]
  node [
    id 100
    label "GGTGGGGTCCCACCCCC--GGGTCAGATCTGAGCTGGCCAGC"
  ]
  node [
    id 101
    label "TCCCTG--TGGGGAGCT--AGCTCTGCGCAGGCTGGGCCCAG"
  ]
  node [
    id 102
    label "GGGGAGGTCTCCCCCTC--GAGGCAGATCTGTGCAGGCCTGC"
  ]
  node [
    id 103
    label "GGGAAGTACTTCCCCCA--TGGGCAGATCTGCGGTGGCCATC"
  ]
  node [
    id 104
    label "GGCAGGTACCTGCCTCCGTGGAGCGGATCCGTGCAGGCCTGC"
  ]
  node [
    id 105
    label "GGTGGGATCCCACCGGG--CCCACAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 106
    label "CCGCCCTAGGGCGGGCTCGAGCGTCGATCGACCCCCGCGGGG"
  ]
  node [
    id 107
    label "GGAGGAGCTCCTCCCCC--GGGACGGATCCGTGTTGGCCAAC"
  ]
  node [
    id 108
    label "GGGGTA--TGCCCCGCTCGAGCCTTGATCAAGCCTGGCTGGG"
  ]
  node [
    id 109
    label "GGCAGGTACCTGCCCCC--GGGACGGTACCGTGTTGGCCAAC"
  ]
  node [
    id 110
    label "GGCAGGTACCTGCCCCCGTGGGGCGGATCCGTAGTGGCCACT"
  ]
  node [
    id 111
    label "GGGGAGATCTCCCCGCG--CGCGGTGGCCATCGGCGGCCGTC"
  ]
  node [
    id 112
    label "GGCTGGTACCAGCCCCC--GGGCCTGATCAGGAATGGCCATT"
  ]
  node [
    id 113
    label "GGAGGA--TCCTCCCCC--GGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 114
    label "GGAGGGGTCCCTCCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 115
    label "GGAGGGGCCCCTCCGCG--CGCGGTGATCATTGGGGGCCCTC"
  ]
  node [
    id 116
    label "GGGTTGGCCAACCCGCCTAGGCGCACTAGTGTGTAGGCCTAC"
  ]
  node [
    id 117
    label "GGCGGGTACCCGCCCCC--GGGTCTGATCAGAGGGGGCCCTC"
  ]
  node [
    id 118
    label "GGAGAGATCTCTCCGCG--CGCGTGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 119
    label "CCCGCGGCCGCGGGGCC--GGCGCGGATCCGCCCCGGCCGGG"
  ]
  node [
    id 120
    label "GGTGGGATCCCACCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 121
    label "GGGTCGGTCGGCCCCCCGTGGGGCGGATCCGCGCTGGCCAGC"
  ]
  node [
    id 122
    label "GGCGGATATCCGCCCCC--GGGCCTGATCAGGAGTGGCCACT"
  ]
  node [
    id 123
    label "GGTGGATATCCACCCCG--CGGTCCGATCGGGGCAGGCCTGC"
  ]
  node [
    id 124
    label "GGTAGAGCTCTACCCCC--GGGGCAGATCTGTGTTGGCCAAC"
  ]
  node [
    id 125
    label "CCCGCGATCGCGGGGTTCGAACGCGGATCCGCGCTGGCCGGC"
  ]
  node [
    id 126
    label "GGGCTGGCCGGCCCTCC--GGACTTGATCAAGGGGGGCCCTC"
  ]
  node [
    id 127
    label "GGAAGGGCCCTTCCGCC--GGCGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 128
    label "GGTGGGATCCCACCCCC--GGGGCAGATCTGTGTTGGCCAAC"
  ]
  node [
    id 129
    label "GGGGGGGCCCCCCCCCC--GGGGCAGATCTGCGATGGCCGTC"
  ]
  node [
    id 130
    label "GGGTGGGTCCACCCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 131
    label "GGAGGGATCCCTCCGCC--GGCGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 132
    label "GGAGAGGCCTCTCCCCC--GGGGCGGATCCGCGTTGGCCAAC"
  ]
  node [
    id 133
    label "GGGAGTGCGCTCCCGCG--CGCACGGATCCGTGTAGGCCTAC"
  ]
  node [
    id 134
    label "GGAGGGATCCCTCCGCG--CGCGCTGGCCAGTGGCGGCCGCC"
  ]
  node [
    id 135
    label "GGAGGGGCCCCTCCCCC--GGGACAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 136
    label "GCCCCGGCCGGGGCGCC--GGCTGAGATCTCAGCGGGCCCGC"
  ]
  node [
    id 137
    label "GGAGGAATTCCTCCCCC--GGGGCAGATCTGTCATGGCCATG"
  ]
  node [
    id 138
    label "GGAGGAGCTCCTCCGCG--CGCGCGGATCCGCGGTGGCCACT"
  ]
  node [
    id 139
    label "GGGTTGATCGGTCCCTCGTGGGACGGATTCGTGCTGGCCAGC"
  ]
  node [
    id 140
    label "GGTGGCGCGCCACCGCC--GGCGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 141
    label "GGAGGGGCCCCTCCGCCGTGGCGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 142
    label "GGAGGGGTCCCTCCCCC--GGGGCAGATCTGCGATGGCCGTC"
  ]
  node [
    id 143
    label "GCCAGGTACCTGGCCCC--GGGGCTGATCAGCGGAGGCCTTC"
  ]
  node [
    id 144
    label "GGAGAGGCCTCTCCGCC--GGCGGAGATCTCCGGCGGCCGTC"
  ]
  node [
    id 145
    label "GGGTCGGCCGGCCCCCC--GGGGCAGATCTGCGGGGGCCCTC"
  ]
  node [
    id 146
    label "GGGGGGGCCCCCCCGCA--TGCGGTGGCCACTGGGGGCCCTC"
  ]
  node [
    id 147
    label "GGAGGGGCCCCTCCTCC--GGAACGGATCCGTGCTGGCCAGC"
  ]
  node [
    id 148
    label "GGGTAGGCCTGCCCCCC--GGGACGGATCCGTGATGGCCATC"
  ]
  node [
    id 149
    label "GGAGGGGCCCCTCCGCCGTGGCGCAGATCTGCGTTGGCCAAC"
  ]
  node [
    id 150
    label "GGAGGGGCCCCTCCGCC--GGCGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 151
    label "GGTGGAGCTCCACCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 152
    label "GGTGCGATCGCACCTCC--GGAGTTGATCAATGCTGGCCAGC"
  ]
  node [
    id 153
    label "GGGTAGGCCTGCCCGCCGTGGCCCAGATCTGGGAAGGCCTTC"
  ]
  node [
    id 154
    label "GGAGGGGTCCCTCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 155
    label "GTCTCTGCAGGGACGCGCGCGCTTTGGCCGGAGGTGGCCACC"
  ]
  node [
    id 156
    label "GGGGAGATCTCCCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 157
    label "GGGGAGATCTCCCCCCC--GGGGCAGATCTGCGCAGGCCTGC"
  ]
  node [
    id 158
    label "GCGGTGATCACTGCGCTCGAGCTCGGATCTGACCGTGCACGG"
  ]
  node [
    id 159
    label "GGGAGTGCACTCCCGCA--TGCGTAGATCTATGCTGGCCAGC"
  ]
  node [
    id 160
    label "GATGGGGCCCCATCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 161
    label "GGGTCGATCGGCCCCCCGTGGGGCGGATCCGTGCTGGCCAGC"
  ]
  node [
    id 162
    label "GGAGGAGCTCCTCCCGT--ACGACGGATCCGTGTTGGCCAAC"
  ]
  node [
    id 163
    label "GGGTCGATCGGCCCCCC--GGGGCGGATCCGCGTTGGCCAAC"
  ]
  node [
    id 164
    label "GGGTCGGCCGGCCCTCCGTGGAACGGATCCGTGCTGGCCAGC"
  ]
  node [
    id 165
    label "GGGTCGGCCGGCCCCCC--GGGGCGGATCCGCGTTGGCCAAC"
  ]
  node [
    id 166
    label "TCCCAG--TTGGGAGCT--AGCTCTGTGCAGGCCAGGCCTGG"
  ]
  node [
    id 167
    label "GGGGAGTACTCCCCGCG--CGCGGTGGCCATCGGCGGCCGTC"
  ]
  node [
    id 168
    label "GGAGGGATCCCTCCCCC--GGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 169
    label "GGTGAGATCTCACCCTC--GAGGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 170
    label "GGTGGGGCCCCACTGCCGTGGCGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 171
    label "CTCTGTGCGCGGAGGCA--TGCGCGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 172
    label "GGGTAGGCTTGCCCGCG--CGCACTGGCCAGTGGGGGCCCTC"
  ]
  node [
    id 173
    label "GGGTAGGCTTGCCCGCG--CGCTCTGATCAGAGGGGGCCCTC"
  ]
  node [
    id 174
    label "GGGTAGGCCTACCCGCG--CGCACAGATCTGTGGAGGCCTCC"
  ]
  node [
    id 175
    label "GGGGAGGCCTCCCCCCC--GGGACAGATCTGTGGAGGCCTCC"
  ]
  node [
    id 176
    label "GGATGGGTCCATCCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 177
    label "GGAGGGGCCCCTCCGCG--CGCGCGGATCCGCGGCAGCTGCC"
  ]
  node [
    id 178
    label "GGAGGGATCCCTCCGCC--GGCGCAGATCTGTGTAGGCCTAC"
  ]
  node [
    id 179
    label "GGAGGGGTCCCTCCCCC--GGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 180
    label "GGGTCGGCCGGCCCTCC--GGAACGGATCCGTGTTGGCCAAC"
  ]
  node [
    id 181
    label "GGAAGGGCCCTTCCGCG--CGCGCGGATCCGCGGCAGCTGCC"
  ]
  node [
    id 182
    label "GGCAGGTACCTGCCCCC--GGGGCGGTACCGTGCAGGCCTGC"
  ]
  node [
    id 183
    label "GGGTGTTAGCACCCCCA--TGGGCAGATCTGCGGTGGCCATC"
  ]
  node [
    id 184
    label "GGTGAGGCCTCACCCCC--GGGGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 185
    label "GGGTGGTACCACCCCCA--TGGGCAGATCTGCGGTGGCCATC"
  ]
  node [
    id 186
    label "GGGAGAATTCTCCCCCC--GGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 187
    label "GGGCGTGCGCGCCCCCCGTGGGACGGGCCCGTCTAGGCCTAG"
  ]
  node [
    id 188
    label "GGGTCGATCGGCCCTCCGTGGAACGGATCCGTGCTGGCCAGC"
  ]
  node [
    id 189
    label "GGAGGGATCCCTCCCCC--GGGTCAGATCTGAGCAGGCCTGC"
  ]
  node [
    id 190
    label "GGAGGGATCCCTCCCCC--GGGGCAGATCTGTGCTGGCCAGC"
  ]
  node [
    id 191
    label "CCCGACTAGTCGGGGCTCGAGCTTGGATCCAAGCTGGCCGGC"
  ]
  node [
    id 192
    label "GGGCAGTACTGCCCGCC--GGCACTGATCAGTGGAGGCCTTC"
  ]
  node [
    id 193
    label "TCCTGG--TCAGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 194
    label "GGATGGGTCCATCCGCGATCGCCCAGATCTGGGTGAGCTCAC"
  ]
  node [
    id 195
    label "CCCGCGGCCGCGGGGCC--GGCGCGGATCCGCGCCGGCCGGC"
  ]
  node [
    id 196
    label "GGCGAAATTTCGCCGCC--GGCACAGATCTGTGATGGCCATC"
  ]
  node [
    id 197
    label "GGGAGAATTCTCCCCCC--GGGGCGGATCCGTGATGGCCATC"
  ]
  node [
    id 198
    label "GGGAGGATCCTCCCCCC--GGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 199
    label "GCAGGGGCCCCTGCCCC--GGGTCAGATCTGAGATGGCCATC"
  ]
  node [
    id 200
    label "GGGGGGATCCCCCCGCA--TGCGGTGGCCACTGGGGGCCCTC"
  ]
  node [
    id 201
    label "GGCAGGTACCTGCCCCC--GGGGCAGATCTGTGCAGGCCTGC"
  ]
  node [
    id 202
    label "GCTGTGATCGCGGCGTACGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 203
    label "GGAGGGATCCCTCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 204
    label "GGAGGGTACCCTCCCCC--GGGGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 205
    label "GGCAGGTACCTGCCCCC--GGGGCGGTACCGCGTTGGCCAAC"
  ]
  node [
    id 206
    label "GGTGGATATCCACCCCG--CGGCCCGATCGGGGCAGGCCTGC"
  ]
  node [
    id 207
    label "GGGTCGATCGACCCCCCGTGGGACGGATTCGTGCTGGCCAGC"
  ]
  node [
    id 208
    label "GGGTAGGCCTACCCGCC--GGCGCAGATCTGTGGTGGCCATC"
  ]
  node [
    id 209
    label "GGGGATATATCCCCGCA--TGCGCGGATCCGCCTTGGCCAAG"
  ]
  node [
    id 210
    label "GCCAGGTACCTGGCCCCGTGGGTCTGATCAGAGGGGGCCCTC"
  ]
  node [
    id 211
    label "GGGGAGATCTCCCCCTC--GAGGCAGATCTGCGCAGGCCTGC"
  ]
  node [
    id 212
    label "GCAGGGGCCCCTGCCCC--GGGTCAGATCTGAGGTGGCCACC"
  ]
  node [
    id 213
    label "GGGTCGATCGGCCCCCCGTGGGGCGGATCCGCGCTGGCCAGC"
  ]
  node [
    id 214
    label "GGGTCGTACGGCCCCCC--GGGACGGATCCGTCGTGGCCACG"
  ]
  node [
    id 215
    label "GGTGGGGCCCCACCGCG--CGCGCGGATCCGCGGCAGCTGCC"
  ]
  node [
    id 216
    label "GGGTAGATCTACCCGCC--GGCGCAGATCTGTGGTGGCCATC"
  ]
  node [
    id 217
    label "GGAAGGGCCCTTCCGCG--CGCGCGGATCCGCGGTGGCCACT"
  ]
  node [
    id 218
    label "GGCAGGTACCTGCCCCC--GGGGCGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 219
    label "GGGTCGGCCGGCCCCCCGTGGGGCGGATCCGTGCTGGCCGGC"
  ]
  node [
    id 220
    label "GCCGTGATCACGGCGTATGTACCTGCGCGCAGCCTGGCTGGG"
  ]
  node [
    id 221
    label "GGGGAGGCCTCCCCCCC--GGGGCAGATCTGCGGGGGCCCTC"
  ]
  node [
    id 222
    label "GGCGGGTACCCGCCCCC--GGGACTGGCCAGTGGGGGCCCTC"
  ]
  node [
    id 223
    label "GGACAGATCTGTCCGCG--CGCGCTGATCAGCAGTGGCCACT"
  ]
  node [
    id 224
    label "GGTGGGGCCCCACCCCC--GGGGCAGATCTGTGTTGGCCAAC"
  ]
  node [
    id 225
    label "GGCGAGATCTCGCCCCC--GGGACGGATCCGTGTAGGCCTAC"
  ]
  node [
    id 226
    label "GGTGAGATCTCACCCCC--GGGGCGGATCCGCGAAGGCCTTC"
  ]
  node [
    id 227
    label "GGAGGAGCTCCTCCGCC--GGCGGAGATCTCCGCAGGCCTGC"
  ]
  node [
    id 228
    label "GGAGAGGCCTCTCCGCG--CGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 229
    label "GGGTAGGCCTGCCCCCA--TGGGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 230
    label "GGAGAGGCCTCTCCGCG--CGCACTGATCAGTGGGGGCCCTC"
  ]
  node [
    id 231
    label "GGCAAAGCTTTGCCGTC--GACGCGGATCCGCGTAGGCCTAC"
  ]
  node [
    id 232
    label "GCTGGAATTCCAGCGTG--CACGGAGATCTCCGTAGGCCTAC"
  ]
  node [
    id 233
    label "GGAGGGGCCCCTCCGCG--CGCGCAGATCTGTGGCAGCTGCC"
  ]
  node [
    id 234
    label "GGGGGTTAGCCCCCGCG--CGCGTGGATCCATATAGGCCTAT"
  ]
  node [
    id 235
    label "GGCAGGTACCTGCCCCC--GGGGCGGATCCGTATAGGCCTAT"
  ]
  node [
    id 236
    label "TCCCGG--TTGGGAGCTTAAGTTCTGCGCAGACCAGGCCTGG"
  ]
  node [
    id 237
    label "GGGTAGGCCTGCCCCCG--CGGGTGGATCCACGATGGCCATC"
  ]
  node [
    id 238
    label "GGGGGGATCTCCCCCCA--TGGGCGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 239
    label "GCGGATGCGTCTGCGCTCGAGCCCGGATCCGGGTGGGCCCGT"
  ]
  node [
    id 240
    label "GGAGGGGCCCCTCCGGA--TCCTCAGATCTGAGCTGGCCAGC"
  ]
  node [
    id 241
    label "GGTTGGATCCAACCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 242
    label "GGGGAGATCTCCCCCCA--TGGACGGATCCGTGCAGGCCTGC"
  ]
  node [
    id 243
    label "GGGGAGATCTCCCCCTC--GAGGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 244
    label "GGAGGGATCCCTCCGCG--CGCGCGGATCCGTAGAGGCCTCT"
  ]
  node [
    id 245
    label "GGAGGGATCCCTCCCCC--GGGGCGGATCCGCGGAGGCCTCC"
  ]
  node [
    id 246
    label "GGGGAGGCCTCCCCGCC--GGCAGGGATCCCTGGTGGCCACC"
  ]
  node [
    id 247
    label "GGGCAGGCCTGCCCCCC--GGGGCAGATCTGCCAAGGCCTTG"
  ]
  node [
    id 248
    label "GGGGAGATCTCCCCGCAGTTGCTCAGATCTGAGTAGGCCTAC"
  ]
  node [
    id 249
    label "GGAGGATATCCTCCCCC--GGGGCAGATCTGTGGTGGCCACC"
  ]
  node [
    id 250
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGCGATGGCCGTC"
  ]
  node [
    id 251
    label "GGGGAGATCTCCCCCTC--GAGACGGATCCGTGCAGGCCTGC"
  ]
  node [
    id 252
    label "GGAGGAGCTCCTCCCCC--GGGGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 253
    label "GGGGATGCATCCCCGCA--TGCGCGGATCCGCCTTGGCCAAG"
  ]
  node [
    id 254
    label "GGGAGAGCTCTCCCCCC--GGGGCAGATCTGTGGTGGCCGCC"
  ]
  node [
    id 255
    label "GGATGGGCCCATCCTCC--GGAGCAGATCTGTGCTGGCCAGC"
  ]
  node [
    id 256
    label "GGAGGGGCCCCTCCGCCGTGGCCCAGATCTGGACAGGCCTGT"
  ]
  node [
    id 257
    label "GGAGGGGCCCCTTCCCC--GGGACGGATCCGTGTTGGCCAAC"
  ]
  node [
    id 258
    label "GGAGGGGCCCCTCCCCC--GGGACAGATCTGTGGTGGCCACC"
  ]
  node [
    id 259
    label "GGGTGGATCCACCCCCC--GGGGCAGATCTGCGCAGGCCTGC"
  ]
  node [
    id 260
    label "GGGCAGATCTGCCCCCC--GGGGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 261
    label "GGCGATGCGTCGCCCCCGTGGGGCGGATCCGTCCAGGCCTGG"
  ]
  node [
    id 262
    label "GGGTCGGCCGGCCCCCCGTGGGACGGATCCGTGTTGGCCAAC"
  ]
  node [
    id 263
    label "GGAGGGATCCCTCCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 264
    label "GGCGAGTACTCGCCCCC--GGGTCTGATCAGAGGGGGCCCTC"
  ]
  node [
    id 265
    label "GGGGAGATCTCCCCGTG--CACGCAGATCTGCGGCGGCCGTC"
  ]
  node [
    id 266
    label "GGAGAGGCCTCTCCCCC--GGGGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 267
    label "GGTGGGGCCCCACCCCC--GGGGCGGATCCGCGGAGGCCTCC"
  ]
  node [
    id 268
    label "TCCTGG--TCAGGAGCT--AGTTCTGTGCGGGCCAGGCCTGG"
  ]
  node [
    id 269
    label "GGAGGGGCCCCTCCGGTGTACCCCAGATCTGGGCTGGCCAGC"
  ]
  node [
    id 270
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 271
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGTGTTGGCCAAC"
  ]
  node [
    id 272
    label "GCCAGGTACCTGGCCCC--GGGGCGGATCCGCAGAGGCCTCT"
  ]
  node [
    id 273
    label "GGAGGAGCTCCTCCCCC--GGGGCAGATCTGTGTTGGCCAAC"
  ]
  node [
    id 274
    label "GGTGGGGCCCCACCCCC--GGGTCAGATCTGAGGAGGCCTCC"
  ]
  node [
    id 275
    label "GGGGAGATCTCCCCCCA--TGGGCAGATCTGCGTAGGCCTGC"
  ]
  node [
    id 276
    label "GGCAGGTACCTGCCCCC--GGGGCTGATCAGCGGGGGCCCTC"
  ]
  node [
    id 277
    label "GGGTCGATCGGCCTCCCGTGGGACGGATTCGTGCTGGCCAGC"
  ]
  node [
    id 278
    label "AGCCCA--TGGGCTGTC--GGCCCGGATCCGGGTGGGCCCGC"
  ]
  node [
    id 279
    label "GGAGGGGCCCCTCCCCC--GGGGCGGATCCGCGTTGGCCAAC"
  ]
  node [
    id 280
    label "GGGGGTGCGCCCCCGCA--TGCAGGGATCCCTGTTGGCCAAC"
  ]
  node [
    id 281
    label "GGTGAGATCTCACCCTC--GAGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 282
    label "CCCGTCTAGACGGGGCTCGAGCTCGGATCCGAGCTGGCCGGC"
  ]
  node [
    id 283
    label "GGCGGTGCGCCGCCCCCGTGGGGCGGATCCGTCCAGGCCTGG"
  ]
  node [
    id 284
    label "GGGTAGGCCTGCCCGCG--CGCTCTGATCAGAGGGGGCCCTC"
  ]
  node [
    id 285
    label "GGGTCGGCCGGCCCCCCGTGGGGCGGATCCGTGCTGGCCAGC"
  ]
  node [
    id 286
    label "GGAGGGGCCCCTCCCCC--GGGCCGGGCCCGGGGAGGCCTCC"
  ]
  node [
    id 287
    label "GGAGGAATTCCTCCGCG--CGCGCGGTACCGCGGTGGCCACT"
  ]
  node [
    id 288
    label "GGCGGTGCGCCGCCCCC--GGGGCAGATCTGCCCAGGCCTGG"
  ]
  node [
    id 289
    label "GGGGGGTACCCCCCGCA--TGCGGTGGCCACTGGGGGCCCTC"
  ]
  node [
    id 290
    label "GGTGGAATTCCACCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 291
    label "GGGTAGGCCTGCCCGCC--GGCACAGATCTGTGGGGGCCCTC"
  ]
  node [
    id 292
    label "GGAGGGGTCCCTCCGCCGTGGCGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 293
    label "CCCGCGGCCGCGGGGTTCGAACGCGGATCCGCGCTGGCCGGC"
  ]
  node [
    id 294
    label "GGGTCGGCCGGCCCCCCGTGGGGCGGATCCGTGCTAGCTAGC"
  ]
  node [
    id 295
    label "GGAGGGGCCCCTCCCCA--TGGGCGGATCCGTGCAGGCCTGC"
  ]
  node [
    id 296
    label "GCCAGATATCTGGCTCC--GGAGCGGATCCGCGTTGGCCAAC"
  ]
  node [
    id 297
    label "GGGTGGATCCACCCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 298
    label "GGAGGG--CCCTCCGCG--CGCGCGGATCCGCGGCAGCTGCC"
  ]
  node [
    id 299
    label "GGAGGGATCCCTCCCCC--GGGGCAGATCTGCGGTGGCCACC"
  ]
  node [
    id 300
    label "GGCAGGTACCTGCCCCC--GGGGCGGTACCGTGTTGGCCAAC"
  ]
  node [
    id 301
    label "GGAGGGATCCCTCCCCC--GGGGCGGATCCGCGTTGGCCAAC"
  ]
  node [
    id 302
    label "GGCGGGTACCCGCCCCCGTGGGGCGGATCCGTGCAGGCCTGC"
  ]
  node [
    id 303
    label "GCCAGGTACCTGGCCCC--GGGGCGGATCCGTAGAGGCCTCT"
  ]
  node [
    id 304
    label "GGTTGGGCCCAACCCCC--GGGTCAGATCTGAGAAGGCCTTC"
  ]
  node [
    id 305
    label "GGATGGTACCATCCGCG--TGCCCTGGCCAGGGGAGGCCTTC"
  ]
  node [
    id 306
    label "GGCGGGGCCCCGCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 307
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGCGCAGGCCTGC"
  ]
  node [
    id 308
    label "GGAGAGGTCTCTCCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 309
    label "GGTGGGGTCCCACCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 310
    label "GGAGGGATCCCTCCCCC--GGGACGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 311
    label "GAAAGT--ACTTTCGCTCGAGCATCGGCCGATGCAGGCCTGT"
  ]
  node [
    id 312
    label "GGGGGTGCACCCCCGCA--TGCAGAGGCCTCTGTTGGCCAAC"
  ]
  node [
    id 313
    label "GGGTCGGCCGGCCCGCG--CGCGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 314
    label "GGTAAGGCCTTACCCCC--GGGGCGGATCCGCGGTGGCCACC"
  ]
  node [
    id 315
    label "GGAGGGGTCCCTCCCCC--GGGTCAGATCTGAGGTGGCCACC"
  ]
  node [
    id 316
    label "GGGCAGGCCTGCCCCCC--GGGACGGTACCGTGCTGGCCAGC"
  ]
  node [
    id 317
    label "GGAGGAGCTCCTCCCCC--GGGGCAGATCTGTAGTGGCCACT"
  ]
  node [
    id 318
    label "GGCAGGTACCTGCCCCCGTGGGGCGGATCCGTGCAGGCCTGC"
  ]
  node [
    id 319
    label "GTTTCTGCAGAAGCGTG--CACTTCGCGCGAACTCAGCTGGG"
  ]
  node [
    id 320
    label "GGAGGAATTCCTCCGCG--CGCACGGATCCGTAGTGGCCACT"
  ]
  node [
    id 321
    label "GGAGAGGCCTCTCCGCCGTGGCGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 322
    label "GGAGGAGCTCCTCCGCG--CGCGTGGATCCATAGTGGCCACT"
  ]
  node [
    id 323
    label "GGAGGGGCCCCTCCCCC--GGGTCAGATCTGAGTAGGCCTAC"
  ]
  node [
    id 324
    label "GGAGGGATCCCTCCGCCGTGGCGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 325
    label "GGCAGGTACCTGCCCCCGTGGGGCAGATCTGTGTAGGCCTAC"
  ]
  node [
    id 326
    label "TTCCTGGTCAGGAAGCT--AGCTCTGCGCAGACCCGGCCGGG"
  ]
  node [
    id 327
    label "GGGCAGGCCTGCCCCCA--TGGGCGGATCCGCAGAGGCCTCT"
  ]
  node [
    id 328
    label "GCCAGGTACCTGGCCCC--GGGGCGGATCCGTAGAAGCTTCT"
  ]
  node [
    id 329
    label "GGAGGGGCCCCTCCCCC--GGGACGGGCCCGTGTTGGCCAAC"
  ]
  node [
    id 330
    label "GGGTAGGCCTGCCCCCC--GGGACAGATCTGTGATGGCCATC"
  ]
  node [
    id 331
    label "GGATGGGCCCATCCCCC--GGGGCGGTATCGCGTTGGCCAAC"
  ]
  node [
    id 332
    label "TCCCTGGTCAGGGAGTC--GACCTTGCGCAAGCCGGGCCTGG"
  ]
  node [
    id 333
    label "GGCAGGTACCTGCCCCC--GGGGCGGTACCGTGATGGCCATC"
  ]
  node [
    id 334
    label "GGCGGATATCCGCCCCC--GGGGCTGATCAGCGGAGGCCTTC"
  ]
  node [
    id 335
    label "GGAGGGGCCCCTCCGCG--CGCGCGGATCCGCGGCGGCCGTC"
  ]
  node [
    id 336
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGCGGTGGCCACC"
  ]
  node [
    id 337
    label "GGAGGATATCCTCCGCG--CGCGCAGATCTGTGGTGGCCATC"
  ]
  node [
    id 338
    label "GCTGTGATCACGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 339
    label "GCCGGAGCTCCGGTGTC--GACAGAGATCTCTGTAGGCCTAC"
  ]
  node [
    id 340
    label "GGTGGG--CCCACCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 341
    label "GGAGGAATTCCTCCCCC--GGGGCAGATCTGTGCTGGCCAGC"
  ]
  node [
    id 342
    label "GGTGAGGTCTCACCCCC--GGGTCAGATCTGAGAAGGCCTTC"
  ]
  node [
    id 343
    label "GGAGGGATCCCTCCGTCGTGGCGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 344
    label "GGCAGGTACCTGCCCCC--GGGGCTGATCAGCAGTGGCCACT"
  ]
  node [
    id 345
    label "GGGGAGGTCTCCCCCCGTGCGGCCAGATCTGGGCTGGCCAGC"
  ]
  node [
    id 346
    label "GGAGGGGCCCCTCCGCG--CGCGCAGATCTGTGACAGCTGTC"
  ]
  node [
    id 347
    label "GGGGTA--TGTCCCGCTCGAGCTTTGATCAAACCCAGCTGGG"
  ]
  node [
    id 348
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 349
    label "GGAGAGATCTCTCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 350
    label "GGACGGGCCCGTCCGCCGTGGCACAGGCCTGTGGAGGCCTCC"
  ]
  node [
    id 351
    label "GGGGAGATCTCCCCCCC--GGGGCAGGCCTGTGAAGGCCTTC"
  ]
  node [
    id 352
    label "GGGGGG--CCCTCTGCTCGAGCTTTGATCAAGCCCGGTTGGG"
  ]
  node [
    id 353
    label "GGGGAGTACTCCCCCCC--GGGGCAGATCTGTGCAGGCCTGC"
  ]
  node [
    id 354
    label "GGTGAGGCCTCACCCCC--GGGGCGGATCCGCGGAGGCCTCC"
  ]
  node [
    id 355
    label "GGAGGGGCCCCTCCGCG--CGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 356
    label "GGAGAGGCCTCTCCCCC--GGGACGGATCCGTGTTGGCCAAC"
  ]
  node [
    id 357
    label "GGAGGGTACCCTCCCCC--GGGGCAGATCTGCGTTGGCCAGC"
  ]
  node [
    id 358
    label "GGGGGGGCCCCCCCCCA--TGGACGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 359
    label "GGGGAGATCTCCCCCCC--GGGGCTGATCAGTGGAGGCCTCC"
  ]
  node [
    id 360
    label "GGGTGATATTGCCCCCG--CGGGCTGATCAGCCCTGGCCAGG"
  ]
  node [
    id 361
    label "GGGGAGATCTCCCCCCC--GGGCCGGTATCGGGGGGGCCCTC"
  ]
  node [
    id 362
    label "GGGTCGGCCGGCCCCCCGTGGGGTGGATCCACGTTGGCCAAC"
  ]
  node [
    id 363
    label "GGAGGGGCTCCTCCCCC--GGGGCAGATCTGTGTTGGCCAAC"
  ]
  node [
    id 364
    label "GGCAGGTACCTGCCCCCGTGGGGCGGATCCGTGTAGGCCTAC"
  ]
  node [
    id 365
    label "GGCGGTGCGCCGCCCCC--GGGGCAGATCTGTCCAGGCCTGG"
  ]
  node [
    id 366
    label "GGCAGATATCTGCCCCC--GGGGCTGATCAGCACTGGCCAGT"
  ]
  node [
    id 367
    label "GGGTAGATCTGCCCCCC--GGGGCGGATCCGCGGTGGCCACC"
  ]
  node [
    id 368
    label "GGGTCGGCCGGCCCCCG--CGGGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 369
    label "GGAGAGGTCTCTCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 370
    label "GGGGGG--CCCCCCGCG--CGCGCGGATCCGCGGCAGCTGCC"
  ]
  node [
    id 371
    label "GGAGGGATCCCTCCGGA--TCCTCAGATCTGAGCTGGCCAGC"
  ]
  node [
    id 372
    label "GGAGGGGCCCCTCCGCG--CGCGCAGTACTGTGATGGCCATT"
  ]
  node [
    id 373
    label "GGGTAGGCCTGCCCGCC--GGCACAGATCTGTGATGGCCATC"
  ]
  node [
    id 374
    label "GGAGGGGTCCCTCCCCC--GGGGCGGATCCGCGTTGGCCAAC"
  ]
  node [
    id 375
    label "GGGTAGGCCTGCCCCTC--GAGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 376
    label "CCAATCGTGGTTGGGCTCGAGCGAGGGTCCTTACTGGCCGGT"
  ]
  node [
    id 377
    label "GGAGAGGTCTCTCCCCC--GGGGCGGATCCGCGTTGGCCAAC"
  ]
  node [
    id 378
    label "GGAGAGGCCTCTCCCCC--GGGGCAGATCTGCGGTGGCCACC"
  ]
  node [
    id 379
    label "GGCAGGTACCTGCCCCC--GGGTCTGATCAGAGGGGGCCCTC"
  ]
  node [
    id 380
    label "GGCGGATATCCGCCCCC--GGGGCTGATCAGCAGTGGCCACT"
  ]
  node [
    id 381
    label "GGTAGGGTTCTACCGCC--GGCGCGGATCCGCAGAGGCCTTT"
  ]
  node [
    id 382
    label "GGAGGGGCCCCTCCCCC--GGGTCAGATCTGAGTGGGCCTAC"
  ]
  node [
    id 383
    label "GGATGGGCTCATCCCCC--GGGGCAGATCTGTGCTGGCCAGC"
  ]
  node [
    id 384
    label "GGTGGGGCCCCATCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 385
    label "GGAAGGGCCCTTCCGCG--CGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 386
    label "GGGGGTGCACCCCCGCA--TGCTCGGATCCGAGTTGGCCAGC"
  ]
  node [
    id 387
    label "CCGGTGGCCACCGGGTTCGAGCGCGGATCCGCGCTGGCCGGC"
  ]
  node [
    id 388
    label "GGAGAGGCCTCTCCCCC--GGGGCAGATCTGCGCAGGCCTGC"
  ]
  node [
    id 389
    label "GGAGAGGCCTCTCCGCCGTGGCGCAGATCTGCGATGGCCATC"
  ]
  node [
    id 390
    label "GCCAGGTACCTGGCCCCGTGGGGCGGATCCGCACAAGCTTGT"
  ]
  node [
    id 391
    label "GGATGGGTCCATCCCCC--GGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 392
    label "GGAGAGATCTCTCCGCC--GGCAGGGATCCCTGCAGGCCTGC"
  ]
  node [
    id 393
    label "GGGGGG--CCCCCCCCC--GGGGCAGATCTGCGATGGCCGTC"
  ]
  node [
    id 394
    label "GGTGAGGCCTCACCGGA--TCCGCGGATCCGCGAAGGCCTTC"
  ]
  node [
    id 395
    label "GGGGAGATCTCCCCCCC--GGGGCAGATCTGTCAAGGCCTTG"
  ]
  node [
    id 396
    label "GGCACGTACGTGCCCCCGTGGGGCGGATCCGTGTAGGCCTAC"
  ]
  node [
    id 397
    label "GGAGGGATCCCTCCCCC--GGGACGGATCCGTGCTGGCCAGC"
  ]
  node [
    id 398
    label "GGAGGGGCCCCTCCCCC--GGGTCAGATCTGAGCTGGCCAGC"
  ]
  node [
    id 399
    label "GGGTAGGCCTGCCCCCC--GGGACGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 400
    label "GGAGGGATCCCTCCCCC--GGGTCAGATCTGAGAAGGCCTTC"
  ]
  node [
    id 401
    label "GGGTAGGCCTGCCCGCG--CGCTCTGATCAGAGGCGGCCGTC"
  ]
  node [
    id 402
    label "GGTAGGATCCTACCCTC--GAGGCAGATCTGCCCTGGCCAGG"
  ]
  node [
    id 403
    label "GGTGGGGCCCCACTGCC--GGCGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 404
    label "GGAGGAGCTCCTCCGCG--CGCGCTGATCAGTGGCAGCTGTC"
  ]
  node [
    id 405
    label "GGAGGGGCTCCTCCGCC--GGCGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 406
    label "GGCAGGTACCTGCCCCCGTGGGGCGGTACCGTGAAGGCCTTC"
  ]
  node [
    id 407
    label "GCCAGATATCTGGCTCC--GGAGCGGATCCGCAGAAGCTTCT"
  ]
  node [
    id 408
    label "GGAGGGGCTCCTCCACC--GGTACAGATCTGTATAGGCCTAT"
  ]
  node [
    id 409
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 410
    label "GCCAGGTACCTGGCCCC--GGGGCGGATCCGCAGAAGCTTCT"
  ]
  node [
    id 411
    label "GGAAGGGCCCTTCCGCC--GGCGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 412
    label "GGGGGG--CCCCCCGCG--CGCGCAGATCTGCGGCGGCCGTC"
  ]
  node [
    id 413
    label "GGGAGAGCTCTCCCGCT--AGCACAGATCTGTGTAGGCCTGC"
  ]
  node [
    id 414
    label "GGGTAGGCCTGCCCGCC--GGCACAGATCTGTGGTGGCCACC"
  ]
  node [
    id 415
    label "GGGTAGTACTGCCCCCA--TGGGCTGATCAGCGGAGGCCTTC"
  ]
  node [
    id 416
    label "GGAGGGCGCCCTCCGCG--CGCGCAGATCTGCGGTGGCCATC"
  ]
  node [
    id 417
    label "GCACAGGCCTGTGCGCCGTGGCGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 418
    label "GGGGGAATTCCCCCCCC--GGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 419
    label "GGAAAGATCTTTCCGCG--CGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 420
    label "GGACAGGCCTGTCCGCC--GGCGCAGATCTGCAATGGCCATT"
  ]
  node [
    id 421
    label "GGAGAGATCTCTCCCCC--GGGGCAGATCTGCGGTGGCCACC"
  ]
  node [
    id 422
    label "GGACAGGCCTGTCCGCG--CGCTCTGATCAGAGGGAGCTCTC"
  ]
  node [
    id 423
    label "GGAGAGATCTCTCCGTCGTGGCGCAGATCTGTGTTGGCCAGC"
  ]
  node [
    id 424
    label "GGTGGGGCCCCACCCCC--GGGACAGATCTGTGGAGGCCTCC"
  ]
  node [
    id 425
    label "GGGTAGTACTGCCCGCG--CGCGCTGATCAGTGGCGGCCGTC"
  ]
  node [
    id 426
    label "GGCGGGTACCCGCCCCC--GGGGCTGATCAGCGGGGGCCCTC"
  ]
  node [
    id 427
    label "GGGGGG--CCCCCCCCG--CGGGCAGATCTGTGTGGGCCCAC"
  ]
  node [
    id 428
    label "TCCTTG--TAGGGAGCT--AGTTCTGCGCAGGCTGGGTCCAG"
  ]
  node [
    id 429
    label "GGCAGATATCTGCCCCCGTGGGGCGGATCCGTGCAGGCCTGC"
  ]
  node [
    id 430
    label "GGGGGTATGCCCCCGCTCGAGCCTTGATCAAGCCTGGCTGGG"
  ]
  node [
    id 431
    label "GGGGGGATCCCCCCCCA--TGGGCGGATCCGCGCAGGCCTGC"
  ]
  node [
    id 432
    label "GGGGAGATCTCCCCCCA--TGGACTGATCAGTGTAGGCCTGC"
  ]
  node [
    id 433
    label "GGCAGGTACCTGCCCCC--GGGGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 434
    label "TCCCAG--CTGGGAGTT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 435
    label "GGGAGAATTCTCCCCCC--GGGGCAGATCTGTGGTGGCCACC"
  ]
  node [
    id 436
    label "GCCAGATATCTGGCCCC--GGGGCGGATCCGCAGAAGCTTCT"
  ]
  node [
    id 437
    label "GGAGAGGCCTCTCCCCG--CGGGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 438
    label "GGAGGGGCCCCTCCGCG--CGCGCGGATCCGCGGTGGCCACT"
  ]
  node [
    id 439
    label "GGCAGGTACCTGCCCCCGTGGGGCGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 440
    label "GGAGGGATCTCTCCCCC--GGGGCGGATCCGTGTTGGCCAAC"
  ]
  node [
    id 441
    label "GGCGGATATCCGCCCCC--GGGACTGATCAGTAGTGGCCACT"
  ]
  node [
    id 442
    label "GGAGGAGCTCCTCCCCC--GGGGCAGATCTGTGATGGCCGTC"
  ]
  node [
    id 443
    label "GGAGGGATCCCTCCCCC--GGGGCGGATCCGTGTCGGCCGAC"
  ]
  node [
    id 444
    label "GGAGGGATCCCTCCCCC--GGGGCAGATCTGCGGGGGCCTCC"
  ]
  node [
    id 445
    label "GGAGAGATCTCTCCGCG--CGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 446
    label "GGAGGAGTTCCTCCCCC--GGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 447
    label "GGAGGGGCCCCTCCCCC--GGGACAGGCCTGTGAAGGCCTTC"
  ]
  node [
    id 448
    label "GGAGGGATCCCTCCCCC--GGGGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 449
    label "GGCGGTGCGCCGCCCCCGTGGGACGGATCCGTCCAGGCCTGG"
  ]
  node [
    id 450
    label "GGACAGGCCTGTCCGCCGTGGCGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 451
    label "CCGGCGGCCGCCGGGTTCGAACGCGGATCCGCGCTGGCCGGC"
  ]
  node [
    id 452
    label "GGGCGGATCCGCCCCCC--GGGACAGATCTGTGGTGGCCACC"
  ]
  node [
    id 453
    label "GCCGGGTACCCGGCCCC--GGGGCTGATCAGCGGAGGCCTCC"
  ]
  node [
    id 454
    label "GGCGGGTACCCGCCCCCGTGGGGCGGATCCGTCCAGGCCTGG"
  ]
  node [
    id 455
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGCAAAGGCCTTT"
  ]
  node [
    id 456
    label "GGGAAGATCTTCCCCTC--GAGACAGATCTGTGTAGGCCTAC"
  ]
  node [
    id 457
    label "GGAGGGGCCCCTCCGCCGTGGCGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 458
    label "GGAGGGGCCCCTCCGCA--TGCGCGGATCCGCGCAGGCCTGC"
  ]
  node [
    id 459
    label "GGATGGGCCCATCCCCC--GGGGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 460
    label "GGGTCGGCCGGCCCCCCGTGGGGCGGATCCGCGCTGGCCAGC"
  ]
  node [
    id 461
    label "GGGTAGTACTACCCCCA--TGGGCAGATCTGCGGTGGCCATC"
  ]
  node [
    id 462
    label "GGAGAGATCTCTCCCCT--AGGGCAGATTTGCGAAGGCCTTC"
  ]
  node [
    id 463
    label "GCCGGGTACCCGGCCCC--GGGGCGGATCCGCAGAAGCTTCT"
  ]
  node [
    id 464
    label "GGGGGTATACCCCCCCC--GGGTCAGATCTGAGCAGGCCTGC"
  ]
  node [
    id 465
    label "GGGAAGTACTTCCCTCC--GGGGCAGATCTGTGTAGGCCTAC"
  ]
  node [
    id 466
    label "GGTGGGGCCCCATCCCT--AGGGCAGATTTGTGTTGGCCAAC"
  ]
  node [
    id 467
    label "GGGGGGTACCCCCCGCG--CGCGTGGATCCATAGAGGCCTCT"
  ]
  node [
    id 468
    label "CCCGCCTAGGCGGGGCTCGAGCTTGGATCCAAGCTGGCCGGC"
  ]
  node [
    id 469
    label "GGGTAGGCCTACCCGCG--CGCACAGATCTGTGGAGGCCTTC"
  ]
  node [
    id 470
    label "GGCGAGATCTCGCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 471
    label "GGAGGGGCCCCTCCCCA--TGGGCGGATCCGTGTAGGCCTAC"
  ]
  node [
    id 472
    label "GGGGAGGCCTCCCCCCC--GGGGCGGATCCGCAAAGGCCTTT"
  ]
  node [
    id 473
    label "GGCGGAGTTCCGCCCCC--GGGCCAGATCTGGACAGGCCTGT"
  ]
  node [
    id 474
    label "GGAGGGTACCCTCCCCC--GGGGCAGATCTGCGATGGCCATC"
  ]
  node [
    id 475
    label "GGGTCGATCGACCCGCC--GGCACAGTACTGTGCAGGCCTGC"
  ]
  node [
    id 476
    label "CCAACCATGGTTGGGCTCGAGCGAGGATCCTTACTGGCCGGT"
  ]
  node [
    id 477
    label "GGACAGGCCTGTCCGCC--GGCGCAGATCTGCGTTGGCCAGC"
  ]
  node [
    id 478
    label "GGAGAGGCCTCTCCCCGGTCGGGCAGATCTGCGCAGGCCTGC"
  ]
  node [
    id 479
    label "GGGTAGATCTACCCGCG--CGCACAGATCTGTGGAGGCCTCC"
  ]
  node [
    id 480
    label "GGCGGGTACCCGCCACCGTGGTTCTGATCAGAGGGGGCCCTC"
  ]
  node [
    id 481
    label "GGGAGTGCGCTCCCCCC--GGGGCAGATCTGTGGTGGCCACC"
  ]
  node [
    id 482
    label "GGAGGGGCCCCTCCGCC--GGCACAGATCTGTGCTGGCCAGC"
  ]
  node [
    id 483
    label "GGACAGGCCTGTCCGCC--GGCGCAGATCTGCGCTAGCTAGC"
  ]
  node [
    id 484
    label "GGAGGGGCCCCTCCGTC--GGCCCAGATCTGGGTTGGCCAAC"
  ]
  node [
    id 485
    label "GGATAGGCCTATCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 486
    label "GGCGAGGCCTCGCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 487
    label "GCCAGATATCTGGCCCCGTGGGGCGGATCCGTGTAGGCCTAC"
  ]
  node [
    id 488
    label "GGAGGGGCTCCTCCCCC--GGGGCAGATCTGCGTTGGCCAAC"
  ]
  node [
    id 489
    label "GGGTAGATCTACCCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 490
    label "GGGCGTGCGCGCCCCCC--GGGACGGGCCCGTCTAGGCCTAG"
  ]
  node [
    id 491
    label "GGAGGGGCCCCTCCCCC--GGGACGGATCCGTGTTGGCCAAC"
  ]
  node [
    id 492
    label "GGATGGATCCATCCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 493
    label "CCAGCCATGGCTGGGCTCGAGCGAGGATCCTTACTGGCCGGT"
  ]
  node [
    id 494
    label "GGAGGAGCTCCTCCGCG--CGCACGGATCCGTAGTGGCCACT"
  ]
  node [
    id 495
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGTGGAGGCCTCC"
  ]
  node [
    id 496
    label "GGGGAGATCTCCCCCCAGTTGGGCGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 497
    label "GGAGGCTAGCCTCCGCG--CGCGCAGATCTGTGGTGGCCATC"
  ]
  node [
    id 498
    label "GGTGAGATCTCACCGTC--GACGCGGATCCGCAGAGGCCTCT"
  ]
  node [
    id 499
    label "GGTGGGATCCCACCGCC--GGCGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 500
    label "GGCAGGTACCTGCCCCC--GGGGCGGTACCGTCCAGGCCTGG"
  ]
  node [
    id 501
    label "GGGGGGATCCCCCCCTC--GAGACAGATCTGTGCAGGCCTGC"
  ]
  node [
    id 502
    label "GGGTCGGCCGGCCCCCCGTGGGGCGGATCCGCGTTGGCCAAC"
  ]
  node [
    id 503
    label "GGAGAGGTCTCTCCGCCGTGGCGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 504
    label "GCCAGGTACCTGGCTCC--GGAGCGGATCCGCAGAAGCTTCT"
  ]
  node [
    id 505
    label "GGGGAGGCCTCCCCCCC--GGGCCTGGCCAGGGGGGGCCCTC"
  ]
  node [
    id 506
    label "GGTGGAGCTCCACCGCC--GGCGGGGCGCTCCGCGGGCCCGC"
  ]
  node [
    id 507
    label "GGAGGGGCCCCTCCGTCGTGGCCCGGATCCGGGCTGGCCAGC"
  ]
  node [
    id 508
    label "GGTGGGGCCCCACCGCG--CGCGCGGATCCGCGGTGGCCACT"
  ]
  node [
    id 509
    label "GGAGGATATCCTCCCCC--GGGGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 510
    label "GGGGGCATGTCCTCGCTCGAGCTTTGATTAAGCCTGGCTGGG"
  ]
  node [
    id 511
    label "GGAGAGGCCTCTCCCCC--GGGACAGATCTGTGGAGGCCTCC"
  ]
  node [
    id 512
    label "GGGTCGATCGGCCCCCCGTGGGGTGGATCCACGCTGGCCAGC"
  ]
  node [
    id 513
    label "GGAGGCTAGCCTCCGTG--CACGCAGATCTGCGGTGGCCATC"
  ]
  node [
    id 514
    label "GGAGGGGCCCCTCCGCG--CGCGTGGATCCACGGTGGCCACT"
  ]
  node [
    id 515
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 516
    label "GGTGGGATCCCACCTGC--GCAGCAGATCTGTGCTGGCCGGC"
  ]
  node [
    id 517
    label "GGTGAGATCTCACCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 518
    label "GGCGGGTACCCGCCCCC--GGGTCTGATCAGAAGAGGCCTCT"
  ]
  node [
    id 519
    label "GGGGAGATCTCCCCGCG--CGCGGTGATCATCGGCGGCCGCC"
  ]
  node [
    id 520
    label "CGGGGTATGCCCCGGTA--TACCCGGATCCGGGCAAGCTTGC"
  ]
  node [
    id 521
    label "GGCGGGTACCCGCCCCA--TGGACTGATCAGTAGTGGCCACT"
  ]
  node [
    id 522
    label "GGAGGGATCCCTCCGCG--CGCGCGGATCCGCGTAGGCCTAC"
  ]
  node [
    id 523
    label "GGGTCGGTCGGCCCTCCGTGGAGCGGATCCGCGCTGGCCAGC"
  ]
  node [
    id 524
    label "GGAGAGGCCTCTCCGCCGTGGCGCAGATCTGCGTTGGCCAGC"
  ]
  node [
    id 525
    label "GGGGAGATCTCCCCCCC--GGGGCAGATCTGTGGAGGCCTCC"
  ]
  node [
    id 526
    label "GGGGAGATCTCCCCCCA--TGGACGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 527
    label "GGAGGGGCCCCTCCGCC--GGCACGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 528
    label "GGGGGGATCCCCCCGCC--GGCGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 529
    label "GGGGTA--TGCTTCGCTCGAGCTTTGATCAAGCTTGGCCAGG"
  ]
  node [
    id 530
    label "GGGGGTGCGCCCCCGCA--TGCATGGATCCATGCCAGCTGGC"
  ]
  node [
    id 531
    label "GGAGGGGCCCCTCCGGA--TCCGCGGATCCGCACTGGCCAGT"
  ]
  node [
    id 532
    label "GGAGGGATCCCTCCCCC--GGGACAGATCTGTGGAGGCCTCC"
  ]
  node [
    id 533
    label "GCCAGGTACCTGGCCCCGTGGGGCGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 534
    label "CCCGCGGCCGCGGGGTTCGAACGGGGATCCCCGCTGGCCGGC"
  ]
  node [
    id 535
    label "GCCGAGGCCTCGGCCCA--TGGGCTGATCAGCGGGGGCCCTC"
  ]
  node [
    id 536
    label "GGAGGGGCCCCTCCGCC--GGCGCAGATCTGCACAGGCCTGT"
  ]
  node [
    id 537
    label "GGAGGCCGGCCTCCGCG--CGCGCGGTACCGCGGTGGCCACT"
  ]
  node [
    id 538
    label "GGCGGGTACCCGCCCCCGTGGGGCGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 539
    label "GGGTAGGCCTGCCCGCCGTGGCGCAGATCTGTGGGGGCCCTC"
  ]
  node [
    id 540
    label "GGAGGAGCTCCTCCGCG--CGCACGGTACCGTGGTGGCCACT"
  ]
  node [
    id 541
    label "GGTGAGATCTCACCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 542
    label "GGGTCCATGGGCCCGCTTAAGCTTTGATCAAGATCGGCCGGT"
  ]
  node [
    id 543
    label "GGGGGGGTCCCCCCCCA--TGGACGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 544
    label "GGAGGGGCCCCTCCGCG--CGCGCGGATCCGCGGCGGCCGCC"
  ]
  node [
    id 545
    label "GGCAGGTACCTGCCCCC--GGGGCAGATCTGCGTTGGCCAAC"
  ]
  node [
    id 546
    label "GGAGGGATCCCTCCCCC--GGGGCAGATCTGCGATGGCCATC"
  ]
  node [
    id 547
    label "GGTGGGGCCCCACCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 548
    label "CCCGCCTAGGCGGGGCTCGAGCTCGGATCCGAGCTGGCCGGC"
  ]
  node [
    id 549
    label "GGGCAGGCCTGCCCCCG--CGGGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 550
    label "GGGTAGTACTACCCCCA--TGGGCTGATCAGCGGTGGCCATC"
  ]
  node [
    id 551
    label "GGAGGGGCCCCTCCGCG--CGCGCAGATCTGCGGCGGCCGTC"
  ]
  node [
    id 552
    label "GGGCAGTACTGCCCCCA--TGGGCAGATCTGCGGTGGCCATC"
  ]
  node [
    id 553
    label "TCCCTA--TGGGGAGCT--AGTTCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 554
    label "GGGGAGATCTCCCCCCC--GGGGCTGATCAGCGGAGGCCTCC"
  ]
  node [
    id 555
    label "GGAGGAGCTCCTCCATC--GGTACAGATCTGTGTAGGCCTAC"
  ]
  node [
    id 556
    label "GGAGGGGTCCCTCCCCC--GGGTCAGATCTGAGCTGGCCAGC"
  ]
  node [
    id 557
    label "GGCAGATATCTGCCCCC--GGGGCTGATCAGCGGGGGCCCTC"
  ]
  node [
    id 558
    label "GGGTAGGCCTACCCGCG--CGCACAGATCTGTAGAGGCCTCT"
  ]
  node [
    id 559
    label "GGAGGGGCCCCTCCCCC--GGGTCAGATCTGAGCAGGCCTGC"
  ]
  node [
    id 560
    label "GGAGAGGCCTCTCCCCC--GGGACGGATCCGTGCTGGCCAGC"
  ]
  node [
    id 561
    label "GGAGGAGCTCCTCCGCC--GGCGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 562
    label "GGGTCGGTCGGCCCTCC--GGAGCAGATCTGCGTAGGCCTAC"
  ]
  node [
    id 563
    label "GGCTGGTACCAGCCCCC--GGGGCAGATCTGTGCAGGCCTGC"
  ]
  node [
    id 564
    label "GGGGAGATCTCCCCCCC--GGGGCAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 565
    label "GGGGGTGCGCCCCCGCA--TGCCCAGATCTGGGGTGGCCATC"
  ]
  node [
    id 566
    label "GGTGAGGTCTCACCGGA--TCCGCGGATCCGCGAAGGCCTTC"
  ]
  node [
    id 567
    label "GGAGGAATTCCTCCGCG--CGCGCGGTACCGCAGTGGCCACT"
  ]
  node [
    id 568
    label "GGGTAGGCCTGCCCGCC--GGCACAGATCTGTGGCGGCCGCC"
  ]
  node [
    id 569
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGCGATGGCCATC"
  ]
  node [
    id 570
    label "GGTTCCATGGAACCGTGTGCACCTGGGTCCAGCTGAGCTCAG"
  ]
  node [
    id 571
    label "GGTGAGTACTCACCCTC--GAGGCAGATCTGCCGTGGCCACG"
  ]
  node [
    id 572
    label "GCTCTG--CAGGGCGGC--GCCTTCGGCTGAAGGTGGCCACC"
  ]
  node [
    id 573
    label "TCCTGC--GTAGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 574
    label "GGAGGGATCCCTCCCCC--GGGGCAGATCTGCAAAGGCCTTT"
  ]
  node [
    id 575
    label "GGAGAGGCCTCTCCCCC--GGGGCAGATCTGTGTTGGCCAAC"
  ]
  node [
    id 576
    label "GGGGAGATCTCCCCCCC--GGGGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 577
    label "GGGTGGATCCACCCCCCGTGGGACAGATCTGTGTAGGCCTAC"
  ]
  node [
    id 578
    label "GGTGGGGCCCCACCCCC--GGGACAGATCTGTGGTGGCCACC"
  ]
  node [
    id 579
    label "GGGGGTGCGCCCCCCCC--GGGGCAGATCTGCGGAGGCCTCC"
  ]
  node [
    id 580
    label "GGGGGTATGCCCCTCTC--GAGTTTGATCAAGTCTGGCCAGG"
  ]
  node [
    id 581
    label "GGTGGGGCCCCACCCCC--GGGTCAGATCTGAGAAGGCCTTC"
  ]
  node [
    id 582
    label "CCCGCGGCCGCGGGGCCTGGGCGCGGATCCGCCCCGGCCGGG"
  ]
  node [
    id 583
    label "GGGAGCGCGCTCCCCCCGTGGGACGGGCCCGTCAAGGCCTTG"
  ]
  node [
    id 584
    label "GGGCAGTACTGCCCCCA--TGGGCTGATCAGCGGAGGCCTTC"
  ]
  node [
    id 585
    label "GGATGGGTCCATCCCCC--GGGGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 586
    label "GGGGGGATCCCCCCCCA--TGGACGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 587
    label "GGGTCAGCTGGCCCCCCGTGGGGCGGATTCGCGTTGGCCAAC"
  ]
  node [
    id 588
    label "GGGGAGATCTCCCCCCC--GGGGCGGATCCGTGATGGCCATC"
  ]
  node [
    id 589
    label "GGGTAAGCTTACCCGCC--GGCGCGGATCCGTGTAGGCCTAC"
  ]
  node [
    id 590
    label "GGAGAGGCCTCTCCCCC--GGGGCAGATCTGTGCTGGCCAGC"
  ]
  node [
    id 591
    label "GGGGAGGTCTCCCCCTC--GAGACAGATCTGTGCAGGCCTGC"
  ]
  node [
    id 592
    label "GGGGGGATCCCCCCGCC--GGCGCAGATCTGCGCAGGCCTGC"
  ]
  node [
    id 593
    label "GGAGGGGCCCCTCCGCC--GGCGGGGATCCCCGCAGGCCTGC"
  ]
  node [
    id 594
    label "GGAGGGGCCCTTCCGCG--CGCGCGGATCCGCGGCAGCTGCC"
  ]
  node [
    id 595
    label "GGAGGGGCCCCTCCGCC--GGCGCGGATCCGCGCAGGCCTGC"
  ]
  node [
    id 596
    label "GGGAAGATCTTCCCCCG--CGGGCAGATCTGTGTAGGCCTGC"
  ]
  node [
    id 597
    label "GGTGGGATCCCACCGTC--GACGCAGATCTGCAGAGGCCTCT"
  ]
  node [
    id 598
    label "GGAGGGGCCCCTCCCCC--GGGGCAGATCTGTACTGGCCAGT"
  ]
  node [
    id 599
    label "GGGGGGGTCCCCCCCCA--TGGACAGATCTGTGAAGGCCTTC"
  ]
  node [
    id 600
    label "GGAGGAGCTCCTCCCCC--GGGGCGGATCCGCGTTGGCCAAC"
  ]
  node [
    id 601
    label "GGGGGGATCCCCCCCCC--GGGCCTGGCTAGGGGGGGCCCTC"
  ]
  node [
    id 602
    label "GGTGGAGCTCCACCCCC--GGGGCAGATCTGTGTTGGCCAAC"
  ]
  node [
    id 603
    label "GGAGGATATCCTCCGTG--CACGCAGATCTGCGGTGGCCATC"
  ]
  node [
    id 604
    label "GGGGAGTACTCCCCCCC--GGGGCAGATCTGTCAAGGCCTTG"
  ]
  node [
    id 605
    label "GGTGGGGCCCCACCCCC--GGGACGGGCCCGTGAAGGCCTTC"
  ]
  node [
    id 606
    label "GGCGGGATCCCGCCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 607
    label "GGTTGGGCCCAACCGCT--AGCACGGTACCGTATAGGCCTAT"
  ]
  node [
    id 608
    label "GGGCAGATCTGCCCCTC--GAGGCAGATCTGCGGAGGCCTTC"
  ]
  node [
    id 609
    label "GGAAAGATCTTTCCGCG--CGTGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 610
    label "GGAGGGGCCCCTCCGCG--CGCGGTGGCCACTGGGGGCCCTC"
  ]
  node [
    id 611
    label "GATGGGGCCCCATCCCC--GGGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 612
    label "GGAGGGGCCCCTCCCCC--GGGTCAGATCTGAGATGGCCGTC"
  ]
  node [
    id 613
    label "GGAGGAGCTCCTCCACC--GGTACAGATCTGTGTAGGCCTAC"
  ]
  node [
    id 614
    label "CCGACCATGGTCGGGCTCGAGCGAGGATCCTTACTGGCCGGT"
  ]
  node [
    id 615
    label "TCCCGG--CTGGGAGCT--AGTTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 616
    label "GGGTCGATCGGCCCGCCGTGGCGCAGATCTGCGCTGGCCAGC"
  ]
  node [
    id 617
    label "GGAGGGGCCCCTCCCCC--GGGTCAGATCTGAGGTGGCCACC"
  ]
  node [
    id 618
    label "GGGGAA--TTCCCCCCC--GGGGCGGATCCGCGTAGGCCTAC"
  ]
  node [
    id 619
    label "GGGTAGGCCTGCCCGCC--GGCGCAGATCTGTGATGGCCATC"
  ]
  node [
    id 620
    label "GGCGGGTACCCGCCCCC--GGGGCTGATCAGCAGTGGCCACT"
  ]
  node [
    id 621
    label "GGGCAAATTTGCCCCCA--TGGGCAGATCTGCGGTGGCCATC"
  ]
  node [
    id 622
    label "GGAGAGGCCTCTCCCCGGTCGGGCAGTACTGCACTGGCCAGT"
  ]
  node [
    id 623
    label "GGAGGGATCCCTCCCCC--GGGACGGATCCGTGTTGGCCAAC"
  ]
  node [
    id 624
    label "GGTGAGTACTCACCCTC--GAGGCAGATCTGCGAAGGCCTTC"
  ]
  node [
    id 625
    label "GGCAGGTACCTGCCCCCGTGGGGCGGATCCGTACAGGCCTGT"
  ]
  edge [
    source 0
    target 120
  ]
  edge [
    source 0
    target 309
  ]
  edge [
    source 3
    target 82
  ]
  edge [
    source 6
    target 294
  ]
  edge [
    source 17
    target 539
  ]
  edge [
    source 18
    target 333
  ]
  edge [
    source 19
    target 154
  ]
  edge [
    source 23
    target 495
  ]
  edge [
    source 28
    target 385
  ]
  edge [
    source 30
    target 477
  ]
  edge [
    source 32
    target 446
  ]
  edge [
    source 33
    target 591
  ]
  edge [
    source 34
    target 369
  ]
  edge [
    source 38
    target 207
  ]
  edge [
    source 38
    target 277
  ]
  edge [
    source 40
    target 388
  ]
  edge [
    source 47
    target 386
  ]
  edge [
    source 52
    target 74
  ]
  edge [
    source 61
    target 177
  ]
  edge [
    source 62
    target 120
  ]
  edge [
    source 62
    target 309
  ]
  edge [
    source 62
    target 76
  ]
  edge [
    source 64
    target 279
  ]
  edge [
    source 64
    target 491
  ]
  edge [
    source 74
    target 208
  ]
  edge [
    source 74
    target 619
  ]
  edge [
    source 75
    target 177
  ]
  edge [
    source 76
    target 384
  ]
  edge [
    source 76
    target 547
  ]
  edge [
    source 81
    target 385
  ]
  edge [
    source 82
    target 400
  ]
  edge [
    source 84
    target 403
  ]
  edge [
    source 86
    target 177
  ]
  edge [
    source 91
    target 564
  ]
  edge [
    source 102
    target 591
  ]
  edge [
    source 109
    target 300
  ]
  edge [
    source 114
    target 263
  ]
  edge [
    source 114
    target 154
  ]
  edge [
    source 118
    target 445
  ]
  edge [
    source 121
    target 460
  ]
  edge [
    source 121
    target 213
  ]
  edge [
    source 123
    target 206
  ]
  edge [
    source 130
    target 297
  ]
  edge [
    source 131
    target 178
  ]
  edge [
    source 132
    target 377
  ]
  edge [
    source 142
    target 250
  ]
  edge [
    source 154
    target 203
  ]
  edge [
    source 156
    target 564
  ]
  edge [
    source 160
    target 611
  ]
  edge [
    source 161
    target 213
  ]
  edge [
    source 168
    target 546
  ]
  edge [
    source 168
    target 179
  ]
  edge [
    source 173
    target 284
  ]
  edge [
    source 174
    target 469
  ]
  edge [
    source 176
    target 492
  ]
  edge [
    source 177
    target 594
  ]
  edge [
    source 181
    target 594
  ]
  edge [
    source 203
    target 263
  ]
  edge [
    source 205
    target 300
  ]
  edge [
    source 219
    target 285
  ]
  edge [
    source 250
    target 569
  ]
  edge [
    source 257
    target 491
  ]
  edge [
    source 271
    target 363
  ]
  edge [
    source 272
    target 303
  ]
  edge [
    source 273
    target 363
  ]
  edge [
    source 279
    target 374
  ]
  edge [
    source 283
    target 449
  ]
  edge [
    source 285
    target 460
  ]
  edge [
    source 287
    target 567
  ]
  edge [
    source 288
    target 365
  ]
  edge [
    source 292
    target 324
  ]
  edge [
    source 301
    target 374
  ]
  edge [
    source 308
    target 369
  ]
  edge [
    source 309
    target 547
  ]
  edge [
    source 315
    target 617
  ]
  edge [
    source 321
    target 524
  ]
  edge [
    source 323
    target 382
  ]
  edge [
    source 328
    target 410
  ]
  edge [
    source 335
    target 544
  ]
  edge [
    source 349
    target 369
  ]
  edge [
    source 358
    target 543
  ]
  edge [
    source 359
    target 554
  ]
  edge [
    source 363
    target 488
  ]
  edge [
    source 373
    target 619
  ]
  edge [
    source 384
    target 611
  ]
  edge [
    source 394
    target 566
  ]
  edge [
    source 398
    target 556
  ]
  edge [
    source 405
    target 561
  ]
  edge [
    source 409
    target 495
  ]
  edge [
    source 415
    target 584
  ]
  edge [
    source 419
    target 609
  ]
  edge [
    source 444
    target 448
  ]
  edge [
    source 459
    target 585
  ]
  edge [
    source 517
    target 541
  ]
  edge [
    source 525
    target 576
  ]
  edge [
    source 543
    target 586
  ]
  edge [
    source 555
    target 613
  ]
]
