graph [
  node [
    id 0
    label "GGCCAGGCCTGGCCGCTCGAGCCCCGCGCGGGGGCGGCCGCC"
  ]
  node [
    id 1
    label "GCCCGGATCCGGGCGCTCGAGCGAGGATCCTCCTTGGCCAAG"
  ]
  node [
    id 2
    label "GGATCGATCGATCCGCTCGAGCACGGATCCGTGGCAGCTGTC"
  ]
  node [
    id 3
    label "GGTGCCATGGCACCGCTCGAGCACGGATCCGTCCTGGCCAGG"
  ]
  node [
    id 4
    label "GCCAAA--TTTGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 5
    label "GGTATCTAGATACCGCTCGAGCAAGGATCCTTCCCGGCCGGG"
  ]
  node [
    id 6
    label "GCTGAAATTTCGGCGTC--GACTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 7
    label "GTCGAAATTTTGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 8
    label "GCCGGTGCGCTGGCGCTCGAGCGAGGATCCTTGTCAGCTGAC"
  ]
  node [
    id 9
    label "GGCTGGGCCCAGCCGCTCGAGCTCCGCGCGGAGCCGGCCGGC"
  ]
  node [
    id 10
    label "CGGAACGCGTTCCGACTCGAGTTCTGATCAGAACAGGCCTGT"
  ]
  node [
    id 11
    label "GCCCAGATCTGGGCGCTCGAGCGGGGATCCCCGGTGGCCGCC"
  ]
  node [
    id 12
    label "GCCCAGATCTGGGCGCTCGAGCGAGGATCCTCCTTGGCCGAG"
  ]
  node [
    id 13
    label "GCCCAGGTCTGGGCGCTCGAGCTCAGATCTGACCCGGCCGGG"
  ]
  node [
    id 14
    label "GCCAAA--TTTGGCGCTCGAGCTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 15
    label "GGCCGGGCCCGGCCGCTCGAGCAGGGATCCCTGGGGGCCCTC"
  ]
  node [
    id 16
    label "GCCGCTGCGGCGGCGCTCGAGCGTGGATCCACACCGGCCGGT"
  ]
  node [
    id 17
    label "GGCTCGGCCGAGCCGCTCGAGCACGGATCCGTGGCGGCCGTC"
  ]
  node [
    id 18
    label "GGTGATGCATCACCGCTCGAGCATAGATCTATGGCGGCCGTC"
  ]
  node [
    id 19
    label "GGCCGGGCCCGGCCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 20
    label "GCCCGGATCCGGGCGCTCGAGCGAGGATCCTCGGCAGCTGTC"
  ]
  node [
    id 21
    label "GCCGCCTAGGCGGCGCTCGAGCCTCGATCGAGCCTGGCCGGG"
  ]
  node [
    id 22
    label "GGCCTG--CAGGCCGCTCGAGCACGGATCCGTGGCAGCTGTC"
  ]
  node [
    id 23
    label "GCTTCTGCGGAAGCGCTCGAGCGGGGATCCCCGGTGGCCACT"
  ]
  node [
    id 24
    label "GCCCAGGCCTGGGCGCTCGAGCGCGGATCCGCGCTGGCCGGC"
  ]
  node [
    id 25
    label "GGCTCGGCCGAGCCGCTCGAGCAGGGATCCCTGGCGGCCGTC"
  ]
  node [
    id 26
    label "GCTGAAGCTTTAGCGCTCGAGCTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 27
    label "TCATAC--GTATGAGCTCGAGCTTACTAGTAAGCAGGCCTGC"
  ]
  node [
    id 28
    label "GGTAATGCATTACCGCTCGAGCCAGCATGCTGGTTGGCCAAT"
  ]
  node [
    id 29
    label "CCCCCGATTGGGGGGCTCGAGTCTTGTACAAGGTCAGCTGAC"
  ]
  node [
    id 30
    label "GCCCAGGCCTGGGCGCTCGAGCTGCGATCGCAGGTGGCCGCC"
  ]
  node [
    id 31
    label "GCCGAGGCCTCGGCGCTCGAGCCGTGATCACGGGCGGCCGCC"
  ]
  node [
    id 32
    label "GCCGAAATTTTGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 33
    label "TCCCGG--TTGGGGGTCTGGATCGGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 34
    label "GGCCTGGCCGGGCCGCTCGAGCGAGGATCCTTGGCAGCTGCC"
  ]
  node [
    id 35
    label "GCTCGA--TCGGGCGCTCGAGCTTAGATCTAAACCAGCTGGT"
  ]
  node [
    id 36
    label "GCCAAGGCCTTGGCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 37
    label "GCCGGGATCCTGGCGCTCGAGCGAGGATCCTCACCAGCTGGT"
  ]
  node [
    id 38
    label "GCCGAAATTTCGGCGCTCGAGCTTAGATCTGACCCGGCCGGG"
  ]
  node [
    id 39
    label "GCCTCGTACGAGGCGCTCGAGCGCGGATCCGCCCTGGCCGGG"
  ]
  node [
    id 40
    label "GGCTTGGCCGAGCCGCTCGAGCGAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 41
    label "GCCGAAGCTTTGGCGCTCGAGCTTAGATCTGACCTGGCCGGG"
  ]
  node [
    id 42
    label "GCCGGGATCCTGGCGCTCGAGCGAGGATCCTCGCCAGCTGGC"
  ]
  node [
    id 43
    label "GGCTTGATCAAGCCGCTCGAGCGGAGATCTCCGGTGGCCGCC"
  ]
  node [
    id 44
    label "GCCCGGATCCGGGCGCTCGAGCAGGGATCCCTGCTGGCCGGC"
  ]
  node [
    id 45
    label "GCCCGAATTCGGGCGCTCGAGCAAGGATCCTTGACGGCCGTC"
  ]
  node [
    id 46
    label "GGCTTTATAAAGCCGCTCGAGCACGGTACCGTGGTGGCCGCC"
  ]
  node [
    id 47
    label "GCCTAAGTTTAGGCGCTCGAGCACAGATCTGTAACGGCCGTT"
  ]
  node [
    id 48
    label "GCCGAGGCCTCGGCGCTCGAGCGAGGATCCTCGGCGGCCGCC"
  ]
  node [
    id 49
    label "GGCTAGATCTGGCCGCTCGAGCACGGATCCGTGGCGGCCGCC"
  ]
  node [
    id 50
    label "GCCCAGATCTGGGCGCTCGAGCGAGGATCCTCGTTGGCCGAC"
  ]
  node [
    id 51
    label "GGTCAGGCCTGACCGCTCGAGCTCGGATCCGAGGGAGCTCCC"
  ]
  node [
    id 52
    label "GGCTCGGCCGAGCCGCT--AGCACGGATCCGTGGCGGCCGTC"
  ]
  node [
    id 53
    label "CCCCTGGCTGGGGGGCTCGAGCCCTGTATAGGATCCGCGGAT"
  ]
  node [
    id 54
    label "GCCTCGATCGGGGCGCTCGAGCTACGATCGTAACCAGCTGGT"
  ]
  node [
    id 55
    label "GCCTCTGCGGAGGCGCTCGAGCGGGGATCCCCGTTGGCCGAC"
  ]
  node [
    id 56
    label "GGTATTTAGATACCGCTCGAGCACGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 57
    label "GCTGGAATTCCAGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 58
    label "GGTTTCGCGAAACCGCTCGAGCACGGATCCGTGGCGGCTGCC"
  ]
  node [
    id 59
    label "GGCCGGGCCCGGCCGCTCGAGCACGGATCCGTGGCGGCCGTC"
  ]
  node [
    id 60
    label "GCCTCGGCTGAGGCGCTCGAGCACGGATCCGTGACAGCTGTC"
  ]
  node [
    id 61
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 62
    label "GCTGAAATTTCAGCGCTCGAGCTTAGATCTGACCTGGCCGGG"
  ]
  node [
    id 63
    label "GGCTCTGCGGAGCCGCTCGAGCAACGATCGTTACCGGCCGGT"
  ]
  node [
    id 64
    label "GCCAAGATCTTGGCGCTCGAGCTCGCATGCGAGCCGGCCGGC"
  ]
  node [
    id 65
    label "GGCTAAATTTAGCTGCTCGAGCAAGGATCCTTGGTGGCTACC"
  ]
  node [
    id 66
    label "GGCTAGGCCTAGCCGCTCGAGCCAGGATCCTGGCCGGCCGGC"
  ]
  node [
    id 67
    label "TTCCTGGTCGGGAAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 68
    label "GGCCAGTACTGGCCGCTCGAGCGCGGATCCGCCGTGGCCGCG"
  ]
  node [
    id 69
    label "GCCCGGATTCGGGCGCTCGAGCAGGGATCCTTGGCGGCCGCC"
  ]
  node [
    id 70
    label "GGTACCATGGTACCGCTCGAGCAAGGATCCTTACTGGCCAGT"
  ]
  node [
    id 71
    label "GCCGAGTACTCGGCGCTCGAGCAAGGATCCTTTAGGGCCCTG"
  ]
  node [
    id 72
    label "GCCGGGATCCTGGCGCTCGAGCGTGGATCCACACGAGCTCGT"
  ]
  node [
    id 73
    label "GCGGTTTAAATCGCGCTCGAGCCATGATCATGCTGTGCACAG"
  ]
  node [
    id 74
    label "GGCCACGCGTGGCCGCTCGAGCAAGGATCCTTGTTGGCCAAC"
  ]
  node [
    id 75
    label "GCCGCGATTGCGGCGCTCGAGCGAGGATCCTCGACAGCTGTC"
  ]
  node [
    id 76
    label "GCAGCCGCGGCTGCGCTCGAGCCCCGGCCGGGCCGGGCCCGG"
  ]
  node [
    id 77
    label "GTCGCGATCGTGACGTGTGCATACAGATCTGTATCGGCCGGT"
  ]
  node [
    id 78
    label "GCCCGGGCCCGGGCGCTCGAGCTGCGATCGCAGGTGGCCGCC"
  ]
  node [
    id 79
    label "GCCTCGATCGGGGCGCTCGAGCTTAGATCTAAACCAGCTGGT"
  ]
  node [
    id 80
    label "GGCCACGCGTGGCCGCTCGAGCAAGGATCCTTGTTGGCCAAT"
  ]
  node [
    id 81
    label "GCCGAGGCCTCGGCGCTCGAGCGAGGCGCCTCGGCAGCTGCC"
  ]
  node [
    id 82
    label "GGCTCTGCGGAGCCGCTCGAGCCACGATCGTGAGGGGCCCCT"
  ]
  node [
    id 83
    label "GCCGAGATTTCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 84
    label "GCGGTTTAAGTCGCGCTCGAGCCATGATCATGCTGTGCACAG"
  ]
  node [
    id 85
    label "GGCTCGGCCGAGCCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 86
    label "GCCGCTTAGGCGGCGCTCGAGCAAGGATCCTTCGCAGCTGCG"
  ]
  node [
    id 87
    label "TCCCTG--TGGGGAGCT--AGCTCTGCGTGGACCAGGCCTGG"
  ]
  node [
    id 88
    label "GCCGAAATTTCGGCGCTCGAGCTCAGATCTGACTCGGCTGGG"
  ]
  node [
    id 89
    label "GCCTCGATCGAGGCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 90
    label "GGCCAGATCTGGCCGCTCGAGCGAGGATCCTTGGCAGCTGCC"
  ]
  node [
    id 91
    label "GCCGAAATTTCGGCGCTCGAGCTTAGATCTAACCCGGCCGGG"
  ]
  node [
    id 92
    label "GGCTAGATCTGGCCGCTCGAGCAACGATCGTTGCCGGCCGGC"
  ]
  node [
    id 93
    label "GCCTTGATCAAGGCGCTCGAGCTTAGATCTAAACCAGCTGGT"
  ]
  node [
    id 94
    label "GGTCGG--CCGACCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 95
    label "GCCCAGGCCTGGGCGCTCGAGCGCGGATCCGCGGCAGCTGTC"
  ]
  node [
    id 96
    label "GGCTTCGCGAAGCCGCTCGAGCACGGTACCGTGGCAGCTGCC"
  ]
  node [
    id 97
    label "GGCGAGGCCTCGCCGCTCGAGCGTGGATCCATGACGGCCGTC"
  ]
  node [
    id 98
    label "GCCGAAATTTCGGCGCT--AGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 99
    label "GGCCGG--CCGGCCGCTCGAGCGAGGATCCTTGGTGGCCGCC"
  ]
  node [
    id 100
    label "GCCGCCGCGGCGGCGCTCGAGCCCCGGCCGGGCGGGGCCCCG"
  ]
  node [
    id 101
    label "GGCCAAGCTTGGCCGCTCGAGCGAGGATCCTTGGTGGCCGCC"
  ]
  node [
    id 102
    label "GCCGCGGCTGCGGCGCTCGAGCGAGGATCCTCGGCGGCCGCC"
  ]
  node [
    id 103
    label "GCCTCGGCTGAGGCGCTCGAGCGAGGATCCTCGACAGCTGTC"
  ]
  node [
    id 104
    label "GCCGAAATTTTGGCGCTCGAGTTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 105
    label "GGCCAGATCTGGCCGCTCGAGCCACGCGCGTGGCCGGCCGGC"
  ]
  node [
    id 106
    label "GGCTTTGCAAAGCCGCTCGAGCAAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 107
    label "GGCTTGGCCAAGCCGCTCGAGCCTTGATCAAGGGCAGCTGTC"
  ]
  node [
    id 108
    label "GGTCAGGCCTGACCGCTCGAGCATGGATCCATGCCGGCCGGC"
  ]
  node [
    id 109
    label "GGCCATGCATGGCCGCTCGAGCAAGGATCCTTGTTGGCCGAC"
  ]
  node [
    id 110
    label "GGCCAGGTCTGGCCGCTCGAGCTCCGCGCGGAGCCGGCCGGC"
  ]
  node [
    id 111
    label "GGCCAGATCTGGCCGCTCGAGCGAGGATCCTCGGGGGCCCTC"
  ]
  node [
    id 112
    label "GCTAAA--TTTGGCGCTCGAGCCTAGATCTGGCTTGGCCGAG"
  ]
  node [
    id 113
    label "GGCGCGGCCGTGCCGCTCGAGCTCCGCGTGGAACCAGCTGGT"
  ]
  node [
    id 114
    label "GCTGCTTAAGCAGCGCTCGAGCTATGATCATACTGTGCACAG"
  ]
  node [
    id 115
    label "GGTGCCATGGTACCGCTCGAGCACGGATCCGTCCTAGCTAGG"
  ]
  node [
    id 116
    label "GGCCAATATTGGCCGCTCGAGCAGTGATCACTCTTGGCCGAG"
  ]
  node [
    id 117
    label "GCCTAGTACTAGGCGCTCGAGCAAGGATCCTTTAGGGCCCTG"
  ]
  node [
    id 118
    label "GGCTCGGCCGAGCCGCTCGAGCGAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 119
    label "GCCACGGCCGTGGCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 120
    label "GCCTCTGCGGAGGCGCTCGAGCTATGCGCATAGCAAGCTTGC"
  ]
  node [
    id 121
    label "GCCTCGGCTGAGGCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 122
    label "GCCGAAATTTCGGCGCT--AGCTTAGATCTGACCTGGCCGGG"
  ]
  node [
    id 123
    label "GCGGCTTAAGCCGCGCTCGAGCTCAGATCTGGCTGTGCACAG"
  ]
  node [
    id 124
    label "GGTGCCATGGCACCGCTCGAGCAAGGATCCTTGCTGGCCAGC"
  ]
  node [
    id 125
    label "GCCGCTGCGGCGGCGCTCGAGCAGGGATCCCTATCAGCTGAT"
  ]
  node [
    id 126
    label "GGGCAGGCCTGCCCGCTCGAGCATCGCGTGATGGCGGCCGCC"
  ]
  node [
    id 127
    label "GCCGAGGTCTCGGCGCTCGAGCGAAGCGCTTCGATGGCCGTC"
  ]
  node [
    id 128
    label "GGCCGG--CCGGCCGCTCGAGCACGGATCCGTGGCGGCCGTC"
  ]
  node [
    id 129
    label "GCCCATGCGTGGGCGCTCGAGCTTCGATCGAAAGCGGCCGCT"
  ]
  node [
    id 130
    label "GGCCAGATCTGGCCGCTCGAGCTCCGCGTGGAGCCAGCTGGC"
  ]
  node [
    id 131
    label "GCCTCAGCTGAGGCGCTCGAGCCCAGATCTGGCCCGGCCGGG"
  ]
  node [
    id 132
    label "GGCAATGCGTTGCCGCTCGAGCAACGATCGTTGGCGGCCGCC"
  ]
  node [
    id 133
    label "GGTATCTAGATACCGCTCGAGCACGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 134
    label "GGTTCAGCTGAACCGCTCGAGCATGGATCCATGGCAGCTGTC"
  ]
  node [
    id 135
    label "GCCAGA--TTTGGCGCTCGAGCTTAGATCTAATCTGGCCGGG"
  ]
  node [
    id 136
    label "GCCAAA--TTTGGCGTC--GACTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 137
    label "GCCCAGGCCTGGGCGCTCGAGCGGGGATCCCCAGCAGCTGTT"
  ]
  node [
    id 138
    label "GGCCAGATCTGGCCGCTCGAGCTTCGATCGAAGGCGGCCGCC"
  ]
  node [
    id 139
    label "GCCGAAATTTCGGCGCTCGAGCTTAGATCTGACCTAGCTGGG"
  ]
  node [
    id 140
    label "GCTGAAGCTTCAGCGCT--AGCTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 141
    label "GGTGGGATCCCACCGCTCGAGCGTGGATCCACGACAGCTGTC"
  ]
  node [
    id 142
    label "GGCCGG--CCGGCCGCTCGAGCGAGGATCCTTGGCAGCTGCC"
  ]
  node [
    id 143
    label "GCCGAGGCCTCGGCGCTCGAGCCGCGATTGCGGACAGCTGTC"
  ]
  node [
    id 144
    label "GCCCAGATCTGGGCGCTCGAGCGAGGATCCTCACTGGCCGGT"
  ]
  node [
    id 145
    label "GGCTGCATGCAGCCGCTCGAGCACGGATCCGTCCTGGCCAGG"
  ]
  node [
    id 146
    label "GGTGAGATCTCACCGCTCGAGCGAGGATCCTCGGCAGCTGCC"
  ]
  node [
    id 147
    label "GGCTCGGCCGAGCCGCTCGAGCATGGATCCATGGCGGCCGTC"
  ]
  node [
    id 148
    label "GGTTAAATTTAGCTGCTCGAGCAAGGATCCTTGGTGGCCACC"
  ]
  node [
    id 149
    label "GGGCAGGCCTGCCCGCTCGAGCTCCGCGTGGAGGCGGCCGCC"
  ]
  node [
    id 150
    label "GCCGAGGCCTCGGCGCTCGAGCGGGGATCCCCGGGAGCTCTC"
  ]
  node [
    id 151
    label "TAGTCG--CGACTAGCC--GGCATGGATCCATGCAGGCCTGC"
  ]
  node [
    id 152
    label "GCCCGGGTCCGGGCGCTCGAGCTGCGGCCGCAGCCGGCCGGC"
  ]
  node [
    id 153
    label "GGCTTGGCCAAGCCGCTCGAGCATGGATCCATGGCGGCCGTC"
  ]
  node [
    id 154
    label "GGCGAGATCTCGCCGCTCGAGCGCGGATCCGCCCCAGCTGGG"
  ]
  node [
    id 155
    label "GCCTGG--TCGGGCGCTCGAGCTCTGATCAGGGTGGGCCCGC"
  ]
  node [
    id 156
    label "GCCCGGGTCCGGGCGCTCGAGCTGCGGCCGCACCCGGCCGGG"
  ]
  node [
    id 157
    label "GCCGAGGCCTCGGCGCTCGAGCGCGGATCCGCCCCAGCTGGG"
  ]
  node [
    id 158
    label "GGCCTGGCCAGGCCGCTCGAGCCTTGATCAAGGGCAGCTGTC"
  ]
  node [
    id 159
    label "GCTGGG--TCCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 160
    label "GGCCGG--CCGGCCGCTCGAGCATGGATCCATGGCAGCTGTC"
  ]
  node [
    id 161
    label "GCCGAAATTTCGGCGCTCGAGCCTAGATCTAGCTTGGCCGAG"
  ]
  node [
    id 162
    label "GCCCGAATTCGGGCGCTCGAGCGCGGATCCGCCCTGGCCGGG"
  ]
  node [
    id 163
    label "GCCTCGATCGAGGCGCTCGAGCGGGGATCCCCGGTGGCCGCC"
  ]
  node [
    id 164
    label "GCCTTAGCTGAGGCGCTCGAGCCCAGATCTGGCCCGGCCGGG"
  ]
  node [
    id 165
    label "GTCAAA--TTTGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 166
    label "GGCTCGGCCGAGCCGCTCGAGCAAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 167
    label "GGCCAGGCCTGGCCGCTCGAGCGTGGATCCACGACGGCCGTC"
  ]
  node [
    id 168
    label "GCCAAA--TTTGGCGCC--GGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 169
    label "GGCTCGGCCGAGCCGCTCGAGCAAGGATCCTTGGCGGCCGTT"
  ]
  node [
    id 170
    label "GGCGTGGTCACGCCGCTCGAGCACGGATCCGTGGCAGCTGTC"
  ]
  node [
    id 171
    label "GCCTCGGCTGAGGCGCTCGAGCTAGCATGCTAACCGGCCGGT"
  ]
  node [
    id 172
    label "GGCTAGATCTAGCCGCTCGAGCTCCGCGTGGAGCCGGCCGGC"
  ]
  node [
    id 173
    label "GCCCGGGCCCGGGCGCTCGAGCCATGATCATGGGCGGCCGTC"
  ]
  node [
    id 174
    label "GGGCAGGCCTGCCCGCTCGAGCCAGGATCCTGGCGGGCCCGC"
  ]
  node [
    id 175
    label "GCTTTTATAAGGGCGCTTAAGCATAAATTTATATGAGCTCAT"
  ]
  node [
    id 176
    label "GCCTGGGTCCAGGCGCTCGAGCTTCGATCGAACGCGGCCGCG"
  ]
  node [
    id 177
    label "GCCACCTAGGTGGCGCTCGAGCGCAGATCTGCTGGAGCTCCG"
  ]
  node [
    id 178
    label "GGCTCTTAGGAGCCGCTCGAGCGAGGCGCCTTACTGGCCAGT"
  ]
  node [
    id 179
    label "GGTTCAGCTGAACCGCTCGAGCAGGGATCCCTGGCGGCCGTC"
  ]
  node [
    id 180
    label "GGCCAGGCCTGGCCGCTCGAGCTCCGCGCGGAGCCGGCCGGC"
  ]
  node [
    id 181
    label "GCTGACTAGTTAGCGCTCGAGCTCAGATCTGACTGAGCTCAG"
  ]
  node [
    id 182
    label "GCCTTCGCGAAGGCGCTCGAGCGAGGATCCTCACTGGCCGGT"
  ]
  node [
    id 183
    label "GGCCCGGCTGGGCCGCTCGAGCGGGGATCCCCGGCGGCCGCC"
  ]
  node [
    id 184
    label "GCCTAG--CTAGGTGCTCGAGCCCTACGTAGGGCGGGCCCGC"
  ]
  node [
    id 185
    label "GGGCAGATCTGCCCGCTCGAGCAAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 186
    label "GCCCAGATCTGGGCGCTCGAGCGCGGATCCGCCGTGGCCGCG"
  ]
  node [
    id 187
    label "GCCCAGATCTGGGCGCTCGAGCAGGGATCCCTCGTGGCCGCG"
  ]
  node [
    id 188
    label "GGCTCGGCCGAGCCGCTCGAGCTAGGATCCTAGGCGGCCGTT"
  ]
  node [
    id 189
    label "GCCCAGATCTGGGCGCTCGAGCGAGGATCCTCGGCAGCTGTC"
  ]
  node [
    id 190
    label "GGCCAGATCTGGCCGCTCGAGCCAGCATGCTGGCCGGCCGGC"
  ]
  node [
    id 191
    label "GGCTTGATCAAGCCGCTCGAGCGAAGATCTTCGGTGGCCGCC"
  ]
  node [
    id 192
    label "GGGCAGATCTGCCCGCTCGAGCCAGGATCCTGGCCGGCCGGC"
  ]
  node [
    id 193
    label "GCCGAGATCTCGGCGCTCGAGCGGGGATCCCCGGGAGCTCTC"
  ]
  node [
    id 194
    label "GCCTCGGCTGAGGCGCTCGAGCAAGGATCCTTCGCAGCTGCG"
  ]
  node [
    id 195
    label "GGCTCGGCCGAGCCGCTCGAGCTAGGATCCTAGGCGGCCGTC"
  ]
  node [
    id 196
    label "GCCCAGTACTGGGCGCTCGAGCAAGGATCCTTTAGGGCCCTG"
  ]
  node [
    id 197
    label "GCTGAA--TTCAGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 198
    label "GCCTAGGCCTGGGCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 199
    label "GCCGCGGCCGCGGCGTTCGAACCTGGATCCAGGGGTGCACCC"
  ]
  node [
    id 200
    label "GCCGGA--TCCGGCGCTCGAGCTCAGATCTGACCTGGCCGGG"
  ]
  node [
    id 201
    label "GCCGCTGCGGCGGCGCTCGAGCAAGGATCCTTGTTGGCCAAC"
  ]
  node [
    id 202
    label "GCCGAGGCCTCGGCGCTCGAGCGGGGATCCCTGGCAGCTGTC"
  ]
  node [
    id 203
    label "GGCCTGGCCAGGCCGCTCGAGCGAGGATCCTTGGTGGCCGCC"
  ]
  node [
    id 204
    label "GGCTTGATCAAGCCGCTCGAGCAAGGATCCTTGTTGGCCAAC"
  ]
  node [
    id 205
    label "GCTGAAGTTTTGGCGCT--AGTTTAGATCTAGCCTGGCCAGG"
  ]
  node [
    id 206
    label "GCCTTGGCTAAGGCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 207
    label "GCGAAA--TTTTGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 208
    label "GTTGAAGCTTTGGCCTC--GAGTTAGATCTAGCCTGGCCAGG"
  ]
  node [
    id 209
    label "GGAACTTAGGTTCCGCGTGCGCGATGCGCATTCTCGGCCGAG"
  ]
  node [
    id 210
    label "GGGACTTAAGTCCCGCTCGAGCGTGGATCCATCCCAGCTGGG"
  ]
  node [
    id 211
    label "GGTTTTGCAAAACCGCTCGAGCATTGATCAATGGCGGCCGTC"
  ]
  node [
    id 212
    label "GTTTCTGCAGAAGCGTG--CACTTCGCGCGAACTCAGCTGGG"
  ]
  node [
    id 213
    label "GCCCTAGCTGGGGCGCTCGAGCCCAGATCTGGGCCTGCAGGC"
  ]
  node [
    id 214
    label "GCCAAA--TTTGGCGCTCGAGCTTAGATCTGACCTGGCTGGG"
  ]
  node [
    id 215
    label "GCCTCGATCGAGGCGCTCGAGCAGGGATCCCTAGTGGCCACT"
  ]
  node [
    id 216
    label "GCTGAAATTTCAGCGCT--AGCTTAGATTTAACCTGGCCGGG"
  ]
  node [
    id 217
    label "GCGGACGCGTCCGCGCTCGAGCAGGGATCCCTGGGGGCCCTC"
  ]
  node [
    id 218
    label "GGTTTCATGAAACCGCTCGAGCAAGGATCCTTGACAGCTGTC"
  ]
  node [
    id 219
    label "GCCCAGGCCTGGGCGCTCGAGCTGTGATCACAGGCGGCCGTC"
  ]
  node [
    id 220
    label "GCCTAGATCTAGGCGCTCGAGCGAGGATCCTCACTGGCCGGT"
  ]
  node [
    id 221
    label "GCCTGGGCCCAGGCGCTCGAGCGGGGATCCCCGGCAGCTGTC"
  ]
  node [
    id 222
    label "GGCCAGATCTGGCCGCTCGAGCAGGGATCCCTGTCGGCCGAC"
  ]
  node [
    id 223
    label "GCCGAAATTTCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 224
    label "GGCCAGGCCTGGCCGCTCGAGCTTCGCGTGAAGCCGGCCGGC"
  ]
  node [
    id 225
    label "GCCGTGATCACGGCGCTCGAGCCCAGATCTGGGCTGGCCGGC"
  ]
  node [
    id 226
    label "GCCGGGGTCCCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 227
    label "GGTCTTGCGAGACCGCTCGAGCACGGTACCGTGGCAGCTGCC"
  ]
  node [
    id 228
    label "GCCGCCTAGGCGGCGCTCGAGCCTCGATCGAGCCCGGCCGGG"
  ]
  node [
    id 229
    label "GGCTAGGCCTAGCCGCTCGAGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 230
    label "GCTGAA--TTTGGCGCTCGAGTTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 231
    label "GGAGCAATTGTTCCGCA--TGCTCTGGCCAGAACTGGCCAGT"
  ]
  node [
    id 232
    label "GGATCGATCGATCCGCGCGCGCCCGCCGGCGGCCCGGCCGGG"
  ]
  node [
    id 233
    label "GCTGAAATTTTGGCGCT--AGTTTAGATCTGACCCAGCTGGG"
  ]
  node [
    id 234
    label "GGCCAGGCCTGGCCGCTCGAGCTCCGCGCGGAGGCGGCCGCC"
  ]
  node [
    id 235
    label "GCTGAGATCTCAGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 236
    label "GCCAAG--TTTGGCGCTCGAGCTTAGATCTAACCTAGCTGGG"
  ]
  node [
    id 237
    label "GCCCGGATCCGGGCGCTCGAGCGGGGATCCCCCTTGGCCAAG"
  ]
  node [
    id 238
    label "GGCTCTGCGGAGCCGCTCGAGCCACGATCGTGACGGGCCCGT"
  ]
  node [
    id 239
    label "GCCAGAGCTCTGGCGCTCGAGCGAGGCGCCTTGGCAGCTGCC"
  ]
  node [
    id 240
    label "GCCGAAATTTCGGCGCTCGAGCTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 241
    label "GGGTCGGCTGACCCGCTCGAGCTCGGATCCGAGGCGGCCGCC"
  ]
  node [
    id 242
    label "GCCTAAGTTTAGGCGCTCGAGCGCAGATCTGTAACGGCCGTT"
  ]
  node [
    id 243
    label "CGGAACGCGTTCCGGCGTGCGCTGCCGCGGCAGGCGGCCGTC"
  ]
  node [
    id 244
    label "CTGAAA--TTTCAGGCTCGAGCTTAGATCTAACTTGGCCAGG"
  ]
  node [
    id 245
    label "GCCGTGGCCACGGCGTTCGAACCCAGATCTGGGCTGGCCGGC"
  ]
  node [
    id 246
    label "GGCCAAGCTTGGCCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 247
    label "GGCTAGGCCTGGCCGCTCGAGCAACGATCGTTGGCGGCCGCC"
  ]
  node [
    id 248
    label "GCCGAGGCCTCGGCGCTCGAGCGGGGATCCCCGGCAGCTGTC"
  ]
  node [
    id 249
    label "GCCCGGATCCGGGCGCTCGAGCGGGGATCCCCGGTGGCCGCC"
  ]
  node [
    id 250
    label "GCCGGAATTCCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 251
    label "GGCGGGATCCCGCCGCTCGAGCCGCGATCGCGGGCGGCCGCC"
  ]
  node [
    id 252
    label "GGTTTGATCAAACCGCTGTAGCTCAGTACTGAGTTGGCCAAC"
  ]
  node [
    id 253
    label "GCGAGA--TTTCGTGCTCGAGCTTAGATCTAATCTGGCCGGG"
  ]
  node [
    id 254
    label "GCCGGGATCCTGGCGCTCGAGCGAGGATCCTCCGGAGCTCCG"
  ]
  node [
    id 255
    label "GCTGAAATTTCAGCGCTCGAGTTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 256
    label "GGTTGGATCTAACCGCTCGAGCGCAGATCTGCGGCAGCTGCC"
  ]
  node [
    id 257
    label "GGCGCGGTCGTGCCGCTCGAGCTCCGCGTGGAACCAGCTGGT"
  ]
  node [
    id 258
    label "GCTGAAATTTCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 259
    label "GGTGGG--CCCACCGCTCGAGCAAGGATCCTTGGCGGCCGCC"
  ]
  node [
    id 260
    label "GCCCGGGCCCGGGCGCTCGAGCTGCGATCGCAGGCGGCCGTC"
  ]
  node [
    id 261
    label "GCCGGGATCCTGGCGCT--AGCGAGGATCCTCACCGGCCGGT"
  ]
  node [
    id 262
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 263
    label "GCGAAA--TTTTGCGCTCGAGTTTAGATCTAACTTGGCCAGG"
  ]
  node [
    id 264
    label "GCCCAGGCCTGGGCGCTCGAGCTGCGATCGCAGGCGGCCGTC"
  ]
  node [
    id 265
    label "GCCCAAGTTTGGGCGCTCGAGCTCAGATCTGACCCGGCCGGG"
  ]
  node [
    id 266
    label "GCCCAGGCCTGGGCGCTCGAGCGGGGATCCCCGGCAGCTGTC"
  ]
  node [
    id 267
    label "GCCCAGATCTGGGCGCTCGAGCAGGGATCCCTCTTGGCCGAG"
  ]
  node [
    id 268
    label "GCCGGGATCCTGGCGCTCGAGCGGCGATCGCCCCCAGCTGGG"
  ]
  node [
    id 269
    label "GGCCGG--CCGGCCGCTCGAGCAAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 270
    label "GGCCGGGCCCGGCCGCTCGAGCGGGGATCCCCGGGGGCCCTC"
  ]
  node [
    id 271
    label "GAGGGA--TCCCTTGCAGTTGCCTCCGCGGAGGCGGGCCCGC"
  ]
  node [
    id 272
    label "GGCCAGGCCTGGCCGCTCGAGCTGCGCGTGCAGGCGGCCGCC"
  ]
  node [
    id 273
    label "GCTGGGATCTCAGCGCTCGAGCGAGGATCCTCGGCAGCTGCC"
  ]
  node [
    id 274
    label "GCCCAGATTTGGGCGCTCGAGCAGGGATCCCTCGTGGCCGCG"
  ]
  node [
    id 275
    label "GCCGAGATCTCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 276
    label "GCCCCGATCGGGGCGCTCGAGCGAGGATCCTCCCTGGCCGGG"
  ]
  node [
    id 277
    label "GGCCAGGCCTGGCTGCTCGAGCTCCGCGCGGAGGCGGCCGCC"
  ]
  node [
    id 278
    label "GCCGAAATTTCGGCCTC--GAGTTAGATCTAACTTGGCCGGG"
  ]
  node [
    id 279
    label "GCCGCTGCGGCGGCGCTCGAGCGAGGATCCTCAACAGCTGTT"
  ]
  node [
    id 280
    label "GGCTCGGCTGAGCCGCTCGAGCGAGGATCCTTCCCGGCCGGG"
  ]
  node [
    id 281
    label "GCCCAGATCTGGGCGCTCGAGCAAGGATCCTTGTTGGCCAAT"
  ]
  node [
    id 282
    label "GGGCAGGCCTGCCCGCTCGAGCACGGATCCGTGGCAGCTGCC"
  ]
  node [
    id 283
    label "GCTGAAGCTTTAGTCTC--GAGTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 284
    label "GCCGAGGCCTCGGCGCTCGAGCGGGGATCCCCAGCGGCCGTT"
  ]
  node [
    id 285
    label "GCCCAGGCCTGGGCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 286
    label "GGCCAGATCTGGCCGCTCGAGCGAGGATCCTCGGGAGCTCTC"
  ]
  node [
    id 287
    label "CCCCTGGCTGGGGGGCTCGAGCCCTGTACAGGGTTGGCCAAC"
  ]
  node [
    id 288
    label "GGCTCGGCCGAGCCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 289
    label "GCCCCGATCGGGGCGCTCGAGCAGGGATCCCTAGTGGCCACT"
  ]
  node [
    id 290
    label "GCCCAGGCCTGGGCGCTCGAGCGTGGATCCACGGTGGCCGCC"
  ]
  node [
    id 291
    label "GCGGGA--TCCCGCGCTCGAGCTCAGATCTGAGCGTGCACGC"
  ]
  node [
    id 292
    label "GGTTAGATCTGACCGCTCGAGCGTAGATCTGCGGCAGCTGCC"
  ]
  node [
    id 293
    label "GGGGGTATGCCTCCGCTCGAGCTTCGATCGGATCGGGCCCGA"
  ]
  node [
    id 294
    label "GGTGATGCATCACCGCTCGAGCAAGGATCCTTGGGGGCCCTC"
  ]
  node [
    id 295
    label "GCCCAGGCCTGGGCGCTCGAGCAGGGATCCCTGGCGGCCGTC"
  ]
  node [
    id 296
    label "GCCCAGGCCTGGGCGCTCGAGCGAGGATCCTCGGCAGCTGTC"
  ]
  node [
    id 297
    label "GCCCAGATCTGGGCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 298
    label "GGCCGG--CCGGCCGCTCGAGCATGCATGCATGGCAGCTGTC"
  ]
  node [
    id 299
    label "GCTGAAATTTCAGCGCTCGAGCTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 300
    label "GCCCGGATCCGGGCGCTCGAGCGCGGATCCGCGGTGGCTGCC"
  ]
  node [
    id 301
    label "GTCGGGATCCCGGCGCTCGAGCGAGGATCCTCACCAGCTGGT"
  ]
  node [
    id 302
    label "GCCGTTGCGACGGCGCTCGAGCAAGGATCCTTGACAGCTGTC"
  ]
  node [
    id 303
    label "GGCTTTGCAAAGCCGCTCGAGCATGGATCCATGGCGGCCGTC"
  ]
  node [
    id 304
    label "GGCTCGGCCGAGCCGCTCGAGCATGCATGCATGGCAGCTGTC"
  ]
  node [
    id 305
    label "GGCCAGATCTGGCCGCTCGAGCGAGGATCCTTGGCAGCTGTC"
  ]
  node [
    id 306
    label "GGTCAGGCCTGACCGCTCGAGCCGGGATCCCGGGCGGCCGCC"
  ]
  node [
    id 307
    label "GGCCGG--CCGGCCGCTCGAGCTACGATCGTAGGGGGCCCTC"
  ]
  node [
    id 308
    label "GCCGCGATCGCGGCGCTCGAGCGGGGATCCCCCGCAGCTGTG"
  ]
  node [
    id 309
    label "GGCTCTGCGGAGCCGCTCGAGCAACGATCGTTAGCGGCCGCT"
  ]
  node [
    id 310
    label "GGTTCAGCTGAACCGCTCGAGCAAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 311
    label "GCTGAAATTTCAGCGCTCGAGCTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 312
    label "GGCCAGATCTGGCCGCTCGAGCGAGGATCCTTGCCAGCTGGC"
  ]
  node [
    id 313
    label "GGCCAAGCTTGGCCGCTCGAGCGCGGATCCGCCGTGGCCGCG"
  ]
  node [
    id 314
    label "GCCCAAGCTTGGGCGCTCGAGCTGCGATCGCAACTGGCCGGT"
  ]
  node [
    id 315
    label "GCCTCGATTGAGGCGCTCGAGCGAGGATCCTCGACAGCTGTC"
  ]
  node [
    id 316
    label "GCTGAAGCTTCAGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 317
    label "GGCCGGGCCCGGCCGCTCGAGCTGGGATCTCAGGCGGCCGTC"
  ]
  node [
    id 318
    label "GCCGGGGCCCCGGCGCTCGAGCGGGGATCCCCGGCAGCTGTC"
  ]
  node [
    id 319
    label "GCCGGGATCCTGGCGCTCGAGCGAGGATCCTCACGAGCTCGT"
  ]
  node [
    id 320
    label "GCCGAAATTTCGGCGTC--GATTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 321
    label "GGTTCGGCCGAACCGCTCGAGCTTTGATCAAAGGCGGCCGTC"
  ]
  node [
    id 322
    label "GGCTGGGCCCAGCCGCTCGAGCGCGGATCCGTGGCGGCCGCC"
  ]
  node [
    id 323
    label "GCCGGA--TCCGGCGCTCGAGCGAGGATCCTCGGCGGCCGCC"
  ]
  node [
    id 324
    label "GGCCGG--CCGGCCGCTCGAGCTACGATCGTAGGGGGCCCTT"
  ]
  node [
    id 325
    label "GGTATCTAGATACCGCTCGAGCACGGATCCGTCCCAGCTGGG"
  ]
  node [
    id 326
    label "GGTGGG--CCCACCGCTCGAGCAAGGATCCTTGCCGGCCGGC"
  ]
  node [
    id 327
    label "GCCTTGTACAAGGCGCTCGAGCTTCGCGCGAAGCCGGCCGGC"
  ]
  node [
    id 328
    label "GCCCGGATCCGGGCGCTCGAGCGAGGATCCTCCTTGGCCGAG"
  ]
  node [
    id 329
    label "GCCGCTTAGGCGGCGCTCGAGCAAGGATCCTTCTCAGCTGAG"
  ]
  node [
    id 330
    label "GCCTCTGCGGAGGCGCTCGAGCGGGGATCCCCATTGGCCGAT"
  ]
  node [
    id 331
    label "GGTCGTGCACGACCGCTCGAGCGCAGATCTGCGGCGGCCGTC"
  ]
  node [
    id 332
    label "GCCGGGGCCCCGGCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 333
    label "GCCTCTGCGGAGGCGCTCGAGCGGGGATCCCCGGTGGCCGCC"
  ]
  node [
    id 334
    label "GCCGAAATTTCGGCGTTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 335
    label "GCTCAGGCCTGAGCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 336
    label "GGCGGA--TCCGCCGCTCGAGCGAGGATCCTCGGCGGCCGCC"
  ]
  node [
    id 337
    label "GGTGGCATGCTACCGCTCGAGCAAGGATCCTTCCTGGCCAGG"
  ]
  node [
    id 338
    label "GGTGATGCATCACCGCTCGAGCAAGGATCCTTGGTGGCCACT"
  ]
  node [
    id 339
    label "GCCGAAATTTCGGCGTT--AGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 340
    label "GGTTTTGCAAAACCGCTCGAGCGTTGATCAACGGCGGCCGTC"
  ]
  node [
    id 341
    label "GCTGAAGCTTTGGCGTT--AGCTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 342
    label "GGCCAATATTGGCCGCTCGAGCAATGATCATTCTTGGCCGAG"
  ]
  node [
    id 343
    label "GGCTCGGCCGAGTCGCTCGAGCAAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 344
    label "GGCCAGGCCTGGCCGCTCGAGCCTCGCGCGAGGGCGGCCGCC"
  ]
  node [
    id 345
    label "GCCCAGATCTGGGCGCTCGAGCGGGGATCCCCGCTGGCCGGC"
  ]
  node [
    id 346
    label "GGCCCTGTGGGGCCGCTCGAGCACGGATCCGTGTCAGCTGAC"
  ]
  node [
    id 347
    label "GCTGAAATTTCAGCGCTCGAGCTTAGATTTAACTTGGCCGGG"
  ]
  node [
    id 348
    label "GGCCAGATCTGGCCGCTCGAGCAGGGATCCCTGGCGGCCGCC"
  ]
  node [
    id 349
    label "GCCGGAATTTCGGCGCTCGAGCTTAGGTCTGACCTGGCTGGG"
  ]
  node [
    id 350
    label "GGCCGGGCCCGGCCGCTCGAGCTTCGCGTGAAACCGGCCGGT"
  ]
  node [
    id 351
    label "GCCCAGTACTGGGCGCTCGAGCACGGATCCGTTCTGGCCGGA"
  ]
  node [
    id 352
    label "GGCCAGGCCTGGCCGCTCGAGCTCCGCGTGGAGGCGGCCGCC"
  ]
  node [
    id 353
    label "GCCGAA--TTCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 354
    label "GCCACTTAGGTGGCGCTCGAGCTACGATTGTATCCGGCCGGA"
  ]
  node [
    id 355
    label "GGCTCTGCGGAGCCGCTCGAGCTACGATCGTAACCGGCCGGT"
  ]
  node [
    id 356
    label "GCCGAAATTTCGGCGCTCGAGCTCAGATCTGACCTGGCTGGG"
  ]
  node [
    id 357
    label "GGCCAGGCCTGGCCGCTCGAGCGGGGATCCCCGGCAGCTGTC"
  ]
  node [
    id 358
    label "GGCCACTAGTGGCCGCTCGAGCCACGATCGTGCCCAGCTGGG"
  ]
  node [
    id 359
    label "GCCGAGGCCTCGGCGCTCGAGCCAGCCGGCTGGACAGCTGTC"
  ]
  node [
    id 360
    label "GGCTAGATCTAGCCGCTCGAGCGAGGATCCTTGGTGGCCGCC"
  ]
  node [
    id 361
    label "GCCTTTATAAAGGCGCTTAAGCATAAGTTTATATGAGCTCAT"
  ]
  node [
    id 362
    label "GCCCAAGCTTGGGCGCTCGAGCGGGGATCCCCGGTGGCCGCC"
  ]
  node [
    id 363
    label "GCCTCGGCCGAGGCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 364
    label "GCCTTTATGAAGGCGCTCGAGCCCAGATCTGGGCCGGCCGGC"
  ]
  node [
    id 365
    label "GGCTGGGCCCAGCCGCTCGAGCATCGCGCGATGCCGGCCGGC"
  ]
  node [
    id 366
    label "GGCAAGATCTTGCCGCTCGAGCGGTGATCACCCTCGGCCGAG"
  ]
  node [
    id 367
    label "GCCATGGCCATGGCGTTCGAACCTAGATCTAGGCTGGCCGGC"
  ]
  node [
    id 368
    label "GGCCCG--CGGGCCGCTCGAGCATGGATCCATGGCGGCCGTC"
  ]
  node [
    id 369
    label "GGCTCAATTGAGCCGCTCGAGCACGGATCCGTGGCGGCCGTC"
  ]
  node [
    id 370
    label "GGTAGCGCGCTGCCGCC--GGCCTGGATCCAGGTGGGCCCAC"
  ]
  node [
    id 371
    label "GGGGCGGTCGCCCCGCTCGAGCCCGGATCCGGGGGGGCCCCC"
  ]
  node [
    id 372
    label "GGCCGG--CCGGCCGCTCGAGCATGCATGCATGGCGGCCGTC"
  ]
  node [
    id 373
    label "GCCGCGGCTGCGGCGCTCGAGCTTCGCGCGAAGAAGGCCTTC"
  ]
  node [
    id 374
    label "GCGGTGATCACCGCGCTTGAGCTCAGATCTGAGCATGCATGC"
  ]
  node [
    id 375
    label "GCCGAA--TTCGGTGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 376
    label "GGCTCGGCCGAGCCGCTCGAGCTTGGATCCAAGGCGGCCGTC"
  ]
  node [
    id 377
    label "GCCGCCTAGGCGGCGCTCGAGCCTCGATCGGGCCCGGCCGGG"
  ]
  node [
    id 378
    label "GCCTTTGCGAAGGCGCTCGAGCGGGGATCCCCAGTGGCCGCT"
  ]
  node [
    id 379
    label "GCCCAGATCTGGGCGCTCGAGCAAGGATCCTTGCTGGCCGGC"
  ]
  node [
    id 380
    label "GCCTCGATCGGGGCGCTCGAGCCACGATCGTGACCAGCTGGT"
  ]
  node [
    id 381
    label "GCTGAAGCTTTGGCGCTCGAGTTTAGATCTGGCCTGGCCAGG"
  ]
  node [
    id 382
    label "GGCTAGGCCTGGCCGCTCGAGCACGGATCCGTGGCAGCTGCC"
  ]
  node [
    id 383
    label "GGCTAGGCCTAGCCGCTCGAGCTCCGCGCGGAGGCGGCCGCC"
  ]
  node [
    id 384
    label "GGCCAGATCTGGCCGCTCGAGCTCCGCGTGGAAGCGGCCGCT"
  ]
  node [
    id 385
    label "GCTGAG--TTCAGCGCTCGAGCTTAGATCTAACCCGGCCGGG"
  ]
  node [
    id 386
    label "GTCGAAATTTCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 387
    label "GGCTGGATCCAGCCGCTCGAGCGAGCCGGCTTGGGAGCTCTC"
  ]
  node [
    id 388
    label "GTTGAAATTTCGGCGCTCGAGCTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 389
    label "GCCTGGGCCCAGGCGCTCGAGCAAGGATCCTTGGGGGCCCTC"
  ]
  node [
    id 390
    label "GGGCAGGCCTGCCCGCTCGAGCTCCGCGCGGAGGCGGCCGCC"
  ]
  node [
    id 391
    label "GGCCGG--CCGGCCGCTCGAGCAAGGATCCTTGGCAGCTGCC"
  ]
  node [
    id 392
    label "GCCTCGGCTGAGGCGCTCGAGCAGGGATCCCTCGCAGCTGCG"
  ]
  node [
    id 393
    label "GGCCAATATTGGCCGCTCGAGCGAGGATCCTCTCTGGCCAGA"
  ]
  node [
    id 394
    label "GGGGCGGTCGTCCCGCTCGAGCCGGGATCCCGGCAGGCCTGC"
  ]
  node [
    id 395
    label "GCCCAGATCTGGGCGCTCGAGCGTGGATCCACGCTGGCCGGC"
  ]
  node [
    id 396
    label "GGGGCGGCCGCCCCGCTCGAGCCCCGGCCGGGGGGGGCCCCC"
  ]
  node [
    id 397
    label "GGCTCGATCGAGCCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 398
    label "GCCGGGATCCTGGCGCTCGAGCGTGGATCCACACCAGCTGGT"
  ]
  node [
    id 399
    label "GCCCAGGTCTGGGCGCTCGAGCGAGGATCCTCAGCGGCCGTT"
  ]
  node [
    id 400
    label "GGCTCGGCCGAGCCGCTCGAGCGAGGATCCTCGGCGGCCGCC"
  ]
  node [
    id 401
    label "GGCCAGGCCTGGCCGCTCGAGCGGCGATCGCCGGGAGCTCTC"
  ]
  node [
    id 402
    label "GCCAAGGCCTTGGCGTTCGAACCTGGATCCAGGGGTGCACCC"
  ]
  node [
    id 403
    label "GGCCCGGCTGGGCCGCTCGAGCTACGGCCGTAGGCGGCCGCC"
  ]
  node [
    id 404
    label "GGCCAATATTGGCCGCTCGAGCGCGGATCCGCCTTGGCCGAG"
  ]
  node [
    id 405
    label "GGCGGGGCCCCGCCGCTCGAGCGCGGATCCGCCCCAGCTGGG"
  ]
  node [
    id 406
    label "GCGAAA--TTTCGCGCTCGAGCTTAGATCTGACCTGGCCGGG"
  ]
  node [
    id 407
    label "GCCGCTATGGCGGCGCTCGAGCAAGGATCCTTGGGAGCTCCC"
  ]
  node [
    id 408
    label "GCCCTGTACAGGGCGCTCGAGCCCAGATCTGGGCTGGCCGGC"
  ]
  node [
    id 409
    label "GCCGAGGCCTCGGCGCTCGAGCGTGGATCCACGGCGGCCGTC"
  ]
  node [
    id 410
    label "GGACAGATCTGTCCGCTCGAGCAAGGATCCTTGGGGGCCCTC"
  ]
  node [
    id 411
    label "GCCCAGTACTGGGCGCTCGAGCGAGGATCCTCTCTGGCCGGA"
  ]
  node [
    id 412
    label "GCGAAA--TTTCGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 413
    label "GCCCAGGCCTGGGCGCTCGAGCGAGGATCCTCGACAGCTGTC"
  ]
  node [
    id 414
    label "GCCCAGGTCTGGGCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 415
    label "GCCGAAGTTTCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 416
    label "GGTTAGGCCTAACCGCTCGAGCGGGGATCCCCGGGGGCCCTC"
  ]
  node [
    id 417
    label "GCTGAAATTTCAGCGCTCGAGCTTAGATCTAATCTGGCCGGG"
  ]
  node [
    id 418
    label "GGCTAGGCCTGGCCGCTCGAGCAACGATCGTTGCCGGCCGGC"
  ]
  node [
    id 419
    label "GCCCCGGCCGGGGCGCTCGAGCACCGGCCGGTCCGGGCCCGG"
  ]
  node [
    id 420
    label "GGGACGATCGTCCCGCTCGAGCTGCGATCGCAGCTGGCCGGC"
  ]
  node [
    id 421
    label "GGCGGA--TCCGCCGCTCGAGCACGGATCCGTCCCAGCTGGG"
  ]
  node [
    id 422
    label "GCCGAAATTTCGGCCTC--GAGTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 423
    label "GGCAAGATCTTGCCGCTCGAGCGCGCATGCGCCCCGGCCGGG"
  ]
  node [
    id 424
    label "GGCTAATATTAGCCGCTCGAGCGTTGATCAACCTTGGCCGAG"
  ]
  node [
    id 425
    label "GGAACT--AGTTCCGCTCGAGCTTAGATCTAAGGTGGCCATC"
  ]
  node [
    id 426
    label "GGCTCGGCCGAGCCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 427
    label "GGTTCGATCGAACCGCTCGAGCAAGGATCCTTGACAGCTGTC"
  ]
  node [
    id 428
    label "GGCCGAGCTCGGCCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 429
    label "GCCGCTGCGGCGGTGCTCGAGCAAGGATCCTTAGGAGCTCCT"
  ]
  node [
    id 430
    label "GCCTAATATTGGGCGCTCGAGCATCGGCCGATGTAGGCCTGC"
  ]
  node [
    id 431
    label "GCCGAAATTTTGGCCTC--GAGTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 432
    label "GCTAAG--TTTAGCGCTCGAGCACAGGCCTGTAACGGCCGTT"
  ]
  node [
    id 433
    label "GCCGTGGTCACGGCACTCGAGTCATGATCATGGCTGGCCGGC"
  ]
  node [
    id 434
    label "GGTCTTGCGAGACCGCTCGAGCATGGTACCATGGCAGCTGCC"
  ]
  node [
    id 435
    label "GTCAGGATCCTGGCGTC--GACGAGGATCCTCACCAGCTGGT"
  ]
  node [
    id 436
    label "GGGGGG--CCCCCCGCC--GGCCCGGTACCGGGTGGGCCCAC"
  ]
  node [
    id 437
    label "GGCTAAATTTAGCTGCTCGAGCAAGGATCCTTGGTGGCCACC"
  ]
  node [
    id 438
    label "GCCCAGGCCTGGGCGCTCGAGCTGCGATCGCAGGCAGCTGCC"
  ]
  node [
    id 439
    label "GCTCCCGCGGGAGCGCTCGAGTCTTGGCCAAGGAAAGCTTTC"
  ]
  node [
    id 440
    label "GCCCGGATCCGGGCGCTCGAGCGGGGATCCCCGGCGGCCGCC"
  ]
  node [
    id 441
    label "GCCCGGTACCGGGCGCTCGAGCGGGGATCCCCCGTGGCCGCG"
  ]
  node [
    id 442
    label "GGCTGGATCCAGCCGCTCGAGCGAGGATCCTTGGTGGCCGCC"
  ]
  node [
    id 443
    label "GCCGAGGCCTCGGCGCTCGAGCTGCGATCGCAGGCGGCCGCC"
  ]
  node [
    id 444
    label "GGCGAGGCCTTGCCGCTCGAGCGCGGATCCGTGACGGCCGTC"
  ]
  node [
    id 445
    label "GGCTCGATCGAGCCGCTCGAGCACGGATCCGTGGCGGCCGTC"
  ]
  node [
    id 446
    label "GCTAAG--TTTGGCGCTCGAGCTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 447
    label "GCCGAGGCCTCGGCGCTCGAGCGAGGATCCTTGATGGCCGTC"
  ]
  node [
    id 448
    label "GCTGAAGCTTCAGCGCTCGAGCTTAGATCTAATCTGGCCGGA"
  ]
  node [
    id 449
    label "GCCCGAATTCGGGCGCTCGAGCGAGGATCCTTGGCGGCCGCC"
  ]
  node [
    id 450
    label "GCCCGGATCCGGGCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 451
    label "GCCCGGATCCGGGCGCTCGAGCAGGGATCCCTCTTGGCCGAG"
  ]
  node [
    id 452
    label "GCTGAAATTTCGGCGCTCGAGCTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 453
    label "GCCAAA--TTTGGCGCTCGAGCTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 454
    label "GCCCGGATCCGGGCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 455
    label "GGCCAGGCCTGGCCGCTCGAGCTCCGATCGGAAGCGGCCGCT"
  ]
  node [
    id 456
    label "GCCCCGATCGGGGCGCTCGAGCAAGGATCCTTCGTGGCCGCG"
  ]
  node [
    id 457
    label "GCCTTGATCAGGGCGCT--AGCTTAGATTTAAACCAGCTGGT"
  ]
  node [
    id 458
    label "GCCTGAATTCAGGCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 459
    label "TCCGGGGCCCCGGAGCTCGAGCCTCGGCCGAGGCTGGCCAGC"
  ]
  node [
    id 460
    label "GGCCTTGCGAGGCCGCTCGAGCGAGGATCCTTGGGAGCTCTC"
  ]
  node [
    id 461
    label "GGCTGGATCCGGCCGCTCGAGCGAGGATCCTTGTCGGCCGGC"
  ]
  node [
    id 462
    label "TCCCTG--TAGGGAGCT--AGCTCTGTGCAGGCCAGGCCTGG"
  ]
  node [
    id 463
    label "GGCTTGGTCAAGCCGCTCGAGCGAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 464
    label "GTCGCAATTGTGACGTGTGCATACAGATCTGTATCGGCCGGT"
  ]
  node [
    id 465
    label "GCCCAGGCCTGGGCGCTCGAGCGTGGATCCACGTTGGCCGAC"
  ]
  node [
    id 466
    label "GCCCAGATCTGGGCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 467
    label "GCCTAGATCTAGGCGCTCGAGCGAGGATCCTCGTTGGCCGAC"
  ]
  node [
    id 468
    label "GGTGATGCATCACCGCTCGAGCAAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 469
    label "GCCCGAATTCGGGCGCTCGAGCGGGGATCCCCCCTGGCCGGG"
  ]
  node [
    id 470
    label "GGCTCGGCTGAGCCGCTCGAGCGCGGATCCGCGGCGGCCGCC"
  ]
  node [
    id 471
    label "GCCGGAATTTCGGCGCTCGAGCTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 472
    label "GGTCAGGCCTGACCGCTCGAGCACGGCGCCGTGGCGGCCGCC"
  ]
  node [
    id 473
    label "GCCTGGGCCCAGGCGCTCGAGCGGGGATCCCCGCTGGCCGGC"
  ]
  node [
    id 474
    label "GCCGCTGCGGCGGCGCTCGAGCGGGGATCCCCCGCAGCTGCG"
  ]
  node [
    id 475
    label "GGTTCTGCGGAACCGCTCGAGCGTGGATCCGCGTTGGCCAAT"
  ]
  node [
    id 476
    label "GGCCTGATCAGGCCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 477
    label "GTTGAAATTTCGGCGTC--GACTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 478
    label "GGTGGG--TCCACCGCTCGAGCAAGGATCCTTGGCGGCCGCC"
  ]
  node [
    id 479
    label "GGCCAG--CTGGCCGCTCGAGCATGGATCCATGGCAGCTGTC"
  ]
  node [
    id 480
    label "GCCTCGGCTGAGGCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 481
    label "GCCGAGGCCTCGGCGCTCGAGCCAGCATGCTGCCCAGCTGGG"
  ]
  node [
    id 482
    label "GCGAAA--TTTCGCGTT--AGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 483
    label "GCCGAGGCCTCGGCGCTCGAGCGCGGATCCGCGGCAGCTGTC"
  ]
  node [
    id 484
    label "GGCCGG--TCGGCCGCTCGAGCATGGATCCATGGCGGCCGTC"
  ]
  node [
    id 485
    label "GGCCGG--CCGGCCGCTCGAGCATGGATCCATGGCGGCCGTC"
  ]
  node [
    id 486
    label "GCCCAGATCTGGGCGCTCGAGCCTGCCGGCAGCCCGGCCGGG"
  ]
  node [
    id 487
    label "GCCCAGATCTGGGCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 488
    label "GGCCAGGCCTGGCCGCTCGAGCGGGGATCCCCGGGAGCTCTC"
  ]
  node [
    id 489
    label "GCCGGAATTTCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 490
    label "GCCACCTAGGTGGCGCTCGAGCAAGGATCCTTTAGGGCCCTG"
  ]
  node [
    id 491
    label "GCGTTA--TAACGCCCC--GGGATGGCGTCATGAGGGCCCTC"
  ]
  node [
    id 492
    label "GGACAGGTTTGTCCGCTCGAGCTCGGATCCGAGACGGCCGTC"
  ]
  node [
    id 493
    label "GGAACTTAGGTTCCGTGTGCGCGATGCGCATTCTCGGCTGAG"
  ]
  node [
    id 494
    label "GCCGAGGCCTCGGCGCTCGAGCGAGGATCCTCGCTGGCCGGC"
  ]
  node [
    id 495
    label "GGCGCGGCCGCGCCGCTCGAGCACGGATCCGTGGCAGCTGTC"
  ]
  node [
    id 496
    label "GGTGAGATCTCACCGCTCGAGCGTGGATCCACGACAGCTGTC"
  ]
  node [
    id 497
    label "GGCCAGATCTGGCCGCTCGAGCCACGCGTGTGGCCAGCTGGC"
  ]
  node [
    id 498
    label "GCCGGGATCCTGGCGCTCGAGCGAGGATCCTCGGCGGCCGCC"
  ]
  node [
    id 499
    label "GGCCGAGTTCGGCCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 500
    label "GCCTCGATCGAGGCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 501
    label "GGCCGG--CCGGCCGCTCGAGCGCGGATCCGCGGCAGCTGCC"
  ]
  node [
    id 502
    label "GCCCGGATCCGGGCGCTCGAGCGAAGATCTTCCTTGGCCAAG"
  ]
  node [
    id 503
    label "GGCTAGGCCTAGCCGCTCGAGCACGGATCCGTGGGGGCCCTC"
  ]
  node [
    id 504
    label "GGTGCCTAGGCACCGCTCGAGCATGGATCCATCTTGGCCAAG"
  ]
  node [
    id 505
    label "GGCCCTGCGGGGCCGCTCGAGCGAGGATCCTCGGCAGCTGTC"
  ]
  node [
    id 506
    label "GCCCGGATCCGGGCGCTCGAGCGCGGATCCGCGGCGGCCGTC"
  ]
  node [
    id 507
    label "GCCTCAATTGAGGCGCTCGAGCCCAGATCTGGCCCGGCCGGG"
  ]
  node [
    id 508
    label "GCCGGGATCCTGGCGCTCGAGCGGCGATCGCCCGCAGCTGCG"
  ]
  node [
    id 509
    label "GCTGAAATTTCAGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 510
    label "GCCCAGGCCTGGGCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 511
    label "GCGGGA--TCCCGTGCTCGAGCTCAGATCTGAGCGTGCACGC"
  ]
  node [
    id 512
    label "GCCGCGGCCGCGGCGCTCGAGCTCAGATCTGAGCCGGCCGGC"
  ]
  node [
    id 513
    label "CCCCTGGCTGGGGGGCTCGAGCCCTGTACAGGGTCGGCCGAC"
  ]
  node [
    id 514
    label "GGCCTGGCCGGGCCGCTCGAGCGAGGATCCTTGGTGGCCGCC"
  ]
  node [
    id 515
    label "GCCGACCGGTCGGCGCGTGCGCCCCGTGCGGGCTCGGCCGAG"
  ]
  node [
    id 516
    label "GCCGAGATCTCGGCGCTCGAGCAGGGATCCCTCGTGGCCACG"
  ]
  node [
    id 517
    label "GGTATCTAGATACCGCTCGAGCACGGATTCGTCCCGGCCGGG"
  ]
  node [
    id 518
    label "GCCGTGGCCACGGCGTTCGAACCTGGATCCAGGGGTGCACCC"
  ]
  node [
    id 519
    label "GCCCAAGCTTGGGCGCTCGAGCTCAGATCTGACCCGGCCGGG"
  ]
  node [
    id 520
    label "GGCCAGATCTGGCCGCTCGAGCTCCGCGTGGAGCCGGCCGGC"
  ]
  node [
    id 521
    label "GGCCAGGCCTGGCCGCTCGAGCGCGGATCCGCGGCAGCTGCC"
  ]
  node [
    id 522
    label "GGCCGG--CCGGCCGCTCGAGCAAGGATCCTTGGCGGCCGCC"
  ]
  node [
    id 523
    label "GCCGAGGCCTCGGCGCTCGAGCCGGCATGCCGGCCGGCCGGC"
  ]
  node [
    id 524
    label "GCTTGA--TCAGGCGCTCGAGCTTAGATCTAAACCAGCTGGT"
  ]
  node [
    id 525
    label "GGCCCGGCTGGGCCGCTCGAGCCGCGATCGCGGCCGGCCGGC"
  ]
  node [
    id 526
    label "GGCCCGGCTGGGCCGCTCGAGCCGCGATCGCGGCCAGCTGGC"
  ]
  node [
    id 527
    label "GGCCAGATCTGGCCGCTCGAGCGAGGATCCTCGGCAGCTGCC"
  ]
  node [
    id 528
    label "GCCGCCGCGGCGGCGCTCGAGCCCCGGCCGGGGCGGGCCCGC"
  ]
  node [
    id 529
    label "GCTGAAATTTTGGCGCTCGAGCTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 530
    label "GGCGAGATCTCGCCGCTCGAGCGCGGATCCGCGGCGGCCGTC"
  ]
  node [
    id 531
    label "GCCGCGGCCGCGGCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 532
    label "GCCTGGGCCCAGGCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 533
    label "GCCGGGATCTTGGCGCTCGAGCGAGGATCCTCACCAGCTGGT"
  ]
  node [
    id 534
    label "GCCACGATCGTGGCGCTCGAGCGAGGATCCTCGCTGGCCGGC"
  ]
  node [
    id 535
    label "GCCCGGATCCGGGCGCTCGAGCGGGGATCCCCCTTGGCCGAG"
  ]
  node [
    id 536
    label "GGCCAGATCTGGCCGCTCGAGCAGCGATCGCTGGCGGCCGTC"
  ]
  node [
    id 537
    label "GCTGAAATTTTGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 538
    label "GGCGGGATCCCGCCGCTCGAGCGCGGATCCGCCCCAGCTGGG"
  ]
  node [
    id 539
    label "GTCAGGATCCTGGCGCTCGAGCGAGGATCCTCACCAGCTGGT"
  ]
  node [
    id 540
    label "GCCTTGATCAAGGCGTG--CACCGAGATCTCGGGAGGCCTCT"
  ]
  node [
    id 541
    label "GCCGAGATCTCGGCGCTCGAGCGCGGATCCGCACAGGCCTGT"
  ]
  node [
    id 542
    label "GGCCACGCGTGGTCGCTCGAGCAAGGATCCTTGTTGGCCAAC"
  ]
  node [
    id 543
    label "GCTAAG--TTTAGCGCTCGAGCGTAGATCTACAGCGGCCGTT"
  ]
  node [
    id 544
    label "GCCGTGGCCACGGCGCTCGAGCCCAGATCTGGGCTGGCCGGC"
  ]
  node [
    id 545
    label "GCCGAGATCTTGGCGCTCGAGCGAGGATCCTCCGCGGCCGCG"
  ]
  node [
    id 546
    label "GGCTCGATCGAGCCGCTCGAGCGGAGATCTCCGGTGGCCGCC"
  ]
  node [
    id 547
    label "GGCCTGGCCAGGCCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 548
    label "GCCCAGGCCTGGGCGCTCGAGCGGGGATCCCCGGTGGCCGCC"
  ]
  node [
    id 549
    label "CCGAAA--TTTCGGGCT--AGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 550
    label "CCCCTGGCTGGGGGGCTCGAGCTCTGTACAGAGTCAGCTGAC"
  ]
  node [
    id 551
    label "GGCCAGGCCTGGCCGCTCGAGCTCCGCGCGGAAGCGGCCGCT"
  ]
  node [
    id 552
    label "GGCCTGATCAGGCCGCTCGAGCAAGGATCCTTACTGGCCGGT"
  ]
  node [
    id 553
    label "GTCAAAGCTTTGGCGCTCGAGTTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 554
    label "GGCCGGGCCCGGCCGCTCGAGCGCGGATCCGCGCCAGCTGGC"
  ]
  node [
    id 555
    label "GGCCAGATCTGGCCGCTCGAGCACGGATCCGTGGCGGCCGCC"
  ]
  node [
    id 556
    label "GCCTGGGCCCAGGCGCTCGAGCGGGGATCCCCGGTGGCCGCC"
  ]
  node [
    id 557
    label "GGCTTTGCGAAGCCGCTCGAGCACGGTACCGTGGCAGCTGCC"
  ]
  node [
    id 558
    label "GCCCAGATCTGGGCGCTCGAGCGAAGATCTTCGGCGGCCGTC"
  ]
  node [
    id 559
    label "GGCCAGATCTGGCCGCTCGAGCTTCGCGTGAACCCGGCCGGG"
  ]
  node [
    id 560
    label "GGCCAGGCCTGGCCGCTCGAGCACCGCGCGGTGGCGGCCGCC"
  ]
  node [
    id 561
    label "GGAACTGCGGTTCCGCC--GGCCCAGATCTGGGCTGGCCAGT"
  ]
  node [
    id 562
    label "GCCGAGGCCTCGGCGCTCGAGCCTGGTACCAGGACAGCTGTC"
  ]
  node [
    id 563
    label "GGGTCAGCTGACCCGCTCGAGCTTAGATCTAAGGCGGCCGTC"
  ]
  node [
    id 564
    label "GCCCGAGCTCGGGCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 565
    label "GGTTGG--CCAACCGCTCGAGCGCGGATCCGCGGCGGCCGCC"
  ]
  node [
    id 566
    label "GCCAGGGCCCTGGCGCTCGAGCCGTGTACACGACCGGCCGGT"
  ]
  node [
    id 567
    label "GGCCGG--CCGGCCGCTCGAGCAAGGATCCTTGGGGGCCCTC"
  ]
  node [
    id 568
    label "GCCTCAATTGGGGCGCTCGAGCTTAGATCTAAACCAGCTGGT"
  ]
  node [
    id 569
    label "GCGGGA--TCCCGCGCTCGAGCTCAGATCTGAACGTGCACGT"
  ]
  node [
    id 570
    label "GCCATGTACATGGCGTTCGAACCCAGATCTGGGCTGGCCGGC"
  ]
  node [
    id 571
    label "CCTCCGGCTGGGGGGCTCGAGCCCTGCGCAGGGTCGGCCGAC"
  ]
  node [
    id 572
    label "GCCCAGGCCTGGGCGCTCGAGCGCGGATCCGCACTGGCCGGT"
  ]
  node [
    id 573
    label "GCCCGGGCCCGGGCGCTCGAGCCGTGATCACGGGCGGCCGTC"
  ]
  node [
    id 574
    label "GCAGCGATCGCTGCGCTCGAGCCCTGGCCAGGGCCGGCCGGC"
  ]
  node [
    id 575
    label "GCCTCGGCTGAGGCGCTCGAGCGGGGATCCCCAGTGGCCGCT"
  ]
  node [
    id 576
    label "GCTGAAATTTCGGCGCTTGAGTTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 577
    label "GCCTCGGCCGAGGCGCTCGAGCCACGATCGTGGGTGGCCGCC"
  ]
  node [
    id 578
    label "GCCACGGCCGTGGCGCTCGAGCGCGGATCCGCGCTGGCCGGC"
  ]
  node [
    id 579
    label "GGCTCTGCGGAGCCGCTCGAGCTTCGATCGAAACCGGCCGGT"
  ]
  node [
    id 580
    label "GCCGGGATCCTGGCGCTCGAGCGAGGATCCTCACCGGCCGGT"
  ]
  node [
    id 581
    label "GGCGGGATCCCGCCGCTCGAGCACGGATCCGTCCCAGCTGGG"
  ]
  node [
    id 582
    label "GCCCAGGTCTGGGCGCTCGAGCCTGCCGGCAGCCCGGCCGGG"
  ]
  node [
    id 583
    label "GCTGAAATTTCGGCGTT--AGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 584
    label "GGCCAGATCTGGCCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 585
    label "GCCGAAATTTCGGTGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 586
    label "GCCGGA--TCCGGCGCTCGAGCGGGGATCCCCCTTGGCCGAG"
  ]
  node [
    id 587
    label "GCTGAAGCTTTGGCGCT--AGCTTAGATCTAGCCTGGCCAGG"
  ]
  node [
    id 588
    label "GCTGAAATTTCAGCGCTCGAGCTCAGATCTGACCTGGCCGGG"
  ]
  node [
    id 589
    label "GGCCAGGTCTGGCCGCTCGAGCGAGGATCCTTGCCAGCTGGC"
  ]
  node [
    id 590
    label "GGCGCTGCAGCGCCGCTCGAGCTACGATCGTAGGCGGCCGTC"
  ]
  node [
    id 591
    label "CCGAAA--TTTCGGGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 592
    label "CCCCCGGTCGGGGGGCTCGAGCCTTGTGCAAGGCCAGCTGGT"
  ]
  node [
    id 593
    label "GCCCAGGCCTGGGCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 594
    label "GATTTGATCAAATCGCTCGAGCAAGGATCCTTAGTGGCCACT"
  ]
  node [
    id 595
    label "CCCCCGGCTGGGGGGCTCGAGCCCTGTACAGGGTCAGCTGAC"
  ]
  node [
    id 596
    label "GCCGGAATTCTGGCGCTCGAGCGAGGATCCTCCCCAGCTGGG"
  ]
  node [
    id 597
    label "GGGTTTGCAAACCCGCTCGAGCTTAGATCTAAGGCGGCCGTC"
  ]
  node [
    id 598
    label "GCCCGGGCCCGGGCGCTCGAGCCGTGATCACGGGTGGCCGCC"
  ]
  node [
    id 599
    label "GCCTAGGCCTGGGCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 600
    label "GCCTGGGCCCAGGCGCTCGAGCTGCGATCGCAGGCGGCCGTC"
  ]
  node [
    id 601
    label "GCCGCGATCGCGGCGCTCGAGCTCAGATCTGACCTGGCCGGG"
  ]
  node [
    id 602
    label "GTCAGGATCCTGGCGCTTGAGCGAGGATCCTCACTGGCTGGT"
  ]
  node [
    id 603
    label "GCCGCTGCGGTGGCGCTCGAGCGAGGATCCTTAGGAGCTCCT"
  ]
  node [
    id 604
    label "GGCCGGGCCTGGCCGCTCGAGCGACGATCGTCGGGAGCTCTC"
  ]
  node [
    id 605
    label "GCTGAA--TTCAGCGCTCGAGTTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 606
    label "GCCTTGGCCAAGGCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 607
    label "GGCTCTTAGGAGCCGCTCGAGCGAGGCGCCTTACTAGCTAGT"
  ]
  node [
    id 608
    label "GCCCGAGCTCGGGCGCTCGAGCGGCGATCGCCGGTGGCCGCC"
  ]
  node [
    id 609
    label "GGCCTGGCTAGGCCGCTCGAGCAAGGATCCTTGGCGGCCGCC"
  ]
  node [
    id 610
    label "GGCCATGCGTGGCCGCTCGAGCAAGGATCCTTGTTGGCCAAC"
  ]
  node [
    id 611
    label "GTCAGGATCCTGGCGCC--GGCGAGGATCCTCACCAGCTGGT"
  ]
  node [
    id 612
    label "GGCCAGGCCTGGCCGCTCGAGCACGGATCCGTGACAGCTGTC"
  ]
  node [
    id 613
    label "GCCGAGGCCTCGGCGCTCGAGCGGGGATCCCCGGGGGCCCTC"
  ]
  node [
    id 614
    label "GCCGAAATTTCGGCGCTCGAGCTTAGATCTGACCTGGCCGGG"
  ]
  node [
    id 615
    label "GGCTCGGCCGAGCCGCTCGAGCTAGGATCCTGGGCGGCCGTC"
  ]
  node [
    id 616
    label "GCCCAGGCCTGGGCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 617
    label "GGCCTGGCCGGGCCGCTCGAGCACGGATCCGTGGCAGCTGTC"
  ]
  node [
    id 618
    label "GCCGGGATCCCGGCGCC--GGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 619
    label "GCCGGGATCCTGGCGCTCGAGCGGGGATCCCCCGCAGCTGCG"
  ]
  node [
    id 620
    label "CGGCTC--GAGCCGGCTCGAGCTTGGTACCAAGGGGGCCCTC"
  ]
  node [
    id 621
    label "GGCCCGGCCGGGCCGCTCGAGCAAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 622
    label "GGCTCGATCGAGCCGCTCGAGCAGGGATCCCTCCTGGCCAGG"
  ]
  node [
    id 623
    label "GCCCAGATCTGGGCGCTCGAGCGAGGATCCTCCGTGGCCGCG"
  ]
  node [
    id 624
    label "GCACATGCGTGTGCACTCGAGTAAATATATTTGTAAGCTTAC"
  ]
  node [
    id 625
    label "GGCGGA--TCCGCCGCTCGAGCACGGATCCGTGGCAGCTGCC"
  ]
  node [
    id 626
    label "GCCCAGATCTGGGCGCTCGAGCGCGGATCCGCGCTGGCCGGC"
  ]
  node [
    id 627
    label "GCCCGA--TCGGGCGCTCGAGCTTAGATCTAAACCAGCTGGT"
  ]
  node [
    id 628
    label "GCTGAAATTTTGGCGCTCGAGCTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 629
    label "GGCCAGGCTTGGCCGCTCGAGCCGCGGCCGCGGGCGGCCGCC"
  ]
  node [
    id 630
    label "GGTCTCATGAGACCGCTCGAGCAAGGATCCTTGTTGGCCGAC"
  ]
  node [
    id 631
    label "GGTTCAGCTGAACCGCTCGAGCTGTGATCACAGGCGGCCGTC"
  ]
  node [
    id 632
    label "GGCCGGGCCCGGCCGCTCGAGCGCGGATCCGCGGCAGCTGCC"
  ]
  node [
    id 633
    label "GCCGCCTAGGCGGCGCTCGAGCCTCGATCGAGCCCCGCGGGG"
  ]
  node [
    id 634
    label "GCCCCGGCCGGGGCGCTCGAGCCCCGGCCGGGCCGGGCCCGG"
  ]
  node [
    id 635
    label "GGTCTCGCGAGACCGCTCGAGCCTCGCGTGAGACCGGCCGGT"
  ]
  node [
    id 636
    label "GGCTCAGCTGAGCCGCTCGAGCAAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 637
    label "GCCGAGGCCTCGGCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 638
    label "GGCCAGGCCTGGCCGCTCGAGCCTGGATCCAGGGCGGCCGCC"
  ]
  node [
    id 639
    label "GCCGAAATTTTGGCGCTCGAGCTCAGATCTGACCTGGCCGGG"
  ]
  node [
    id 640
    label "GGCCGG--CCGGCCGCTCGAGCGAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 641
    label "GCCCAGATCTGGGCGCTCGAGCAAGGATCCTTGGTGGCCGCC"
  ]
  node [
    id 642
    label "GCCTCGATCGAGGCGCTCGAGCGCGGATCCGCGCTGGCCGGC"
  ]
  node [
    id 643
    label "GCCTCGATCGAGGCGCTCGAGCGAGGATCCTCCCTGGCCGGG"
  ]
  node [
    id 644
    label "GGTTCAGCTGAACCGCTCGAGCTTTGATCAAAGGCGGCCGTC"
  ]
  node [
    id 645
    label "GCCCAGATCTGGGCGCTCGAGCGAGGATCCTCGCTGGCCGGC"
  ]
  node [
    id 646
    label "GCCGGA--TCCGGCGCTCGAGCGAGGATCCTCGGCAGCTGCC"
  ]
  node [
    id 647
    label "GGGGCG--CGCTCCGCG--CGCCTGGCGCCGGTTTGGCCAAG"
  ]
  node [
    id 648
    label "GGCTCTGCGGAGCCGCTCGAGCAGCGATCGCTAGCGGCCGCT"
  ]
  node [
    id 649
    label "GGCTAGATCTGGCCGCTCGAGCGAGGATCCTTGTCGGCCGGC"
  ]
  node [
    id 650
    label "GCCGAAATTTTGGCGCTCGAGCTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 651
    label "GGCTCGGCCGAGCCGTC--GACGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 652
    label "GGCCTG--CAGGCCGCTCGAGCATGCATGCATGGCGGCCGTC"
  ]
  node [
    id 653
    label "GGCCAGGCCTGGCCGCTCGAGCGGGGATCCCCGGCGGCCGTC"
  ]
  node [
    id 654
    label "GCCCGGATCCGGGCGCTCGAGCGGGGATCCCCCGTGGCCGCG"
  ]
  node [
    id 655
    label "GCGGGA--TCCCGCGCTCGAGCTCAGATCTGAGCGTGCGCGC"
  ]
  node [
    id 656
    label "TCATAC--GTGTGAGCC--GGCCTTGATCAAGACGGGCCCGT"
  ]
  node [
    id 657
    label "GTCAGGATCCTGGCGCTCGAGCGAGGATCCTCACCGGCTGGT"
  ]
  node [
    id 658
    label "GGGGCGGCCGCCCCGCTCGAGCCCGGATCCGGGGGGGCCCCC"
  ]
  node [
    id 659
    label "GCCGAGGTTTCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 660
    label "GGCCGG--CCGGCCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 661
    label "GCGAAA--TTTCGCGCTCGAGCTTAGATCTAACCTGGTCAGG"
  ]
  node [
    id 662
    label "GCCAAA--TTTGGCGTTCGAGCTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 663
    label "GGCCAGGCCTGGCCGCTCGAGCGCGGATCCGCGGCGGCCGTC"
  ]
  node [
    id 664
    label "GCCGGGGCCCCGGCGCTCGAGCGCGGATCCGCCCTGGCCGGG"
  ]
  node [
    id 665
    label "GGGAGT--ACTCTCGCTCGAGCCCCGCGCGGGGCGGGCCCGC"
  ]
  node [
    id 666
    label "GGCTCGATCGAGCCGCTCGAGCGCGGATCCGCGTAGGCCTAC"
  ]
  node [
    id 667
    label "CCCCCGGCTGGGGGGCTCGAGCCTTGATCAAGGTCAGCTGAC"
  ]
  node [
    id 668
    label "GCCCAGGCCTGGGCGCTCGAGCTGCGATCGCAGCTGGCCGGC"
  ]
  node [
    id 669
    label "GGCCAGATCTGGCCGCTCGAGCCGGCCGGCCGGGCGGCCGTC"
  ]
  node [
    id 670
    label "GGCCAGATCTGGCCGCTCGAGCGAGGATCCTTGCTGGCCAGT"
  ]
  node [
    id 671
    label "CCCCTGGCTGGGGGGCTCGAGCCCTGTACAGGATCCGCGGAT"
  ]
  node [
    id 672
    label "GGCCGA--TCGGCCGCTCGAGCAAGGATCCTTGGCGGCCGTC"
  ]
  node [
    id 673
    label "GCCTCGATCGAGGCGCTCGAGCGCGGATCCGCCCTGGCCGGG"
  ]
  node [
    id 674
    label "GGTTGTGCACAACCGCTCGAGCGCAGATCTGCGGCGGCCGTC"
  ]
  node [
    id 675
    label "GGCTCGATCGAGCCGCTCGAGCGAGGATCCTCACTGGCCAGT"
  ]
  node [
    id 676
    label "GGCTTGGCCAGGCCGCTCGAGCGAGGATCCTTGCTGGCCAGC"
  ]
  node [
    id 677
    label "GCCAAA--TTTGGCGCC--GGCTCAGATCTGACCTGGCCGGG"
  ]
  node [
    id 678
    label "GGCCTGTACAGGCCGCTCGAGCAGTGATCACTCTTGGCCGAG"
  ]
  node [
    id 679
    label "GCTGAAATTTCGGCGCTCGAGTTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 680
    label "GCTGAAATTTTGGCGCTCGAGTTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 681
    label "GCCCGGGCCCGGGCGCTCGAGCGTGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 682
    label "GCCCAAGCTTGGGCGCTCGAGCTGCGATCGCAGGTGGCCGCC"
  ]
  node [
    id 683
    label "GGCCCGATCGGGCCGCTCGAGCGAGGATCCTTGGTGGCCGCC"
  ]
  node [
    id 684
    label "GTCGGA--TCTGGCGCTCGAGTGAGGATCCTCACCGGCTGGT"
  ]
  node [
    id 685
    label "GCCATGGCCATGGCGTTCGAACCCAGATCTGGGCTGGCCGGC"
  ]
  node [
    id 686
    label "GCTGAAATTTCGGCGTTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 687
    label "GGCCTG--CAGGCCGCTCGAGCTACGATCGTAGGCGGCCGTC"
  ]
  node [
    id 688
    label "GGCCAGGTCTGGCCGCTCGAGCTCCGCGCGGAGTCGGCCGAC"
  ]
  node [
    id 689
    label "GCTGAAGCTTCAGCGCTCGAGCTTAGATCTAATCTGGCTGGG"
  ]
  node [
    id 690
    label "GGTGCTTAGGCACCGCAGTTGCTCCCGCGGGATGTGGCCACG"
  ]
  node [
    id 691
    label "GCCCGGGTCCGGGCGCTCGAGCCGCGGCCGCGCCCGGCCGGG"
  ]
  node [
    id 692
    label "GGTTTCGCGAAACCGCTCGAGCACGGATCCGTGACAGCTGTC"
  ]
  node [
    id 693
    label "GGCCTGGCCGGGCCGCTCGAGCGAGGATCCTTGTTGGCCGAC"
  ]
  node [
    id 694
    label "GCCCAGGCCTGGGCGCTCGAGCCGTGATCACGGGCGGCCGTC"
  ]
  node [
    id 695
    label "GGCCGG--CCGGCCGCTCGAGCGAGGATCCTTGGCGGCCGCC"
  ]
  node [
    id 696
    label "GGCCTGTACAGGCCGCTCGAGCAATGATCATTCTTGGCCGAG"
  ]
  node [
    id 697
    label "GGCCAGGCTTGGCCGCTCGAGCTGCGGCCGCAGGCGGCCGCC"
  ]
  node [
    id 698
    label "GCTGAGGCCTCAGCGCTCGAGCCAGGTACCTGGACAGCTGTC"
  ]
  node [
    id 699
    label "GGCGGG--CCCGCCGCTCGAGCGGGGATCCCCAGGGGCCCTT"
  ]
  node [
    id 700
    label "GCCGAAATTTCGGTGCTCGAGCTTAGATCTAACTTGGCCGGG"
  ]
  node [
    id 701
    label "GGCCAATATTGGCCGCTCGAGCGCGGATCCGCCGTGGCCGCG"
  ]
  node [
    id 702
    label "GCCCAGATTTGGGCGCTCGAGCGAGGATCCTCGCTGGCCAGC"
  ]
  node [
    id 703
    label "GTAGTG--CACTGCGCC--GGCTTGGATTCAGGTGGGCCCAC"
  ]
  node [
    id 704
    label "GCCTCGGCCGAGGCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 705
    label "GCCTAGGCCTGGGCGCTCGAGCGAGGATCCTCGGCAGCTGCC"
  ]
  node [
    id 706
    label "GGCTGGATCTAGCCGCTCGAGCGAGGATCCTTGGTGGCCGCC"
  ]
  node [
    id 707
    label "GCTTCTGCGGAAGCGCTCGAGCGAGGATCCTCGATGGCCGTC"
  ]
  node [
    id 708
    label "CCCCCGGCTGGGGGGCTCGAGCCCTGTACAGGGTCGGCCGAC"
  ]
  node [
    id 709
    label "CCGGAA--TTCCGGGCTCGAGCTTAGATCTAACCCGGCTGGG"
  ]
  node [
    id 710
    label "GGTCCGATCGGACCGCTCGAGCCTTGATCAAGGGCAGCTGTC"
  ]
  node [
    id 711
    label "GCTGAAATTTCAGCGCTCGAGCTTAGATTTAACCTGGCCGGG"
  ]
  node [
    id 712
    label "GCCTCAATTGGGGCGCTCGAGCTACGATCGTAACCAGCTGGT"
  ]
  node [
    id 713
    label "GGCCGG--CCGGCCGCTCGAGCGCGGATCCGCGTTGGCCGAC"
  ]
  node [
    id 714
    label "GCCGGTCGGCCGGCGCGTGCGCCCTGTACAGGCCCGGCCGGG"
  ]
  node [
    id 715
    label "GGGCAGGCCTGCCCGCTCGAGCCTCGCGTGAGGGCGGCCGCC"
  ]
  node [
    id 716
    label "GCCTCTGCGGAGGCGCTCGAGCGAGGATCCTCGTTGGCCGAC"
  ]
  node [
    id 717
    label "GGCGGGATCCCGCCGCTCGAGCCGTGATCACGCCCGGCCGGG"
  ]
  node [
    id 718
    label "GGCCACATGTGGCCGCTCGAGCAGGGATCCCTCCTAGCTAGG"
  ]
  node [
    id 719
    label "GGCCAGATCTGGCCGCTCGAGCTTCGCGTGAAGCCGGCCGGC"
  ]
  node [
    id 720
    label "GGTCAGGCCTGACCGCTCGAGCTCCGCGCGGAGGCGGCCGCC"
  ]
  node [
    id 721
    label "GCCCGGGCCCGGGCGCTCGAGCGCGGATCCGCGGTGGCCGCC"
  ]
  node [
    id 722
    label "GCCAAA--TTTGGCGCT--AGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 723
    label "GGTGATGCATCACCGCTCGAGCAAGGATCCTTGCTGGCCGGC"
  ]
  node [
    id 724
    label "GCCGCCGTGGCGGCGCTCGAGCCGTGATCACGGCTGGCCGGC"
  ]
  node [
    id 725
    label "GCCCAGATTTGGGCGCTCGAGCGAGGATCCTCGCTGGCCGGC"
  ]
  node [
    id 726
    label "GCGAAA--TTTCGCGCTCGAGCTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 727
    label "GCCTGGGCCCAGGCGCTCGAGCGCGGATCCGCGCTGGCCGGC"
  ]
  node [
    id 728
    label "GCCCCTGCGGGGGCGCTCGAGCCCAGATCTGGCCCGGCCGGG"
  ]
  node [
    id 729
    label "CCAAAA--TTTTGGGCTCGAGCTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 730
    label "GCCTAGGTCTGGGCGCTCGAGCCTGCCGGCAGCCCGGCCGGG"
  ]
  node [
    id 731
    label "GCTGAA--TTTGGCGCTCGAGTTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 732
    label "GGCTCTGCGGAGCCGCTCGAGCAGCGATCGCTAACGGCCGTT"
  ]
  node [
    id 733
    label "GCTGGATATCTAGCGCTCGAGCCTAGATCTAGCCCGGCCGGG"
  ]
  node [
    id 734
    label "GCGGAA--TTCCGCCTC--GAGTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 735
    label "GGCCAGGCCTGGCCGCTCGAGCCTGGATCCAGGACAGCTGTC"
  ]
  node [
    id 736
    label "GGCCAGGCCTGGCCGCTCGAGCTCCGATCGGAGGCGGCCGCC"
  ]
  node [
    id 737
    label "GCTGAAATTTCGGCGCTCGAGCTTAGATCTAACTTGGCCGGG"
  ]
  node [
    id 738
    label "GCGGCCGCGGCCGCGCTCGAGCCCCGGCCGGGCCGGGCCCGG"
  ]
  node [
    id 739
    label "GGTAGG--CCTACCGCTCGAGCATGGATCCATGCCGGCCGGC"
  ]
  node [
    id 740
    label "GGCTCTTAGGAGCCGCTCGAGCGAGGCGCCTTCCCAGCTGGG"
  ]
  node [
    id 741
    label "GCCTCGGCTGAGGCGCTCGAGCGCGGATCCGCGGCGGCCGCC"
  ]
  node [
    id 742
    label "GGCTCGATCGAGCCGCTCGAGCAAGGATCCTTGGCAGCTGCC"
  ]
  node [
    id 743
    label "GGAACTTAGGTTCCGCGTGCGCGATGCGCATCCTCGGCCGAG"
  ]
  node [
    id 744
    label "GGCCGG--CCGGCCGTC--GACATGGATCCATGGCGGCCGTC"
  ]
  node [
    id 745
    label "GCTCAGGCCTGAGCGCTCGAGCGGGGATCCCCGGCAGCTGTC"
  ]
  node [
    id 746
    label "GGCCAGGCTTGGCCGCTCGAGCTCCGCGCGGAGCCGGCCGGC"
  ]
  node [
    id 747
    label "GGCTTTGCAAAGCCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 748
    label "GCCGTGGCCACGGCGTTCGAACCCGGATCCGGGCCGGCCGGC"
  ]
  node [
    id 749
    label "GGTCTGATCAGACCGCTCGAGCGAGCCGGCTTGGTGGCCACC"
  ]
  node [
    id 750
    label "GGCCGG--CCGGCCGCTCGAGCAAGGATCCTTGGCAGCTGTC"
  ]
  node [
    id 751
    label "GGCGAGGCCTCGCCGCTCGAGCGTGGATCCACGACGGCCGTC"
  ]
  node [
    id 752
    label "GGCTCGGTCGAGCCGCTCGAGCATGGATCCATGGCGGCCGTC"
  ]
  node [
    id 753
    label "GGGCAGGCCTGCCCGCTCGAGCCTCGCGCGAGGGCGGCCGCC"
  ]
  node [
    id 754
    label "GGCCGG--CCGGCCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 755
    label "GGCCAGATCTGGCCGCTCGAGCGAGGATCCTTCCCAGCTGGG"
  ]
  node [
    id 756
    label "GTTGAAATTTCGGCGCTCGAGCTTAGATCTAACCTAGCTGGG"
  ]
  node [
    id 757
    label "GCCTCGGCTGAGGCGCTCGAGCGAGGATCCTCGGCGGCCGCC"
  ]
  node [
    id 758
    label "GCCAAAATTTTGGTGCTCGAGTTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 759
    label "GGCCCGGTCGGGCCGCTCGAGCAAGGATCCTTACTGGCCGGT"
  ]
  node [
    id 760
    label "GCTTCGTACGAAGCGCTCGAGCGAGGATCCTCCTTGGCCGAG"
  ]
  node [
    id 761
    label "GGCCGG--CCGGCCGCTCGAGCGCGGATCCGCGATGGCCGTC"
  ]
  node [
    id 762
    label "GGCCACATGTGGCCGCTCGAGCAAGGATCCTTCCTGGCCAGG"
  ]
  node [
    id 763
    label "GGCCAG--CTGGCCGCTCGAGCATGGATCCATGGCGGCCGTC"
  ]
  node [
    id 764
    label "GGTTTAGCTGAACCGCTCGAGCTGTGATCACAGGCGGCCGTC"
  ]
  node [
    id 765
    label "GCCTCGATCGAGGCGCTCGAGCGAGGATCCTCCGTGGCCGCG"
  ]
  node [
    id 766
    label "GGCCCGGCCGGGCCGCTCGAGCCTTGATCAAGGGCAGCTGTC"
  ]
  node [
    id 767
    label "GGTTTCGCGAAACCGCTCGAGCGTTGATCAACGGCAGCTGTC"
  ]
  node [
    id 768
    label "GCCCAGATCTGGGCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 769
    label "GCCCTAGCTGGGGCGCTCGAGCCCAGATCTGGCCCGGCCGGG"
  ]
  node [
    id 770
    label "GCCGAAATTTCGGCGCTCGAGCTCAGATCTGACCTGGCCGGG"
  ]
  node [
    id 771
    label "GCCGAAATTTCGGTGCTCGAGTTCAGATCTGACCTGGCCGGG"
  ]
  node [
    id 772
    label "GCCCAGATCTGGGCGCTCGAGCATGGATCCATGCCGGCCGGC"
  ]
  node [
    id 773
    label "GCCGAAATTTCGGCGCTCGAGCTTAGATCTAACTTGGCCGGG"
  ]
  node [
    id 774
    label "GGCCAGATCTGGCCGCTCGAGCGAGGATCCTCGGTGGCCGCC"
  ]
  node [
    id 775
    label "GCCGCGGCCGCGGCGTTCGAACCGGGATCCCGGGGTGCACCC"
  ]
  node [
    id 776
    label "GCCGGGGCCCCGGCGCTCGAGCTCCGGCCGGAGAGGGCCCTC"
  ]
  node [
    id 777
    label "GCTGAAGCTTCAGCCTC--GAGTTAGATCTAACCTGGCCAGG"
  ]
  node [
    id 778
    label "GGCTCTGCGGAGCCGCTCGAGCTGCGATCGTAACCGGCCGGT"
  ]
  node [
    id 779
    label "GGTCGGATCCGACCGCTCGAGCCACGCGCGTGACCGGCCGGT"
  ]
  node [
    id 780
    label "GGCTCTGCGGAGCCGCTCGAGCACGGATCCGTGGCGGCCGCC"
  ]
  node [
    id 781
    label "GCTCGGGCCCGAGCGCTCGAGCGGGGATCCCCGGCAGCTGTC"
  ]
  node [
    id 782
    label "GGCCAGGTCTGGCCGCTCGAGCTCCGCGTGGAAGCGGCCGCT"
  ]
  node [
    id 783
    label "GGCCAGATCTGGCCGCTCGAGCGAGGATCCTCGGCGGCCGTC"
  ]
  node [
    id 784
    label "GCCGCTGTGGCGGCGCTCGAGCAAGGATCCTTAAGGGCCCTT"
  ]
  node [
    id 785
    label "GGTTCA--TGGGTCGCT--AGCCAAGGCCTTGGTGGGCCCAC"
  ]
  node [
    id 786
    label "GGCGAGATTTCGCCGCTCGAGCGAGGCGCCTTCCCAGCTGGG"
  ]
  node [
    id 787
    label "GGGCAGGCCTGCCCGCTCGAGCGGGGCGCCCCGGCGGCCGTC"
  ]
  node [
    id 788
    label "GGCTGGATCCAGCCGCTCGAGCGGAGATCTCCGGCGGCCGTC"
  ]
  node [
    id 789
    label "GGCCAGATCTGGCCGCTCGAGCTCCGCGTGGAGACAGCTGTC"
  ]
  node [
    id 790
    label "GGCCAGGCCTGGCCGCTCGAGCTCCGCGCGGAACCGGCCGGT"
  ]
  node [
    id 791
    label "GGCCCGGCTGGGCCGCTCGAGCCCCGGCCGGGGGCGGCCGCC"
  ]
  node [
    id 792
    label "GGCCTGATCGGGCCGCTCGAGCGAGGATCCTTGGTGGCCGCC"
  ]
  node [
    id 793
    label "GCCTCGGCCGAGGCGCTCGAGCGGGGATCCCCGGTGGCCGCC"
  ]
  node [
    id 794
    label "GGCCCGGCCGGGCCGCTCGAGCGAGGATCCTTGGTGGCCGCC"
  ]
  node [
    id 795
    label "GGCTCGATCGAGCCGCTCGAGCACGGATCCGTGGCAGCTGCC"
  ]
  node [
    id 796
    label "ACCAGGATCCTGGTGCC--GGCTTGGATCCAAGTGGGCCCAC"
  ]
  node [
    id 797
    label "GGAGATATATCTCCGCTCGAGCGTGGATCCATACTGGCCAGT"
  ]
  node [
    id 798
    label "GTTAGG--TCTAGCGCTCGAGCAAGGATCCTTAGTGGCCACT"
  ]
  node [
    id 799
    label "GCCCGAATTCGGGCGCTCGAGCGAGGATCCTCCCTGGCCGGG"
  ]
  node [
    id 800
    label "GCCGAAATTTCGGCGCTCGAGCTTAGATCTAACCTGGCTGGG"
  ]
  node [
    id 801
    label "GCCTGGATCCAGGCGCTCGAGCGCGGATCCGCGCTGGCCGGC"
  ]
  node [
    id 802
    label "GGCCAGATCTGGCCGCTCGAGCACGGATCCGTGGCAGCTGCC"
  ]
  node [
    id 803
    label "GCCTTGATCAGGGCGCTCGAGCTTAGATCTAAACCAGCTGGT"
  ]
  node [
    id 804
    label "GCCAAAATTTTGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 805
    label "GCCGGGATCCTGGCGCTCGAGCGCGGATCCGCGCCAGCTGGC"
  ]
  node [
    id 806
    label "GCCGCAGCTGCGGCACTCGAGTCAAGATCTTGGCTGGCCGGC"
  ]
  edge [
    source 1
    target 328
  ]
  edge [
    source 4
    target 165
  ]
  edge [
    source 4
    target 453
  ]
  edge [
    source 4
    target 14
  ]
  edge [
    source 7
    target 386
  ]
  edge [
    source 7
    target 32
  ]
  edge [
    source 21
    target 228
  ]
  edge [
    source 32
    target 223
  ]
  edge [
    source 32
    target 650
  ]
  edge [
    source 32
    target 104
  ]
  edge [
    source 32
    target 804
  ]
  edge [
    source 32
    target 537
  ]
  edge [
    source 35
    target 627
  ]
  edge [
    source 37
    target 533
  ]
  edge [
    source 38
    target 614
  ]
  edge [
    source 38
    target 91
  ]
  edge [
    source 40
    target 118
  ]
  edge [
    source 47
    target 242
  ]
  edge [
    source 49
    target 555
  ]
  edge [
    source 53
    target 671
  ]
  edge [
    source 56
    target 133
  ]
  edge [
    source 62
    target 509
  ]
  edge [
    source 62
    target 588
  ]
  edge [
    source 65
    target 437
  ]
  edge [
    source 73
    target 84
  ]
  edge [
    source 74
    target 80
  ]
  edge [
    source 74
    target 610
  ]
  edge [
    source 74
    target 542
  ]
  edge [
    source 83
    target 275
  ]
  edge [
    source 83
    target 223
  ]
  edge [
    source 83
    target 659
  ]
  edge [
    source 85
    target 400
  ]
  edge [
    source 85
    target 118
  ]
  edge [
    source 90
    target 305
  ]
  edge [
    source 90
    target 527
  ]
  edge [
    source 91
    target 223
  ]
  edge [
    source 93
    target 803
  ]
  edge [
    source 96
    target 557
  ]
  edge [
    source 97
    target 751
  ]
  edge [
    source 98
    target 339
  ]
  edge [
    source 98
    target 122
  ]
  edge [
    source 99
    target 695
  ]
  edge [
    source 110
    target 180
  ]
  edge [
    source 113
    target 257
  ]
  edge [
    source 118
    target 166
  ]
  edge [
    source 131
    target 164
  ]
  edge [
    source 133
    target 517
  ]
  edge [
    source 142
    target 391
  ]
  edge [
    source 147
    target 752
  ]
  edge [
    source 148
    target 437
  ]
  edge [
    source 149
    target 390
  ]
  edge [
    source 166
    target 343
  ]
  edge [
    source 166
    target 169
  ]
  edge [
    source 180
    target 746
  ]
  edge [
    source 187
    target 274
  ]
  edge [
    source 188
    target 195
  ]
  edge [
    source 195
    target 615
  ]
  edge [
    source 198
    target 616
  ]
  edge [
    source 202
    target 248
  ]
  edge [
    source 203
    target 514
  ]
  edge [
    source 207
    target 412
  ]
  edge [
    source 209
    target 743
  ]
  edge [
    source 214
    target 453
  ]
  edge [
    source 223
    target 386
  ]
  edge [
    source 223
    target 415
  ]
  edge [
    source 223
    target 800
  ]
  edge [
    source 223
    target 773
  ]
  edge [
    source 223
    target 240
  ]
  edge [
    source 223
    target 614
  ]
  edge [
    source 223
    target 258
  ]
  edge [
    source 223
    target 334
  ]
  edge [
    source 223
    target 585
  ]
  edge [
    source 223
    target 489
  ]
  edge [
    source 228
    target 377
  ]
  edge [
    source 230
    target 731
  ]
  edge [
    source 234
    target 277
  ]
  edge [
    source 234
    target 352
  ]
  edge [
    source 237
    target 535
  ]
  edge [
    source 240
    target 650
  ]
  edge [
    source 240
    target 471
  ]
  edge [
    source 249
    target 440
  ]
  edge [
    source 250
    target 489
  ]
  edge [
    source 255
    target 509
  ]
  edge [
    source 258
    target 452
  ]
  edge [
    source 258
    target 686
  ]
  edge [
    source 258
    target 737
  ]
  edge [
    source 258
    target 509
  ]
  edge [
    source 258
    target 537
  ]
  edge [
    source 259
    target 478
  ]
  edge [
    source 265
    target 519
  ]
  edge [
    source 269
    target 522
  ]
  edge [
    source 269
    target 640
  ]
  edge [
    source 278
    target 422
  ]
  edge [
    source 291
    target 655
  ]
  edge [
    source 291
    target 511
  ]
  edge [
    source 296
    target 413
  ]
  edge [
    source 299
    target 509
  ]
  edge [
    source 300
    target 454
  ]
  edge [
    source 307
    target 324
  ]
  edge [
    source 311
    target 509
  ]
  edge [
    source 311
    target 452
  ]
  edge [
    source 312
    target 589
  ]
  edge [
    source 334
    target 686
  ]
  edge [
    source 339
    target 583
  ]
  edge [
    source 347
    target 711
  ]
  edge [
    source 353
    target 375
  ]
  edge [
    source 355
    target 778
  ]
  edge [
    source 356
    target 770
  ]
  edge [
    source 360
    target 706
  ]
  edge [
    source 371
    target 658
  ]
  edge [
    source 384
    target 782
  ]
  edge [
    source 391
    target 750
  ]
  edge [
    source 406
    target 412
  ]
  edge [
    source 412
    target 726
  ]
  edge [
    source 414
    target 593
  ]
  edge [
    source 414
    target 768
  ]
  edge [
    source 415
    target 659
  ]
  edge [
    source 417
    target 509
  ]
  edge [
    source 422
    target 431
  ]
  edge [
    source 428
    target 499
  ]
  edge [
    source 442
    target 706
  ]
  edge [
    source 452
    target 628
  ]
  edge [
    source 452
    target 800
  ]
  edge [
    source 453
    target 662
  ]
  edge [
    source 471
    target 489
  ]
  edge [
    source 480
    target 757
  ]
  edge [
    source 484
    target 485
  ]
  edge [
    source 486
    target 582
  ]
  edge [
    source 509
    target 711
  ]
  edge [
    source 513
    target 708
  ]
  edge [
    source 514
    target 794
  ]
  edge [
    source 522
    target 695
  ]
  edge [
    source 529
    target 650
  ]
  edge [
    source 529
    target 537
  ]
  edge [
    source 537
    target 628
  ]
  edge [
    source 539
    target 657
  ]
  edge [
    source 582
    target 730
  ]
  edge [
    source 585
    target 700
  ]
  edge [
    source 593
    target 599
  ]
  edge [
    source 614
    target 770
  ]
  edge [
    source 628
    target 680
  ]
  edge [
    source 631
    target 764
  ]
  edge [
    source 639
    target 770
  ]
  edge [
    source 640
    target 695
  ]
  edge [
    source 640
    target 754
  ]
  edge [
    source 645
    target 725
  ]
  edge [
    source 681
    target 721
  ]
  edge [
    source 683
    target 792
  ]
  edge [
    source 700
    target 773
  ]
  edge [
    source 702
    target 725
  ]
  edge [
    source 715
    target 753
  ]
  edge [
    source 737
    target 773
  ]
]
