graph [
  node [
    id 0
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGGGAGGCCTCC"
  ]
  node [
    id 1
    label "GGGCCCATGGGCCCGCTTGAGCTCCGATCGGAACCGGCCGGT"
  ]
  node [
    id 2
    label "GCCCTCGCGAGGGCGCTCGAGCGCACCGGTGTCTGGGCCCAG"
  ]
  node [
    id 3
    label "GCCTGT--ACGGGCGCTCGAGCTCAGATCTGGGGTGGCCACT"
  ]
  node [
    id 4
    label "GGGTCTGCAGACCCGCTCGGGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 5
    label "AGGCTTGCAAGCCTGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 6
    label "GGGTCTGCAGACCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 7
    label "GGCCGGTACTGGCCGCTTGAGCTGGTGCGCCAGTGGGCCCGT"
  ]
  node [
    id 8
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGTGCCAGCGGGCCCGT"
  ]
  node [
    id 9
    label "GGGATCATGATCCCGCTCGAGCCAGGTACCTGGGAGGCCTCC"
  ]
  node [
    id 10
    label "GGCCCATATGGGCCCTT--GAGTCGTGCGCGAGCAGGCCTGC"
  ]
  node [
    id 11
    label "GGGCCTATAGGCCCGCTCGAGCCTTCGCGAAGGAAGGCCTTC"
  ]
  node [
    id 12
    label "TGGCCTGCAGGCCAGCTCGAGCTACGCGCGTAGGCAGCTGCC"
  ]
  node [
    id 13
    label "GGGCCCGCGGGCCCGCTCGAGCTGCGCGCGCACGGGGCCCCG"
  ]
  node [
    id 14
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCGT"
  ]
  node [
    id 15
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGGCTGCAGCC"
  ]
  node [
    id 16
    label "GGGGCTATAGCCCCGCTCGAGCCTTCGCGAAGGGAGGCCTCC"
  ]
  node [
    id 17
    label "GGGCATATATGCCCGCTCGAGCCGTCTGGACGGGTGGCCACC"
  ]
  node [
    id 18
    label "GGGGATATATCCCCGCTCGAGCCACCCGGGTGGGTAGCTACC"
  ]
  node [
    id 19
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGCCAACGGGCCCGT"
  ]
  node [
    id 20
    label "AGGGCAGCTGCCCTGCTCGAGTCTCGGCCGAGCGGGGCCCCG"
  ]
  node [
    id 21
    label "GGGCTTGCAGGCCCGCTCGAGCCGCGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 22
    label "GGGCTTGCAAGCCCGCTCGAGTCACGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 23
    label "GGCCGT--ACGGTCGCTCGAGCTGGTGTGCCAACAGGCCTGT"
  ]
  node [
    id 24
    label "GCCTTCTAGAGGGCGCTCGAGCTCGTGCGCGAACAGGCCTGT"
  ]
  node [
    id 25
    label "GGGCCTATAGGCCCGCTCGAGCCTTTATGAAGGGAGGCCTCC"
  ]
  node [
    id 26
    label "GGGCTTATAAGCCCGCTCGAGCCACGCGCGTGGCAAGCTTGC"
  ]
  node [
    id 27
    label "GCCGGT--ACTGGCGCTCGAGCTGGTGCGCCAGCGGGCCCGC"
  ]
  node [
    id 28
    label "GGGCTTGCAAGCCCGCTCGAGTCACGCGCGTGGGAAGCTTCT"
  ]
  node [
    id 29
    label "GCTCCCGCGGGAGCGCTCGAGCTTGGTGCCGAGCGGGCCCGC"
  ]
  node [
    id 30
    label "GCGGTTATAACCGCGCTCGAGCCGACATGTCGCCAAGCTTGG"
  ]
  node [
    id 31
    label "GGGCCGGTCGGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 32
    label "GGGGGTATACCCCCGCTCGAGCCTTCATGAAGCCAGGCCTGG"
  ]
  node [
    id 33
    label "GGGCCCGCGGGCCCGCATGTGCCCCGGCCGGGATGCGCGCAT"
  ]
  node [
    id 34
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGGGCCGCGGCC"
  ]
  node [
    id 35
    label "GGCCGT--ATGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCGT"
  ]
  node [
    id 36
    label "GGCTGGTACTGGCCACTCGAGTTGGTGCGCCAGTGGGCCCGT"
  ]
  node [
    id 37
    label "GGCCCGTACGGGCCGCTCGAGCTGGTGCGCCAGTGGGCCTGT"
  ]
  node [
    id 38
    label "GCTGGT--ACTGGCGCTCGAGCTGGTGCGCCAACGGGCCCGT"
  ]
  node [
    id 39
    label "GGGGGCGCGCCCCTGCTCGAGCGCGGTGCCGCGTGGGCCCAC"
  ]
  node [
    id 40
    label "GCCCCGGCCGGGGCGCC--GGCTGGGATCTCAGCGGGCCCGT"
  ]
  node [
    id 41
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGCCAATGGGCCCAT"
  ]
  node [
    id 42
    label "GGGCCAGCTGGCCCGCTCGAGCCTGCTGGCAGAATAGCTATT"
  ]
  node [
    id 43
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGAAGGCCTTC"
  ]
  node [
    id 44
    label "GGGCCAATTGGCCCGCTCGAGCCCACTGGTGGCTCGGCCGAG"
  ]
  node [
    id 45
    label "GGCCTATATGGGCCGTTCGAGCTCGTGCGCGAGCAGGCCTGC"
  ]
  node [
    id 46
    label "GGGCCTTAAGGCCCGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 47
    label "AGGCTAGCTAGCCTGCC--GGCCACGGCCGTGCTGGGCCCAG"
  ]
  node [
    id 48
    label "GGCCGGTACTGGCTGCTCGAGCTGGTGTGCCAGCGGGCCCGT"
  ]
  node [
    id 49
    label "GGGGTTGCAACCCCGCT--AGCCTCGGCCGAGACCGGCCGGT"
  ]
  node [
    id 50
    label "GCTGGT--ACTGGTGCT--AGCTGGCGCGCCAGCGGGTTCGT"
  ]
  node [
    id 51
    label "GGCCCGTACGGGCCGCTCGAGCTGGTGCGCCAATGGGCCCAT"
  ]
  node [
    id 52
    label "GCCGCC--GGCGGCGCTCGAGCTGGGTGCCCAGCAGGCCTGC"
  ]
  node [
    id 53
    label "GGGCCCGCGGGCCCGCTTGAGCCACGGCCGTGCTGGGCCCAG"
  ]
  node [
    id 54
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGATGTGCACAT"
  ]
  node [
    id 55
    label "GGGTCTGCAGACCCGCTCGAGCCCGTCGGCGGGTAGGCCTAC"
  ]
  node [
    id 56
    label "GGGTCAGCTGACCCGCTCGAGCCCACTGGTGGTGCGGCCGCA"
  ]
  node [
    id 57
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGGGTGGCCACC"
  ]
  node [
    id 58
    label "GGGCCCGTGGGCCCGCTCGAGTCACCCGGGTGGGTAGCTACC"
  ]
  node [
    id 59
    label "GGGCTTGCAGGCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 60
    label "GGAAATATATTTCCGTTCGAACTTCCCGGGAAGGTGGCCGCC"
  ]
  node [
    id 61
    label "GCTCCCGCGGGAGCGTCTGGACCTGGTACCGGGCGGGCCCGC"
  ]
  node [
    id 62
    label "GGTCGCATGTGACCATG--CATTCGATGTCGAGCCAGCTGGC"
  ]
  node [
    id 63
    label "GGGCCCGCGGGCCCGCTCGAGCCGGGGCCCCGCCGGGCCCGG"
  ]
  node [
    id 64
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 65
    label "GGGCTATATGGCCCGCTCGAGCCTGTGCGCAGCCAGGCCTGG"
  ]
  node [
    id 66
    label "GGGCCTATAGGCCCGCTCGAGCCACGGCCGTGGATGGCCATT"
  ]
  node [
    id 67
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGTTGGCCAAT"
  ]
  node [
    id 68
    label "CCTTTCGCGGAAGGGCTCGAGCGCGGCGCCGCGCAGGCCTGC"
  ]
  node [
    id 69
    label "GGCCTATATGGGCCGCTCGAGCTCGTGCACGAGCAGGCCTGC"
  ]
  node [
    id 70
    label "AGTCTCGCGAGACTGCTCGAGCCTACATGTAGGGCAGCTGCC"
  ]
  node [
    id 71
    label "AGGGCGGCCGCCCTGCT--AGTCTCGGCCGAGCGGGGCCCCG"
  ]
  node [
    id 72
    label "GGGCGATATCGCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 73
    label "GGGCCCGCGGGCCCGCTCGAGCCACCCGGGTGGGTAGCTACC"
  ]
  node [
    id 74
    label "GGGCTCGCGGGCCCGCTCGAGCCACGATCGTGGGAGGCCTCC"
  ]
  node [
    id 75
    label "GGGCCCGCGGGCCCGCTTGAGCCACGGCCGTGACGCGCGCGT"
  ]
  node [
    id 76
    label "GGCCGT--ACGGCCCTC--GAGTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 77
    label "GGGCCTGCAGGCCCGCTCGAGCCTGTGCGCAGACAGGCCTGT"
  ]
  node [
    id 78
    label "GGGGCTATAGCCCCGCTCGAGCCTTCCGGAAGTCTGGCCAGA"
  ]
  node [
    id 79
    label "AGATCCGCGGGTCTGCTCGAGCCTACATGTAGAGCAGCTGCT"
  ]
  node [
    id 80
    label "GGGCCGATCGGCCCGCTCGAGCCACGGCCGTGGGAGGCCTCC"
  ]
  node [
    id 81
    label "GGGCCTATAGGCCCGCTCGAGTCACCCGGGTGCCAGGCCTGG"
  ]
  node [
    id 82
    label "GGGCCAGTTGGCCCGCTCGAGCCACGCGCGTGGAAAGCTTTC"
  ]
  node [
    id 83
    label "GCCGCCATGGCGGCGTC--GACTGGGTGCCCAGCAGGCCTGC"
  ]
  node [
    id 84
    label "GGGCTCGCGGGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 85
    label "AGGCTTGCAAGCCTGCTCGAGCCACCCGGGTGGGCAGCTGCC"
  ]
  node [
    id 86
    label "GGTCCCATGGGACCACTCGAGTCTGAGCTCAGGAGAGCTCTC"
  ]
  node [
    id 87
    label "GGCCGT--ATGGCCGTTCGAGCTGGTGCACCAGTGGGCCCAT"
  ]
  node [
    id 88
    label "GGGCCTGCAGGCCCGCTCGAGCCTCGCGCGAGACAAGCTTGT"
  ]
  node [
    id 89
    label "AGGTCTATAGACCTGCTCGAGCCTACATGTAGTGCAGCTGCG"
  ]
  node [
    id 90
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 91
    label "GGTCTG--CAGACCGCTCGAGCCCGTCGGCGGGTTGGCCAAC"
  ]
  node [
    id 92
    label "GGGCCTATAGGCCCGCTCGAGCCCACATGTGGAGAGGCCTCT"
  ]
  node [
    id 93
    label "GGTTCA--TGAATCGTGTACACTTTGCGCAGACTGGGCCCGG"
  ]
  node [
    id 94
    label "GGGCTTATAAGCCCGCTCGAGCTACCCGGGTAAGAGGCCTCT"
  ]
  node [
    id 95
    label "GGCCAT--ATGGCCGCTCGAGCTCGTGCGCGAGCAGGCCTGC"
  ]
  node [
    id 96
    label "GGGGCTATAGTCCCGCTCGAGCCACCTGGGTGATGAGCTCAT"
  ]
  node [
    id 97
    label "GGGGCTATAGCCCTGCTCGAGCCTCCGCGGAGGCTGGCCAGT"
  ]
  node [
    id 98
    label "GGGATTGTAATCCCGCTCGAGCTACCTGGGTAAATAGCTATT"
  ]
  node [
    id 99
    label "GCGGCG--CGTCGCGCTCGAGCCACGATCGTGGATGGCCATT"
  ]
  node [
    id 100
    label "GGCCTATATGGGCCGCTCGAGCTCGTGCGCGAGCAGGCCTGC"
  ]
  node [
    id 101
    label "GGGTCTGCAGGCCCGCTCGAGCCACGTGCGTGGGAAGCTTCC"
  ]
  node [
    id 102
    label "GGGCCTATAGGCCCGCTCGAGCCTGCCGGCAGACTGGCCAGT"
  ]
  node [
    id 103
    label "GGGTCTATAGACCCGCTCGAGTCACCCGGGTGAGAGGCCTCT"
  ]
  node [
    id 104
    label "GGCCGGTACTGGCCGCTCGAGTTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 105
    label "GGGCTTATAAGCCCGCTCGAGTCACCCGGGTGGGAGGCCTCC"
  ]
  node [
    id 106
    label "GGACCTGCAGGTCCGCTCGAGCCACGCGCGTGGGTAGCTACT"
  ]
  node [
    id 107
    label "GGCCGT--ACGGCCTTC--GAGTGGTGCGCCAGCGGGTCCGT"
  ]
  node [
    id 108
    label "GGGCCTCGAGGCCCGCTCGAGCTGCCCGGGCAGGTGGCCACC"
  ]
  node [
    id 109
    label "GGTCCGTACGGACCGCC--GGCCCGTGCGCGGGGCGGCCGCC"
  ]
  node [
    id 110
    label "GGGCCTGCAGGCCCGCTCGAGCCTTCTGGAAGATTAGCTAAT"
  ]
  node [
    id 111
    label "GGGTCTGCAGACCCGCTCGAGCCACGCGCGTGGGTAGCTACT"
  ]
  node [
    id 112
    label "CGGGGTATACCCCGGCTCGGGCCTCGTGCGAGCTCGGCCGAG"
  ]
  node [
    id 113
    label "GCCCTGATTAGGGCGCC--GGCTGAGGCCTCAGCGGGCCCGC"
  ]
  node [
    id 114
    label "GGTCGGTACCGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGC"
  ]
  node [
    id 115
    label "GGCTGT--ACGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 116
    label "GGGCGTGCATGCCCGCTCGAGCCTGTGCGCAGGCTGGCCAGC"
  ]
  node [
    id 117
    label "CGGAGTATATTCCGGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 118
    label "ACATGG--CCGTGTGTTCGAATCTCGCGCGGGCCAGGTCTGG"
  ]
  node [
    id 119
    label "AGCCAG--CTGGCTGCT--GGCTGGTGCATCAATGGGCCCAT"
  ]
  node [
    id 120
    label "GGGCCTATAGGCCCGCTCGAGCCACCCGGGTGTGAGGCCTCA"
  ]
  node [
    id 121
    label "GGGCTCGCGAGCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 122
    label "GGCCCATATGGGCCGCTTGAGCTCGTGCGTGAGCAGGCCTGC"
  ]
  node [
    id 123
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGTCAGCGGGCCCGT"
  ]
  node [
    id 124
    label "GGTCCTTAGGGACCGCTCGAGCTGGTGCGCCAGCGAGCTCGT"
  ]
  node [
    id 125
    label "GGCCCATATGGGCCGCTCGAGCTGGTGCGCCAGCAGGCCTGC"
  ]
  node [
    id 126
    label "GTCCTG--CAGGACGCT--AGTTTGGTGCCAATTGGGCCCAA"
  ]
  node [
    id 127
    label "GGTCTCTAGAGACCGCC--GGCCCGTGCGCGGAGCAGCTGCT"
  ]
  node [
    id 128
    label "GGTCCGTATGGACCGCTCGAGCTCGTGCGCGAGAGAGCTCTC"
  ]
  node [
    id 129
    label "GGGGTG--TACCTCGCTCGAGCTGTGCGTACACTAGGCCTGG"
  ]
  node [
    id 130
    label "GGAGGTATACCTCCGTTCGAACCTCCCGGGAGGATGGCCATC"
  ]
  node [
    id 131
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCGCTAGCGGGCCCGT"
  ]
  node [
    id 132
    label "AGGGCGGCCGCCCTGCTCGAGTCTCGGCCGAGCGGGGCCCCG"
  ]
  node [
    id 133
    label "AGGCCTGCAGGCCTGCTCGAGCCCGTGCGCGGGGCAGCTGCC"
  ]
  node [
    id 134
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 135
    label "GGGCTCGCGGGCCCGCTCGAGCCTGCTGGCAGACTAGCTAGT"
  ]
  node [
    id 136
    label "AGGACAGCTGTCCTGCTCGAGTCTCGGCCGAGCGGGGCCCCG"
  ]
  node [
    id 137
    label "GGCCGTTAATGGCCGCTCGAGCTCGTGCGCGAGCGGGCCCGT"
  ]
  node [
    id 138
    label "GGCCGGTACTGGCCGTC--GACTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 139
    label "GGTCCGCGTGGACCGTTCGAGCTCGTGCGCGAGTGGGCCCAC"
  ]
  node [
    id 140
    label "GGGCTAGCTAGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 141
    label "AGGCTAGCTAGCCTGCC--GGCCACGGCCGTGATGGGCCCAT"
  ]
  node [
    id 142
    label "GGCCGGTGTTGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 143
    label "GGGCTCGCGGGCCCGCTCGAGCTTCGATCGAAATGAGCTCAT"
  ]
  node [
    id 144
    label "GCTTTGTACAGAGCGCTCGAGCTCGTGCGCGAACAGGCCTGT"
  ]
  node [
    id 145
    label "GGGGCTATAGCCCCGCTCGAGCCTTCCGGAAGCCAGGCCTGG"
  ]
  node [
    id 146
    label "GGGCCAATTGGCCCGCTCGAGCCTCGGCCGGGCACGGCCGTG"
  ]
  node [
    id 147
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGGCAGCTGCC"
  ]
  node [
    id 148
    label "GGTCCTGCAGGACCGTTCGAACTTGGTGCCGAGCGGGCCCGC"
  ]
  node [
    id 149
    label "GGCCTATATAGGCCGCTTGAGCTGGTCGGCCAGCAGGCCTGC"
  ]
  node [
    id 150
    label "GTTTCA--TGAAACGTG--CATTCTGCGCAGACTGGGCCCAG"
  ]
  node [
    id 151
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGAAAGCTTTC"
  ]
  node [
    id 152
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGCCAACGGGCCTGT"
  ]
  node [
    id 153
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGGGTAGCTACC"
  ]
  node [
    id 154
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGATGGCCATT"
  ]
  node [
    id 155
    label "GGGCCTATAGGCCCGCTCGAGCCTGTCGACAGGCTGGCCAGC"
  ]
  node [
    id 156
    label "GGGCCTGCAGGCCCGCTCGAGCCACCCGGGTGGGTAGCTACC"
  ]
  node [
    id 157
    label "GGTCTCTAGAGACCGCC--GGCCCGTGCACGGAGCGGCCGCT"
  ]
  node [
    id 158
    label "GGGGATATATCCCCGCTCGAGCCTTCATGAAGCCAGGCCTGG"
  ]
  node [
    id 159
    label "GGGAGCATGTTCCCGCTCGAGCCTGTGCGCAGCGAGGCCTCG"
  ]
  node [
    id 160
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGATGGCCATC"
  ]
  node [
    id 161
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGGGTAGCTACT"
  ]
  node [
    id 162
    label "GCGCGGTACCGCGCGCTCGAGCCGTCGCGACGACAAGCTTGT"
  ]
  node [
    id 163
    label "AGGCTG--CAGCCTGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 164
    label "GGGCTTGCAGGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 165
    label "GGGCCTGCAGGCCCGCTCGAGCCTACATGTAGCGTGGCCACG"
  ]
  node [
    id 166
    label "GGCCTATATGGGCCCTC--GAGTCGTGCGCGAGCAGGCCTGC"
  ]
  node [
    id 167
    label "GGCCGT--ACGGCCGTC--GACTGGTGCGCCAACGGGCCCGT"
  ]
  node [
    id 168
    label "GGGCGTATACGCCCGCTCGAGCCCACATGTGGCGTGGCCACG"
  ]
  node [
    id 169
    label "GGCCCATATGGGCCGCTCGAGCTCGTGCGCGAGCAGGCCTGC"
  ]
  node [
    id 170
    label "GGGCACGCGTGCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 171
    label "GGGCCTATAGGCCCGCTCGAGTCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 172
    label "GGGCTATATAGCCCGCTCGAGCCACCCGGGTGCCTGGCCAGG"
  ]
  node [
    id 173
    label "GGGGTTGCAGCCCCGCTTGAGCCCCGGCCGGGACCGGCCGGT"
  ]
  node [
    id 174
    label "GGGCTATATGGCCCGCTCGAGCCACGGCCGTGCCTGGCCAGG"
  ]
  node [
    id 175
    label "GGGCCTGCAGGCCCGCTCGAGCCACCCGGGTGAGAGGCCTCT"
  ]
  node [
    id 176
    label "GGGACTGCAGTCCCGCTCGAGCCTTCTGGAAGATAAGCTTAT"
  ]
  node [
    id 177
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 178
    label "GGGCCTATAGGCCCGCTCGAGCCTTCGCGAAGGGAGGCCTCC"
  ]
  node [
    id 179
    label "AGTCTCGCGAGACTGCTCGAGCCTACATGTAGCGCGGCCGCG"
  ]
  node [
    id 180
    label "GCCATGGCCGTGGCGCC--GGCTGTGATCACAGCGGGCCCGT"
  ]
  node [
    id 181
    label "GGCCGGTACTGGCCGCTCGAGTTGGTGCGCCAGTGGGCCCAT"
  ]
  node [
    id 182
    label "GGTCGGTACCGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCGC"
  ]
  node [
    id 183
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 184
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCGCCAATGGGCCCGT"
  ]
  node [
    id 185
    label "GGGCTCATGGGCCCGCTCGAGCCACCCGGGTGGCTAGCTAGC"
  ]
  node [
    id 186
    label "GGTGGT--ACTGCCGCTCGAGCTGGTGCGCCAGCGGGCCTGT"
  ]
  node [
    id 187
    label "GGGTTTGCAAACCCGCTCGAGCCACCCGGGTGGATGGCCATT"
  ]
  node [
    id 188
    label "GGGCCTGCAGGCCCGCTCGAGCCACCCGGGTGGATGGCCATT"
  ]
  node [
    id 189
    label "GGGCTTGCAAGCCCGCTCGAGCCTACATGTAGCCTGGCCAGG"
  ]
  node [
    id 190
    label "GGGCCTGCAGGCCCGCTCGAGCCACCCGGGTGGGACGCGTCC"
  ]
  node [
    id 191
    label "GGGACTGCAGTCCCGCTCGAGCCGTGCGCACGACAAGCTTGT"
  ]
  node [
    id 192
    label "GGTCCCGCGGGACCACTCGAGTCTGAGCTCAGGAGAGCTCTC"
  ]
  node [
    id 193
    label "GGCCTATATGGGCTGCTCGAGCTCGTGCGCGAGCAGGCCTGC"
  ]
  node [
    id 194
    label "GATCTCTAGAGATCGCC--GGCCGGTGCGCCGAGCGGCCGCT"
  ]
  node [
    id 195
    label "GGCCGT--ACGGCCGTC--GGCTGGCGCGCCAGTGGGCCCGT"
  ]
  node [
    id 196
    label "GCCGGT--ACTGGCGCTCGAGTTGGTGTGCCAGTGGGCCCGT"
  ]
  node [
    id 197
    label "AGGCTTATAAGCCTGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 198
    label "GGGTCTGCAGACCCGCTCGAGCTTCGCGCGAGGGTGGCCACT"
  ]
  node [
    id 199
    label "GGTTCC--GGAACCGCC--GGCTCGTGCGCGGAGCGGCCGCT"
  ]
  node [
    id 200
    label "ACGGGAGCTTCCGTGCTCGAGCCACGCGCGTGGGCAGCTGCC"
  ]
  node [
    id 201
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCGCCAACGGGCTCGT"
  ]
  node [
    id 202
    label "GGGCCCGCGGGCCCGCATGTGCCCCGGCCGGGATGAGCTCAT"
  ]
  node [
    id 203
    label "GGGGCTATAGTCCCGCTCGAGCCACCTGGGTGATGGGCCCAT"
  ]
  node [
    id 204
    label "GGGCTTGCAGGCCCGCTCGAGCCACGCGCGTGGAAAGCTTTC"
  ]
  node [
    id 205
    label "GGCCTGTACGGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCAT"
  ]
  node [
    id 206
    label "GGGCCCGCGGGCCCGCTTGAGCCCCGGCCGGGCCGGGCCCGG"
  ]
  node [
    id 207
    label "GGCTTG--CAGGTCGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 208
    label "GGGCCCGCGGGCCCGCATGTGCCCCGGCCGGGGTGCGCGCAC"
  ]
  node [
    id 209
    label "GGCCTATATGGGCCGCTCGAGCTTGTGCGCGAGCAGGCCTGC"
  ]
  node [
    id 210
    label "GGCCGT--ACGGCCGCTCGAGCTGGCGCGCCAGCGGGCCCGT"
  ]
  node [
    id 211
    label "GCCCCGGCCGGGGCGCC--GGCTGAGATCTCAGCGGGCCCGC"
  ]
  node [
    id 212
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGGTAGCTACC"
  ]
  node [
    id 213
    label "GCCCTGATCGGGGCGCC--GGCTGAGGCCTCAGCGGGCCCGC"
  ]
  node [
    id 214
    label "GGGTGATATCACCCGCTCGAGCCTCGTACGAGCCTGGCCAGG"
  ]
  node [
    id 215
    label "GGTCTA--TGGGCCGTTCGAATTCATATGTGAATAGGCTTGT"
  ]
  node [
    id 216
    label "GGCCGGTATTGGCCGCTCGAGCTGGTGTGCCAGCGGGTCCGT"
  ]
  node [
    id 217
    label "GGCCGCTAGCGGCTGCTCGAGCCCGTCGGCGGGTTGGCCAAC"
  ]
  node [
    id 218
    label "GCCCCGGCCGGGGCGCC--GGCTGAGATCTCAGCGGGCCCGT"
  ]
  node [
    id 219
    label "GGGGCTATAGCCCCGCTCGAGCCTTCCGGAAGACAGGCCTGT"
  ]
  node [
    id 220
    label "GGGCCCTAGGGCCCGCTCGAGCTGCCCGGGCACGAGGCCTCG"
  ]
  node [
    id 221
    label "GGGCCCATGGGCCCGCTCGAGCCTTCGCGAAGCCAGGCCTGG"
  ]
  node [
    id 222
    label "GGGCCCGCGGGCCCGCATGTGCCCCGGCCGGGGTGCGCGCAT"
  ]
  node [
    id 223
    label "GGTCTCGCGGGACCCTC--GAGTTGGTGTCGAACGGGCTTGT"
  ]
  node [
    id 224
    label "GGCTTG--CAGGCCGCTCGAGCTTGCGCGCAGAGAGGCCTTT"
  ]
  node [
    id 225
    label "AGTCCTATGGGACTGCTCGAGCCTTCTGGAAGGGCAGCTGTC"
  ]
  node [
    id 226
    label "GGGCGTTAACGCCCGCTCGAGCCACCCGGGTGCCTGGCCAGG"
  ]
  node [
    id 227
    label "GGGCCCGCGGGCCCGCTCGAGCCACGCGCGTGGGCAGCTGCC"
  ]
  node [
    id 228
    label "GGTAGCGCGCTGCCGCC--GGCCTGGATCTAGGTGGGCCCAC"
  ]
  node [
    id 229
    label "GTTTGATATCAAACGCTCGAGCGTTGATCAACGCAGGCCTGT"
  ]
  node [
    id 230
    label "GTAGATGCGTCTACGCTCGAGCCGCAATTGCGGCAGGCCTGC"
  ]
  node [
    id 231
    label "GGCCAGTATTGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 232
    label "GGTTCTTAGGAACCGCC--GGCTCGTGCGCGGAGCGGCCGCT"
  ]
  node [
    id 233
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCACCAGCGGGCCCGT"
  ]
  node [
    id 234
    label "GCCGAAATTTCGGCGCTCGAGCTTAGATCTAACCTGGCCGGG"
  ]
  node [
    id 235
    label "GGGTCTGCAGACCCGCTCGAGCCACTCGGGTGGGTAGCTGCC"
  ]
  node [
    id 236
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCGT"
  ]
  node [
    id 237
    label "GGCCTGTATGGGCCGCTCGAGCTGGTGCGCCAATGGGCCCAT"
  ]
  node [
    id 238
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGATGGCCATC"
  ]
  node [
    id 239
    label "GGCTGGCGCTGGCCGCTCGAGCTGGTGCGCCAATGGGCCCAT"
  ]
  node [
    id 240
    label "GGCCTATATGGGCCGCTCGAGCTGGTGCGCCAGCAGGCCTGC"
  ]
  node [
    id 241
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCACCAGCGGGCCCGC"
  ]
  node [
    id 242
    label "GCCATGGCCGTGGCGCC--GGCTGTGATCACAGCGGGCCTGC"
  ]
  node [
    id 243
    label "GGGCCGATCGGCCCGCTCGAGCCACGGCCGTGAGAGGCCTCT"
  ]
  node [
    id 244
    label "GGGCGTATACGCCCGCTCGAGCCTTCGCGAAGCCTGGCCAGG"
  ]
  node [
    id 245
    label "CGGCATGCATGCCGGCTCGAGCGCGTCGACGTGAAGGCCTTC"
  ]
  node [
    id 246
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGAGTGGCCACT"
  ]
  node [
    id 247
    label "GGCTGGTACTGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCAT"
  ]
  node [
    id 248
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGATGGCCATT"
  ]
  node [
    id 249
    label "GGCCTATATGGGCCGCTCGAGTTCGTGCGCGAGTAGGCCTGC"
  ]
  node [
    id 250
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGGACGCGTCC"
  ]
  node [
    id 251
    label "GGGCCTATAGGCCCCTC--GAGCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 252
    label "GGGCTTGCAAGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 253
    label "GCTGGT--ACTGGCGCTCGAGTTGGTGTGCCAGTGGGCCCGT"
  ]
  node [
    id 254
    label "AGGCGCGCGTGCCTGCTCGAGCCACGATCGTGGGCAGCTGCC"
  ]
  node [
    id 255
    label "GGCCGT--ACGGCCGTC--GACTGGTGCACCAGCGGGCCCGT"
  ]
  node [
    id 256
    label "GGCCTATATAGGCCGCTCGAGCTCGTGCGCGAACAGGCCTGT"
  ]
  node [
    id 257
    label "CTGGCG--CGCCAGGTTTAAACAGTGATCGCTGCGGGCCCGC"
  ]
  node [
    id 258
    label "GGGCGCATGTGCCCGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 259
    label "GGGTCTGCAGACCCGCTCGAGCCCGTCGGCGGGATGGCCATC"
  ]
  node [
    id 260
    label "TGGCTG--TAGCCAGCTCGAGCCACGATCGTGGGAGGCCTTC"
  ]
  node [
    id 261
    label "GGGCCTATAGGCCCGCTCGAGCCTTCCGGAAGGCTGGCCAGC"
  ]
  node [
    id 262
    label "GGGCTTATAAGCCCGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 263
    label "GGGTTTGCAGACCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 264
    label "GGCCGT--ACGGCCGCTCGAGCCGGTGCGCCGGCGGGCCCGT"
  ]
  node [
    id 265
    label "GTTTCTGCAGGAGCGTGCGCGCTTCGGCTGAAGGTGGCCACC"
  ]
  node [
    id 266
    label "AGTCCTATGGGACTGCTCGAGCCCACATGTGGGGCAGCTGCC"
  ]
  node [
    id 267
    label "GGCCGGTATTGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 268
    label "GGGCCTATAGGCCCGCTCGAGCCGTCGCGACGGCTGGCCAGC"
  ]
  node [
    id 269
    label "GGGTCTGCAGACCCGCTCGAGCCACGCGCGTGAGTAGCTACT"
  ]
  node [
    id 270
    label "CGGAGCATGTTCCGGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 271
    label "GGCCGGTACTGGCCGCTCGGGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 272
    label "GGGCTAGCTGGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 273
    label "GGGTCTGCAGACCCGCTCGAGCCACGCGCGTGGGAGGCTTCC"
  ]
  node [
    id 274
    label "GGGCCAGCTGGCCCGCTCGAGCCTTCTGGAAGAGTAGCTACT"
  ]
  node [
    id 275
    label "GGCGGT--ACTGCCGCTCGAGCTGGTGCGCCAGTGGGCCCGT"
  ]
  node [
    id 276
    label "GGCCGGTACTGGCCGCTCGAGCTAGTGTGCTAGCGGGCCCGT"
  ]
  node [
    id 277
    label "GGGCTCATGAGCCCGCTCGAGCCACGCGCGTGGATGGCCATT"
  ]
  node [
    id 278
    label "GGTTTG--CAAGCCGCTCGAGCCACGTGCGTGGGAGGCCTCC"
  ]
  node [
    id 279
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGAGAGGCCTCT"
  ]
  node [
    id 280
    label "GGGCCTATAGGCCCGCTCGAGCCTTCGCGAAGAGAGGCCTCT"
  ]
  node [
    id 281
    label "GCCCTGATCAGGGCGCC--GGCTGAGATCTCAGCGGGCCCGC"
  ]
  node [
    id 282
    label "GGGCTCATGGGCCCGCTCGAGCCACGATCGTGGGTGGCCACC"
  ]
  node [
    id 283
    label "GGTCCGCGTGGACCGCTCGAGTTCGTGCGCGAGTGAGCTCAC"
  ]
  node [
    id 284
    label "GGTCTG--CAGACCGCTCGAGCTTGGTGCCGAGCGGGCCCGC"
  ]
  node [
    id 285
    label "GGGTCTGCAGACCCGCC--GGCCCGTCGGCGGGTTGGCCAAC"
  ]
  node [
    id 286
    label "GGCTGT--ACGGCCGCTCGAGCTGGTGTGCCAGTGGGCCCAT"
  ]
  node [
    id 287
    label "GGGACTGCAGTCCCGCTCGAGCCGTGCGCACGATAAGCTTAT"
  ]
  node [
    id 288
    label "AGTCCTATGGGACTGCTCGAGCCTACATGTAGGGCAGCTGCC"
  ]
  node [
    id 289
    label "GGGCGTATACGCCCGCTCGAGCCAATCGATTGGGTGGCCACC"
  ]
  node [
    id 290
    label "GGGCCTTAAGGCCCGCTCGAGCCACCCGGGTGTGTGGCCACA"
  ]
  node [
    id 291
    label "GGGCCA--TGGCCCGCGCGCGCCCCGCGCGGGGGTGGCCACC"
  ]
  node [
    id 292
    label "GGGATCATGGTCCCGCTCGAGCCAGGTACCTGGGAGGCCTCC"
  ]
  node [
    id 293
    label "AGTCTCATGGGACTGCTCGAGCCTACATGTAGGGCAGCTGCC"
  ]
  node [
    id 294
    label "GGCCGT--ATGGCCGCTCGAGCTGGTGCGCCAACGGGCCCGT"
  ]
  node [
    id 295
    label "AGTCTCGCGGGACTGCTCGAGCCTACATGTAGCGTGGCCACG"
  ]
  node [
    id 296
    label "GGGCCATATGGCCCGCTCGAGCCGGTCGACCGCCTGGCCAGG"
  ]
  node [
    id 297
    label "GGGTTTGCAAACCCGCTCGAGCCACGCGCGTGGGAAGCTTCT"
  ]
  node [
    id 298
    label "GGGCCCTAGGGCCCGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 299
    label "GGGCTTGTAAGCCCGCTCGAGCCACGCGCGTGGATGGCCATC"
  ]
  node [
    id 300
    label "GGGTCTATAGACCCGCTCGAGCCCGTGCGCGGATAAGCTTAT"
  ]
  node [
    id 301
    label "TGTGATATATCACAGCTTAAGCCTCGCGTGAGGAAAGCTTTC"
  ]
  node [
    id 302
    label "GGGCTA--TAGCCCGCTCGAGCCACGCGCGTGGATGGCCATT"
  ]
  node [
    id 303
    label "GGGCCTGCAGGCCCGCTCGAGCTCCGGCCGGGACAAGCTTGT"
  ]
  node [
    id 304
    label "GGACCTGCAGGTCCGCTCGAGCTCCGGCCGGGACAAGCTTGT"
  ]
  node [
    id 305
    label "TCATGG--CCGTGAGCC--GGCTGTGATCACAGCGGGCCCGT"
  ]
  node [
    id 306
    label "GGCCGGTATTGGCCGCTCGAGTTGGTGTGCCAGCGGGTCCGT"
  ]
  node [
    id 307
    label "GGCCGGTACTGGCCGCTCGAGTTGGTGCGCCAATGGGCCCAT"
  ]
  node [
    id 308
    label "GGGCTAGCTGGCCCGCTCGAGCCACGATCGTGGGAGGCCTCC"
  ]
  node [
    id 309
    label "GGGCTTATAAGCCCGCTCGAGCTACGCGCGTAGGTGGCCACC"
  ]
  node [
    id 310
    label "GGGCCTATAGGCCCGCTCGAGCCATCCGGATGGGTGGCCACC"
  ]
  node [
    id 311
    label "GGGCTTGCAAGCCCGCTCGAGCCTACATGTAGCGTGGCCACG"
  ]
  node [
    id 312
    label "GCTCTCATGGGAGCGCTCGAGCTGGGTGCCCAACAGGCCTGT"
  ]
  node [
    id 313
    label "GCTGTTATAACAGCGCTCGAGTCCCGTGCGGGAGTGGCCATT"
  ]
  node [
    id 314
    label "GGCCGGTACCGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCGT"
  ]
  node [
    id 315
    label "GGGTCTGCAGACCCGCTCGAGCCCGTGCGCGGGTTGGCCAAC"
  ]
  node [
    id 316
    label "GGGCTTGCAGGCCCGCTCGAGCCGCGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 317
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGGATGCATCC"
  ]
  node [
    id 318
    label "GGCCGTTAATGGCCCTC--GAGTCGTGCGCGAGCGGGCCCGT"
  ]
  node [
    id 319
    label "GGGCCTATGGGCCCGCTCGAGCCTTCGCGAAGGGAGGCCTCC"
  ]
  node [
    id 320
    label "GTCTCTGCAGGGACGCGCGCGCTTTGGCTGAAGGTGGCCACC"
  ]
  node [
    id 321
    label "GGCCTATATGGGCCGCTCGAGCTGGTGCGCCAACAGGCCTGT"
  ]
  node [
    id 322
    label "GGGCCAATTGGCCCGCTCGAGCCTCGGCCGGGACCGGCCGGT"
  ]
  node [
    id 323
    label "CGGAATATATTCCGGCTCGAGCCTCCGCGGAGGTTGGCCAAT"
  ]
  node [
    id 324
    label "GGGCGTATACGCCCGCTCGAGCCATCCGGATGCCAGGCCTGG"
  ]
  node [
    id 325
    label "GGGCGTGCATGCCCGCTCGAGCCTGTGCGCAGACTGGCCAGT"
  ]
  node [
    id 326
    label "GCGGCTATAGCCGCGCTCGAGCTAGAGCTCTAGCTGGCCAGC"
  ]
  node [
    id 327
    label "GCCCTGATTAGGGCGCC--GGCTGAGGTCTCAGCGGGCCCGC"
  ]
  node [
    id 328
    label "AGTCTCATGAGACTGCTCGAGCCTACATGTAGGACGGCCGTC"
  ]
  node [
    id 329
    label "GGCCGGTACCGGCCCTC--GAGTGGTGCGCCAACGGGCCCGT"
  ]
  node [
    id 330
    label "GGGCCAATTGGCCCGCTCGAGCCTCGGCCGGGCTCGGCCGAG"
  ]
  node [
    id 331
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCACCAGCAGGCCTGT"
  ]
  node [
    id 332
    label "AAAAGT--ACTTTTGCTCGAGCGTCGGCCGATATAGGCCTAT"
  ]
  node [
    id 333
    label "GGGCTCGCGAGCCCGCTCGAGCCGCGCGCGCGAGTGGCCACT"
  ]
  node [
    id 334
    label "AGGTCTGCAGACCTGCTCGAGCCACGCGCGTGGGCAGCTGCC"
  ]
  node [
    id 335
    label "GGCCGT--ATGGCCGCTCGAGTTGGTGCACTAATGGGCCTAT"
  ]
  node [
    id 336
    label "GGGGCTATAGCCCCGCTCGAGCCATCCGGATGACAGGCCTGT"
  ]
  node [
    id 337
    label "GGGCCCATGGGCCCGCTCGAGCCACGCGCGTGGGTAGCTACC"
  ]
  node [
    id 338
    label "GGCCGT--ATGGCCGCTCGAGCTGGTGTGCCAATGGGCCCGT"
  ]
  node [
    id 339
    label "GGCCGGTACTGGCCCTC--GAGTGGTGCGCCAATGGGCCCAT"
  ]
  node [
    id 340
    label "GGCCGT--ACGGCCGTC--GACTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 341
    label "GGCTGGCGCTGGCCGCTCGAGCTGGTGTGCCAGTGGGCCCAT"
  ]
  node [
    id 342
    label "GGGCCCGCGGGCCCCTC--GAGCACCCGGGTGGGTAGCTACC"
  ]
  node [
    id 343
    label "GGTCGCATGTGACCATG--CATTCGATGTCGAGCCGGCCGGC"
  ]
  node [
    id 344
    label "GGGTCAGTTGACCCGCTCGAGCCCGTCGGCGGGATGGCCATC"
  ]
  node [
    id 345
    label "AGGCCTGCAGGCCTGCTCGAGCTACCCGGGTAGGTGGCCACT"
  ]
  node [
    id 346
    label "GCCTGA--TTAGGTGCTCGAGCTCAGATCTGATAGGGCCCTG"
  ]
  node [
    id 347
    label "GGGCCGGTCGGCCCGCTCGAGCCACGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 348
    label "CGGGCTATAGCCCGGCTCGAGTCACCCGGGTGGATGGCCATT"
  ]
  node [
    id 349
    label "GGCCGGTATTGGCCGTTCGAGCTGGTGTGCCAGCGGGTCCGT"
  ]
  node [
    id 350
    label "GGGCGTATACGCCCGCTCGAGCCGATCGATCGGGTGGCCACC"
  ]
  node [
    id 351
    label "GGGCCTGCAGGCCCGCTCGAGCCTGTGCGCAGAGTGGCCACT"
  ]
  node [
    id 352
    label "GGGCTTATAAGCCCGCTCGAGCCACCCGGGTGAGAGGCCTCT"
  ]
  node [
    id 353
    label "GCTGGT--ACTGGCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 354
    label "GCTGTA--TGCGGCGCTCGAGCTGGGTGCCCAGCAGGCCTGC"
  ]
  node [
    id 355
    label "GGGCCTTAAGGCCCGCTCGAGCTGCCTGGGCATCAGGCCTGA"
  ]
  node [
    id 356
    label "GGGCCTGCAGGCCCGCTCGAGCCACCCGGGTGGATAGCTATC"
  ]
  node [
    id 357
    label "GGGCCTATAGGCCCGCTCGAGCCATCGCGATGGCAAGCTTGC"
  ]
  node [
    id 358
    label "GGTCCTGCGGGACCGCTCGAGCTTGGTGCCGAGCGGGCCCGC"
  ]
  node [
    id 359
    label "GGCCGT--ATGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 360
    label "GGCTGGTATCGGCCGTTCGAGCTGGTGCGCCAGTGGGCCCAT"
  ]
  node [
    id 361
    label "GGGTCTATAGACCCGCTCGAGCCACGCGCGTGGGTAGCTACC"
  ]
  node [
    id 362
    label "GGGAATATGTTCCCATTTGAGTATTACGTAATGCTGGCCAGT"
  ]
  node [
    id 363
    label "GGGTCTGCAGACCCGCTCGAGCCCGTGCGCGGATAAGCTTAT"
  ]
  node [
    id 364
    label "GGGCCTATAGGCCCGCTCGAGCCTTCCGGAAGACAGGCCTGT"
  ]
  node [
    id 365
    label "TAGTCTATAGACTATCTCGAGAATCGATCGATGTAAGCTTAC"
  ]
  node [
    id 366
    label "GGCCTATATGGGCCGCTCGAGCTCGTGCGTGAGCAGGCCTGC"
  ]
  node [
    id 367
    label "GGGCCCGCGGGCCCGCTCGAGCCCCGGCCGGGGCGGGCCCGC"
  ]
  node [
    id 368
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGGCTGCAGTC"
  ]
  node [
    id 369
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGCCAGTGGGCCTAT"
  ]
  node [
    id 370
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGATAGCTATC"
  ]
  node [
    id 371
    label "GGGGCTATAGCCCCGCTCGAGCCAGAGCTCTGGCTGGCCAGC"
  ]
  node [
    id 372
    label "GGGGCTATAGCCCCGCTCGAGCCTTCATGAAGCCAGGCCTGG"
  ]
  node [
    id 373
    label "AGTCTCGCGAGACTGCTTGAGCCTACATGTAGCGTGGCCACG"
  ]
  node [
    id 374
    label "GGCCTATATGGGCCGCTCGAGCTCGTGCGCGAGCAGGCTTGC"
  ]
  node [
    id 375
    label "GGGACTATAGTCCCGCTCGAGCTACCTGGGTAATGGGCCCGT"
  ]
  node [
    id 376
    label "GGCCGT--GCGGCCGCTCGAGTTGGTGCGCCAACGGGCCTGT"
  ]
  node [
    id 377
    label "GGGCCCGCGGGCCCGCTCGAGCCACGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 378
    label "GGGCCTATAGGCCCGCTCGAGCCACGATCGTGAGTGGCCACT"
  ]
  node [
    id 379
    label "CGGGGTATACCCCGGCCCGGGCCTCGTGCGAGCTCGGCCGAG"
  ]
  node [
    id 380
    label "AGTCCTATGGGACTGCTCGAGCCTTCTGGAAGGGCAGTTGTC"
  ]
  node [
    id 381
    label "GGACCCATGGGTCCGCATGTGCTCCGGCCGGATAGAGCTCTG"
  ]
  node [
    id 382
    label "GGGCTAGCTGGCCCGCTCGAGCCGCGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 383
    label "GGTCCCGCGGGACCGCTCGAGCTTGGTGCCGAGCGGGCCCGC"
  ]
  node [
    id 384
    label "AGTAGAGCTCTGCTGCGCGCGTCTGGGCCCAGGATGGCCATC"
  ]
  node [
    id 385
    label "AGGTCTGCAGACCTGCTCGAGCCACCCGGGTGGGCAGCTGCC"
  ]
  node [
    id 386
    label "GGGCCGGCCGGCCCGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 387
    label "GGCTGGTACTGGCCGCTCGAGCTGGTGCGCTAGTGGGCCCGT"
  ]
  node [
    id 388
    label "GGTCCCGCGGGACCGCTCGAGCCTGGTGCCGGGCGAGCTCGC"
  ]
  node [
    id 389
    label "GGGCGTATATGCCCGCTCGAGCCACGCGCGTGGATGGCCATT"
  ]
  node [
    id 390
    label "GCCCCGGCCGGGGCGTC--GGCTGAGATCTCAGCGGGCCCGT"
  ]
  node [
    id 391
    label "GGCCAGTACTGGCCGCTCGAGCTGGTGCGCCAGCGGGCCTGT"
  ]
  node [
    id 392
    label "AGGTCTGCAGGCCTGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 393
    label "GGGCCCGCGGGCCTGCTCGAGCCACGCGCGTGATAAGCTTAT"
  ]
  node [
    id 394
    label "GGGCCCATGGGCCCGCTCGAGTCACCCGGGTGGGTAGCTACC"
  ]
  node [
    id 395
    label "GGGCTG--CGGCCCGCTCGAGCCACCCGGGTGGAAGGCCTTC"
  ]
  node [
    id 396
    label "AGCCGCATGCGGCTGCTCGAGCCCGTCGGCGGGATGGCCATC"
  ]
  node [
    id 397
    label "GGCCGGTACTGGCCGCTCGAGCTCGTGCGCGAGCGGGCCCGT"
  ]
  node [
    id 398
    label "GGGGCTGCAGCCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 399
    label "GACCAC--GTGGTCGCTCGAGCGTCAATTGGCGCCGGCCGGC"
  ]
  node [
    id 400
    label "GGCCGGTACCGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 401
    label "GGGTTTGCAGACCCGCTCGAGCCTGTGCGCAGGTAGGCCTAC"
  ]
  node [
    id 402
    label "GGTCCCTAGGGACCGCC--GGCTCGTGCGCGGAGCAGCTGCT"
  ]
  node [
    id 403
    label "GCGTTCGCGAACGCGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 404
    label "GGCTAT--ATGGCCGTTCGAGCTTATGTATAAATAAGCTTAT"
  ]
  node [
    id 405
    label "GGGCTTATAAGCCCGCTCGAGCCACCCGGGTGGGAGGCCTCC"
  ]
  node [
    id 406
    label "GGGCTTATAAGCCCGCTCGAGCCACGCGCGTGGATGGCCATC"
  ]
  node [
    id 407
    label "GGGACAGCTGTCCCGCTCGAGCCCGCTGGCGGAATAGCTATT"
  ]
  node [
    id 408
    label "GGGCCTTAAGGCCCGCTCGAGCTACCCGGGTAGGTGGCCACC"
  ]
  node [
    id 409
    label "AGGCTTGCAAGCCTGTTTAAACTACGCGCGTAAACAGCTGTT"
  ]
  node [
    id 410
    label "GCGAGTGCATTCGCGCTCGAGCCACGCGCGTGCCCAGCTGGG"
  ]
  node [
    id 411
    label "GTGATA--TATCACGCTCGAGCCACCCGGGTGGGCAGCTGCC"
  ]
  node [
    id 412
    label "GGGCTTATAAGCCCGCTCGAGCCACGCGCGTGGATGGCCATT"
  ]
  node [
    id 413
    label "GGGCCCGCGGGCCCGCTCGAGCTCCGGCCGGGACAAGCTTGT"
  ]
  node [
    id 414
    label "GGGCCCGCGGGCCCGCTTGAGCTCCGGCCGGAGTGGGCCCAC"
  ]
  node [
    id 415
    label "GGCTGGTACTGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 416
    label "GCCTAT--ATGGGCGCTCGAGCTCGTGCGCGAGCAGGCCTGC"
  ]
  node [
    id 417
    label "GCCGGT--ACTGGCGCTCGAGCTGGTGCGCCAATGGGCCCAT"
  ]
  node [
    id 418
    label "GGGTCAGTTGACCCGCTCGAGCCCGTCGGCGGGCTGGCCAGC"
  ]
  node [
    id 419
    label "GGCCTATATGGGCCGCTCGAGCTCGTGCGTGAGTAGGCCTGC"
  ]
  node [
    id 420
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGTGTGGGTGGCCATT"
  ]
  node [
    id 421
    label "GGGCCATATGGCCCGCTCGAGCCACCCGGGTGCCTGGCCAGG"
  ]
  node [
    id 422
    label "GGAGGTATGCTTCCGTTCGAACCTCCCGGGAGAATGGCCATT"
  ]
  node [
    id 423
    label "GTGGCTGCAGTCACTTT--AAACCATGCGTGGCTGGGCCCAG"
  ]
  node [
    id 424
    label "GGGTGAGTTCACCCGCTCGAGCGCTGGCCAGTGGCGGCCGTC"
  ]
  node [
    id 425
    label "GGACTATATGGTCCGCTCGAGCCTGTGCGCAGCCAGGCCTGG"
  ]
  node [
    id 426
    label "GGGCCTATAGGCCCGCTCGAGCCCCCGCGGGGAGTCGCGACT"
  ]
  node [
    id 427
    label "GGGGGGATCCCTCCGCTCGAGCCTTTCGAAAGGCAGGCCTGC"
  ]
  node [
    id 428
    label "GGGCTA--TGGCCCCTT--GAGCGCGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 429
    label "GGGCCTGCAGGCCCGCTCGAGCCGCGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 430
    label "GGGCTA--TAGCCCGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 431
    label "GGGTTTGCAGACCCGCTCGAGCCCGTCGGCGGGTTGGCCAAC"
  ]
  node [
    id 432
    label "GGGAGCGCGTTCCCGCTCGAGCCACGGTCGTGGATGGCCATT"
  ]
  node [
    id 433
    label "GGGCCTATAGGCCCGCTCGAGCCACCCGGGTGTGTGGCCACA"
  ]
  node [
    id 434
    label "GGGTTTGCAGGCCCGCTCGAGCCACGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 435
    label "GGCTGGCGCTGGCCGCTCGAGCTGGTGCACCAATGGGCCTAT"
  ]
  node [
    id 436
    label "GGTCCCTAGGGACCGCC--GGCTCGTGCGCGGAGCGGCCGCT"
  ]
  node [
    id 437
    label "GGGCCCGCGGGCCCGCTCGAGCCGCGCGCGCGCGGGGCCCCG"
  ]
  node [
    id 438
    label "AGGCTTGCAGGCCTGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 439
    label "GGGCCCATGGGCCCGCTCGAGCCACGATCGTGAGTGGCCACT"
  ]
  node [
    id 440
    label "GGGCCAGCTGGCCCGCTCGAGCTACCCGGGTAGGTGGCCACC"
  ]
  node [
    id 441
    label "GGGCTCGCGGGCCCGCTCGAGCCACGCGCGTGGTAAGCTTAC"
  ]
  node [
    id 442
    label "GGGCCTATAGGCCCGCTCGAGCCATCGCGATGGGTGGCCACC"
  ]
  node [
    id 443
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGACTGGCCAGT"
  ]
  node [
    id 444
    label "GGGTCTGCAGACCCGCTCGAGCCACTCGAGTGGGTAGCTGCC"
  ]
  node [
    id 445
    label "GGCTGT--ACGGCCGCTCGAGCTGGTGCGCCAGTGGGCCTGT"
  ]
  node [
    id 446
    label "GGGCTTGCAGGCCCGCTCGAGCCTACATGTAGCCAGGCCTGG"
  ]
  node [
    id 447
    label "GGGTCTGTAGACCCGCTCGAGCCTGTGCGCAGGTTGGCCAAC"
  ]
  node [
    id 448
    label "GGGCTTGCAGGCCCGCTCGAGCCTACATGTAGCGTGGCCACG"
  ]
  node [
    id 449
    label "TGGGTG--CACTCAGCTCGAGCCTTGCGCGAGCTGGGCTCAG"
  ]
  node [
    id 450
    label "GGGCCGATCGGCCCGCTCGAGCCACGGCCGTGGGAAGCTTCC"
  ]
  node [
    id 451
    label "GGGCCTATGGGCCCGCTCGAGCCACGATCGTGAGTGGCCACT"
  ]
  node [
    id 452
    label "GGGCGCGCGTGCCCGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 453
    label "AGTCCA--TGGACTGCTCGAGCCTACATGTAGGGCAGCTGCC"
  ]
  node [
    id 454
    label "GAGTTTATAAACTCATTTAAATTTACTGGTAAATTGGCCAGT"
  ]
  node [
    id 455
    label "GTTTCG--CGAAACGTG--CATTTTGCGCAAACCTGGCCAGG"
  ]
  node [
    id 456
    label "GGGCCTATAGGCCCGCTCGAGCCTACATGTAGGATGGCCATC"
  ]
  node [
    id 457
    label "GGGTCTATAGACCCGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 458
    label "GGGCCCGTGGGCCCGCTCGAGCCACCCGGGTGGATGGCCATC"
  ]
  node [
    id 459
    label "GGGCTATATAGCCCGCTCGAGCCACCCGGGTGCTTGGCCAAG"
  ]
  node [
    id 460
    label "GGGCTCATGAGCCCGCTCGAGCTGCGCGCGCAGGTGGCCACT"
  ]
  node [
    id 461
    label "GGTCGCTAGTGACCGCTCGAGCTGGTGCGCCAGCGAGCTCGT"
  ]
  node [
    id 462
    label "GGCTCTATGGGGCCGCTCGAGCCTGGTACCAGGTGAGCTCAC"
  ]
  node [
    id 463
    label "GGCGGT--ACCGCCGCTCGAGCTGGTGCACTGGCGGGCCCGC"
  ]
  node [
    id 464
    label "GGTCCTGCAGGACCGCTCGAGCTTGGTGCCGAGCGGGCCCGC"
  ]
  node [
    id 465
    label "GGGCTTATAGGCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 466
    label "GCTCAGATCTGAGCGCC--GGCTTGGATTCAAGTAGGCCTGC"
  ]
  node [
    id 467
    label "GGGACTATAGTCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 468
    label "GCGAGGGCTCTCGCGCTCGAGCCACGGCCGTGCCGAGCTCGG"
  ]
  node [
    id 469
    label "GCATCCCGGGATGCGCTCGAGCCACGATCGTGGATGGCCATC"
  ]
  node [
    id 470
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGTGCCAATGGGCCCAT"
  ]
  node [
    id 471
    label "GGCCGT--ACGGTCGCTCGAGCTGGTGTGCCAGTGGGCCCGT"
  ]
  node [
    id 472
    label "GGTCTGTACGGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 473
    label "AGGCTTGCAGGCCTGCTTGAGCCACCCGGGTGGGTGGCTACT"
  ]
  node [
    id 474
    label "GGGCCTATAGGCCCGCTCGAGCCTGTCGACAGACTGGCCAGT"
  ]
  node [
    id 475
    label "AGATCCGCGGGTCTGCTCGAGCCTACATGTAGACCAGCTGGT"
  ]
  node [
    id 476
    label "GGGCCTGCAGGCCCGCTCGAGCCACGATCGTGGATGGCCATC"
  ]
  node [
    id 477
    label "GGGTCTGCAGGCCCGCTCGAGCCCGCTGGCGGAATGGCCATT"
  ]
  node [
    id 478
    label "GGGCCTGCAGGCCCGCTCGAGCTGCGCGCGCAACTGGCCAGT"
  ]
  node [
    id 479
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCACCAATGGGCCTGT"
  ]
  node [
    id 480
    label "GCTCCATATGGAGCGCGCGCGCTGGTATGCCGGGGAGCTCCC"
  ]
  node [
    id 481
    label "GGTTCCGCGGGACCGCGCGCGCTGGTGCGCCAGAGGGCCCTC"
  ]
  node [
    id 482
    label "GGGGGCGCGCCCCTGCTCGAGCGCGGCGCCGCGTGGGCCCAC"
  ]
  node [
    id 483
    label "GGGCCTGCAGGCCCGCTCGAGCCACCCGGGTGAGAAGCTTCT"
  ]
  node [
    id 484
    label "GGGCCTATAGGCCCGCTCGAGTCACCCGGGTGACAAGCTTGT"
  ]
  node [
    id 485
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGGGTAGCTGCC"
  ]
  node [
    id 486
    label "GGGCTCATGGGCCCGCTCGAGCCGCGCGCGCGGATGGCCATC"
  ]
  node [
    id 487
    label "GGGCCTATAGGCCCGCTCGAGCCTTCGCGAAGCCTGGCCAGG"
  ]
  node [
    id 488
    label "GGGCCAGCTGGCCCGCTCGAGCCACGCGCGTGGGCAGCTGCC"
  ]
  node [
    id 489
    label "GGGCGTATACGCCCGCTCGAGTCACCCGGGTGCCTGGCCAGG"
  ]
  node [
    id 490
    label "GGTTCCATGGAACCACTCGAGTTGGTGCGCCAGAGGGCCCTC"
  ]
  node [
    id 491
    label "GGGTTTGCAAGCCCGCTCGAGCCACGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 492
    label "AGGCTTGCAGGCCTGCTCGAGCCACCCGGGTGAGTGGCCACT"
  ]
  node [
    id 493
    label "GGGCGTGCATGCCCGCTCGAGCCTGTGCGCAGGATGGCCATT"
  ]
  node [
    id 494
    label "AGCAGAGCTCTGCTGCC--GGTTTGGGCCCAGGATGGCCATC"
  ]
  node [
    id 495
    label "GGCCGGTATCGGCCGTTCGAGCTGGTGTGCCAGTGGGCCCAT"
  ]
  node [
    id 496
    label "GGGTCTGCAGGCCCGCTCGAGCCACGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 497
    label "GGGCGCATGCGCCCGCTCGAGCCACCCGGGTGCCATGCATGG"
  ]
  node [
    id 498
    label "GGGCTCATGAGCCCGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 499
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGGTGGCCATT"
  ]
  node [
    id 500
    label "AGTCTCTAGGGACTGCTCGAGCCTACATGTAGCGCGGCCGCG"
  ]
  node [
    id 501
    label "GGGTCTGCAGACCCGCTCGAGCCACGCGCGTGACAAGCTTGT"
  ]
  node [
    id 502
    label "GGCCGGTACTGGCTGTC--GACTGGTGTGCCAATGGGCCCGT"
  ]
  node [
    id 503
    label "GGGGCTATAGCCCCGCTCGAGCCTTCGCGAAGCGAGGCCTCG"
  ]
  node [
    id 504
    label "GGGTCTGCAGACCCGCTCGAGCTACGCGCGTAGGTGGCCACT"
  ]
  node [
    id 505
    label "GGGCCTCGAGGCCCGCTCGAGCTACCCGGGTAACTGGCCAGT"
  ]
  node [
    id 506
    label "GGGCCTATAGGCCCGCTCGAGCCAGTCGACTGGCTGGCCAGC"
  ]
  node [
    id 507
    label "GGGCCCGCGGGCCCGCTCGAGCCCCGGCCGGGGGGGGCCCCC"
  ]
  node [
    id 508
    label "GGCCTATATAGGCCGCTCGAGCTCGTGCGCGAGCAGGCCTGC"
  ]
  node [
    id 509
    label "GCGAGCATGTTCGCGCTCGAGCCACGATCGTGGATGGCCATT"
  ]
  node [
    id 510
    label "GGTTCCTAGGAACCGCC--GGCTCGTGCGCGGAGCAGCTGCT"
  ]
  node [
    id 511
    label "GGGCCATATGGCCCGCTCGAGCCTGTGCGCAGCCAGGCCTGG"
  ]
  node [
    id 512
    label "GGCAGT--ACTGCCGCTCGAGCTGGTGCGCCAGTGGGCCCAT"
  ]
  node [
    id 513
    label "GGCCAGTACTGGCCGCTCGAGCTGGTGCGTCAGCGGGCCCGT"
  ]
  node [
    id 514
    label "GATCGGTACCGGTCGCTCGAGCTGGTGCGCCAGCGGGCCCGC"
  ]
  node [
    id 515
    label "GGGCTTGCAAGCCCGCTCGAGCCACGCGCGTGGATGGCCATC"
  ]
  node [
    id 516
    label "GGGCCCGCGGGCCCGCTTGAGCCACGGCCGTGCTGCGCGCAG"
  ]
  node [
    id 517
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCACCAGCGGGCCCGT"
  ]
  node [
    id 518
    label "GGTCTCATGGGACCGCTCGAGCTACGGCCGTAGGCGGCCGCC"
  ]
  node [
    id 519
    label "GGTTCCTAGGAACCGCC--GGCCCGTGCGCGGAGCGGCCGCT"
  ]
  node [
    id 520
    label "GGGCCTGTAGGCCCGCTCGAGCCACGATCGTGGGTGGCCACC"
  ]
  node [
    id 521
    label "GTGGTAATTATCACGCTCGAGCCCAGCGTTGGCGAGGCCTTG"
  ]
  node [
    id 522
    label "GGCCAGTACTGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCAT"
  ]
  node [
    id 523
    label "CGGGCTATAGCCCGGCTCGAGCCACCCGGGTGGATGGCCATT"
  ]
  node [
    id 524
    label "GGGGTCATGACCCCGCTCGAGCCACGCGCGTGGGAGGCCTCT"
  ]
  node [
    id 525
    label "GGGCGTATACGCCCGCTCGAGCCTTCGCGAAGCCAAGCTTGG"
  ]
  node [
    id 526
    label "GGGCCTGCAGGCCCGCTCGAGCCGCGCGCGCGACAGGCCTGT"
  ]
  node [
    id 527
    label "GGCCGT--ACGGCCGTTCGAGCTGGCGCGCCAGTGGGCCCAT"
  ]
  node [
    id 528
    label "AGGCTTGCAAGCCTGCTCGAGCCACCCGGGTGAGTGGCCACT"
  ]
  node [
    id 529
    label "GGGCGTATACGCCCGCTCGAGCCGATCGATCGTCTGGCCAGA"
  ]
  node [
    id 530
    label "GGGCCTCGAGGCCCGCTCGAGCTGCCCGGGCACCAGGCCTGG"
  ]
  node [
    id 531
    label "GGGTCTATAGACCCGCTCGAGCCCGTCGGCGGGATGGCCATC"
  ]
  node [
    id 532
    label "AGGCTTGCAAGCCTGTTTAAACCGCGCGCGTGAACAGCTGTT"
  ]
  node [
    id 533
    label "GCGCTGGTCGGCGCGCTCGAGCTACGATCGTAGGAGGCCTCC"
  ]
  node [
    id 534
    label "GGGCTCATGAGCCCGCTCGAGCTACGCGCGTAGATGGCCATT"
  ]
  node [
    id 535
    label "GGGCTCGCGGGCCCGCTTGAGCCACGGCCGTGACGCGCGCGT"
  ]
  node [
    id 536
    label "GGGCCTGCAGGCCCGCTCGAGCCTCGCGCGAGGATGGCCATT"
  ]
  node [
    id 537
    label "GGCTGT--ACGGCCGCTCGAGCTGGTGCACCAGTGGGCCCAT"
  ]
  node [
    id 538
    label "GCCTGT--ACGGGTGCTCGAGTTGGTGCGCTAGCGGGCCCGT"
  ]
  node [
    id 539
    label "GGCTAT--ATGGCCGTTCGAGCTTGTGCGTGAGCAGGCCTGC"
  ]
  node [
    id 540
    label "GGGCCTATAGGCCCGCTCGAGCCGTCCGGACGACTGGCCAGT"
  ]
  node [
    id 541
    label "GGGCTTGCAAGCCTGTTTGAACTGCGCGCGCAAGCAGCTGCT"
  ]
  node [
    id 542
    label "GGGCCGGTCGGCCCGCTCGAGCCACCCGGGTGGAAAGCTTTC"
  ]
  node [
    id 543
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGCCAGCGGGCCTGT"
  ]
  node [
    id 544
    label "GCGCTG--TGGTGCGCTTAAGCCCTGTACAGGCTGGGCCCAG"
  ]
  node [
    id 545
    label "GGGTTTGCAAACCTGCTCGAGCCACGCGCGTGGGAAGCTTCT"
  ]
  node [
    id 546
    label "GGTCCTATGGGACCGCTCGAGCTACGGCCGTAGGCGGCCGCC"
  ]
  node [
    id 547
    label "GGGCGATATCGCCCGCTCGAGCCTTCTGGAAGCCTGGCCAGG"
  ]
  node [
    id 548
    label "GGGGCTGCAGCCCTGCTCGAGCCCGTGCGCGGGTTGGCCAAC"
  ]
  node [
    id 549
    label "GGGCCTATAGGCCCGCTCGAGCCGTCATGACGGCAGGCCTGC"
  ]
  node [
    id 550
    label "GCGGCTATAGCCGCGCTCGAGCCTTCCGGAAGCCAGGCCTGG"
  ]
  node [
    id 551
    label "GGCTCT--AGAGCCGCTTAAGCCCTGTACAGGTTGGGCCCAG"
  ]
  node [
    id 552
    label "GGGTCTGCAGACCCGCTCGAGCCCGTCGGTGGGTTGGCCAAC"
  ]
  node [
    id 553
    label "GGGTCTATAGACCCGCTCGAGTCGTCCGGACGGCTGGCCAGC"
  ]
  node [
    id 554
    label "GGGCCTATAGGCCCGCTCGAGCCTTCGCGAAGCCAGGCCTGG"
  ]
  node [
    id 555
    label "AGTCCCATGGGACTGCTCGAGCCTACATGTAGGGCAGCTGCC"
  ]
  node [
    id 556
    label "GGCCAT--ATGGCCGTC--GACTCGTGCGCGAGCAGGCTTGC"
  ]
  node [
    id 557
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGGTAGCTACC"
  ]
  node [
    id 558
    label "GCCCTGATCAGGGCGCC--GGCTGAGGCCTCAGCGGGCCCGC"
  ]
  node [
    id 559
    label "GGGACTATAGTCCCGCTCGAGTCACGCGCGTGGATGGCCATT"
  ]
  node [
    id 560
    label "GGGCTTGCAGGCCCGCTCGAGCTTACATGTAACGTGGCCACG"
  ]
  node [
    id 561
    label "GGTCCTGCGGGATCGCTCGAGCTGGTGCGCCAGCGAGCTCGT"
  ]
  node [
    id 562
    label "GGGTCTATAGACCCGCTCGAGCCACCCGGGTGGGCCGCGGCC"
  ]
  node [
    id 563
    label "TCCCTGGTCGGGGAGTT--GATCTGCATGCAGCCAGGCCTGG"
  ]
  node [
    id 564
    label "GGGCTATATGGCCCGCTCGAGCCACCCGGGTGTCTGGCCAGA"
  ]
  node [
    id 565
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGAATAGCTATT"
  ]
  node [
    id 566
    label "GGGTCTATAGACCCGCTCGAGCCACCCGGGTGGGTGGCCACC"
  ]
  node [
    id 567
    label "GGGCCCGCGGGCCCGCTCGAGCCCCGGCCGGGCGGGGCCCCG"
  ]
  node [
    id 568
    label "GGTCGGTACCGACCGCTCGAGCTGGTGCACCAGCGGGCCCGC"
  ]
  node [
    id 569
    label "GGGCTTATAAGCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 570
    label "GGGCTAGCTAGCCTGCTCGAGCCACGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 571
    label "GCCGGT--ACTGGCGCC--GGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 572
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGAGTAGCTACT"
  ]
  node [
    id 573
    label "GGTCGT--ACGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCGC"
  ]
  node [
    id 574
    label "GGGTCTGCAGGCCCGCTCGAGCCACGCGCGTGGGAGGCTTCC"
  ]
  node [
    id 575
    label "CGGAGTATATTCCGGCTCGAGCCACGCGCGTGGATGGCCATT"
  ]
  node [
    id 576
    label "GGGGTTATAACCCCGCTCGAGCCTTCATGAAGCCAGGCCTGG"
  ]
  node [
    id 577
    label "AGCAGAGCTCTGCTGGC--GCTCTGGGCCCAGGATGGCCATC"
  ]
  node [
    id 578
    label "GGTCTCTAGAGACCGCC--GGCCCGTGCGCGGAGCGGCCGCT"
  ]
  node [
    id 579
    label "GGGTTTGCAAGCCCGCTCGAGCCACGTACGTGGGAAGCTTCT"
  ]
  node [
    id 580
    label "GGGCCCGCGGGCCCGCTTGAGCCCCGGCCGGGATGCGCGCAT"
  ]
  node [
    id 581
    label "GGGCCGGTCGGCCCGCTCGAGCCACGCGCGTGGCAAGCTTGC"
  ]
  node [
    id 582
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCGCCGGCGGGCCCGT"
  ]
  node [
    id 583
    label "GGGTCTGCAGACCCGCTCGAGCCTCGCGCGGGGGTGGCCACT"
  ]
  node [
    id 584
    label "GGGCCCGCGGGCCCGCTCGAGCCACGCGCGTGGGTAGCTACC"
  ]
  node [
    id 585
    label "GCGGGTGCATCCGCGCTCGAGCCACGCGCGTGCCCAGCTGGG"
  ]
  node [
    id 586
    label "GGCCAGTACTGGCCGCTCGAGCTGGTGCGCCAATGGGCCCAT"
  ]
  node [
    id 587
    label "GGAAATATATTTCCGCTCGAGCTTCGGCCGAAGGTGGCCATC"
  ]
  node [
    id 588
    label "GGGCCCGCGGGCCCGCTTGAGCCACGGCCGTGCTGAGCTCAG"
  ]
  node [
    id 589
    label "AGTCTCGCGGGACTGCTCGAGTCTACATGTAGCCCAGCTGGG"
  ]
  node [
    id 590
    label "GTCTCTGCAGGGACGCGCGCGCTTCGGCTGAAGGTGGCCACC"
  ]
  node [
    id 591
    label "AGTCCCGCGGGACTGCTCGAGTCTACATGTAGCCCAGCTGGG"
  ]
  node [
    id 592
    label "GGCGGT--ACTGCCGCT--AGTTGGTGCGCCAACGGGCCCGT"
  ]
  node [
    id 593
    label "GGGCCAATTGGCCCGCTCGAGCCTCGGCCGGGCGCGGCCGCG"
  ]
  node [
    id 594
    label "GGCCGT--ACGGCCGCC--GGCTGGTGCACCAACGGGCCTGT"
  ]
  node [
    id 595
    label "GGGCGCGCGTGCCCGCC--GGCCACGGCCGTGATGGGCCCAT"
  ]
  node [
    id 596
    label "GGGCTCATGAGCCCGCTCGAGCCACGCGCGTGAGTGGCCACT"
  ]
  node [
    id 597
    label "GGAGGCATGTCTCCGTTCGAACCTCCCGGGAGGGTGGCCACC"
  ]
  node [
    id 598
    label "GGGAGTATACTCCCGCTCGAGCCACCCGGGTGGATGGCCATT"
  ]
  node [
    id 599
    label "GGGCGTATATGCCCGCTCGAGCCTGTGCGCAGGCTGGCCAGC"
  ]
  node [
    id 600
    label "GGTCCCTAGGGACCGCC--GGCTGGTGCGCCAAGCAGCTGTT"
  ]
  node [
    id 601
    label "GGTCCG--CGGGCCGCTTAAGCCCTGTACAGGCTGGGCCCAG"
  ]
  node [
    id 602
    label "GGGCTTATAAGCCCGCTCGAGCCACGCGCGTGAATGGCCATT"
  ]
  node [
    id 603
    label "ATCGCCGCGGCGATGCTCGAGCCCGCCGGCGGGCTGGCCAGC"
  ]
  node [
    id 604
    label "GTCCTGGTCAGGACGCTCGAGCTCGTGCGCGACGGGGCCCTG"
  ]
  node [
    id 605
    label "GGAGGCATGCTTCCGTTCGAACCTCCCGGGAGGATGGCCATC"
  ]
  node [
    id 606
    label "GGGCCTGTGGGCCCGCTCGAGCCACGCGCGTGGGCAGCTGCC"
  ]
  node [
    id 607
    label "GGGCCTATAGGCCCGCTCGAGCTACGATCGTAGGTGGCCACC"
  ]
  node [
    id 608
    label "GGCCGT--ACGGCCGCT--AGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 609
    label "GGCCGGTATTGGCCGTTCGAGCTGGTGCGCCAGTGGGCCCAT"
  ]
  node [
    id 610
    label "GGGTTCGCGAGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 611
    label "TGTCCTGCAGGGTGGCTCGAGCCTCGCGTGAGCTGGGCCCAG"
  ]
  node [
    id 612
    label "GGGCGCATGCGCCCGCTCGAGCCACCCGGGTGCGAAGCTTCG"
  ]
  node [
    id 613
    label "AGTCCCGCGGGACTGCTCGAGCCTACATGTAGAGCGGCCGCT"
  ]
  node [
    id 614
    label "GGGTCTGCAGACCCGCTCGAGCTACGCGCGTAGGTAGCTACT"
  ]
  node [
    id 615
    label "AGTCTCGCGGGACTGCTCGAGCCTACATGTAGTGCGGCCGCA"
  ]
  node [
    id 616
    label "GGGCCTGCAGGCCCGCTCGAGCCTTCTGGAAGCCTGGCCAGG"
  ]
  node [
    id 617
    label "GGCGCTGCAGTGCCGCTTAAGCCCTGTACAGGCTGAGCTCAG"
  ]
  node [
    id 618
    label "GGGCCGGTCGGCCCGCTCGAGCCTCGGCCGGGCGCGGCCGCG"
  ]
  node [
    id 619
    label "AGGTCTGCAGACCTGCTCGAGCCCGTGCGCGGGTTGGCCAAT"
  ]
  node [
    id 620
    label "GGGCCCGCGGGCCCGCTCGAGCCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 621
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGGGCAGCTGCC"
  ]
  node [
    id 622
    label "CCTGGTGCACCAGGGCTCGAGCCAGAGCTCTGCGCGGCCGTG"
  ]
  node [
    id 623
    label "GGGCCCGCGGGCCCGCTCGAGCTGCGATCGCAGGTGGCCACT"
  ]
  node [
    id 624
    label "GCGCCCATGGGCGCGCTCGAGCCACGATCGTGGGTGGCCACC"
  ]
  node [
    id 625
    label "GGCTGGTACTGGCCGCTCGAGCTGGTGTGCCAGCGGGCCCGT"
  ]
  node [
    id 626
    label "GGTTCCATGGAGCCGTGTGCACTCTGCGCAGACTGGGCCCAG"
  ]
  node [
    id 627
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGAGTGGCCACT"
  ]
  node [
    id 628
    label "GCCTGA--TTGGGCGCTCGAGCTCAGATCTGACAGGGCCCTG"
  ]
  node [
    id 629
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGGGAAGCTTCC"
  ]
  node [
    id 630
    label "GGGTCG--CGACCCGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 631
    label "GGGCTCGCGGGCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 632
    label "GGGCCCGCGGGCCCGCTCGAGCCATCCGGATGGGAGGCCTCC"
  ]
  node [
    id 633
    label "GCTCCGGCCGGGGCGCC--GGCTGAGATCTCAACGGGCCCGT"
  ]
  node [
    id 634
    label "GGGTCGGTCGACCCGCTCGAGCTACGCGCGTAGATGGCCATC"
  ]
  node [
    id 635
    label "GGGTCTGCAGGCCCGCTCGAGCCTACATGTAGCGTGGCCACG"
  ]
  node [
    id 636
    label "GGTACTGCGGTGCCGCTTAAGCCTTGTACAGGCTGGGCCCAG"
  ]
  node [
    id 637
    label "GGGCGTTAACGCCCGCTCGAGCCGGTCGACCGCGTGGCCACG"
  ]
  node [
    id 638
    label "GGTCGTCGATGGCCGCTCGAGCCTTCGCGAAGCGGGGCCCCG"
  ]
  node [
    id 639
    label "AGGTCTGCAGACCTGCTCGAGCTCGTGCGCGGGTTGGCCAAC"
  ]
  node [
    id 640
    label "GGTTCCTAGGAACCGCC--GGCTCGTGCGCGGAGCGGCCGCT"
  ]
  node [
    id 641
    label "GGCCGGTACTGGCCGCTTGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 642
    label "GGCCGT--ACGGCTGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 643
    label "GGGCCCGCGGGCCCGCTCGAGCCACGGCCGTGCTGGGCCCAG"
  ]
  node [
    id 644
    label "GGGCCCGCGGGCCCGCTTGAGCCACGGCCGTGATGAGCTCAT"
  ]
  node [
    id 645
    label "GGGCCGGCCGGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 646
    label "GCGCTTGCAGGCGCGCTCGAGCCTCGCGCGAGGCTAGCTAGC"
  ]
  node [
    id 647
    label "GGGCTTGCAAGCCCGCTCGAGCCACGCGCGTGGGAAGCTTCT"
  ]
  node [
    id 648
    label "GGCCGGTACTGGCCGTC--GATTGGTGCGCCAGCGGGCCTGT"
  ]
  node [
    id 649
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGTTGGCCAAC"
  ]
  node [
    id 650
    label "GGTCGT--ACGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 651
    label "TAGTCTATAGACTATCTCGAGAATCGATCGATGTGAGCTCGC"
  ]
  node [
    id 652
    label "AGGCCCGCGGGCCTGCTCGAGCCACGCGCGTGGGCAGCTGCC"
  ]
  node [
    id 653
    label "GGGCTAGCTGGCCCGCTCGAGCCGCGCGCGTGGCAAGCTTGC"
  ]
  node [
    id 654
    label "GGGCCTGCAGGCCCGCTCGAGTCACCCGGGTGATAAGCTTAT"
  ]
  node [
    id 655
    label "GGGTCTGCAGACCCGCTCGAGCCCGTCGGCGGGTTGGCCAAC"
  ]
  node [
    id 656
    label "GGTCCCTAGGGACCGCC--GGCTGGTGCGCCAAGCAGCTGCT"
  ]
  node [
    id 657
    label "GGGTCTATAGACCCGCTCGAGCCACGCGCGTGGATGGCCATT"
  ]
  node [
    id 658
    label "GGTGGT--ACTGCCGCTCGAGCTGGTGCGCCAGTGGGCCCGT"
  ]
  node [
    id 659
    label "GGAACTGCAGTTCCGCTCGAGCCACCGCGGTGGGTGGCCACT"
  ]
  node [
    id 660
    label "GGCCGT--ATGGCCGCTCGAGCTGGTGCACCAGCGGGCCCGT"
  ]
  node [
    id 661
    label "AGCAGAGCTCTGCTGCGCGCGTCTGGGCCCAGGATGGCCATC"
  ]
  node [
    id 662
    label "GTTCTGGTCGGAACGCTCGAGCTCGTGCGCGACAGGGCCCTG"
  ]
  node [
    id 663
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 664
    label "GGCTCCATGGGGCCGCTCGAGCCTGGTACCAGGCGAGCTCGC"
  ]
  node [
    id 665
    label "GGGCTCTAGGGCCCGCTCGAGCCACCCGGGTGCCTGGCCAGG"
  ]
  node [
    id 666
    label "GGGGCTATAGCCCCGCTCGAGCCAGAGCTCTGGATGGCCATC"
  ]
  node [
    id 667
    label "GGGCTTGCAGGCCCGCTCGAGCTTACATGTAACCTGGCCAGG"
  ]
  node [
    id 668
    label "GGCTAG--CTGGCCGCTCGAGCCGCGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 669
    label "CCCCGG--CCGGGGGCC--GGCTGAGATCTCAGCGGGCCCGC"
  ]
  node [
    id 670
    label "GGGCTTGCAGGCCCGCTCGAGCCACGCGCGTGGCTGGCCAGC"
  ]
  node [
    id 671
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGTGCCAACGGGCCCGT"
  ]
  node [
    id 672
    label "AGTCTCGCGAGACTGCTCGAGCCTACATGTAGTGCGGCCGCA"
  ]
  node [
    id 673
    label "GGGGCTATAGCCCCGCTCGAGCCTTCCGGAAGGGAGGCCTCC"
  ]
  node [
    id 674
    label "GGGCCGATCGGCCCGCTCGAGCCCACTGGTGGCTCGGCCGAG"
  ]
  node [
    id 675
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGAGTAGCTACT"
  ]
  node [
    id 676
    label "GGGCCTATAGGCCCGCTCGAGCCTTCATGAAGGGAGGCCTCC"
  ]
  node [
    id 677
    label "GCGGGAGCTTCCGCGCTCGAGCCACGCGCGTGGGCAGCTGCC"
  ]
  node [
    id 678
    label "GGGATCATGGTCCCGCTCGAGCCAGGTACCTGGGATGCATCC"
  ]
  node [
    id 679
    label "GGACCACGTGGTCCGCTCGAGCGTCGGCCGATCAGGGCCCTG"
  ]
  node [
    id 680
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGC"
  ]
  node [
    id 681
    label "TGGGGT--ACCTCAGCTTAAGCCTTGCGCAGGCTGGGCCTAG"
  ]
  node [
    id 682
    label "GGTCTG--CAGACCGCTCGAGCCACCCGGGTGGGCAGCTGCC"
  ]
  node [
    id 683
    label "GGGCCTTAAGGCCCGCTCGAGCCTTCGCGAAGGGAGGCCTCC"
  ]
  node [
    id 684
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGCTGGCCAGC"
  ]
  node [
    id 685
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 686
    label "GGGCTCGCGAGCCCGCTCGAGCCACGCGCGTGAGTGGCCACT"
  ]
  node [
    id 687
    label "GGGCCTGCAGGCCCGCTCGAGCCACCCGGGTGGGAGGCCTCC"
  ]
  node [
    id 688
    label "GGGCCTATAGGCCCGCTCGAGCCCGCCGGCGGACTGGCCAGT"
  ]
  node [
    id 689
    label "GGCCTATATGGGCCGCTCGAGTTCGTGCGCGAGCAGGCCTGC"
  ]
  node [
    id 690
    label "GGGCCCTAGGGCCCGTC--GACCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 691
    label "GGCGGT--ACCGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 692
    label "GGGCCATATGGCCCGCTCGAGCCAGTCGACTGCTTGGCCAAG"
  ]
  node [
    id 693
    label "GTCAGGATTCTGACGCC--GGCCTGCGCGCAGGTGGGCCCAC"
  ]
  node [
    id 694
    label "GGCGGT--ACTGCCGCTCGAGCTGGTGCGCCAGCGGGCCTGT"
  ]
  node [
    id 695
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGTGCCAGTGGGCCCGT"
  ]
  node [
    id 696
    label "GGCCTATATGGGCCGCTCGAGCTCGCTGGCGAGCAGGCCTGC"
  ]
  node [
    id 697
    label "GGGCCTATAGGCCCGCTCGAGCCAGTCGACTGGATGGCCATC"
  ]
  node [
    id 698
    label "GGGCGG--CCGCCCGCTCGAGCCGCGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 699
    label "GGGGCTATAGCCCCGCTCGAGCCATCGCGATGCCTGGCCAGG"
  ]
  node [
    id 700
    label "GGTCGGTACCGGCCGCTCGAGCTGGTGCGTCAGTGGGCCCGC"
  ]
  node [
    id 701
    label "AGTCTCATGAGACTGCTCGAGCCTACATGTAGGGCAGCTGCC"
  ]
  node [
    id 702
    label "GGGCGTATACGCCCGCTCGAGCCAGCTAGCTGGGTGGCCACC"
  ]
  node [
    id 703
    label "GCCTTGTACAGGGCGCTCGAGCTCGTGCGCGAACAGGCCTGT"
  ]
  node [
    id 704
    label "AGTCTCGCGGGACTGCTCGAGCCTACATGTAGGGCAGCTGCC"
  ]
  node [
    id 705
    label "GGGCCTGCAGGCCCGCTCGAGCCCGCCGGCGGAATGGCCATT"
  ]
  node [
    id 706
    label "GGGCGTATACGCCCGCTCGAGCCATCCGGATGCCTGGCCAGG"
  ]
  node [
    id 707
    label "GGAAGTATACTTCCGCTCGAGCCACCCGGGTGGATGGCCATT"
  ]
  node [
    id 708
    label "GGGCGTATACGCCCGCTCGAGTCACCCGGGTGCCAGGCCTGG"
  ]
  node [
    id 709
    label "AGTCTCGCGGGACTGCTCGAGTCTACATGTAGGGCAGCTGCC"
  ]
  node [
    id 710
    label "GCCGCCATGGCGGCGCTCGAGCTGGGTGCCCAGCAGGCCTGC"
  ]
  node [
    id 711
    label "GGGCTATATGGCCCGCTCGAGCCACCCGGGTGCCTGGCCAGG"
  ]
  node [
    id 712
    label "TGGTCTGCAGACCAGCC--GGCCTTGTGCAAGGAGGGCCCTT"
  ]
  node [
    id 713
    label "GCGAGCGCGTTCGCGCTCGAGCCACGATCGTGGATGGCCATT"
  ]
  node [
    id 714
    label "GGGACTATAGTCCCGCTCGAGCCACCCGGGTGCCAGGCCTGG"
  ]
  node [
    id 715
    label "GGCGGT--ACTGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 716
    label "GGCCAGTACTGGCCGCTCGAGCTGGTGCACCAATGGGCCCAT"
  ]
  node [
    id 717
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGTAAGCTTAC"
  ]
  node [
    id 718
    label "GGGTGATATCACCCGCTCGAGCCTTCTGGAAGCCAGGCCTGG"
  ]
  node [
    id 719
    label "GGTCGGTACTGACCGCTCGAGCTGGTATGCCAATGAGCTCAT"
  ]
  node [
    id 720
    label "GGGCTTGCAAGCCCGCTCGAGCCTTCTGGAAGATTAGCTAAT"
  ]
  node [
    id 721
    label "GGCCGG--TCGGTTGCTCGAGCGCTGCGCAGCGGGGGCCCCC"
  ]
  node [
    id 722
    label "GGGGACGCGTCCCTGCTCGAGCGCGGGTCCGTGTGGGCCCAC"
  ]
  node [
    id 723
    label "GGGCCCATGGGCCCGCTCGAGCCACGCGCGTGAGTGGCCACT"
  ]
  node [
    id 724
    label "GCCTGT--ATGGGCGTC--GACTGGTGCGCCAACAGGCCTGT"
  ]
  node [
    id 725
    label "GGCCGT--ACGGCCGCTCGAGTTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 726
    label "GGGCCGATCGGCCCGCGCGCGCCCCGCGCGGGGGTGGCCACC"
  ]
  node [
    id 727
    label "GGGCCCATGGGCCCGCTCGAGCCTTCGCGAAGGGAGGCCTCC"
  ]
  node [
    id 728
    label "GGGAGCGCGTTCCCGCTCGAGCCACGATCGTGGATGGCCATT"
  ]
  node [
    id 729
    label "GGGCCGGTCGGCCCGCTCGAGCCACGCGCGTGGTAGGCCTAC"
  ]
  node [
    id 730
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGGGTGGCCGCT"
  ]
  node [
    id 731
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 732
    label "GGGCCTGCAGGCCCGCTCGAGCCATCCGGATGGGAGGCCTCC"
  ]
  node [
    id 733
    label "GCTCCG--CGGAGCGCTCGAGCTTGGTGCCGAGCGGGCCCGC"
  ]
  node [
    id 734
    label "GGGCCTGTAGGCCCGCTCGAGCCACGATCGTGGATGGCCATC"
  ]
  node [
    id 735
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGAATGGCCATT"
  ]
  node [
    id 736
    label "GGGCCCGCGGGCCCGCTTGAGCCCCGGCCGGGGGGGGCCCCC"
  ]
  node [
    id 737
    label "GGCCGGTACCGGCCGCTCGAGCTGGTGCACCAGCGGGCCCGC"
  ]
  node [
    id 738
    label "GGGCCTGCAGGCCCGCTCGAGCCGCGCGCGCGGATAGCTATC"
  ]
  node [
    id 739
    label "GGACGCATGTGTCCGCTCGAGCCACCCGGGTGCCAGGCCTGG"
  ]
  node [
    id 740
    label "AGTCCCGCGGGACTGCTCGAGCCTACATGTAGTGCGGCCGCA"
  ]
  node [
    id 741
    label "GGGCTTGCAGGCCCGCTCGAGCCGACATGTCGCGTGGCCACG"
  ]
  node [
    id 742
    label "GGGCTTTAAGGCCCGCTCGAGCCACCTGGGTGGGTGGCCACC"
  ]
  node [
    id 743
    label "GGGCCTTAAGGCCCGCTCGAGCTACCCGGGTAAGTGGCCACT"
  ]
  node [
    id 744
    label "ATGAATGCATTCATGCTTAAGCCCCGATCGGGGCAGGCCTGC"
  ]
  node [
    id 745
    label "GGGCCTGCGGGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 746
    label "GGGTCTATAGACCCGCTCGAGCCACGCGCGTGAGTGGCCACT"
  ]
  node [
    id 747
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 748
    label "GGCCGGTACTGGCCCTC--GGGTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 749
    label "AGTCTG--CGGACTGCTCGAGTCTACATGTAGGGCAGCTGCC"
  ]
  node [
    id 750
    label "GGGCTTGCAGGCCCGCTCGAGCCACGATCGTGGCTGGCCAGC"
  ]
  node [
    id 751
    label "GGGCGTGCACGCCCGCTCGAGCCAGCCGGCTGCGTGGCCACG"
  ]
  node [
    id 752
    label "GGAAAATATTTTCCTCA--TGGCTGGCGCTAGACAGGCCTGT"
  ]
  node [
    id 753
    label "GGTCGGTACCGACCGCTCGAGCTGGTGCACTAGCGGGCCCGC"
  ]
  node [
    id 754
    label "GGGTCTGCAGACCCGCTCGAGCCTGTGCGCAGGTAGGCCTAC"
  ]
  node [
    id 755
    label "GGGCTCGCGAGCCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 756
    label "GGGCCTATAGGCCCGCTCGAGCCACCCGGGTGGTTGGCCAAC"
  ]
  node [
    id 757
    label "AGTCCCGCGGGACTGCTCGAGCCTACATGTAGCGCAGCTGCG"
  ]
  node [
    id 758
    label "GGTCTA--TAGACCGCTTGAGCTTGCCGGCAAGCAGGCCTGC"
  ]
  node [
    id 759
    label "GCGAGGGCCCTCGCGCTCGAGCCTCGGCCGAGCCGGGCCCGG"
  ]
  node [
    id 760
    label "GGCCGGCGCTGGCTGCTCGAGTTGGTGCACCAATAGGCTTAT"
  ]
  node [
    id 761
    label "GCTGGT--ACTGGTGCTCGAGCTGGTGCGCCAGCGGGTTCGT"
  ]
  node [
    id 762
    label "GGGAGTTAATTCCCGCTCGAGCCTGTGCGCAGCCAGGCCTGG"
  ]
  node [
    id 763
    label "GCTGGT--ACTGGTGCTCGAGCTGGTGTGCCAGCGGGTTCGT"
  ]
  node [
    id 764
    label "GGGCCCGCGGGCCCGCTCGAGCCTCGCGCGAGCGGGGCCCCG"
  ]
  node [
    id 765
    label "GGGCCTATAGGCCCGCTCGAGCCATCGCGATGGCTGGCCAGC"
  ]
  node [
    id 766
    label "AGGCTAGCTAGCCTGCC--GGCCTCGGCCGGGATGGGCCCAT"
  ]
  node [
    id 767
    label "TGTCTCGCGAGACAGCTCGAGTCTACATGTAGGACAGCTGTC"
  ]
  node [
    id 768
    label "GGGCCTGCGGGCCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 769
    label "GGGATTGTAATCCCGCTCGAGCTACCATGGTAAATAGCTATT"
  ]
  node [
    id 770
    label "GGCTGT--ACGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCGT"
  ]
  node [
    id 771
    label "GGGCTTATAAGCCCGCTCGAGCCACGCGCGTGGCTGGCCAGC"
  ]
  node [
    id 772
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCGCCAGCGGGCCTGT"
  ]
  node [
    id 773
    label "GCGGTTATAACCGCGCTCGAGCCCACATGTGGCCTAGCTAGG"
  ]
  node [
    id 774
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGATAGCTATC"
  ]
  node [
    id 775
    label "GGGGCTATAGCCCTGCTCGAGCCTCCGCGGAGACTGGCCAGT"
  ]
  node [
    id 776
    label "GGGTCTGCAGACCCGCTCGAGCTCGTCGGCGAGTTGGCCAAC"
  ]
  node [
    id 777
    label "GGACCTATAGGTCCGCTCGAGCCTTCCGGAAGGGTGGCCACC"
  ]
  node [
    id 778
    label "GGCCTATATGGGCCGCTCGAGCTCGTGCGCGAACAGGCCTGT"
  ]
  node [
    id 779
    label "AGGACTGCAGTCCTGCTCGAGCCGCCCGGGTGGGTAGCTACT"
  ]
  node [
    id 780
    label "GTCCTG--CAGGACGCTCGAGCCTCGCGCGAGCTGGGCCCGG"
  ]
  node [
    id 781
    label "GGGCCTATAGGCCCGCTCGAGCCTGCCGGCAGAGTGGCCACT"
  ]
  node [
    id 782
    label "CCTAAG--CTTAGGGCTTGAGCTTGTGTGCAAGTGGGCCTAT"
  ]
  node [
    id 783
    label "GGTCCGTATGGACCGCTCGAGCTCGTGCGCGAGTGGGCCCAC"
  ]
  node [
    id 784
    label "GGGCCTTAAGGCCCGCTCGAGCCACCTGGGTGAGTGGCCACT"
  ]
  node [
    id 785
    label "GGGCTTGCAGGCCCGCTCGAGCCACGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 786
    label "GGGCGCGCGTGCCCGCTCGAGTCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 787
    label "GGCCTA--TAGGCCGCTCGAGCCACGCGCGTGAATGGCCATT"
  ]
  node [
    id 788
    label "GGGCCTGCAGGCCCGCTCGAGCCACGCGCGTGACTAGCTAGT"
  ]
  node [
    id 789
    label "GGGCCGTACGGCCTGCTCGAGCCCGGCGCCGGGCGGGCCCGC"
  ]
  node [
    id 790
    label "AGGCTTGCAGGCCTGCTCGGGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 791
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGTGCCAGCGGGCCTGT"
  ]
  node [
    id 792
    label "GGGCCTATAGGCCCGCTCGAGCCGCGCGCGCGGGTGGCCACC"
  ]
  node [
    id 793
    label "GGTGCTGCAGTGCCGCTTAAGCCCTGTACAGGCTGGGCCCAG"
  ]
  node [
    id 794
    label "GGCCAGTACTGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCGT"
  ]
  node [
    id 795
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGCCGATGGGCCCAT"
  ]
  node [
    id 796
    label "GGTCCGCGTGGACCGCTTGAGCTCGTGCGCGAGTGAGCTCAC"
  ]
  node [
    id 797
    label "GGCCGGTACTGGCCGCTCGAGCTGGTGCGCTAGCGGGCCCGT"
  ]
  node [
    id 798
    label "GGGCCTATAGGCCCGCC--GGCCCGCCGGCGGGGTGGCCACC"
  ]
  node [
    id 799
    label "GGGCCTATAGGCCCGCTCGAGCCATCCGGATGGCTGGCCAGC"
  ]
  node [
    id 800
    label "GCCGCCATGGCGGCGCC--GGCTGGGTGCCCAGCAGGCCTGC"
  ]
  node [
    id 801
    label "GGCCAGTACTGGCCGCTTGAGCTGGTGCGCCAGTGGGTCCAT"
  ]
  node [
    id 802
    label "AGGCCTGCAGGCCTGCTCGAGCTACGCGCGTAGGCAGCTGCC"
  ]
  node [
    id 803
    label "GGGTCTGCAGACCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 804
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCGCCAGTGGGCCCAC"
  ]
  node [
    id 805
    label "GGGACTGCAGTCCCGCTCGAGCCACCCGGGTGGGAGGCCTCT"
  ]
  node [
    id 806
    label "GGGTTTGCAGACCCGCTCGAGCCACGCGCGTGGTAGGCCTAC"
  ]
  node [
    id 807
    label "GGTCCTATAGGACTGCTCGAGCCACGATCGTGGCTGGCCAGC"
  ]
  node [
    id 808
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 809
    label "AGGCCTGCAGGCCTGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 810
    label "GGGCCGATCGGCCCGCTCGAGCCTCGGCCGGGCGCGGCCGTG"
  ]
  node [
    id 811
    label "GCCATGGCCGTGGCGCC--GGTTGTGATCACAGCGGGCCCGT"
  ]
  node [
    id 812
    label "GGGCTCATGGGCCCGCTCGAGCCGCGCGCGCGGATGGCCGTC"
  ]
  node [
    id 813
    label "GCTGGT--ATTGGCGCT--AGCTGGTGCGCCAGCGGGCCTGT"
  ]
  node [
    id 814
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGAGAGGCCTCT"
  ]
  node [
    id 815
    label "GGGGATATATCCCCGCTCGAGCCTTCGCGAAGCGAGGCCTCG"
  ]
  node [
    id 816
    label "GGGCCCGCGGGCCCGCATGTGCCCCGGCCGGGATGTGCACAT"
  ]
  node [
    id 817
    label "GGTGGT--ACTGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGT"
  ]
  node [
    id 818
    label "AGGCCTGCAGGCCTGCTCGAGCCACCCGGGTGGGCAGCTGCC"
  ]
  node [
    id 819
    label "GGCCGT--ACGGCCGCTCGAGCTGGTGCGCCAGCGGGCCCGC"
  ]
  node [
    id 820
    label "AGTCTTGCAAGACTGCTCGAGCCCACATGTGGCGCGGCCGCG"
  ]
  node [
    id 821
    label "GGCCTATATGGGCCGCTCGAGCTCGTGCGCGAGTAGGCCTGC"
  ]
  node [
    id 822
    label "GTCATGGCCGTGACGCC--GGCTGTGATCACAGCGGGCCCGT"
  ]
  node [
    id 823
    label "GGGCGCATGTGCCCGCTCGAGCCACGCGCGTGGATGGCCATT"
  ]
  node [
    id 824
    label "GCCTCGGCCGAGGCGCC--GGCTGAGATCTCAGCGGGCCCGT"
  ]
  node [
    id 825
    label "GGCCGT--ATGGCCCTC--GAGTGGTGCGCCAACGGGCCCGT"
  ]
  node [
    id 826
    label "GGGTCTGCAGACCCGCTCGAGCCACCCGGGTGGCTGGCCAGC"
  ]
  node [
    id 827
    label "GGGCGTATACGCCCGCTCGAGCCTTCGCGAAGCCAGGCCTGG"
  ]
  node [
    id 828
    label "GGGCCGGCCGGCCCGCTCGAGCCCACTGGTGGCTCGGCCGAG"
  ]
  node [
    id 829
    label "GGGCTTGCAGGCCCGCTCGAGCCTACATGTAGCCTGGCCAGG"
  ]
  node [
    id 830
    label "GGGCTTATAGGCCCGCTCGAGCCACGCGCGTGGATGGCCATT"
  ]
  node [
    id 831
    label "GGGCCTATAGGCCCGCTCGAGCCTTCCGGAAGGGAGGCCTCC"
  ]
  node [
    id 832
    label "GGGTCTGTAGACCCGCTCGAGCCCGTCGGCGGGTTGGCCAAC"
  ]
  node [
    id 833
    label "GGGTCTATAGACCCGCTCGAGCCGCGCGCGTGGGTGGCCACC"
  ]
  node [
    id 834
    label "GGGCTTGCAGGCCCGCTCGAGCCACGCGCGTGGGCTGCAGCC"
  ]
  node [
    id 835
    label "TTCAAAGCTTTGAAGCTCGAGCCATAATTATGTAAGGCCTTA"
  ]
  node [
    id 836
    label "GATCCATATGGATCGCTCGAGCTCGGTACCGAGTGGGCCCAC"
  ]
  node [
    id 837
    label "GGTGCG--CGCGCCGCT--GGCCTGGATCCAGGTGGGCCCAC"
  ]
  node [
    id 838
    label "GGCCTATATAGGCCGCTCGAGCTCGTGTGTGAGTAGGCCTGC"
  ]
  node [
    id 839
    label "GGACCTGCAGGTCCGCTCGAGCCTTCCGGAAGGGTGGCCACC"
  ]
  node [
    id 840
    label "GGTTCTGCAGAACCGCTCGAGCGCGAGCTCGTGCTGGCCAGC"
  ]
  node [
    id 841
    label "GCGTTTGCAAACGCGCTCGAGCCACGCGCGTGGGTGGCCACT"
  ]
  node [
    id 842
    label "ACTGGC--GCCAGTGTTTAAACAGTGATCGCTGCGGGCCCGC"
  ]
  node [
    id 843
    label "GGTCCGCGTGGACCGCTCGAGCTCGTGCGCGAGTGAGCTCAC"
  ]
  node [
    id 844
    label "GGGCCTATAGGCCCGCTCGAGCCACGCGCGTGGGAAGCTTCC"
  ]
  node [
    id 845
    label "GGGTCAGTTGACCCGCTCGAGCCCGTCGGCGGGTTGGCCAAC"
  ]
  node [
    id 846
    label "GGCCGT--ACGGCCGTTCGAGCTGGTGCGCCAACGGGCCCGT"
  ]
  node [
    id 847
    label "GGAAGTATATTTCCGCTCGAGCCACCCGGGTGGGTGGCCACT"
  ]
  node [
    id 848
    label "GGGTCTGCAGACCCGCTCGAGCCCGTCGGCGGGAAGGCCTTC"
  ]
  node [
    id 849
    label "GGGCCTTAAGGCCCGCTCGAGCCACGCGCGTGCCTGGCCAGG"
  ]
  node [
    id 850
    label "GGGTCGGTCGACCCGCTCGAGCCACGCGCGTGGGAGGCCTCC"
  ]
  node [
    id 851
    label "GGGCTTCGAAGCCCGCTCGAGCCGTCCGGACGTCTGGCCAGA"
  ]
  node [
    id 852
    label "GGCCGGTATTGGCCGCTCGAGCTGGTGCGCCAACGGGCCCGT"
  ]
  node [
    id 853
    label "GTCTGT--ATGGGCGCTCGAGCTGGTGCACCAGTGGGCCCAT"
  ]
  node [
    id 854
    label "GGGCCAATTGGCCCGCTCGAGCCTTCTGGAAGCCTAGCTAGG"
  ]
  node [
    id 855
    label "GGACCTGCAGGTCCGCTCGAGCCACGCGCGTGGGTGGCCACC"
  ]
  node [
    id 856
    label "GGGTCTGCAGACCCGATCGATCCACCCGGGTGGGTGGCCACC"
  ]
  node [
    id 857
    label "GCGCTG--CAGTGCGTT--AGCCCTGTACAGGCTGGGCCCAG"
  ]
  node [
    id 858
    label "GCCCGG--CCGGGCGCC--GGCTGAGATCTCAGCGGGCCCGC"
  ]
  node [
    id 859
    label "GGGCTCTAGGGCCCGCTCGAGCTCGTGCGCGGGGTGGCCACT"
  ]
  node [
    id 860
    label "GTCCTG--CAGGACGTGCGCGCTTCAGCTGAAGGTGGCCACC"
  ]
  node [
    id 861
    label "GGTCTATATAGGCCGCTCGAGTTTGTGTACGAACAGGCCTGT"
  ]
  node [
    id 862
    label "GGTCTGTATAGACCGCTCGAGCTCGTGCGCGAGAGAGCTCTC"
  ]
  node [
    id 863
    label "AGTCCCGCGGGACTGCTCGAGCCTACATGTAGAGCAGCTGCT"
  ]
  node [
    id 864
    label "GCCCGG--CCGGGCGCC--GGCTGAGATCTCAGCGGGCCCGT"
  ]
  node [
    id 865
    label "GGGGCTATAGCCCCGCTCGAGCCAGCATGCTGGCTGGCCAGC"
  ]
  node [
    id 866
    label "CGCGGA--TCCGCGGCTCGAGCTCGGGCCCGAGCGGGCCCGC"
  ]
  edge [
    source 4
    target 64
  ]
  edge [
    source 5
    target 528
  ]
  edge [
    source 5
    target 438
  ]
  edge [
    source 7
    target 641
  ]
  edge [
    source 7
    target 14
  ]
  edge [
    source 8
    target 671
  ]
  edge [
    source 8
    target 808
  ]
  edge [
    source 8
    target 695
  ]
  edge [
    source 9
    target 292
  ]
  edge [
    source 14
    target 314
  ]
  edge [
    source 14
    target 685
  ]
  edge [
    source 14
    target 794
  ]
  edge [
    source 15
    target 368
  ]
  edge [
    source 19
    target 685
  ]
  edge [
    source 19
    target 152
  ]
  edge [
    source 19
    target 852
  ]
  edge [
    source 21
    target 429
  ]
  edge [
    source 21
    target 785
  ]
  edge [
    source 22
    target 28
  ]
  edge [
    source 25
    target 676
  ]
  edge [
    source 28
    target 647
  ]
  edge [
    source 31
    target 645
  ]
  edge [
    source 33
    target 222
  ]
  edge [
    source 35
    target 359
  ]
  edge [
    source 35
    target 236
  ]
  edge [
    source 38
    target 353
  ]
  edge [
    source 39
    target 482
  ]
  edge [
    source 40
    target 218
  ]
  edge [
    source 41
    target 307
  ]
  edge [
    source 41
    target 795
  ]
  edge [
    source 41
    target 470
  ]
  edge [
    source 41
    target 586
  ]
  edge [
    source 45
    target 100
  ]
  edge [
    source 53
    target 643
  ]
  edge [
    source 57
    target 64
  ]
  edge [
    source 58
    target 394
  ]
  edge [
    source 59
    target 747
  ]
  edge [
    source 64
    target 730
  ]
  edge [
    source 65
    target 511
  ]
  edge [
    source 69
    target 100
  ]
  edge [
    source 70
    target 704
  ]
  edge [
    source 75
    target 535
  ]
  edge [
    source 84
    target 755
  ]
  edge [
    source 90
    target 429
  ]
  edge [
    source 90
    target 496
  ]
  edge [
    source 90
    target 785
  ]
  edge [
    source 97
    target 775
  ]
  edge [
    source 100
    target 366
  ]
  edge [
    source 100
    target 821
  ]
  edge [
    source 100
    target 374
  ]
  edge [
    source 100
    target 193
  ]
  edge [
    source 100
    target 169
  ]
  edge [
    source 100
    target 209
  ]
  edge [
    source 100
    target 689
  ]
  edge [
    source 100
    target 508
  ]
  edge [
    source 101
    target 496
  ]
  edge [
    source 104
    target 685
  ]
  edge [
    source 105
    target 405
  ]
  edge [
    source 111
    target 269
  ]
  edge [
    source 112
    target 379
  ]
  edge [
    source 113
    target 558
  ]
  edge [
    source 113
    target 327
  ]
  edge [
    source 114
    target 182
  ]
  edge [
    source 115
    target 808
  ]
  edge [
    source 115
    target 770
  ]
  edge [
    source 121
    target 631
  ]
  edge [
    source 123
    target 685
  ]
  edge [
    source 123
    target 513
  ]
  edge [
    source 125
    target 240
  ]
  edge [
    source 131
    target 808
  ]
  edge [
    source 134
    target 747
  ]
  edge [
    source 134
    target 627
  ]
  edge [
    source 140
    target 272
  ]
  edge [
    source 142
    target 267
  ]
  edge [
    source 151
    target 204
  ]
  edge [
    source 152
    target 543
  ]
  edge [
    source 153
    target 161
  ]
  edge [
    source 153
    target 485
  ]
  edge [
    source 154
    target 160
  ]
  edge [
    source 154
    target 499
  ]
  edge [
    source 154
    target 830
  ]
  edge [
    source 154
    target 735
  ]
  edge [
    source 157
    target 578
  ]
  edge [
    source 164
    target 252
  ]
  edge [
    source 164
    target 731
  ]
  edge [
    source 164
    target 316
  ]
  edge [
    source 165
    target 448
  ]
  edge [
    source 165
    target 635
  ]
  edge [
    source 167
    target 340
  ]
  edge [
    source 171
    target 177
  ]
  edge [
    source 172
    target 711
  ]
  edge [
    source 177
    target 499
  ]
  edge [
    source 177
    target 246
  ]
  edge [
    source 177
    target 183
  ]
  edge [
    source 178
    target 319
  ]
  edge [
    source 180
    target 811
  ]
  edge [
    source 181
    target 307
  ]
  edge [
    source 182
    target 700
  ]
  edge [
    source 183
    target 465
  ]
  edge [
    source 184
    target 236
  ]
  edge [
    source 186
    target 817
  ]
  edge [
    source 186
    target 694
  ]
  edge [
    source 189
    target 829
  ]
  edge [
    source 196
    target 253
  ]
  edge [
    source 208
    target 222
  ]
  edge [
    source 210
    target 808
  ]
  edge [
    source 211
    target 218
  ]
  edge [
    source 213
    target 558
  ]
  edge [
    source 216
    target 306
  ]
  edge [
    source 216
    target 349
  ]
  edge [
    source 218
    target 390
  ]
  edge [
    source 225
    target 380
  ]
  edge [
    source 231
    target 267
  ]
  edge [
    source 232
    target 640
  ]
  edge [
    source 233
    target 685
  ]
  edge [
    source 233
    target 241
  ]
  edge [
    source 235
    target 485
  ]
  edge [
    source 235
    target 444
  ]
  edge [
    source 236
    target 770
  ]
  edge [
    source 236
    target 808
  ]
  edge [
    source 236
    target 695
  ]
  edge [
    source 238
    target 248
  ]
  edge [
    source 241
    target 737
  ]
  edge [
    source 241
    target 680
  ]
  edge [
    source 249
    target 821
  ]
  edge [
    source 249
    target 689
  ]
  edge [
    source 255
    target 340
  ]
  edge [
    source 256
    target 778
  ]
  edge [
    source 262
    target 569
  ]
  edge [
    source 263
    target 803
  ]
  edge [
    source 264
    target 582
  ]
  edge [
    source 267
    target 685
  ]
  edge [
    source 267
    target 852
  ]
  edge [
    source 271
    target 685
  ]
  edge [
    source 272
    target 382
  ]
  edge [
    source 273
    target 803
  ]
  edge [
    source 273
    target 574
  ]
  edge [
    source 275
    target 715
  ]
  edge [
    source 275
    target 658
  ]
  edge [
    source 283
    target 843
  ]
  edge [
    source 288
    target 555
  ]
  edge [
    source 293
    target 701
  ]
  edge [
    source 293
    target 555
  ]
  edge [
    source 294
    target 359
  ]
  edge [
    source 297
    target 545
  ]
  edge [
    source 299
    target 406
  ]
  edge [
    source 299
    target 515
  ]
  edge [
    source 311
    target 448
  ]
  edge [
    source 314
    target 400
  ]
  edge [
    source 319
    target 727
  ]
  edge [
    source 320
    target 590
  ]
  edge [
    source 348
    target 523
  ]
  edge [
    source 358
    target 464
  ]
  edge [
    source 358
    target 383
  ]
  edge [
    source 359
    target 660
  ]
  edge [
    source 359
    target 808
  ]
  edge [
    source 366
    target 419
  ]
  edge [
    source 378
    target 451
  ]
  edge [
    source 384
    target 661
  ]
  edge [
    source 391
    target 543
  ]
  edge [
    source 392
    target 809
  ]
  edge [
    source 400
    target 685
  ]
  edge [
    source 401
    target 754
  ]
  edge [
    source 406
    target 412
  ]
  edge [
    source 412
    target 830
  ]
  edge [
    source 412
    target 602
  ]
  edge [
    source 415
    target 685
  ]
  edge [
    source 415
    target 625
  ]
  edge [
    source 419
    target 821
  ]
  edge [
    source 420
    target 499
  ]
  edge [
    source 421
    target 711
  ]
  edge [
    source 431
    target 655
  ]
  edge [
    source 432
    target 728
  ]
  edge [
    source 434
    target 496
  ]
  edge [
    source 434
    target 785
  ]
  edge [
    source 434
    target 491
  ]
  edge [
    source 438
    target 809
  ]
  edge [
    source 438
    target 492
  ]
  edge [
    source 438
    target 790
  ]
  edge [
    source 439
    target 451
  ]
  edge [
    source 445
    target 770
  ]
  edge [
    source 452
    target 786
  ]
  edge [
    source 457
    target 746
  ]
  edge [
    source 465
    target 569
  ]
  edge [
    source 471
    target 695
  ]
  edge [
    source 476
    target 734
  ]
  edge [
    source 485
    target 621
  ]
  edge [
    source 486
    target 812
  ]
  edge [
    source 492
    target 528
  ]
  edge [
    source 496
    target 574
  ]
  edge [
    source 498
    target 596
  ]
  edge [
    source 507
    target 736
  ]
  edge [
    source 517
    target 808
  ]
  edge [
    source 517
    target 660
  ]
  edge [
    source 519
    target 640
  ]
  edge [
    source 522
    target 586
  ]
  edge [
    source 522
    target 794
  ]
  edge [
    source 543
    target 685
  ]
  edge [
    source 543
    target 791
  ]
  edge [
    source 552
    target 655
  ]
  edge [
    source 568
    target 753
  ]
  edge [
    source 582
    target 808
  ]
  edge [
    source 586
    target 716
  ]
  edge [
    source 589
    target 591
  ]
  edge [
    source 600
    target 656
  ]
  edge [
    source 610
    target 755
  ]
  edge [
    source 615
    target 672
  ]
  edge [
    source 615
    target 740
  ]
  edge [
    source 641
    target 685
  ]
  edge [
    source 642
    target 808
  ]
  edge [
    source 650
    target 808
  ]
  edge [
    source 655
    target 832
  ]
  edge [
    source 658
    target 817
  ]
  edge [
    source 680
    target 685
  ]
  edge [
    source 685
    target 797
  ]
  edge [
    source 691
    target 715
  ]
  edge [
    source 694
    target 715
  ]
  edge [
    source 704
    target 709
  ]
  edge [
    source 715
    target 817
  ]
  edge [
    source 725
    target 808
  ]
  edge [
    source 731
    target 745
  ]
  edge [
    source 747
    target 768
  ]
  edge [
    source 761
    target 763
  ]
  edge [
    source 772
    target 808
  ]
  edge [
    source 796
    target 843
  ]
  edge [
    source 808
    target 819
  ]
  edge [
    source 858
    target 864
  ]
]
