graph [
  node [
    id 0
    label "TCCGCGATCGCGGAGTTTGAATCGTGCGCGCGCGGGGCCCCG"
  ]
  node [
    id 1
    label "TCCCGA--TCGGGAATATGTATCCCGCGCGGGCGGGGCCCTG"
  ]
  node [
    id 2
    label "TCCTCGATCGGGGAGTT--GATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 3
    label "TCCCGG--CCGGGAGTTCGGATCAGCATGCTGTTGGGCCTGA"
  ]
  node [
    id 4
    label "TCCTCT--AGGGGAGTATGTATCCCGTGCGGGCGGGGCCCCG"
  ]
  node [
    id 5
    label "TCCTCGTACGGGGAGTATGTATTCTGCGCAGACAGGGCTCTG"
  ]
  node [
    id 6
    label "GGGGTTGCAGCCCCGCTCGAGCCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 7
    label "GGAACCGCGGTTCCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 8
    label "GGAGGCGCGCTTCCGTGTACACCGGCCGGCCGGCGGGCCCGT"
  ]
  node [
    id 9
    label "GGGCCCGCGGGCCCGTCTGGATCCACCGGTGGGCGGGCCCGT"
  ]
  node [
    id 10
    label "TCCTCGATCGGGGAGTATGTATCCCGCGCGGGTGGGGCTCCG"
  ]
  node [
    id 11
    label "GGCTTGGCCAAGTCGCTCGAGTCTGGCGCCAGGAGGGCCCTT"
  ]
  node [
    id 12
    label "GTTTTG--CAGAACGTG--CACTTTGCGCGAACTTGGCCGAG"
  ]
  node [
    id 13
    label "GGTCCCGCGGGACCGGTTAGCCCCGCGCGCGGGCCGGCCGGC"
  ]
  node [
    id 14
    label "GGCCCTGCAGGGTCGCGCGCGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 15
    label "GGCCCTGCAGGGTCGCGCGCGTCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 16
    label "GGCCCAGCTGGGTCGCGCGCGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 17
    label "GGCCCCATGGGGTCGCGATCGCCCTCCGGAGGACGAGCTCGT"
  ]
  node [
    id 18
    label "TCCTCGTACGAGGAGTATGTATCCCGCGCGGGTGGGGCCCTG"
  ]
  node [
    id 19
    label "GGCCTGGCCAGGTCGTTCGAATCTAGCGCTAGGTGGGCCCAT"
  ]
  node [
    id 20
    label "TCCCTGGTCAGGGGGTCTGGATTGGCATGCTACTGGGCCTGG"
  ]
  node [
    id 21
    label "GCCTAG--CTAGGCGCTTAAGCTTATATATAAGACGGCCGTT"
  ]
  node [
    id 22
    label "GGGGGTGCGCTCCCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 23
    label "TCCCTGGCTGGGGAGCCTAGGTTGGCATGCTGTCAGGCCTGG"
  ]
  node [
    id 24
    label "GGCCCGATCGGGTCGTTCGAACCTAGCGCTAGGAGGGCCCTT"
  ]
  node [
    id 25
    label "GGTGCGTACGCACCGTTCGAATCGTGCGCACGAGGGGCCCCT"
  ]
  node [
    id 26
    label "GGTCTGGCCAGACCGTTCGAATCGTGCGCACGGCGGGCCCGT"
  ]
  node [
    id 27
    label "TTCCGATATCGGAAGTCTGGATTCGGCGCCGGCGGGGCCCCG"
  ]
  node [
    id 28
    label "GGTCTATATAGACCGGGGCCCCTCGCCGGCGAACGGGCCCGT"
  ]
  node [
    id 29
    label "GTTTCCGTGGAAACGTG--CATTTCGCGTGAACCTGGCCGGG"
  ]
  node [
    id 30
    label "GCCCGGGCTCGGGCGTG--CATCAACCGGTTGGCGGGCCCGC"
  ]
  node [
    id 31
    label "TCCTCG--CGGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 32
    label "GGGGGTGCACTCCCGCTCGAGCCCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 33
    label "TCCCTGGCTAGGGAGTCTGGATTGGCATGCTGTCAGGCCTGG"
  ]
  node [
    id 34
    label "GGAGCAGCTGCTCCGTTCGAATTCGGCGTCGAGCGGGCCCGT"
  ]
  node [
    id 35
    label "TCTCGT--ACGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 36
    label "TCCGGGATTCCGGGGTTTGAATCGCGCGTGCGCGGGGCCCCG"
  ]
  node [
    id 37
    label "GGTTCCATGGGACCGTCTGGACCCTGCGCAGGACGGGCCCGT"
  ]
  node [
    id 38
    label "GGACTGGCCAGTCCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 39
    label "GTCCGAATTCGGGCGTG--CATGAGCCGGCTCTCGGGCCCGG"
  ]
  node [
    id 40
    label "TCCTCGTACGGGGAGTATGTATCCCGCGTGGGCGGGGTCCCG"
  ]
  node [
    id 41
    label "TCCGTGATCGCGGAGTTTGAATACCGTATGGTCGGGGCCCCG"
  ]
  node [
    id 42
    label "TCCCGG--TCGGGAGTCTGGACCAGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 43
    label "TCCTCGATCGGGGAGTATGTATCCCGCGCGGGCGGGGCTCCG"
  ]
  node [
    id 44
    label "TCCTCGTACGGGGAGTATGTATTCCGCGCGGACAGGGCCCTG"
  ]
  node [
    id 45
    label "GGGCTCGCGAGCCCGTGTACACCCGGCGCCGGGGGGGCCCCT"
  ]
  node [
    id 46
    label "GCCCAGGCCTGGGCGTG--CATACGGCGCCGTACGGATCCGT"
  ]
  node [
    id 47
    label "GGTCTGGCCAGACCGTTCGAATTATGTGCATAGCGAGCTCGT"
  ]
  node [
    id 48
    label "TCCCTGGTCGGGGAGTCCGGATCAGTGTGCTGCTGGGCCTGG"
  ]
  node [
    id 49
    label "GGGGGCGCGCTCCCGTTATAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 50
    label "GGAGTTGCAACTCCGCTCGAGCCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 51
    label "GGGGGATATTCTCCGCTCGAGCCTCGCGCGAGGTGGGCCCAC"
  ]
  node [
    id 52
    label "GGAGTGGCCACTCCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 53
    label "GGAGCGGCCGCTCCGTTCGAATCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 54
    label "GGCTCTGCAGAGTCGAGCGCTCCCACCGGTGGGCGGGCCCGT"
  ]
  node [
    id 55
    label "GGTCGCATGTGACCGTCCGGACCCTGCGCAGGGCGGGCCCGC"
  ]
  node [
    id 56
    label "GCCCGGATCCGGGCGTG--CATCAACCGGTTGGCGGGCCCGC"
  ]
  node [
    id 57
    label "TCCCTGGTCAGGGAGTCCGGACCGGTGTGCCGCTGGGCCTGG"
  ]
  node [
    id 58
    label "GCGGTTGCAACCGCGCTCGAGTCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 59
    label "GGAGCCATGGTTCCGCTCGAGCCCCGGCCGGGGCGGGCCCGC"
  ]
  node [
    id 60
    label "TCCGGGATTCCGGAGTTTGAATCGCGCGTGCGCGGGGCCCCG"
  ]
  node [
    id 61
    label "GGAGCGGCCGTTCCGCTCGAGCCTGCCGGCAGGCGGGCCCGT"
  ]
  node [
    id 62
    label "TCCCTG--CAGGGAGCCTGGGTTGGCATGCTATTGGGCCCAA"
  ]
  node [
    id 63
    label "GGGCTTTAAGGCCCGTGTACACCCACATGTGGACGGGCCCGT"
  ]
  node [
    id 64
    label "TCCTTGGCCAAGGAGTATGTATTCCGCGCGGACGGGGCCCTG"
  ]
  node [
    id 65
    label "GGGAGG--CCTCCCGCTCGAGCCAGGCGCCTGGCGAGCTCGT"
  ]
  node [
    id 66
    label "TCTCTTGCAAGAGAGTTTGAATCGCGCGCGCGCGGGGCCCCG"
  ]
  node [
    id 67
    label "GGGGAGTACTCCCCGTTATAACCCGGCGCCGGACGGGCCCGT"
  ]
  node [
    id 68
    label "GGTCCGGCCGGACCGTGTGCATACTGCGCAGTGCGGGCCCGT"
  ]
  node [
    id 69
    label "GGGGGTGCACTCCCGCTCGAGCCTGGCGCCAGGCGGGCCCGT"
  ]
  node [
    id 70
    label "GGATCAGCTGGTCCGTTCGAATCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 71
    label "GGTGCGGCCGCACCGTTCGAATCAGGCGCCTGGCGGGCCCGT"
  ]
  node [
    id 72
    label "GGTCCTGCAGGACCGAGCGCTCCCACCGGTGGGCGGGCCCGT"
  ]
  node [
    id 73
    label "GCGGCTGTAGCCGCGCTCGAGTTAAGCGCTTAACGGGCCCGT"
  ]
  node [
    id 74
    label "GGGGGCGCGCTCCCGTTCGAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 75
    label "GGAGCTGCAGCTCCGAACGTTCTCTGCGCAGAGCGGGCCCGT"
  ]
  node [
    id 76
    label "GGGGACGCGTCCCCGTTCGAATCTGCCGGCAGGCGGGCCCGT"
  ]
  node [
    id 77
    label "GGTTCCGCGGAACCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 78
    label "GGGGCTGCAGCCCCGTTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 79
    label "GGGGGTGCATCCCCGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 80
    label "TTCTTGGTCAAGGAGTCCGGACCAGTGTGCTGCCAGGCCTGG"
  ]
  node [
    id 81
    label "GGGGGTGCACTCCCGCTCGAGCCAAGCGCTTGGCGAGCTCGT"
  ]
  node [
    id 82
    label "TCTCGT--ACGGGAGTATGTATCCCGCGTGGGCGGGGCCCCG"
  ]
  node [
    id 83
    label "GGCCCAGCTGGGTCGCTCGAGCCTAGCGCTAGGAGGGCCCTT"
  ]
  node [
    id 84
    label "GGAGCTGCAGCTCCGCTCGAGCCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 85
    label "GGTCGCATGTGACCGTCTGGACCCTGCGCAGGACGGGCCCGT"
  ]
  node [
    id 86
    label "TCCTCGTACGGGGAGTATGTATCCCGCGTGGGCGGGGCCCCG"
  ]
  node [
    id 87
    label "GGTCTGGCCAGACCGTTCGAATTCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 88
    label "GGATCGGTCGATCCGTTTGAACTCGGCGCCGAGCGGGCCCGT"
  ]
  node [
    id 89
    label "TCCCGG--TCGGGAGTCCGGATTGGCATGCCGCTGGGCCTGG"
  ]
  node [
    id 90
    label "GGCCCAGCTGGGTCGCTCGAGTCTGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 91
    label "GGGGGTATGCCCCCGCTCGAGCCTTGATCAAGCTTGGCCGGG"
  ]
  node [
    id 92
    label "GGGGGCGCGCTCCCGCGATCGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 93
    label "GGATTGATCAGTCCGTTTAAATTTGGCGTCGAACGGGCCCGT"
  ]
  node [
    id 94
    label "GGAGACGCGTCTCCGTGTGCATACGGCGCCGTGCGGGCCCGT"
  ]
  node [
    id 95
    label "TCTTCCATGGGAGAGTG--CATTCCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 96
    label "TCCTCGTACGGGGAGTATGTATCCCGCGCGGGTGGGGCCCCG"
  ]
  node [
    id 97
    label "GGCCTGGCCAGGTCGCTCGAGTCTGGCGCCAGGAGGGCCCTT"
  ]
  node [
    id 98
    label "TCCCTG--CAGGGAGCT--GGTCAGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 99
    label "GGTTCGTACGAACCGTCTGGACCCTGCGCAGGACGAGCTCGT"
  ]
  node [
    id 100
    label "GGGGCTGCAGCCCCGCTCGAGCCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 101
    label "GCGGTGGCCGCCGCGCTCGAGTCCGGCGCTGGGCGGGCCCGT"
  ]
  node [
    id 102
    label "GGTTCCTAGGAACCGTGTACATCCTCCGGAGGGCGGGCCCGT"
  ]
  node [
    id 103
    label "GGTCCGTACGGACCGTC--GACCCTGCGCAGGACGAGCTCGT"
  ]
  node [
    id 104
    label "GCTCGGATCCGAGCGTG--CATGGGCCGGCTCTCGGGCCCGA"
  ]
  node [
    id 105
    label "TCCTCGTATGGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 106
    label "GCGGCTGCAGCCGCGTTTGAACCCTGCGCAGGGAGGGCCCTT"
  ]
  node [
    id 107
    label "GATCCGTACGGATCACTCGAGTCCTCCGGAGGAAGGGCCCTT"
  ]
  node [
    id 108
    label "GGAGCCGCGGCTCCGTTCGAACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 109
    label "GGGGGTGCACTCCCGTTCGAACCTTGCGCAAGGCGAGCTCGT"
  ]
  node [
    id 110
    label "TCCCTG--CGGGGAGTCCGGACTGGCATGCCGCCGGGCCTGG"
  ]
  node [
    id 111
    label "TCCCTGGCCGGGGAGCC--GGTTGGCATGCCATTGGGCCTGG"
  ]
  node [
    id 112
    label "GATCTATATAGATCGCTCGAGCCCGCCGGCGGGCCGGCCGGC"
  ]
  node [
    id 113
    label "GGAGCCATGGCTCCGCTCGAGCCTGCCGGCAGGCGGGCCCGT"
  ]
  node [
    id 114
    label "TCCTCGTACGGGGAGTATGTATTCTGCGCAGACAGGGTCCTG"
  ]
  node [
    id 115
    label "GGAGCGGCCGCTTCGCTCGAGCCCAGCGCTGGGCGGGCCCGT"
  ]
  node [
    id 116
    label "GGAACGGCCGTTTCATTTAAATTTGATGTCAAGCGGGCCCGT"
  ]
  node [
    id 117
    label "GGGGGTGCACTCCCGCTCGAGCTCGGCGCCGAGCGGGCCCGT"
  ]
  node [
    id 118
    label "CCCTGG--TCAGGGGTCTAGATTGGTGCACCACTGGGCCCAG"
  ]
  node [
    id 119
    label "TCCCTGGTCAGGGAGTC--GACCGGCGTGCTGCCAGGCCTGG"
  ]
  node [
    id 120
    label "GGTCTGGCCAGACCGTTCGAATCGTGCGCACGACGGGCCCGT"
  ]
  node [
    id 121
    label "GGGGGTGCGCTCCCGTTCGAACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 122
    label "GGCTCCGCGGAGTCGTTTAAACCCGGCGTCGGGCGGGCCCGC"
  ]
  node [
    id 123
    label "GCCCTGGCCAGGGCGTG--CATCAGGATCCTGTCGGGCCCGA"
  ]
  node [
    id 124
    label "GGTGCGGCCGCACCGTTCGAATCCGGCGCCGGACGGGCCCGT"
  ]
  node [
    id 125
    label "TCCTGT--ACAGGAGTACGTATCCCGCGTGGGTGGGGCCCTG"
  ]
  node [
    id 126
    label "GGAGCTGCAGCTCCGCTCGAGTCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 127
    label "CGGGGTGCACCCTGGCTCGAGCTTCCGCGGAAGCGGGCCCGT"
  ]
  node [
    id 128
    label "TCCTCGTATGGGGAGTATGTATCCTGTATGGGTGGGGCCCCG"
  ]
  node [
    id 129
    label "GGTGCGGCCGCACCGTTCGAATTCGGCGCCGGACGGGCCCGT"
  ]
  node [
    id 130
    label "GGTGCGGCCGCACCGTTCGAATCCGGCGTCGGGCGGGCCCGT"
  ]
  node [
    id 131
    label "TCCTTG--CAAGGAGAT--GTTTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 132
    label "TCCTCG--TGAGGAGTATGTATCTCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 133
    label "GGTCTGGCCAGACCGTTCGAATCGTGCGCATGACGGGCCCGT"
  ]
  node [
    id 134
    label "GTCGTTGCAGCGGCGTATGTATCCCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 135
    label "TCCTCGTACGGGGAGTATGTATCCTGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 136
    label "GGTCCATATGGACCGAG--CTCTCTCCGGAGAATCAGCTGAT"
  ]
  node [
    id 137
    label "GGGCCCGCGGGCCCGTGTACATGAGCCGGCTCGCGGGCCCGT"
  ]
  node [
    id 138
    label "TCCTGT--ACAGGAGTATGTATCTTGCGTGGGCGGGGCCCTG"
  ]
  node [
    id 139
    label "GGTCCCGCGGGGCCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 140
    label "TCCCTGGTCAGGGAGTCCGGACCGGCATGCTGCCGGGCCTGG"
  ]
  node [
    id 141
    label "TCCCTGGTCAGGGAGTC--GACCTGTGTGCAGCTGGGCCTGG"
  ]
  node [
    id 142
    label "GGAGCCGCGGCTCCGTTCGAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 143
    label "GTCTCCGCGGAGACGGGGCCCCTCACCGGTGAGCGGGCCCGC"
  ]
  node [
    id 144
    label "TCGTTG--CAACGGGTGTGTATCCCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 145
    label "GAGGGTGCACTCTCGCGCGCGCACGGCGCCGTGCGGGCCCGT"
  ]
  node [
    id 146
    label "TCCTCGTACGGGGAGTATGTATCCCGCGCGGGCAGGGCCCTG"
  ]
  node [
    id 147
    label "TCCTCGTACGGGGAGTA--TATTCCGCGCGGACGGGGCCCTG"
  ]
  node [
    id 148
    label "GCGGTGGCCGCCGCGCTCGAGTCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 149
    label "CCCTAG--TTAGGGGTCTAGATCGGCATGCTGCTGGGCCCAG"
  ]
  node [
    id 150
    label "GGACTGGCCAGTCCGTTCGAATCTGGCGCCAGGCGAGCTCGT"
  ]
  node [
    id 151
    label "GGAGCGGCCGTTCCGTTCGAATTCGGCGCCGAGCGGGCCCGT"
  ]
  node [
    id 152
    label "GGCCCAGCTGGGTCGCTCGAGCCCAGCGCTGGGAGGGCCCTT"
  ]
  node [
    id 153
    label "TCCTGG--TTGGGAGTC--GACCAGCATGCTGCCAGGCTTGG"
  ]
  node [
    id 154
    label "GGAGCGGCCGCTCCGTTCGAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 155
    label "GTCCGGATCCGGGCGTG--CATGAGCCGGCTCTCGGGCCCGG"
  ]
  node [
    id 156
    label "GGCCCAGCTGGGTCGTTCGAACCTAGCGCTAGGAGGGCCCTT"
  ]
  node [
    id 157
    label "GGGGAGTACTTCCCGCTCGAGCCCGGCGTCGGGCGGGCCCGT"
  ]
  node [
    id 158
    label "GGGGGTGCACTCCCGCTCGAGCCAAGCGTTTGGCGAGCTCGT"
  ]
  node [
    id 159
    label "GGGGATGCATCCCCGTGTACACCTGCCGGCAGGCGGGCCCGT"
  ]
  node [
    id 160
    label "TCCTTGTACGGGGAGTGCGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 161
    label "TCCTCGTACGGGGAGTATGTGTCCCGTGCGGGCGGGGCCCCG"
  ]
  node [
    id 162
    label "GCCCTGGCCAGGGCGTG--CATCAGGATCCTGTCGGGCCCGG"
  ]
  node [
    id 163
    label "GTCTCTGCGGAGGCGTATGTATCATGGCCGTGCCGGGCCCGG"
  ]
  node [
    id 164
    label "TCTCTGGCTGGGGAGTTCGGATTGGCATGCTGTCAGGCCTGG"
  ]
  node [
    id 165
    label "GCCCGGGCTCGGGCGTG--CATCGACCGGTCGGCGGGCCCGC"
  ]
  node [
    id 166
    label "GGAGTTGCAACTCCGCTCGAGTCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 167
    label "TCCCGGGCCTGGGAGTCTGGATTGGCATGCTGTCAGGCTTGG"
  ]
  node [
    id 168
    label "GTCGTTGCAACGGCGTATGTATTCCGCGCGGACCGGGCCCGG"
  ]
  node [
    id 169
    label "GTCCTG--CAGGGCGCTCGAGCCTCGCGCGAGCTGGGCCCAG"
  ]
  node [
    id 170
    label "GGAGTGGTCACTCCGTTATAACTCCGCGCGGAGCGGGCCCGT"
  ]
  node [
    id 171
    label "GGTCCGGCCGGATCGTTCGAATCCAGCGCTGGGAGGGCCCTT"
  ]
  node [
    id 172
    label "GGTCCTATAGGACCGTG--CACCCTGCGCAGGGCCGGCCGGC"
  ]
  node [
    id 173
    label "GCGGGTGCACTCGCGCTCGAGCCCGGCGCCGGACGGGCCCGT"
  ]
  node [
    id 174
    label "GGATCGGCCGGTCCGTTCGAATTCGGTACCGAACGGGCCCGT"
  ]
  node [
    id 175
    label "GGCCCGGTCGGGTCGTTTGAATCCGCCGGCGGAGGGGCCCCT"
  ]
  node [
    id 176
    label "GGCCCTGCGGGGTCGCTCGAGTCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 177
    label "GCCCCCGCGGGGGCGTATGTATCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 178
    label "TCCCTGGTCAGGGAGCT--GGTTGGTGTGCCACCAGGCCTGG"
  ]
  node [
    id 179
    label "GGTCCCGCGGGACCGTG--CACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 180
    label "GTCCGGATCCGGGCGTG--CATGAGCCGGCTCCCGGGCCCGG"
  ]
  node [
    id 181
    label "GCCCCGGCCGGGGCGTATGTATCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 182
    label "GGTCTGGCCAGACCGTTCGAATCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 183
    label "GGAGCGGCCGTTCCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 184
    label "GGTCTGGCCAGACCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 185
    label "GGTCGCATGCGACCGTCCGGACCCTGCGCAGGGCGGGCCCGC"
  ]
  node [
    id 186
    label "CCTCGT--ACGGGGGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 187
    label "GGGGGAGCTCTCCCGTTATAACTCGCCGGCGAGCGGGCCCGT"
  ]
  node [
    id 188
    label "GGTCCCGCGGGACCGTG--CACTCGCCGGCGAGCGGGCCCGT"
  ]
  node [
    id 189
    label "GGCCCAGCTGGGTCGCTCGAGCCCGCCGGCGGGTGAGCTCAT"
  ]
  node [
    id 190
    label "GGGGGTGCACCCTCGCTCGAGCTCGGATCCGAGCGGGCCCGT"
  ]
  node [
    id 191
    label "GGAGGCGCGCTTCCGTGTACATCAGCCGGCTGGCGGGCCCGT"
  ]
  node [
    id 192
    label "TCCTCATATGGGGAGTATGTACCCCGCGTGGGCGGGGCCCCG"
  ]
  node [
    id 193
    label "GGCCCGGCCGGGTCGTTCGAACCCGCCGGCGGGTGAGCTCAT"
  ]
  node [
    id 194
    label "GGGGGCGCGTCCCCGTTCGAACCTGGCGTCAGGCGAGCTCGT"
  ]
  node [
    id 195
    label "GGAGTGGCCACTCCGTTCGAATCTGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 196
    label "GGGGGTGCATCCCCACTCGAGTCCTGTACAGGGCGAGCTCGT"
  ]
  node [
    id 197
    label "GCCCGGGCCCGGGCGTGTACATGGGGCGCCCTTCGGGCCCGG"
  ]
  node [
    id 198
    label "TCCCTGGTCAGGGAGTC--GACCTGTGTGCAGCCAGGCCTGG"
  ]
  node [
    id 199
    label "GGAGCGGCCGCTCCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 200
    label "GGGGTGGCCACCCCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 201
    label "GAGGGCGCGCTCTCGCGATCGCACGGCGCCGTGCGGGCCCGT"
  ]
  node [
    id 202
    label "GGCTCAGCTGAGTCGCTCGAGTCCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 203
    label "GGAGGTGCACTTCCGCTCGAGTCTTGCGCAAGGCGAGCTCGT"
  ]
  node [
    id 204
    label "TCCTTGGCCAAGGAGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 205
    label "TCCCTGGTCAGGGAGTCCGGACTGGTGTGCCGTCGGGCCTGG"
  ]
  node [
    id 206
    label "GCAGCGGCCGTTGCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 207
    label "TCCTGG--CCGGGAGTC--GATCTGTGCACAGCTGGGCCTGG"
  ]
  node [
    id 208
    label "TCCCAGGCCTGGGAGCCTAGGTCAGCATGCTGTTGGGTCTGG"
  ]
  node [
    id 209
    label "GCGGATGCATTCGCGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 210
    label "GGCCCCATGGGGTCGCGATCGCCCTCCGGAGGACGGGCCCGT"
  ]
  node [
    id 211
    label "GGAGCCGCGGCTCCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 212
    label "GGTCCGGCCGGACCGTTCGAATCCTGCGCAGGGCGGGCCCGC"
  ]
  node [
    id 213
    label "GGAGTTGTAACTCCGCTCGAGCCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 214
    label "GGTTCT--AGAACCGTCTGGACCCTGCGCAGGACGAGCTCGT"
  ]
  node [
    id 215
    label "CCTGGG--CCTGGGGTATGTATCGCGTATGCGCCGGGCCCGG"
  ]
  node [
    id 216
    label "GGGGACGCGTCCCCGTGCGCATCCGGTACCGGGCGGGCCCGT"
  ]
  node [
    id 217
    label "GGTCAG--CTGACCGTA--TACTCTCCGGAGAGCGGGTCCGT"
  ]
  node [
    id 218
    label "GGGACAGCTGTCCCGTTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 219
    label "GGGGGCGCGCTCCCGCGATCGCCTGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 220
    label "GGTGACGCGTCGCCGTTCGAGCGGGGATCCTCGCGGGCCCGT"
  ]
  node [
    id 221
    label "TTCTCGGCCGGGGAGTATGTATCGCGTATGCGCCGGGCCCGG"
  ]
  node [
    id 222
    label "GGCCCAGCTGGGTCGCGCGCGTCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 223
    label "TCCTGA--TCGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 224
    label "GGAGGCGCGCCTCCGTGTACATCGGCCGGCCGGCGGGCCCGT"
  ]
  node [
    id 225
    label "GGTCCGGCCGGACCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 226
    label "GCGGCCGCGGCCGCGTTTGAATCCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 227
    label "TCCGCGATCGCGGAGTTTGAATGGCGCGTGCCCGGGGCCCCG"
  ]
  node [
    id 228
    label "TCCTTGTACAAGGGGTATGTATCCTGCGCAGGCGGGGCCCCG"
  ]
  node [
    id 229
    label "GCATGG--TCATGCGTTCGAATCTCGCGCGGGCTGGGCCCAG"
  ]
  node [
    id 230
    label "GGGACTGCAGTCCCGCTCGAGTCTTGCGCAAGGCGGGCCCGT"
  ]
  node [
    id 231
    label "GGTCTGGCCAGACCGTTCGAATTCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 232
    label "TCCTCGTACGGGGAGTATGTATTCTGCGCAGACAGGGCCTTG"
  ]
  node [
    id 233
    label "GGAGCTGCAGCTCCGTGTACATTCTGCGCAGAGCGGGCCCGT"
  ]
  node [
    id 234
    label "GGGGTGGCCACCCCGTTATAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 235
    label "GGGGCCGCGGCCTCGCTCGAGTCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 236
    label "CCTCGT--ACGGGGGTATGTATTCTGCGCAGACAGGGCCCTG"
  ]
  node [
    id 237
    label "TCCCTGGTTGGGGAGTCTGGATCGGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 238
    label "TCTCGT--ACGGGAGTATGTATTCCGCGCGGATGGGGCCCCG"
  ]
  node [
    id 239
    label "GGTTCGGCCGAACCGTGTACATCTTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 240
    label "GGTTCTGCAGAACCGTG--CACTCGCCGGCGAGCGGGCCCGT"
  ]
  node [
    id 241
    label "GGAGCCGCGGCTCCGTTATAACCCGGCGTCGGGCGGGCCCGT"
  ]
  node [
    id 242
    label "GGATCCATGGATTCGCTTAAGTTCATCGATGGATCAGCTGAT"
  ]
  node [
    id 243
    label "GGCCCCGCGGGGTCGCGCGCGCCCGCCGGCGGGCCGGCCGGT"
  ]
  node [
    id 244
    label "GGATTGGCCAGTCCGTTCGAATCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 245
    label "GCCCGGGCCCGGGCGTGTGCATGGGGCGCCCCCCGGGCCCGG"
  ]
  node [
    id 246
    label "GGTGTGGCCACACCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 247
    label "GTTCGGATCCGAACGTG--CATGAGCCGGCTCTCGGGCCCGG"
  ]
  node [
    id 248
    label "GCGGGTGCACTCGCGCTCGAGTCTGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 249
    label "GAGGGTGCACTCTCGCGATCGCACGGCGCCGTGCGGGCCCGT"
  ]
  node [
    id 250
    label "TCTCTGGCCAGAGAGTATGTATCGCGCGTGCGCCGGGCCCGG"
  ]
  node [
    id 251
    label "GGATTG--CAGTCCGTTCGAGCCCGCCGGCGGGCGGGCCTGT"
  ]
  node [
    id 252
    label "GGTGCATATGCACCGAGCGCTCCTTGCGCAAGACGGGCCCGT"
  ]
  node [
    id 253
    label "TCCCTGGCTAGGGACCT--AGGCAGTGTGCTGCCAGGCCTGG"
  ]
  node [
    id 254
    label "TCCTCT--AGGGGAGTATGTATTCTGCGCAGACAGGGCCCTG"
  ]
  node [
    id 255
    label "GTTGTTGCAATGGCGTATGTATCCCGCGCGGGCCGGGCTCGG"
  ]
  node [
    id 256
    label "GTCGTTGCAACGGCGTATGTATCCTGCGCAGGCCGGGCCCGG"
  ]
  node [
    id 257
    label "GGTCGCATGTGACCGTCTGGACCCTGCGCAGGGCGGGCCCGC"
  ]
  node [
    id 258
    label "TCCCTGGTCAGGGAGTCTGGATTGGCATGCTACTGGGCCTGG"
  ]
  node [
    id 259
    label "GGTTCGGCCGGACCGTTCGAATCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 260
    label "TCTTCCATGGGAGAGTATGTATCGAGCGCTCGCCGGGCCCGG"
  ]
  node [
    id 261
    label "GGGGAAATTTCCCCGCTCGAGTCTGGTGCCAGGCGGGCCCGT"
  ]
  node [
    id 262
    label "TCCTCGATCGGGGAGTATGTATTCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 263
    label "TCCTGT--ACGGGAGTATGTATTCTGCGCAGACAGGGCCCTG"
  ]
  node [
    id 264
    label "GTCGTTGCAACGGCGTATGTATCCCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 265
    label "GGAGTGGCCGCTCCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 266
    label "GGATCGGCCGGTCCGTTCGAATCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 267
    label "TCTCCTTAGGGAGAGTATGTACCAAGCGCTTGCCGGGCCCGG"
  ]
  node [
    id 268
    label "GGTGCGTACGCACCGTTCGAATCCTGCGCAGGACGGGCCCGT"
  ]
  node [
    id 269
    label "GGAGCCGCGGCTCCGTTATAACCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 270
    label "TCCTCT--GGGGGAGTATATATCCCACGTGGGTGGGGCCCTG"
  ]
  node [
    id 271
    label "GCATTG--CAATGCGTTCGAATCTTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 272
    label "TCCCTGGTCGGGGATCC--GGACGGCGTGCTGCCAGGCCTGG"
  ]
  node [
    id 273
    label "GCCCAGGCCTGGGCGTG--CATATTGCGCAATTCGGATCCGA"
  ]
  node [
    id 274
    label "GGCCTAGCTAGGTCGCTCGAGTCCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 275
    label "GGGGTCGCGGCCCCGTTATAACCCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 276
    label "TCTTCCGCGGGAGAGTATGTATCAAGCGCTTGCCGGGCCCGG"
  ]
  node [
    id 277
    label "GGAGCCGCGGCTCCGTTCGAACCTGGCGCCAGGCGAGCTCGT"
  ]
  node [
    id 278
    label "GGGGGCGCGCTCCCGTTCGAACCCGGGTCCGGGCGGGCCCGT"
  ]
  node [
    id 279
    label "GGGGGTGCACTCCCGCTCGAGCCATGCGCATGGTGAGCTCAT"
  ]
  node [
    id 280
    label "GGTCCCGCGGGACCGAGCGCTCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 281
    label "GGGGTGGCCACCCCGTTCGAACCTTGCGCAAGGCGGGCCCGT"
  ]
  node [
    id 282
    label "TCCCGG--CCGGGAGTTCGGATCAGTGTGCTGTCAGGCCTGA"
  ]
  node [
    id 283
    label "GAACTAGCTAGTTCCTT--GAGCTTCCGGAAGGCCGGCCGGT"
  ]
  node [
    id 284
    label "GGCCCGGCCGGGTCGTTCGAATCCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 285
    label "GGAGCGGCCGCTCCGTTCGAATTCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 286
    label "GGTCCAGCTGGACCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 287
    label "GAAGTGGTCACTTCGTTCGAACCTGGCGCCAGGCGGGCCCGT"
  ]
  node [
    id 288
    label "GGGATTGCAATCCCGTTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 289
    label "GGTCTGGCCAGACCGTTCGAATTCGCCGGCGAGCGGGCCCGT"
  ]
  node [
    id 290
    label "TCCCTGGCCAGGGACCT--AGGCAGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 291
    label "GGGGGCGCGCTCCCGTGTACATCGGCCGGCCGGCGGGCCCGT"
  ]
  node [
    id 292
    label "GGGGTCGCGGCCCCGCTCGAGCTCGGCGCCGAGCGAGCTCGT"
  ]
  node [
    id 293
    label "GGTCCCGCGGGACCGTGTACACCCTGCGCAGGGTGGGCCCAT"
  ]
  node [
    id 294
    label "GGAGCCGCGGCTCCGTTTGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 295
    label "TCCTCGATCGGGGGATATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 296
    label "GCGGCGGCCGCCGCGTTCGAATCCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 297
    label "GGGGTGGCCGCCCCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 298
    label "GGAGCGGCCGTTCCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 299
    label "TGCTCT--AGGGCAGCTCGAGCCTCGCGCGAGCTGGGCCCAG"
  ]
  node [
    id 300
    label "GGAGTGGCCACTCCGTTCGAATCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 301
    label "GCCCGGGCCCGGGCGTG--CATCGGGATCCCGTCGGGCCCGA"
  ]
  node [
    id 302
    label "GGTCCTGCAGGATCGAGCGCTCCCACCGGTGGGCGGGCCCGT"
  ]
  node [
    id 303
    label "GGTTCCGCGGAACCGTG--CACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 304
    label "TCCCTGGTCGGGGAGTCCGGACTGGCGTGCCGCCGGGCCTGG"
  ]
  node [
    id 305
    label "TCCTCGTATGGGGAGTATGTATCCTGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 306
    label "GGAGCCGCGGCTCCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 307
    label "GTCGTTGCAGCGGCGTATGTATCCCGCGCGGGCCGGGCTCGG"
  ]
  node [
    id 308
    label "GCCCCGGCCGGGGCGTTCGGATCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 309
    label "GGTGCGGCCGCACCGTTCGAATCTGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 310
    label "TCCCTGGTCAGGGAGTCTGGATCAGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 311
    label "GCAGCGGCCGCTGCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 312
    label "GTTCCGCGCGGAACACTCGAGTCCTCCGGAGGAGGGGCCCCT"
  ]
  node [
    id 313
    label "GCGGGTGCACTCGCGCTCGAGCCTGGCGCCAGGCCGGCCGGT"
  ]
  node [
    id 314
    label "TCCCTG--TGGGGAGTCCGGACTGGTGTGCCGCCAGGCCTGG"
  ]
  node [
    id 315
    label "GGAGCCGCGGCTCCGTTATAACCCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 316
    label "TCTTCGATCGGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 317
    label "GCCCGGGCCCGGGCGTGTACATCGGGCGCCCGTCGGGCCCGG"
  ]
  node [
    id 318
    label "TCCCGG--CCGGGAGCCTGGGTTGGTGTGCTGTCAGGCCTGG"
  ]
  node [
    id 319
    label "GCCCGGGCCCGGGCGTGTACATCGGGCGCCCGTCGGGCCCGA"
  ]
  node [
    id 320
    label "GCGGGAGCTCTCGCGTTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 321
    label "GGCCTGGCCAGGTCGTTCGAACCCGCCGGCGGGTGGGCCCAT"
  ]
  node [
    id 322
    label "GGCCCGGTCGGGTCGTTCGAACCTAGCGCTAGAGGGGCCCCT"
  ]
  node [
    id 323
    label "GGATCGGTCGGTCCGTGCGCACTCGCCGGCGGGCCGGCCGGC"
  ]
  node [
    id 324
    label "TCCCGA--TCGGGAGTATGTATCCCGCGTGGGCGGGGTCCCG"
  ]
  node [
    id 325
    label "GCCCTGGCCAGGGCGTG--CATAAGCCGGCTTTCGGATCCGG"
  ]
  node [
    id 326
    label "GGTTCAGCTGGACCGTA--TACTCTCCGGAGAGCGGGCCCGT"
  ]
  node [
    id 327
    label "TCCCTGGTCGGGGAGTCCGGACCGGCGTGCCGCCAGGCCTGG"
  ]
  node [
    id 328
    label "GATTCGGCCGGATCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 329
    label "GGGGTTGCAACCCCGCTCGAGTCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 330
    label "GGGGATATATCCTCGTGTACACCTTGGCCAAGACGGGCCCGT"
  ]
  node [
    id 331
    label "TCTCGT--ATGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 332
    label "GCCCTGGCCAGGGCGTG--CATCGGGATCCCGTCGGGCCCGG"
  ]
  node [
    id 333
    label "GGTCTGGCCAGATCGTTCGAATCGTGCGCATGACGGGCCCGT"
  ]
  node [
    id 334
    label "GGGGACGCGTCCCCGTTCGAACCCGGCGTCGGGCGGGCCCGT"
  ]
  node [
    id 335
    label "GGGTCTGCAGACCCGTTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 336
    label "TCCTCGTACGAGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 337
    label "GGTCCTGCAGGACCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 338
    label "GGGGCGGCCGCCCCGTTATAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 339
    label "GGAGCTGCAGCTCCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 340
    label "TCCCGT--ACGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 341
    label "GGACCGGCCGGTCCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 342
    label "GCGGCGGCCGCCGCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 343
    label "GGAGCGGCCGCTCCGTTCGAATTCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 344
    label "GGGGACGCGTCCCCGTTCGAACCTGCCGGCAGGCGGGCCCGT"
  ]
  node [
    id 345
    label "TTGTTG--CAACGAGTATGTATCCCGCGCGGGCCGGGCCTGG"
  ]
  node [
    id 346
    label "GGAGGTGCACCTCCGCGTACGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 347
    label "TTCTGG--CTAGAAGTCTGGATCAGCATGCTGCTGGGCCTGG"
  ]
  node [
    id 348
    label "TCCCTGGTCAGGGAGTCTGGACTGGTGTGCCGCCAGGCCTGG"
  ]
  node [
    id 349
    label "GGGGGTGCACTCCCGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 350
    label "TCCTGT--ACGGGAGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 351
    label "GGCGCAGCTGCGTCGTTCGAATCCAGCGCTGGGAGGGCCCTT"
  ]
  node [
    id 352
    label "GCAGTGGCCACTGCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 353
    label "TCCCTGGTCAGGGAGTCCGGACTGGCGTGCCATCGGGCCTGG"
  ]
  node [
    id 354
    label "GGTGCGGCCGCACCGTTCGAACTCGGCGCCGAACGGGCCCGT"
  ]
  node [
    id 355
    label "GGTCCTGCAGGACCGTGTACATCCTCTAGAGGGCGGGCCCGT"
  ]
  node [
    id 356
    label "TCCTCGGCCGGGGAGTATGTATCGCGTATGCGCCGGGCCCGG"
  ]
  node [
    id 357
    label "GGGGACGCGTCCCCGTGATCATCCGGTACCGGGCGGGCCCGT"
  ]
  node [
    id 358
    label "GGTTCGGCCGGACCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 359
    label "TCCCTGGCCAGGGAGTC--GGTTGGCATGCTGTCAGGCCTGG"
  ]
  node [
    id 360
    label "TCCTCGATCGGGGAGTATGTATCTCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 361
    label "GGTTCCGCGGAACCGCTCGAGTCTTGCGCAAGGCGAGCTCGT"
  ]
  node [
    id 362
    label "GGAGCAGCTGCTCCGTCTGGATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 363
    label "GGCCTCATGGGGTCGCTCGAGCCCGCCGGCGGGAGGGCCCTC"
  ]
  node [
    id 364
    label "TCCCTGGTCGGGGAGTCCGGACCGGCGTGCTGCCGGGCCTGG"
  ]
  node [
    id 365
    label "TCCTCGTACGGGGAGTATGTATCCTGCGCAGGCAGGGTCCTG"
  ]
  node [
    id 366
    label "GGTCCGGCCGGACCGTGTGCATTCTGCGCAGAGCGGGCCCGT"
  ]
  node [
    id 367
    label "TCCTGG--TCAGGAGTC--GACCTGCGCGCAGCCAGGCCTGG"
  ]
  node [
    id 368
    label "GGTTCCATGGGACCGTCTGGACCCTCCGGAGGGCGGGCCCGC"
  ]
  node [
    id 369
    label "GGTTCCATGGAACCGTCTGGACCCTGCGCAGGACGGGCCCGT"
  ]
  node [
    id 370
    label "GGTTCCATGGAACCGTGTACATTCTCCGGAGGGCGGGCCCGT"
  ]
  node [
    id 371
    label "GGTTCCGCGGGACCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 372
    label "TCTCGT--ACGGGAGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 373
    label "GGTGTGGCCGCACCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 374
    label "GCAGCGGCCGCTGCGTTCGAATCCGGCGCCGGACGGGCCCGT"
  ]
  node [
    id 375
    label "TCCTCATATGGGGAGTATGTATCTTACGTGGGTGGGGCCCCA"
  ]
  node [
    id 376
    label "GGTCCATATGGACCGAG--CTCCCTCCGGAGGGCGGGCCCGC"
  ]
  node [
    id 377
    label "TCCCTGGCCAGGGAGTC--GGCCAGCATGCTGTTGGGCCTGG"
  ]
  node [
    id 378
    label "GGTTCTGCAGAACCGTG--CACTCGCCGGCGAGCGGGTCCGT"
  ]
  node [
    id 379
    label "GGGGTCGCGATCCCGTGTACACCTGGCGCCGGGTGGGCCCAT"
  ]
  node [
    id 380
    label "CCCTGG--TCAGGGGTCTAGATTGGTGTGCCACTGGGCCCGG"
  ]
  node [
    id 381
    label "TCTCGT--ACGGGAGTATGTATTCTGCGCAGACAGGGTCCTG"
  ]
  node [
    id 382
    label "TCTTCGTATGAGGAGTATGTATTCTGCGCAGATGGGGCCCTG"
  ]
  node [
    id 383
    label "TCTTCATATGGGGAGTA--TATCCTGTGTGGGCAGGGTCCTG"
  ]
  node [
    id 384
    label "GCCCCGGCCGGGGCGTGTGCATCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 385
    label "GGTCCGGCCGGACCGTTCGAATCATGCGCATGGCGGGCCCGT"
  ]
  node [
    id 386
    label "TCCCGG--CCGGGAGAT--GTTCGCGTATGCGCCGGGCTCGG"
  ]
  node [
    id 387
    label "TCCCTGGTCGGGGAGTCCGGACTGGCGTGCTGCCAGGCCTGG"
  ]
  node [
    id 388
    label "GCCGTAGCTACGGCGTCTGGATAGGGCGCCCTCCGGGCCCGG"
  ]
  node [
    id 389
    label "GGTCTCGCGAGACCGTGTACATTCTGCGCAGAGCGGGCCCGT"
  ]
  node [
    id 390
    label "TCCTGT--ACGGGAGTATGTATCCTGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 391
    label "GGGACTGCAGTCCCGTTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 392
    label "GCGGTGGCCACCGCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 393
    label "TCCTGT--ACAGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 394
    label "GGTCCTGCAGGACCGTGATCATCCTCTAGAGGGCGGGCCCGT"
  ]
  node [
    id 395
    label "GCGGGTGCACTCGCGCTCGAGCCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 396
    label "GGCCTGGCCAGGTCGTTCGAATCCAGCGCTGGGTCGGCCGAT"
  ]
  node [
    id 397
    label "GGTCCTGCGGGACCGTGTACATCCTGCGCAGGGCCGGCCGGT"
  ]
  node [
    id 398
    label "TCCCTGGTCGGGGAGCT--GGTCAGCATGTTGCCAGGCCTGG"
  ]
  node [
    id 399
    label "GGGACCGCGGTCCCGTTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 400
    label "GCCGCGGCCGCGGCGTCTGGATGGGGCGCCCTCCGGGCCCGG"
  ]
  node [
    id 401
    label "GGTGCGGCCGCACCGTTCGAATCCTGCGCAGGACGGGCCCGT"
  ]
  node [
    id 402
    label "GGAGCGATCGTTCCATTTAAATTTGGCGTCAAGCGGGCCCGT"
  ]
  node [
    id 403
    label "GGCCCGGCCGGGTCGTTCGAATCCAGCGCTGGGACGGCCGTT"
  ]
  node [
    id 404
    label "GGTGTGTACACACCGTTCGAATCCTGCGCAGGACGAGCTCGT"
  ]
  node [
    id 405
    label "GGCCTAGCTAGGTCGCTCGAGTTCGGCGCCGAGAGGGCCCTT"
  ]
  node [
    id 406
    label "GCCCTGGCCAGGGCGTG--CATCAGGCGCCTGTCGGGCCCGG"
  ]
  node [
    id 407
    label "GGAGCCGCGGCTCCGTTCGAACTCGGCGCCGAGCGGGCCCGT"
  ]
  node [
    id 408
    label "GGCCCTGCAGGGTCGCGCGCGCCCGCCGGCGGGCGAGCTCGT"
  ]
  node [
    id 409
    label "GGGGATGCGTCCCCGTGTACACCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 410
    label "GCATTGGCTAATGCGTTCGAATCTTGCGCAGGCTGGGCTTGG"
  ]
  node [
    id 411
    label "GCCCTGGCCAGGGCGTG--CATAAGCCGGCTTTCGGGCCCGA"
  ]
  node [
    id 412
    label "GGTCCATATGGACCGAG--CTCCCTCCGGAGGGTGGGCCCAC"
  ]
  node [
    id 413
    label "TCCCGG--CTGGGAGTCTGGACCGGCATGCTGTCGGGCCTGG"
  ]
  node [
    id 414
    label "GGGGTA--TGCCCTGCTCGAGCTTTGATCAAGTCTGGCCAGG"
  ]
  node [
    id 415
    label "GGTGTGGCCATACCGTTCGAATCATGCGCATGGCGGGCCCGT"
  ]
  node [
    id 416
    label "GGTGTGGCCATACCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 417
    label "GGGGGCGCGCTCCCGTTCGAACCTTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 418
    label "GGTTCCGCGGAACCGTG--CACTCGCCGGCGAGCGGGCCCGT"
  ]
  node [
    id 419
    label "GGAACTGCAGTTCCGTGTACACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 420
    label "TCCCTGGTCGGGGAGTCTGGATCAGCATGCTGCCGGGCCTGG"
  ]
  node [
    id 421
    label "TCCCAGATCTGGGAGTTTGAATACCGTATGGTCAGGGCCCTG"
  ]
  node [
    id 422
    label "GGAGCGGCCGCTCCGTTCGAATTCGGCGCCGAGCGGGCCCGT"
  ]
  node [
    id 423
    label "GGGGTTGCAACCCCGCTCGAGTCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 424
    label "GGGGTGTACATCCCGCTCGAGCCCGGCGTCGGGCGAGCTCGT"
  ]
  node [
    id 425
    label "GGAGCGGCCGTTCCGTTCGAATCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 426
    label "GAGGCTGCGGTCTCGCG--CGCCCCGGCCGGGGCCGGCCGGT"
  ]
  node [
    id 427
    label "GCCCGGGCCCGGGCGTG--CATCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 428
    label "GGTCTCGCGAGACCGTGTACACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 429
    label "GGGGGTGCACTCCCGCTCGAGCCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 430
    label "GGTCCCGCGGGACCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 431
    label "GTCGCA--TGTGACGTCTGGACCCTGCGCAGGGCGGGCCCGC"
  ]
  node [
    id 432
    label "GCAGCGGCCGCTGCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 433
    label "TCCTCGTACGGGGAGTACGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 434
    label "GGGATTGCAGTCCCGTTCGAGCCTGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 435
    label "GGCCCAGCTGGGTCGTTTGAATCCGCCGGCGGGTCGGCCGAT"
  ]
  node [
    id 436
    label "TCCCTGGCTAGGGAGCT--AGCTGGCATGCTGTCAGGCCTGG"
  ]
  node [
    id 437
    label "GGCTCAGCTGAGTCGCTCGAGCCCGCCGGCGGGTGGGCCCAT"
  ]
  node [
    id 438
    label "TCCTGT--ACGGGAGTATGTATTCTGCGCAGACAGGGCCTTG"
  ]
  node [
    id 439
    label "TCCTCGTACGAGGAGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 440
    label "GGGGGTGCATCCCCACTCGAGTCCTGTACAGGGTGGGCCCAT"
  ]
  node [
    id 441
    label "GGGGACGCGTCCCCGCTCGAGCCTGCCGGCAGGCGGGCCCGT"
  ]
  node [
    id 442
    label "GGAGCTGCAGCTCCGTG--CACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 443
    label "GGGGTGGCCATCCCGCTCGAGCTCTGCGCAGAGCGGGCCCGT"
  ]
  node [
    id 444
    label "TCCGCGATCGCGGAGTTTGAATCGCGCGTGCGCGGGGCCCCG"
  ]
  node [
    id 445
    label "GGCCCTGCAGGGTCGCGCGCGCCCGCTGGCGGGCGGGCCCGT"
  ]
  node [
    id 446
    label "GGGGGCGCGTCCCCGCTCGAGCCTGGCGCCAGGCCGGCCGGT"
  ]
  node [
    id 447
    label "TCCTGG--CCAGGAGTTCGGATCGGCATGCTGGCAGGCCTGC"
  ]
  node [
    id 448
    label "GGTCTAGCTGGACCGTGTACATCCTCTAGAGGGCGGGCCCGT"
  ]
  node [
    id 449
    label "GGTCCGGCCGGACCGTGTACATCCAGTACTGGGCGGGCCCGT"
  ]
  node [
    id 450
    label "GGCCCAATTGGGTCGCTCGAGCCCGCCGGCGGGCGGGCCCGC"
  ]
  node [
    id 451
    label "GCGGACGCGTCCGCGCTCGAGTCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 452
    label "TCCCGG--CCGGGAGCCTGGGTCAGCATGCTGTCAGGCCTGA"
  ]
  node [
    id 453
    label "GGTGCGGCCGCACCGTTCGAATTTGGCGCCAGGCGGGCCCGT"
  ]
  node [
    id 454
    label "GGGGTTGCAACCCCGCTCGAGTCTGGCGCCAGGCGGGCCCGT"
  ]
  node [
    id 455
    label "GCCCCGGCCGGGGCGTATGTATGCGGCGCCGCCCGGGCCCGG"
  ]
  node [
    id 456
    label "GGGATTGCAGTCCCGTTTGAGCCCGCCGGCGGGCGGGCTCGT"
  ]
  node [
    id 457
    label "GAGCCG--CGGCTCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 458
    label "TCCTCGTACGGGGGGTATGTATTCTGCGCAGACAGGGCCCTG"
  ]
  node [
    id 459
    label "GCCTTGGCCAAGGCGTG--CATTGGGCGCCCGTCGGGCCCGG"
  ]
  node [
    id 460
    label "TTCCTGGTCAGGAAGTT--GATTGGTATGCTGCCAGGCCTGG"
  ]
  node [
    id 461
    label "TCCTCGTGCGGGGAGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 462
    label "GCCCCGGCCGGGGCGTG--CATCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 463
    label "GGCTCGGCCGAGTCGTTCGAATCCAGCGCTGGGAGGGCCCTT"
  ]
  node [
    id 464
    label "GGGGGTGCACTCCCGCTCGAGCCTTGTACAAGGCGGGCCCGT"
  ]
  node [
    id 465
    label "GGGGCTGCAGCCCCGCTCGAGCCTGGCGTCAGGCGGGCCCGT"
  ]
  node [
    id 466
    label "GGCCCCGCGGGGTCGCTCGAGCCCGCCGGCGGGACGGCCGTT"
  ]
  node [
    id 467
    label "GGGGCCGCGGCCCCGTTATAACCCGGCGTCGGGCGGGCCCGT"
  ]
  node [
    id 468
    label "TCCTCGTACGAGGAATATGTATCCTGCGCAGGCGGGGCCCCG"
  ]
  node [
    id 469
    label "GGCCAG--CTGGTCGTTTGAATCCGCCGGCGGGTCGGCCGAT"
  ]
  node [
    id 470
    label "GGAGCAGCTGCTCCGTTCGAACCCGGCGTCGGGCGGGCCCGT"
  ]
  node [
    id 471
    label "TCCTCT--AGGGGATAT--GTACCCGCGCGGGCAGGGCCCTG"
  ]
  node [
    id 472
    label "GGCCCCGCGGGGCCGTGTACACCCCGCGTGGGGCGGGCCCGT"
  ]
  node [
    id 473
    label "TCCTCGTACGGGGAGTGTGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 474
    label "GGGGTATATATCCCGCTCGAGCCCGGCGTCGGGCGGGCCCGC"
  ]
  node [
    id 475
    label "GGCCCAGCTGGGTCGTTCGAACCCAGCGCTGGGAGGGCCCTT"
  ]
  node [
    id 476
    label "GGTCTAGCTAGACCGTA--TACCCTCTGGAGGGCGGGCCCGT"
  ]
  node [
    id 477
    label "GTTTCTGCAGGGACGCGCGCGCTTTGGCCGAAGGTGGCCATC"
  ]
  node [
    id 478
    label "GGGATTGCAGTCCCGTTCGAGCCCGCCGGCGGGTGGGCCCGT"
  ]
  node [
    id 479
    label "GGGGCCGCGGCCCCGTTCGAACCTGGCGCCAGGCGGGCCCGT"
  ]
  node [
    id 480
    label "GCCCTGGCCAGGGCGTG--CATTGGGCGCCCGTCGGGCCCGG"
  ]
  node [
    id 481
    label "GGGGGCGCGTCCCCGTTCGAACCTGGCGCCAGGCGAGCTCGT"
  ]
  node [
    id 482
    label "GGGGATGCATCCTCGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 483
    label "GGAGCCGCGGCTCCGTTATAACCCGGCGTCGGGCGAGCTCGT"
  ]
  node [
    id 484
    label "TCCCTGGTCAGGGAGTCCGGACTGGCGTGCTGCCAGGCCTGG"
  ]
  node [
    id 485
    label "TCCCTGGTCAGGGAGCT--GGCCGGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 486
    label "TCCTCGGCCGGGGAGTATGTATCCCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 487
    label "GGGATTGCAGTCCCGTTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 488
    label "TCCTCGATCGGGGAGTATGTATCCCGCGCGGGCGGGGCCCTG"
  ]
  node [
    id 489
    label "TCCTGGGCCCAGGAGCCTGGGCTGGCATGCTGTTGGGCCTAG"
  ]
  node [
    id 490
    label "TCCGCGATCGCGGAGTTTGAATCGCGCGCGCGCGGGGCCCCG"
  ]
  node [
    id 491
    label "GATCCGGCCGGATCGTTCGAATCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 492
    label "TTCCAG--TTGGAAGTCTAGATTAGTATGCTACTGGGCCTGG"
  ]
  node [
    id 493
    label "GGTTCTATAGAACCGTCTGGACCCTGCGCAGGACGAGCTCGT"
  ]
  node [
    id 494
    label "GGGGGCGCGCTCCCGTTCGAACTCTGCGCAGAGCGAGCTCGT"
  ]
  node [
    id 495
    label "GGAACCGCGGTTCCGTGTACATCGTCCGGACGGCGGGCCCGT"
  ]
  node [
    id 496
    label "TCCTCT--AGGGGAGTATGTATCTCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 497
    label "TTCCCTGCAGGGGAGTCCGGACTGGCATGCCGCCAGGCCTGG"
  ]
  node [
    id 498
    label "TCCCTGGTTGGGGAGTCCGGACCGGTGTGCCGCTGGGCCTGG"
  ]
  node [
    id 499
    label "TCTCGT--ATGGGAGTATGTATTCTGCGCAGACAGGGCCCTG"
  ]
  node [
    id 500
    label "GGAGCGGCCGCTCCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 501
    label "TCCCGA--TCGGGAGTATGTATCCCGCGTGGGTGGGGCCCCG"
  ]
  node [
    id 502
    label "GGCCCAATTGGGTCGCTCGAGCCCAGCGCTGGGAGGGCCCTT"
  ]
  node [
    id 503
    label "GTCGTTGCAACGGCATT--GATCCCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 504
    label "GGTGGCGCGTCACCGTTCGAATCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 505
    label "GCGGGAGCTCTCGCGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 506
    label "GCGGGAGCTCTCGCGCTCGAGTCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 507
    label "GGAGGCGCGCCTCCGTGTACACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 508
    label "GGGGACGCGTCCCCGTGATCATCCGGTACCGGGCGAGCTCGT"
  ]
  node [
    id 509
    label "TCCCTGGTCAGGGAGCT--GGTCGGCATGCTGCCGGGCCTGG"
  ]
  node [
    id 510
    label "GGTCTCGCGGGACCGTGTACATCCTGCGCAGGGCCGGCCGGT"
  ]
  node [
    id 511
    label "GGATTGATCAGTCCGTTTAAACTTGACGTCAAACGGGCCCGT"
  ]
  node [
    id 512
    label "GGTGCGGCCGCACCGTTCGAATCCGGCGCCGGGTGGGCCCAT"
  ]
  node [
    id 513
    label "TCCGCGATCGCGGAGTTTGAATCGAGCGCTCGCGGGGCCCCG"
  ]
  node [
    id 514
    label "GGCCCAGCTGGGTCGCTCGAGTTCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 515
    label "GGGGTAGCTATCCCGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 516
    label "GGCCCCGCGGGGTCGCTTAAGCCCTGCGCAGGGTCGGCCGAT"
  ]
  node [
    id 517
    label "TCCTCGTATGGGGAGTATGTGTCCCGCGCGGGTGGGGCCCCG"
  ]
  node [
    id 518
    label "TCCCGG--TCGGGAGTCTGGACCAGCATGCTGTCAGGCCTGG"
  ]
  node [
    id 519
    label "GCCCGGGCCCGGGCGTG--CATCGGGATCCCGCCGGGCCCGG"
  ]
  node [
    id 520
    label "GGAGTGGCCGCTCCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 521
    label "GGTCCGGCCGGACCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 522
    label "GGTCCAGCTGGACCGTA--TACTCTCCGGAGAGCGGGCCCGT"
  ]
  node [
    id 523
    label "TCCCTGGTCAGGGAGTCCGGACTGGCGTGCCGCTGGGCCTGG"
  ]
  node [
    id 524
    label "GGTCCCGCGGGACCGCTCGAGCTCCGATCGGAGCCGGCCGGC"
  ]
  node [
    id 525
    label "TCCTCGTATGGGGAGTATGTATTCTGCGCGGACGGGGCCTCG"
  ]
  node [
    id 526
    label "GCATTG--CGATGCGCTTAAGCTTATATATAAGTCAGCTGAT"
  ]
  node [
    id 527
    label "TCCCGA--TCGGGAGTTTGAATGGCGCGTGCCCGGGGCCCCG"
  ]
  node [
    id 528
    label "GGGGCTGCAGCCCCGTTCGAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 529
    label "GGAGCCGCGGCTCCGTTCGAACCCTGCGCAGGGTGGGCCCAT"
  ]
  node [
    id 530
    label "GGGGGTGCACTCCCGCTCGAGTCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 531
    label "GCGGGTGCACTCGCGCTCGAGCCTGGCGCCAGGCGGGCCCGT"
  ]
  node [
    id 532
    label "TCTTCGGCCGGGGAGAT--GTTCGCGTATGCGCCGGGCCCGG"
  ]
  node [
    id 533
    label "GGAGCCGCGGCTTCGTGTACATCCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 534
    label "TCCCTG--CAGGGAGTCTGGATCAGTGTGCTGCCGGGCCTGG"
  ]
  node [
    id 535
    label "GGTCCGTACGGACCGTCTGGACCCTGCGCAGGACGAGCTCGT"
  ]
  node [
    id 536
    label "GGCCCTGCAGGGTCGCGCGCGCTCGCCGGCGAGCGGGCCCGT"
  ]
  node [
    id 537
    label "TCCTGT--ATGGGAGTATGTATTCCGCGCGGATGGGGCCCCG"
  ]
  node [
    id 538
    label "GGTCTTGCAAGACCGTGATCATCCTCTAGAGGGCGGGCCCGT"
  ]
  node [
    id 539
    label "GGGACTGCAGTCCCGTTCGAGCCTGCCGGCAGGCGGGCCCGT"
  ]
  node [
    id 540
    label "GGAGTGGCCATTCCGTTCGAACCCTGCGCAGGGAGGGCCCTT"
  ]
  node [
    id 541
    label "GGTCCCGCGGGATCGAGCGCTCCCACCGGTGGGCGGGCCCGT"
  ]
  node [
    id 542
    label "GGCCCCGCGGGGTCGTGTACATCCACCGGTGGGTGGGCCCAT"
  ]
  node [
    id 543
    label "GGGACTGCAGTCCCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 544
    label "GGTGCGGCCGCACCGTTCGAATTCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 545
    label "TCCTTGTACGGGGAGTT--GATCCCACGTGGGTGGGGCCCCA"
  ]
  node [
    id 546
    label "GGCTCAGCTGAGTCGCTCGAGTCCAGCGCTGGGAGGGCCCTT"
  ]
  node [
    id 547
    label "TCCTCGATCGGGGGGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 548
    label "TCCCTGGCCAGGGAGCC--GGTCAGTGTGCTGTTGGGCCTGG"
  ]
  node [
    id 549
    label "TCCTCGTACGGGGAGTATGTATTCTGCGCGGACAGGGCCCTG"
  ]
  node [
    id 550
    label "GGGGGTGCATCCCCGCTCGAGTCCGGTGCCGGGCGAGCTCGT"
  ]
  node [
    id 551
    label "TCCTCT--AGGGGAGTATGTATCCCACGTGGGCAGGGCCCTG"
  ]
  node [
    id 552
    label "GGCCCCGCGGGGTCGCGCGCGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 553
    label "TTCTGG--CTAGAAGTATGTATCGCGCGTGCGCCGGGCCCGG"
  ]
  node [
    id 554
    label "TTCTCGTACGGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 555
    label "GCCGCCGCGGCGGCGTATGTATCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 556
    label "GGTCCCGCGGGACCGTGTACACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 557
    label "GCCGCGGCCGCGGCGTCTGGATGGGGCGCCCCCCGGGCCCGG"
  ]
  node [
    id 558
    label "GGGGTCGCGGCCCCGTTATAACCCGGCGCCGGGTGGGCCCAT"
  ]
  node [
    id 559
    label "GGGGGTATGCCCCCGCTCGAGCCTTGATCAAGCTTGGCCAGG"
  ]
  node [
    id 560
    label "GGGGGTGCACTCCCGCTCGAGCCATGCGCATGATGGGCTCAT"
  ]
  node [
    id 561
    label "TCCCTGGCCGGGGAGTC--GGTTAGCATGCTGTCAGGCCTGA"
  ]
  node [
    id 562
    label "GTCCGGATCCGGGCGTG--CATAAGGCGCCTTCCGGGCCCGG"
  ]
  node [
    id 563
    label "TCTCTGGCCAGAGAGTATGTATCGCGCGTGCGCTGGGCCCGG"
  ]
  node [
    id 564
    label "GGAGCTGCAGCTCCGTGTACATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 565
    label "GTCCGGATCCGGACGTG--CATGAGCCGGCTCTCGGGCCCGG"
  ]
  node [
    id 566
    label "GGAGTGGCCACTCCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 567
    label "GTCGTTGCAACGACGTT--GATCCCGCGCGGGCCGGGCTCGG"
  ]
  node [
    id 568
    label "GGTCTTGCAAGACCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 569
    label "GGGGACGCGTCCCCGTGATCACCCGGTACCGGGCGGGCCCGT"
  ]
  node [
    id 570
    label "GCCCAAGCTTGGGCGTG--CATCAGCCGGCTGTCGGATCCGA"
  ]
  node [
    id 571
    label "GGGGTCGCGGCCCCGCTCGAGTTCGGCGCCGAGCGAGCTCGT"
  ]
  node [
    id 572
    label "GGGGGTGCACTCCCGCTCGAGCCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 573
    label "GGAGTGGCCGTTCCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 574
    label "TCCTCGTACGGGGAGTATGTATTCCGCGCGGATGGGGCCCCG"
  ]
  node [
    id 575
    label "GGAGCGGCCGCTCCGTTCGAATCCGGCGTCGGGCGGGCCCGT"
  ]
  node [
    id 576
    label "GGGGTCGCGATCCCGCTCGAGCCCGCATGCGGGCGGGCCCGT"
  ]
  node [
    id 577
    label "GGAGCGGCCGTTCCGTT--AATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 578
    label "GGCCTGGCCAGGTCGTTCGAATCCAGCGCTGGGAGGGCCCTT"
  ]
  node [
    id 579
    label "TCTGTGATCGCGGAGTTTGAATGGCGCGTGCCCGGGGCCCCG"
  ]
  node [
    id 580
    label "TCCGAGATCTCGGAGTTTGAATCTCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 581
    label "GGTTCTATAGGACCGTG--CACCCTGCGCAGGACCGGCCGGT"
  ]
  node [
    id 582
    label "GCGGGTGCACTCGCGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 583
    label "GCCCGGATCCGGGCGTG--CATCGACCGGTCGGCGGGCCCGC"
  ]
  node [
    id 584
    label "GGGGTCGCGACCCCGTTATAACCCGGCGTCGGGAGGGCCCTT"
  ]
  node [
    id 585
    label "GGGGGTGCACTCTCGCTCGAGCTCTGCGCAGAGCGGGCCCGT"
  ]
  node [
    id 586
    label "GGGGGCGCGCTCCCGCGATCGCTCGGCGCCGAGCGGGCCCGT"
  ]
  node [
    id 587
    label "GGTCTGGCCAGACCGTTCGAATCCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 588
    label "GGGACTGCAGTCTCGCTCGAGCTTCCCGGGAAGCCAGCTGGT"
  ]
  node [
    id 589
    label "GGGGTTGCAGCCCCGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 590
    label "GGTTTGGCCAGACCGTTCGAATCATGCGCATGGCGGGCCCGT"
  ]
  node [
    id 591
    label "GGTCCTATAGGACCGTG--CACCCTGCGCAGGACCGGCCGGT"
  ]
  node [
    id 592
    label "CTTCGG--CCGGGGGTTTGAATCGCGTATGCGCCGGGCCCGG"
  ]
  node [
    id 593
    label "TTCCTGGTCAGGGAGTCTGGATCAGTGTGCTGCCGGGCCTGG"
  ]
  node [
    id 594
    label "GCCCAGATCTGGGCGTG--CATTCGGCGCCGATCGGATCCGA"
  ]
  node [
    id 595
    label "GGAACCGCGGTTCCGTGTACATCCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 596
    label "GGGGTGTACATCCCGCGATCGCCTGGCGCCGGACGGGCCCGT"
  ]
  node [
    id 597
    label "TCCTCGTACGGGGAGTATGTATTCCGCGCGGACGGGGCCCTG"
  ]
  node [
    id 598
    label "TCCCTGGTCAGGGAGTCTGGACCGGTGTGCCGCCGGGCCTGG"
  ]
  node [
    id 599
    label "GGCCCCGCGGGGTCGCGCGCGCCCGCCGGCGGGTGGGCCCAT"
  ]
  node [
    id 600
    label "GGAGCCGCGGCTCCGCTCGAGCCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 601
    label "TCCTCGTACGGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 602
    label "GGGGTCGCGGCCCCGTTCGAACCCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 603
    label "GCCTCGGCCGAGGCGTG--CATCAGGCGCCTGTCGGGCCCGG"
  ]
  node [
    id 604
    label "TCTTGT--ACGAGAGTATGTATCTCACGTGGGCGGGGCCCCG"
  ]
  node [
    id 605
    label "GGTCCCTAGGGACCGTG--CACCCTCCGGAGGACCGGCCGGT"
  ]
  node [
    id 606
    label "GGGGATGCATTCTCGCTCGAGCTCTGCGCAGAGCGGGCCCGT"
  ]
  node [
    id 607
    label "GGTCCAGCTGGACCGTA--TACCTTCCGGAAGGCGAGCTCGT"
  ]
  node [
    id 608
    label "GGACCTGCAGGTCCGTGCGCACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 609
    label "TCCCTGGTCAGGGAGTCTGGATTGGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 610
    label "TCCCTGGTCGGGGAGTCCGGACCAGTATGCTGCCGGGCTTGG"
  ]
  node [
    id 611
    label "GGCCTCGCGAGGTCGCGCGCGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 612
    label "GGAGCAGCTGTTCCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 613
    label "GGAGCGGCCGCTCCGTTCGAATCGGCCGGCCGGCGGGCCCGT"
  ]
  node [
    id 614
    label "GGCTTAGCTGAGTCGCTCGAGTCCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 615
    label "GGCCCAGCTGGGTCGCTCGAGTCTGGCGCCAGGAGGGCCCTT"
  ]
  node [
    id 616
    label "TCTTGGGCCTAGGAGCCTAGGTTAGTGTGCTGTCAGGCCTGA"
  ]
  node [
    id 617
    label "GCGACGGTCGTCGCGTTCGAATCCGCCGGCGGACGAGCTCGT"
  ]
  node [
    id 618
    label "GCTCTGGCCAGAGCGTG--CATCAGGATCCTGTCGGGCCCGG"
  ]
  node [
    id 619
    label "GCGGGTGCACTCGCGCTCGAGTTCGGCGCCGAGCGGGCCCGT"
  ]
  node [
    id 620
    label "GCGGCTGTAGCCGCACTCGAGTTAAGCGCTTAACGGGCCCGT"
  ]
  node [
    id 621
    label "GCCGATGCATCGGCGCTCGAGCCCCGCGCGGGGAGGGCCCTT"
  ]
  node [
    id 622
    label "GCGGTGGCCGCCGCGCTCGAGTTCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 623
    label "GCCGCGGCCGCGGCGTACGTATCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 624
    label "GTCCGAATTCGGGCGTG--CATGAGCCGGCTCCCGGGCCCGG"
  ]
  node [
    id 625
    label "TTCTCGGCCGGGAAGTATGTATCCCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 626
    label "GGAGTAGCTATTCCGCTCGAGCCCCGCGCGGGGCGGGCCCGT"
  ]
  node [
    id 627
    label "TCCTCGTACGGGGGGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 628
    label "GCGCCCGCGGGCGCGTGATCACCCTCCGGAGGGCCGGCCGGT"
  ]
  node [
    id 629
    label "TCCGTGATCGCGGAGTTTGAACACCGCGCGGTCGGGGCCCCG"
  ]
  node [
    id 630
    label "TCCTCATATGGGGAGAT--GTTCCCGCGTGGGTGGGGCCCTG"
  ]
  node [
    id 631
    label "GGATCGGCCGATCCGTTTGAATTCGGCGCCGAGCGGGCCCGT"
  ]
  node [
    id 632
    label "TCCCTGGTCGGGGAGTT--GATCAGCATGTTGCCAGGCCTGG"
  ]
  node [
    id 633
    label "GGGGGCGCGCTCCCGTGTACACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 634
    label "GGGGTGATCATCCCGCTCGAGCTCTGCGCAGAGCGGGCCCGT"
  ]
  node [
    id 635
    label "TCCTCGGCCGGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 636
    label "GGGGGCGCGCTCCCGTTCGAACTAAGCGCTTAGCGAGCTCGT"
  ]
  node [
    id 637
    label "GGGGCCGCGGCCCCGCTCGAGCCTCGATCGAGGCGGGCCCGT"
  ]
  node [
    id 638
    label "TCCTTG--CAAGGAGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 639
    label "GCCCAGTACTGGGCGTG--CATCAGCCGGCTGACGGATCCGT"
  ]
  node [
    id 640
    label "GCGGGAGCTCCCGCGTTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 641
    label "TCCTTGGCTGGGGAGCCTAGGTTGGCATGCTGTCAGGCCTGA"
  ]
  node [
    id 642
    label "GGGTGG--CCACCCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 643
    label "TCCTGG--CCAGGAGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 644
    label "GGAGCTGCAGCTCCGTGTACATTCGGCGCCGAGCGGGCCCGT"
  ]
  node [
    id 645
    label "GGAACTGCAGTTCCGTGTACATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 646
    label "TCCGTGATCGCGGAGTTTGAATACCGCGCGGTCGGGGCCCCG"
  ]
  node [
    id 647
    label "TCCCTGGCTGGGGAGCCTAGGTCAGCATGCTGTCAGGCCTGG"
  ]
  node [
    id 648
    label "GCGGGAGCTTCCGCGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 649
    label "GGTCTGGCCAGACCGTTCGAATCCTGCGTAGGGCGGGCCCGT"
  ]
  node [
    id 650
    label "GCCTTGGCCAAGGCGTG--CATCAGGCGCCTGTCGGGCCCGG"
  ]
  node [
    id 651
    label "TCTTTGGCCAAGGAGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 652
    label "TCCCTGGTCAGGGAGTC--GACCTGCGTGCAGCGGGGCCTCG"
  ]
  node [
    id 653
    label "GGGGGCGCGCTCCCGTTTGAACTAAGCGCTTAGCGAGCTCGT"
  ]
  node [
    id 654
    label "TCCTTGTATGGGGAGTA--TATCCTGCGCAGGCGGGGCCCTG"
  ]
  node [
    id 655
    label "GGGGGCGCGCTCCCGTGATCACCTGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 656
    label "GGAGCGGCCGCTCCGTTATAACCCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 657
    label "GGATCGGCCGATCCGTTCGAATTCGGTACCGAACGGGCCCGT"
  ]
  node [
    id 658
    label "GGCCTAGCTGGGTCGCTCGAGCCCGCCGGCGGACGGGCCCGT"
  ]
  node [
    id 659
    label "GGTCCGGCCGGACCGTTCGAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 660
    label "GGGGTGGCCACCCCGTGTACACCCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 661
    label "GGTTCAGCTGAACCGTA--TACTCTCCGGAGAGCGGGCCCGT"
  ]
  node [
    id 662
    label "GGGGGTGTGCTTCCGCTCGAGCCATACGTGTGCTGGGCCCAG"
  ]
  node [
    id 663
    label "TCCTCG--CGGGGAGTATGTATTCTGCGCAGACAGGGCCCTG"
  ]
  node [
    id 664
    label "GGAGTTGCAGCTCCGCTCGAGCCCGGCGTCGGGCGGGCCCGT"
  ]
  node [
    id 665
    label "GGCCTATATGGGTCGTCCGGACCCGCCGGCGGACCGGCCGGT"
  ]
  node [
    id 666
    label "GGGACTGCAGTCCCGCTCGAGCCGCGCGCGCGGCGGGCCCGT"
  ]
  node [
    id 667
    label "TCCTTGGCCAAGGAGTATGTATTCCGTGCGGACGGGGCCCCG"
  ]
  node [
    id 668
    label "GCCCTGGCCAGGGCGTG--CATCGGGCGCCCGTCGGGCCCGG"
  ]
  node [
    id 669
    label "GCATTGGCCAATGCGTTCGAATCTCGCGCGGGCCGGGTCCGG"
  ]
  node [
    id 670
    label "GGTCCGTACGGACCGTCTGGACCATCCGGATGACGAGCTCGT"
  ]
  node [
    id 671
    label "TTCTCGATCGGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 672
    label "GGATTGATCAATCCGTTTAAATTTGGCGTCGAACGGGCCCGT"
  ]
  node [
    id 673
    label "GGCCCCGCGGGGTCGTGTACATCCTGCGCAGGGTCGGCCGAT"
  ]
  node [
    id 674
    label "TCTTTCGCGAAAGAGTATGTATCAAGCGCTTGCCGGGCCCGG"
  ]
  node [
    id 675
    label "TCCTTG--CGGGGAGTATGTATTCTGCGCAGACAGGGCCCTG"
  ]
  node [
    id 676
    label "GGTGCGATCGCACCGTTCGAATTCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 677
    label "GCCCAGGCCTGGGCGTG--CATATGCCGGCATTCGGATCCGA"
  ]
  node [
    id 678
    label "GGCCCTGCAGGGTCGCTCGAGTCCGCCGGCGGGCCGGCCGGT"
  ]
  node [
    id 679
    label "TCCTCT--AGGGGAGTGTGTATCCCGCGCGGGTGGGGCCTCG"
  ]
  node [
    id 680
    label "GGGGGCGCGCTCCCGTTCGAACCCTGCGCAGGGCCGGCCGGT"
  ]
  node [
    id 681
    label "TCCCGG--CCGGGAGCTCGGGTTGGCATGCTGTCAGGCCTGG"
  ]
  node [
    id 682
    label "GGGGTCGCGGCCCCGTTCGAATCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 683
    label "TCCTCGTACGGGGAGTATGTATTCTGCGCGGACGGGGCCCCG"
  ]
  node [
    id 684
    label "GGGGGTATACTCCCGCTCGAGCATCGCGCGATGCGAGCTCGT"
  ]
  node [
    id 685
    label "GGGGACGCGTCCCCGTGCGCACCCGGTACCGGGCGAGCTCGT"
  ]
  node [
    id 686
    label "GCGGCTGCAGCCGCGTTTGAATCCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 687
    label "TCCCTGATCGGGGAGTCCGGATCGGCGTGCCGCCGGGCCTGG"
  ]
  node [
    id 688
    label "GGTCCCGCGGGACCGTGATCACCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 689
    label "GGCCCGGCCGGGTCGCTCGAGCCCGCCGGCGGGTGGGCCCAT"
  ]
  node [
    id 690
    label "GGTGCGGCCGCACCGTTCGAATCATGCGCATGGCGGGCCCGT"
  ]
  node [
    id 691
    label "GCGGGCGCGCTCGCGTTCGAACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 692
    label "GGTGCGGCCGCACCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 693
    label "TCCCTGGTTGGGGAGTCCGGACCGGCGTGCCGCCAGGCCTGG"
  ]
  node [
    id 694
    label "GGAGGG--CCCTCCGCGTACGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 695
    label "TCCTCT--AGGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 696
    label "GGGGATGCATCCCCGCTCGAGCCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 697
    label "GGTCCGGCCGGACCGTGTACATCCTCCGGAGGGCGGGCCCGT"
  ]
  node [
    id 698
    label "GGCCTGGCCGGGTCGCTCGAGCCCGCCGGCGGGTGGGCCCAT"
  ]
  node [
    id 699
    label "GGCCTGGCCAGGTCGTTCGAATCCGCCGGCGGGTGAGCTCAT"
  ]
  node [
    id 700
    label "GGGGCTGCAGCCTCGAA--TTCTCGCATGCGAGCGGGCCCGT"
  ]
  node [
    id 701
    label "TCTTGGGCCCAGGAGCT--GGCTGGTGTGCTGTCAGGCCTGG"
  ]
  node [
    id 702
    label "TCCCCGTACGGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 703
    label "TCCTCT--AGAGGAGTATGTATCCCGCGCGGGTGGGGCCCTG"
  ]
  node [
    id 704
    label "GGCTCAGCTGGGTCGCTCGAGTCCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 705
    label "TCCCTGGTCAGGGAGTCTGGACTGGCATGCTGCCGGGCCTGG"
  ]
  node [
    id 706
    label "TCCTCGGCCGGGGAGTGTGTATCGCGTATGCGCCGGGCCCGG"
  ]
  node [
    id 707
    label "TTTCTGGCCAGAGAGTATGTATCGCGCGTGCGCCGGGCCCGG"
  ]
  node [
    id 708
    label "TCCTCGTACGGGGAGTATGTATTCTGCGCAGACAGGGCCCTG"
  ]
  node [
    id 709
    label "GGTTCATATGAACCGGG--CCTCCCGATCGGGACGAGCTCGT"
  ]
  node [
    id 710
    label "GGCCCAGCTGGGTCGCTCGAGCCCGCCGGCGGGAGAGCTCTT"
  ]
  node [
    id 711
    label "TCCTCGTACGGGGAGTATGTGTCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 712
    label "TCTCGG--CCGGGGGTATGTATCGCGTATGCGCCGGGCCCGG"
  ]
  node [
    id 713
    label "GCATGG--CCATGCGTTCGAATCTTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 714
    label "GGTCTGGCCGGACCGTTCGAATCGTGCGCACGACGGGCCCGT"
  ]
  node [
    id 715
    label "GGCCCAGCTGGGTCGCGCGCGCTCGCCGGCGAGCGGGCCCGT"
  ]
  node [
    id 716
    label "GGTTCAGCTGGACCGTA--TACCCTCCGGAGGGCGGGCCCGT"
  ]
  node [
    id 717
    label "GGGGTGGCTATCCCGCTCGAGCCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 718
    label "GGCCTGGCCGGGTCGCTTAAGCCCTGCGCAGGGTGGGCCCAT"
  ]
  node [
    id 719
    label "GGCCCGGTCGGGTCGCTCGAGCCCGCCGGCGGAGGGGCCCCT"
  ]
  node [
    id 720
    label "GGGCTCGCGGGCCCGTGTACATCCACTAGTGGGGGGGCCCCT"
  ]
  node [
    id 721
    label "GGGGGTGCACTCCCGCTCGAGCCTGGCGCTAGGCGAGCTCGT"
  ]
  node [
    id 722
    label "GGTCCAGCTGGACCGTGTACATTCGGTACCGAGCGGGCCCGT"
  ]
  node [
    id 723
    label "GGGGACGCGTCCCCGTTCGAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 724
    label "GGGGGCATGCTCCCGCTCGAGCTCGGCGCCGAGCGGGCCCGT"
  ]
  node [
    id 725
    label "TCCCTGGTCGGGGAGTCCGGACCTGCGCGCGGCCGGGCCTGG"
  ]
  node [
    id 726
    label "GCGGGCGCGCCCGCGCTCGAGTCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 727
    label "TCCTCGTACGGGGAGTATGTATTCCGCGCGGATGGGGCCCTG"
  ]
  node [
    id 728
    label "GGGATTGCAGTCCCGTTTGAGCCCGCCGGCGGGCGGGCTTGT"
  ]
  node [
    id 729
    label "GTCGTTGCAACGGCGTATGTATCCCGCGCGGGCTGGGCCCGG"
  ]
  node [
    id 730
    label "TCTCGT--ACGGGAGTATGTATTCTGCGCAGACAGGGCCCTG"
  ]
  node [
    id 731
    label "GCGCCCGCGGGCGCGTATGTACCCTCCGGAGGGCCGGCCGGT"
  ]
  node [
    id 732
    label "GGTCTGGCCAGACCGTTCGAATCATGCGCATGGCGGGCCCGT"
  ]
  node [
    id 733
    label "GGGGATATATTCTCGTGTACACCCTGGCCAGGACGGGCCCGT"
  ]
  node [
    id 734
    label "GGTCCAGCTGGACCGTA--TACCTTCCGGAAGGCGGGCCCGT"
  ]
  node [
    id 735
    label "GCCTCCGCGGGGGCGTTCGAATGCGCTAGCGTGCGGGCCCGC"
  ]
  node [
    id 736
    label "GCCGCGGCCGCGGCGTA--TATCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 737
    label "GGTCCAGCTGGACCGTA--TACCCTCCGGAGGGCGGGCCCGT"
  ]
  node [
    id 738
    label "TCTTTCGCGAGAGAGTATGTATCAAGCGCTTGCCGGGCCCGG"
  ]
  node [
    id 739
    label "GTCCGGATCCGGGCGTG--CATAAGCCGGCTTCCGGGCCCGG"
  ]
  node [
    id 740
    label "TCTTTGTACAGAGAGTATGTATCAAGCGCTTGCCGGGCCCGG"
  ]
  node [
    id 741
    label "TCCTGT--ACGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 742
    label "GGGATTGCAATCTCGCTCGAGCTCCGCGCGGAGCGGGCCCGT"
  ]
  node [
    id 743
    label "TCCCGG--CCGGGAGTCTGGATCAGCATGCTGTCAGGCCTGG"
  ]
  node [
    id 744
    label "GGGGGCGCGCTCCCGTTCGAATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 745
    label "GGAGGG--CCTTCCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 746
    label "GGTCCCGCGGGACCGTGATCACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 747
    label "TCCCTGGTTGGGGAGTTCGGACTGGCGTGCCACCAGGCCTGG"
  ]
  node [
    id 748
    label "GGGGGCGCGCTCCCGTGTACATCAGCCGGCTGGCGGGCCCGT"
  ]
  node [
    id 749
    label "GTCCGAATTCGGGCGTG--CATGGGCCGGCCCCCGGGCCCGG"
  ]
  node [
    id 750
    label "GGCTCCATGGGGTCGTCTGGACCTGCTAGCGGAGGGGCCCCT"
  ]
  node [
    id 751
    label "GGAGTCGCGACTCCGTGTACACCCCGCGCGGGGCGGGCCCGT"
  ]
  node [
    id 752
    label "GCGGGAGCTCCCGCGTC--GACCCAGCGCTGGGCGGGCCCGT"
  ]
  node [
    id 753
    label "TCCTCGTACGGGGAGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 754
    label "TCCCGG--CCGGGAGTCTGGATCAGCATGCTGTCAGGCTTGG"
  ]
  node [
    id 755
    label "GGCCCCGCGGGGTCGTGTACATTCGCCGGCGAGTCAGCTGAT"
  ]
  node [
    id 756
    label "TCTCGG--CCGGGAGTATGTATCGCGTATGCGCCGGGCCCGG"
  ]
  node [
    id 757
    label "GGCCGGGTCCGGTCGTTCGAACCTAGCGCTAGGTGGGCCCAT"
  ]
  node [
    id 758
    label "GCAGCGGCCGCTGCGTTCGAATCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 759
    label "GGCCTGTACAGGCCGTC--GACCCGGGCCCGGAAGAGCTCTT"
  ]
  node [
    id 760
    label "TCCGTGATCGCGGAGTTTGAATACCGCGTGGTCGGGGCCCCG"
  ]
  node [
    id 761
    label "GCGGGTGCACTCGCGCTCGAGTCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 762
    label "GGGGGG--CCTCCCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 763
    label "TCCGTGATCGCGGAGTTTGAATGGCGCGTGCCCGGGGCCCCG"
  ]
  node [
    id 764
    label "GGGGGCGCGCTCCCGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 765
    label "GGGATTGCAGTCCCGCTCGAGTCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 766
    label "TCCGTGATCGCGGAGTTTGAATCGCGCGCGCGCGGGGCCCCG"
  ]
  node [
    id 767
    label "GGTCCAGCTGGACCGTGTACATCCTCCGGAGGGTGGGCCCAT"
  ]
  node [
    id 768
    label "TCCCTGGTCGGGGAGTCCGGACCAGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 769
    label "GTCGTTGCAGCGGCGTATGTACCCCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 770
    label "GGGGGTGCATCCCCGCTCGAGTCTGGTGCCGGGCGAGCTCGT"
  ]
  node [
    id 771
    label "GGCCTCGCGGGGTCGCTCGAGCCCCGATCGGGGCCGGCCGGC"
  ]
  node [
    id 772
    label "GCCCAGGCCTGGGCGTG--CATTCGGCGCCGATCGGATCCGA"
  ]
  node [
    id 773
    label "GGTCGG--CCGACCGTTCGAATCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 774
    label "TCCCGG--CCGGGAGCCTGGGCCAGTGTGTTGTCAGGCCTGG"
  ]
  node [
    id 775
    label "GCGGGAGCTCCCGCGTTCGAGCCCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 776
    label "GGGGGAGCTCTCTCGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 777
    label "GGGGGTGCACTCCCGCTCGAGTCCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 778
    label "GGGGTGTACACCCCGTTATAACCCGGCGCCGGAGGGGCCCCT"
  ]
  node [
    id 779
    label "TCCTTGGTCAGGGAGTCCGGACTGGCGTGCCACCGGGCCTGG"
  ]
  node [
    id 780
    label "GGGGGCGCGCTCCCGTTCGAACCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 781
    label "GGAGCGGCCGCTCCGTTCGAATCTGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 782
    label "TCCCTGGTTGGGGAGTCCGGACCGGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 783
    label "GGGCTTTAAGGCCCGTGTACATCCACATGTGGGCGGGCCCGT"
  ]
  node [
    id 784
    label "GATCCTGCAGGATCGCTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 785
    label "GGAGCAGCTGCTCCGTGTACATCCAGCGCTGGGCGGGCCCGT"
  ]
  node [
    id 786
    label "GGGGGCGCGCTCCCGTTCGAACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 787
    label "TCCTCGTACGGGGAGTATGTATCCCGCGCGGGTGGGGCTCCG"
  ]
  node [
    id 788
    label "GGCCTAATTGGGTCGCTCGAGCCCGCCGGCGGGCGGGCCCGC"
  ]
  node [
    id 789
    label "GGCCCAGCTGGGTCGCTCGAGTCCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 790
    label "GGCTCGGTCGAGTCGTTCGAATCCAGCGCTGGGAGGGCCCTT"
  ]
  node [
    id 791
    label "TCCTCGTATGGGGAGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 792
    label "GGTTCGGCCGGACCGTTCGAATCATGCGCATGGCGGGCCCGT"
  ]
  node [
    id 793
    label "GGGCCTGCAGGCCCGTTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 794
    label "TCTTTG--CAGAGAGTATGTATCGCGCGTGCGCCGGGCCCGG"
  ]
  node [
    id 795
    label "GGCCTTGCAAGGTCGCGCGCGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 796
    label "GGTGCGTACGCACCGTTCGAATCATGCGCATGACGGGCCCGT"
  ]
  node [
    id 797
    label "GGACCGGCCGGTCCGTTCGAATCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 798
    label "TCCTGT--ACAGGAGTATGTATCCTGCGTGGGTGGGGCTCTG"
  ]
  node [
    id 799
    label "GGACCGGCCGGTCCGTTCGAATCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 800
    label "GTCCGAATTCGGGCGTG--CATAAGCCGGCTTCCGGGCCCGG"
  ]
  node [
    id 801
    label "GGTCCCGCGGGACCGAGCGCTCCCACCGGTGGGCGGGCCCGT"
  ]
  node [
    id 802
    label "TCCCTGGTCGGGGAGTCCGGACCGGCATGCTGCTGGGCCTGG"
  ]
  node [
    id 803
    label "GGAGCTGCAGCTCCGTGATCACCCGGTACCGGGCGGGCCCGT"
  ]
  node [
    id 804
    label "TCCCGG--CCGGGAGTTCGGATTGGCATGCTACTGGGCCTGG"
  ]
  node [
    id 805
    label "GCCGCAGCTGCGGCGTCTGGATGGGGCGCCCCCCGGGCCCGG"
  ]
  node [
    id 806
    label "GCCCGGGCTCGGGCGTG--CATTGACCGGTCGGCGGGCCCGC"
  ]
  node [
    id 807
    label "GGCCCAGCTGGGTCGTTCGAACCCAGCGTTGGATGGGCCCAT"
  ]
  node [
    id 808
    label "GCCCCGGCCGGGGCGTG--CATCAGGCGCCTGATGGGCCCGT"
  ]
  node [
    id 809
    label "GTCGTT--AACGGCGTATGTATCCCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 810
    label "GGAGTGGCCATTCCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 811
    label "GGAGCGGCCGCTCCGCTCGAGTCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 812
    label "TCCCGG--TCGGGAGTCCGGACCAGTGCGCTGCCAGGCCTGG"
  ]
  node [
    id 813
    label "GGGGGCGCGCTCCCGCTCGAGCCTCGATCGAGGCGGGCCCGT"
  ]
  node [
    id 814
    label "GGGGGTGCGCTCCCGTGATCACCTGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 815
    label "GTTCGGATCCGAACGTG--CATGGGCCGGCCTTCGGGCCCGG"
  ]
  node [
    id 816
    label "GGTCCGGCCGGACCGTGTACATCTTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 817
    label "GCGGCGGCCGCCGCGTTCGAATTCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 818
    label "GGGGTCGCGGCCCCGTTCGAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 819
    label "GGTGCGTACGCACCGTTCGAATCCTGCGCAGGACGAGCTCGT"
  ]
  node [
    id 820
    label "GTCCTG--CAGGGCGCTCGAGCCTCGTGCGAGCTGGGCCCGG"
  ]
  node [
    id 821
    label "GGGGTCGCGACCCCGTGTACACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 822
    label "GCGAGTGCACTCGCGCTCGAGTCTGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 823
    label "GGGGTTGCAACCCCGCTCGAGTCCAGCGCTGGGCGGGCCCGT"
  ]
  node [
    id 824
    label "TCCTCGATCGGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 825
    label "GGAGGCGCGCCTCCGTGTACACCATGCGCATGGCGGGCCCGT"
  ]
  node [
    id 826
    label "GGGCTCGCGGGCCCGTGTACATCCACATGTGGGCGGGCCCGT"
  ]
  node [
    id 827
    label "TCTCTG--CAGAGAGTATGTATCGCGCGTGCGCCGGGCCCGG"
  ]
  node [
    id 828
    label "GGTCCGGCCGGACCGTTCGAATCTGCCGGCAGGCGGGCCCGT"
  ]
  node [
    id 829
    label "GGTTCTGCAGGACCGTGTACATCCTCTAGAGGGCGGGCCCGT"
  ]
  node [
    id 830
    label "GGCCCGGCCGGGTCGTTCGAACCTAGCGCTAGGACGGCCGTT"
  ]
  node [
    id 831
    label "TCCTCGTACGGGGAGTA--TATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 832
    label "TTCCTGGTCAGGGAGTC--GATCTGTGTACAGCCAGGCTTGG"
  ]
  node [
    id 833
    label "GGGGCTGCAGCCCCGTG--CACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 834
    label "GTCGTTGCAGCGGCGTATGTATCCCGCGTGGGCCGGGCCCGG"
  ]
  node [
    id 835
    label "GGGGTCGCGACCCCGTTATAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 836
    label "CCTCGT--ACGGGGGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 837
    label "GGTCCCGCGGGACCGTGTACATCCTGCGCAGGGCCGGCCGGT"
  ]
  node [
    id 838
    label "GGGGGCGCGTCCCCGTTCGAACCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 839
    label "GGTCCATATGGACCGAG--CTCCCTCCGGAGGATGGGCCCAT"
  ]
  node [
    id 840
    label "GGGGTGGCCACCCCGTTATAACTCCGCGCGGAGCGGGCCCGT"
  ]
  node [
    id 841
    label "GGTCTAGCTAGACCGTA--TACCCTCCGGAGGGCGGGCCCGT"
  ]
  node [
    id 842
    label "TCCCGT--ACGGGAGTATGTATTCTGCGCAGACAGGGCCCTG"
  ]
  node [
    id 843
    label "GCGGGAGCTCTCGCGCTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 844
    label "GGAGCGGCCGCTCCGTTATAACCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 845
    label "GGTCCATATGGACCGAG--CTCTCTCCGGAGAGTCAGCTGAC"
  ]
  node [
    id 846
    label "GGGGAGTACTCCTCGTTCGAACCCGGCGCCGGACGGGCCCGT"
  ]
  node [
    id 847
    label "TTCTCGTACGGGGAGTATGTATTCCGCGCGGACGGGGCCCCG"
  ]
  node [
    id 848
    label "GCGGTGGCCACCGCGTTCGAATCCTGCGCAGGGTGGGCCCAT"
  ]
  node [
    id 849
    label "TCCCTGGCCAGGGAGCC--GGTCAGCATGCTGTCAGGCCTGG"
  ]
  node [
    id 850
    label "TCCCGA--TCGGGAGTATGTATCCCGCGTGGGCGGGGCCCCG"
  ]
  node [
    id 851
    label "TCCCGG--CCGGGAGTCTGGATTGGCATGCTGTTAGGCCTGA"
  ]
  node [
    id 852
    label "GGCCTGGCCAGGTCGTTCGAATCCAGCGCTGGGAGAGCTCTT"
  ]
  node [
    id 853
    label "GGAGCTGCAGCTCCGCTCGAGCTCCGCGCGGAGTGGGCCCAT"
  ]
  node [
    id 854
    label "TCTCTGGCTAGAGAGTATGTATCGCGCGTGCGCCGGGCCCGG"
  ]
  node [
    id 855
    label "GGGGGCGCGTCCCCGTTCGAACCCGGCGCCGGGAGGGCCCTT"
  ]
  node [
    id 856
    label "TCCTCATATGGGGAGTT--GATTCTGCGTGGGCGGGGCCCCG"
  ]
  node [
    id 857
    label "GGGGGTGCACTCCCGCTCGAGCATCGCGCGATGAGGGCCCTT"
  ]
  node [
    id 858
    label "TCCTGG--CCGGGAGTATGTATCGCGTATGCGCCGGGCCCGG"
  ]
  node [
    id 859
    label "GGGGTGTACATCCCGCGATCGCCTGGCGCCGGACGAGCTCGT"
  ]
  node [
    id 860
    label "GATCCGGCCGGATCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 861
    label "GCCCCGATCGGGGCGTG--CATCAGGCGCCTGACGGGCCCGT"
  ]
  node [
    id 862
    label "GCGGTGGCCACCGCGTTCGAATCCTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 863
    label "GCCGCGGCCGCGGCGTATGTATCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 864
    label "TCCTCGTATGGGGAGTATGTATTCTGCGCAGACAGGGCCCTG"
  ]
  node [
    id 865
    label "TCCTCGTACGAGGAGTATGTATCCCGCGTGGGCGGGGCCCCG"
  ]
  node [
    id 866
    label "GTCTTG--CAAGGCGTATGTATCCCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 867
    label "TCTCGA--TCGGGAGTATGTATCCCGCGCGGGCGGGGCCCCG"
  ]
  node [
    id 868
    label "GGAGCCGCGGCTCCGTGTACATTCGGCGCCGAGCGGGCCCGT"
  ]
  node [
    id 869
    label "GGTTTGGCCAGACCGTTCGAATCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 870
    label "GGAGCTGCAGCTCCGTGTACACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 871
    label "GTCCCGGCCGGGACGTG--CATAGGCCGGCCTACGGATCCGT"
  ]
  node [
    id 872
    label "GGCCTGGCCAGGTCGTTCGAACCCGCCGGCGGGTGAGCTCAT"
  ]
  node [
    id 873
    label "TCCCTGGTCAGGGAGTCCGGACCGGCATGCCGCCGGGCCTGG"
  ]
  node [
    id 874
    label "TCTCCGGCCGGAGAGTATGTATCGCGCGTGCGCCGGGCCCGG"
  ]
  node [
    id 875
    label "GGAGCCGCGGCTCCGTTATAACCCGGCGCCGGGCCGGCCGGT"
  ]
  node [
    id 876
    label "GGAGCCGCGGCTCCGTGGCCATCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 877
    label "TCCCTGGTCAGGGAGTCCGGACCGGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 878
    label "GGTCCTATAGGACCGTCTGGACCCTGCGCAGGACGAGCTCGT"
  ]
  node [
    id 879
    label "TCCGAGATCTCGGAGTATGTATTCCGCGCGGACCGGGCCCGG"
  ]
  node [
    id 880
    label "GGTTCGTACGGACCGTGTACACCCTGATCAGGACGAGCTCGT"
  ]
  node [
    id 881
    label "GGCCGCGCGTGGTCGCTCGAGCCCGCCGGCGGGCCGGCCGGT"
  ]
  node [
    id 882
    label "TCCCGG--TCGGGAGTCCGGACCAGCATGCTGCCAGGCCTGG"
  ]
  node [
    id 883
    label "GGCCCGGCCGGGTCGCTCGAGCCCAGCGCTGGGTCGGCCGAT"
  ]
  node [
    id 884
    label "GGTCCTGCAGGACCGAGCGCTCCCGCCGGCGGGCGGGCCCGT"
  ]
  node [
    id 885
    label "TCCCTGGTCAGGGAGTCCGGACCAGTGTGCTGCCGGGCCTGG"
  ]
  node [
    id 886
    label "GGAGTGGCCACTCCGTTCGAATCCGGCGTCGGGCGGGCCCGT"
  ]
  node [
    id 887
    label "TCCCTGGCCAGGGAGCT--GGTTGGGGCTCTGTCAGGCCTGG"
  ]
  node [
    id 888
    label "GCGGGAGCTCTCGCGTTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 889
    label "GGGGCCGCGGCCCCGTTCGGACCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 890
    label "GGATCGGCCGGTCCGTTTGAATCCGGCGCCGGACGGGCCCGT"
  ]
  node [
    id 891
    label "GGCCCCATGGGGTCGTGTACATCCACCGGTGGGGGGGCCCCC"
  ]
  node [
    id 892
    label "TCGTTG--CAACGGGTATGTATCCCGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 893
    label "GGAGTTGCAATTCCGTTCGAACCCTGCGCAGGGCGGGCCCGT"
  ]
  node [
    id 894
    label "GGCCCGGCCGGGTCGTTCGAATCCAGCGCTGGGAGGGCCCTT"
  ]
  node [
    id 895
    label "GGGATTGCAGTCCTGTTCGAGCCCGCCGGCGGGCGGGCCCGT"
  ]
  edge [
    source 0
    target 490
  ]
  edge [
    source 4
    target 695
  ]
  edge [
    source 5
    target 708
  ]
  edge [
    source 10
    target 43
  ]
  edge [
    source 14
    target 445
  ]
  edge [
    source 14
    target 15
  ]
  edge [
    source 16
    target 222
  ]
  edge [
    source 20
    target 258
  ]
  edge [
    source 22
    target 121
  ]
  edge [
    source 26
    target 120
  ]
  edge [
    source 32
    target 777
  ]
  edge [
    source 35
    target 82
  ]
  edge [
    source 35
    target 331
  ]
  edge [
    source 35
    target 340
  ]
  edge [
    source 36
    target 60
  ]
  edge [
    source 37
    target 369
  ]
  edge [
    source 39
    target 624
  ]
  edge [
    source 40
    target 86
  ]
  edge [
    source 42
    target 882
  ]
  edge [
    source 42
    target 518
  ]
  edge [
    source 43
    target 824
  ]
  edge [
    source 44
    target 597
  ]
  edge [
    source 44
    target 549
  ]
  edge [
    source 50
    target 213
  ]
  edge [
    source 50
    target 166
  ]
  edge [
    source 52
    target 886
  ]
  edge [
    source 52
    target 265
  ]
  edge [
    source 52
    target 195
  ]
  edge [
    source 53
    target 425
  ]
  edge [
    source 55
    target 257
  ]
  edge [
    source 55
    target 185
  ]
  edge [
    source 64
    target 204
  ]
  edge [
    source 72
    target 302
  ]
  edge [
    source 73
    target 620
  ]
  edge [
    source 74
    target 744
  ]
  edge [
    source 76
    target 344
  ]
  edge [
    source 77
    target 371
  ]
  edge [
    source 81
    target 158
  ]
  edge [
    source 84
    target 126
  ]
  edge [
    source 86
    target 865
  ]
  edge [
    source 86
    target 601
  ]
  edge [
    source 87
    target 184
  ]
  edge [
    source 90
    target 789
  ]
  edge [
    source 90
    target 615
  ]
  edge [
    source 91
    target 559
  ]
  edge [
    source 92
    target 219
  ]
  edge [
    source 93
    target 672
  ]
  edge [
    source 96
    target 601
  ]
  edge [
    source 96
    target 787
  ]
  edge [
    source 101
    target 148
  ]
  edge [
    source 105
    target 601
  ]
  edge [
    source 105
    target 305
  ]
  edge [
    source 114
    target 708
  ]
  edge [
    source 120
    target 133
  ]
  edge [
    source 120
    target 714
  ]
  edge [
    source 121
    target 786
  ]
  edge [
    source 123
    target 162
  ]
  edge [
    source 124
    target 692
  ]
  edge [
    source 124
    target 129
  ]
  edge [
    source 129
    target 544
  ]
  edge [
    source 130
    target 692
  ]
  edge [
    source 133
    target 333
  ]
  edge [
    source 134
    target 769
  ]
  edge [
    source 134
    target 264
  ]
  edge [
    source 134
    target 307
  ]
  edge [
    source 134
    target 834
  ]
  edge [
    source 135
    target 601
  ]
  edge [
    source 135
    target 305
  ]
  edge [
    source 139
    target 430
  ]
  edge [
    source 140
    target 873
  ]
  edge [
    source 140
    target 877
  ]
  edge [
    source 142
    target 211
  ]
  edge [
    source 144
    target 892
  ]
  edge [
    source 148
    target 622
  ]
  edge [
    source 151
    target 422
  ]
  edge [
    source 154
    target 199
  ]
  edge [
    source 155
    target 180
  ]
  edge [
    source 155
    target 565
  ]
  edge [
    source 161
    target 711
  ]
  edge [
    source 165
    target 806
  ]
  edge [
    source 173
    target 582
  ]
  edge [
    source 174
    target 657
  ]
  edge [
    source 183
    target 199
  ]
  edge [
    source 184
    target 869
  ]
  edge [
    source 184
    target 649
  ]
  edge [
    source 194
    target 481
  ]
  edge [
    source 199
    target 265
  ]
  edge [
    source 199
    target 285
  ]
  edge [
    source 199
    target 575
  ]
  edge [
    source 199
    target 781
  ]
  edge [
    source 200
    target 297
  ]
  edge [
    source 202
    target 704
  ]
  edge [
    source 202
    target 614
  ]
  edge [
    source 204
    target 667
  ]
  edge [
    source 204
    target 651
  ]
  edge [
    source 206
    target 432
  ]
  edge [
    source 211
    target 294
  ]
  edge [
    source 212
    target 225
  ]
  edge [
    source 221
    target 356
  ]
  edge [
    source 225
    target 358
  ]
  edge [
    source 227
    target 763
  ]
  edge [
    source 231
    target 587
  ]
  edge [
    source 232
    target 708
  ]
  edge [
    source 238
    target 372
  ]
  edge [
    source 240
    target 378
  ]
  edge [
    source 246
    target 373
  ]
  edge [
    source 248
    target 822
  ]
  edge [
    source 248
    target 761
  ]
  edge [
    source 250
    target 563
  ]
  edge [
    source 250
    target 854
  ]
  edge [
    source 250
    target 707
  ]
  edge [
    source 262
    target 824
  ]
  edge [
    source 263
    target 438
  ]
  edge [
    source 263
    target 842
  ]
  edge [
    source 264
    target 729
  ]
  edge [
    source 266
    target 799
  ]
  edge [
    source 269
    target 483
  ]
  edge [
    source 285
    target 422
  ]
  edge [
    source 288
    target 487
  ]
  edge [
    source 292
    target 571
  ]
  edge [
    source 295
    target 547
  ]
  edge [
    source 298
    target 573
  ]
  edge [
    source 298
    target 500
  ]
  edge [
    source 309
    target 692
  ]
  edge [
    source 316
    target 824
  ]
  edge [
    source 317
    target 319
  ]
  edge [
    source 320
    target 843
  ]
  edge [
    source 324
    target 850
  ]
  edge [
    source 326
    target 661
  ]
  edge [
    source 326
    target 522
  ]
  edge [
    source 327
    target 693
  ]
  edge [
    source 328
    target 860
  ]
  edge [
    source 334
    target 723
  ]
  edge [
    source 336
    target 865
  ]
  edge [
    source 336
    target 601
  ]
  edge [
    source 339
    target 870
  ]
  edge [
    source 340
    target 741
  ]
  edge [
    source 342
    target 817
  ]
  edge [
    source 343
    target 500
  ]
  edge [
    source 349
    target 530
  ]
  edge [
    source 355
    target 829
  ]
  edge [
    source 356
    target 706
  ]
  edge [
    source 357
    target 569
  ]
  edge [
    source 360
    target 824
  ]
  edge [
    source 371
    target 430
  ]
  edge [
    source 373
    target 692
  ]
  edge [
    source 374
    target 432
  ]
  edge [
    source 381
    target 730
  ]
  edge [
    source 385
    target 792
  ]
  edge [
    source 387
    target 484
  ]
  edge [
    source 390
    target 741
  ]
  edge [
    source 391
    target 487
  ]
  edge [
    source 393
    target 741
  ]
  edge [
    source 397
    target 837
  ]
  edge [
    source 400
    target 557
  ]
  edge [
    source 417
    target 786
  ]
  edge [
    source 430
    target 556
  ]
  edge [
    source 433
    target 601
  ]
  edge [
    source 434
    target 487
  ]
  edge [
    source 439
    target 753
  ]
  edge [
    source 444
    target 490
  ]
  edge [
    source 450
    target 788
  ]
  edge [
    source 456
    target 728
  ]
  edge [
    source 458
    target 708
  ]
  edge [
    source 461
    target 753
  ]
  edge [
    source 463
    target 790
  ]
  edge [
    source 473
    target 601
  ]
  edge [
    source 476
    target 841
  ]
  edge [
    source 478
    target 487
  ]
  edge [
    source 480
    target 668
  ]
  edge [
    source 487
    target 895
  ]
  edge [
    source 488
    target 824
  ]
  edge [
    source 490
    target 766
  ]
  edge [
    source 496
    target 695
  ]
  edge [
    source 499
    target 730
  ]
  edge [
    source 500
    target 520
  ]
  edge [
    source 501
    target 850
  ]
  edge [
    source 505
    target 888
  ]
  edge [
    source 506
    target 843
  ]
  edge [
    source 510
    target 837
  ]
  edge [
    source 514
    target 789
  ]
  edge [
    source 520
    target 573
  ]
  edge [
    source 520
    target 566
  ]
  edge [
    source 521
    target 816
  ]
  edge [
    source 541
    target 801
  ]
  edge [
    source 544
    target 692
  ]
  edge [
    source 547
    target 824
  ]
  edge [
    source 549
    target 708
  ]
  edge [
    source 550
    target 770
  ]
  edge [
    source 554
    target 601
  ]
  edge [
    source 566
    target 810
  ]
  edge [
    source 573
    target 810
  ]
  edge [
    source 574
    target 753
  ]
  edge [
    source 574
    target 727
  ]
  edge [
    source 579
    target 763
  ]
  edge [
    source 581
    target 591
  ]
  edge [
    source 582
    target 761
  ]
  edge [
    source 590
    target 732
  ]
  edge [
    source 597
    target 753
  ]
  edge [
    source 597
    target 727
  ]
  edge [
    source 601
    target 627
  ]
  edge [
    source 601
    target 702
  ]
  edge [
    source 601
    target 711
  ]
  edge [
    source 623
    target 863
  ]
  edge [
    source 629
    target 646
  ]
  edge [
    source 636
    target 653
  ]
  edge [
    source 640
    target 888
  ]
  edge [
    source 646
    target 760
  ]
  edge [
    source 655
    target 814
  ]
  edge [
    source 663
    target 675
  ]
  edge [
    source 671
    target 824
  ]
  edge [
    source 674
    target 738
  ]
  edge [
    source 683
    target 753
  ]
  edge [
    source 689
    target 698
  ]
  edge [
    source 699
    target 872
  ]
  edge [
    source 704
    target 789
  ]
  edge [
    source 708
    target 864
  ]
  edge [
    source 712
    target 756
  ]
  edge [
    source 716
    target 737
  ]
  edge [
    source 730
    target 842
  ]
  edge [
    source 743
    target 754
  ]
  edge [
    source 753
    target 847
  ]
  edge [
    source 753
    target 791
  ]
  edge [
    source 794
    target 827
  ]
]
