graph [
  node [
    id 0
    label "CTTTTTATGGGAAGGCT--AGCTCTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 1
    label "GGTGTCGCGACACCGCC--GGCATGGTACCATAGCGGCCGCT"
  ]
  node [
    id 2
    label "GGTGCCATGGCACCGCC--GGCAGGGTACCTTCCCGGCCGGG"
  ]
  node [
    id 3
    label "GGCGCTGCAGCGCCCCC--GGGGAAGTACTTTGCCGGCCGGT"
  ]
  node [
    id 4
    label "GGCGACGCGTCGCCGCC--GGCGAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 5
    label "GGCGGCATGCCGCCGCC--GGCAAGGATCCTTATCGGCCGAT"
  ]
  node [
    id 6
    label "GCCGCCGCGGCGGCCCC--GGGTCGGGCCCGAGGGGGCCCCC"
  ]
  node [
    id 7
    label "GGCGACATGTCGCCGCC--GGCGAGGTACCTCCCCGGCCGGG"
  ]
  node [
    id 8
    label "GGCTGGATCCAGCCGCA--TGCACCGATCGGTGTGAGCTCAC"
  ]
  node [
    id 9
    label "GGTCCGGCCGGACCGCA--TGCGCGGATCCGCGTGGGCCCGC"
  ]
  node [
    id 10
    label "GGGGGTATGCCCCTGCTCGAGCTTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 11
    label "GGCGCGATCGCGCCGCA--TGCGCGGCGCCGTACCGGCCGGT"
  ]
  node [
    id 12
    label "GGGGGTGCGCCCCCGCTCGAGCTTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 13
    label "GGCGGCATGCCGCCGCC--GGCGAGGTACCTCCCCGGCCGGG"
  ]
  node [
    id 14
    label "GGTATCGCGATACCGCC--GGCCAGCTAGCTGAGCGGCCGCT"
  ]
  node [
    id 15
    label "GGGGGTGTACCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 16
    label "GGCGACGCGTCGCCGCG--CGCGCGGCGCCGTACCGGCCGGT"
  ]
  node [
    id 17
    label "GCTGAGATCTCAGCGCG--CGCATGGATCCATCCCGGCCGGG"
  ]
  node [
    id 18
    label "GGGGGTATGCCCCTGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 19
    label "GGTCTGATCAGACCGCC--GGCGAGGTACCTCAGCGGCCGCT"
  ]
  node [
    id 20
    label "GGGGGTATGCCCCCGCTCGAGCTTTGGTCAAGCCTGGCCAGG"
  ]
  node [
    id 21
    label "GGCAGTGCACTGCCGCC--GGCTAGGTACCTACTTGGCCAAG"
  ]
  node [
    id 22
    label "GGGGGTATACTCCCGCTTGAGCTTTGATCAAGTCTGGCCAGA"
  ]
  node [
    id 23
    label "GGTGGTGCGCCACCGCC--GGCACGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 24
    label "GGGCCAGCTGGCTCGCG--CGTTCTGATCAGACTAGGCCTGG"
  ]
  node [
    id 25
    label "GAGCCGTACGGCTCGCC--GGCGAGGATCCTCGCCGGCCGGC"
  ]
  node [
    id 26
    label "TCCCGG--CTGGGAGCT--AGCTCTGCGCAGACTGGGCCTGG"
  ]
  node [
    id 27
    label "GGCGTCATGACGCCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 28
    label "GCCCCCGCGGGGGCGGC--GCCCCGGCGCCGGGCAGGCCTGC"
  ]
  node [
    id 29
    label "GGGGGCATGCTCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 30
    label "GCGGCCGCGGCCGCGCG--CGCTCGCCGGCGAGCCGGCCGGC"
  ]
  node [
    id 31
    label "GGTGGAGCTCCACCGCC--GGCACGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 32
    label "GGGGGTGCGCCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 33
    label "GGCGACGCGTCGCCGCC--GGCGAGGCGCCTTCCCGGCCGGG"
  ]
  node [
    id 34
    label "GGGGGCATGCCCCCCTT--GAGTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 35
    label "GGCACCATGGTGCCGCC--GGCGAGGTACCTTTCCAGCTGGA"
  ]
  node [
    id 36
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 37
    label "GCCCGGGCCCGGGCGCA--TGCTCTGATCGGAGTGAGCTCAT"
  ]
  node [
    id 38
    label "GGCGGCATGCCGCCGCC--GGCGAGGTACCTCCCCAGCTGGG"
  ]
  node [
    id 39
    label "GGCGCCATGGCGCCGCC--GGCAGGGTATCCTCCCGGCCGGG"
  ]
  node [
    id 40
    label "GCACTAGCTAGTGCTCG--CGAACGGATCCGTGCAGGCCTGC"
  ]
  node [
    id 41
    label "GGCCGTGCACGGCCCCC--GGGCTCGCGCGAGGCGGGCCCGC"
  ]
  node [
    id 42
    label "GTAGTC--GACTGCGCC--GGCATGGATCCATGCAGGCCTGC"
  ]
  node [
    id 43
    label "GCCTGG--TCGGGCGCT--AGCTCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 44
    label "GGTTCCTAGGAACCGCC--GGCATAGATCTGTATCGGCCGAT"
  ]
  node [
    id 45
    label "GGGGGCATGTCCCCGCTCGAGCTTTGATCAAGCCTAGCTGGG"
  ]
  node [
    id 46
    label "GCCAAGGCCTTGGCGCTTAAGCATGGATCCATGGGAGCTCTC"
  ]
  node [
    id 47
    label "GGCCACGCGTGGCCGCG--CGCGAGGATCCTTCCCGGCCGGG"
  ]
  node [
    id 48
    label "GCCAAGGCCTTGGCGCTTAAGCGTGGATCCATGTGAGCTCAC"
  ]
  node [
    id 49
    label "GGTGGAGCTCCACCGCC--GGCGCGGATCCGTACGGGCCCGT"
  ]
  node [
    id 50
    label "GGCATCGCGATGCCGCC--GGCGAGCTAGCTTAGCAGCTGCT"
  ]
  node [
    id 51
    label "GGCGACGCGTCGCCGCA--TGCGCGGTACCGCGCGGGCCCGC"
  ]
  node [
    id 52
    label "GGCGCGGCCGCGCCGCA--TGCGCGGCGCCGTACCGGCCGGT"
  ]
  node [
    id 53
    label "GGGGGTATACTCCCGTTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 54
    label "TCCTGG--TCAGGAGCT--AGTTCTGCGCAGACCAGGCCTGG"
  ]
  node [
    id 55
    label "GGCTTCGCGAAGCCTCC--GGAGCGGTACCGTAGCGGCCGCT"
  ]
  node [
    id 56
    label "GGCGGCATGCCGCCGCC--GGCGAGGATCCTTTCCAGCTGGA"
  ]
  node [
    id 57
    label "GGCGGTGCGCCGCCGCC--GGCGAGGTACCTTGTCGGCCGAT"
  ]
  node [
    id 58
    label "GGTGGCATGCCACCGCC--GGCGAGGTACCTCCCCAGCTGGG"
  ]
  node [
    id 59
    label "GGCCTCGCGAGGCCGCG--CGCGAGGATCCTTGCCGGCCGGC"
  ]
  node [
    id 60
    label "GGCGCGGCCGCGCCGCC--GGCAAGGTACCTTGTCGGCCGAC"
  ]
  node [
    id 61
    label "GGGGGTATACCCCCGCTCGAGCTTTGATCAAGCCTAGCTAGG"
  ]
  node [
    id 62
    label "TCCCAG--CTGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 63
    label "GGTGCCTAGGCACCGTC--GGCTGGAGCTCCAGTCAGCTGAC"
  ]
  node [
    id 64
    label "GGCGGGTACCCGCCGCG--CGCGCGGATCCGTACCGGCCGGT"
  ]
  node [
    id 65
    label "GGCGCCGCGGCGCCCCC--GGGGAGGTACCTTGACAGCTGTC"
  ]
  node [
    id 66
    label "GGCGTCGCGATGCCGCC--GGCGGGCTAGCTCTCCGGCCGGA"
  ]
  node [
    id 67
    label "GGCGCCGCGGCGCCCCC--GGGGAGGCGCCTTGCCGGCCGGC"
  ]
  node [
    id 68
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGTCTGGCCAGG"
  ]
  node [
    id 69
    label "GGGGGTATGTCCCCGCTCGAGTTTTGATCAAGTCTGGCCGGA"
  ]
  node [
    id 70
    label "GGGCCAGCTGGCTCGTG--CGCTCTGATTAGACCAGGCTTGG"
  ]
  node [
    id 71
    label "GCCGGGATCCCGGCGCCTAGGCGTGGATCCGCGGGGGCCCCC"
  ]
  node [
    id 72
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGTCTGGCCAGA"
  ]
  node [
    id 73
    label "GGGCTGGTTAGCCCGCTCGAGCTGAGATCTTAGCGTGCACGC"
  ]
  node [
    id 74
    label "GGCGGCATGCCGCCGCC--GGCGAGGTATCTTCCCAGCTGGG"
  ]
  node [
    id 75
    label "TCCCGG--TTGGGAGCT--AGCTCTGCGCAGGTCGGGCCTGA"
  ]
  node [
    id 76
    label "TCCCTA--TAGGGAGCT--AGCTCTGCGCAGGCTGGGCCCAG"
  ]
  node [
    id 77
    label "GGCACG--CGTGCCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 78
    label "GGCGACATGTCGCCGCC--GGCGCGGTACCGCCCCGGCCGGG"
  ]
  node [
    id 79
    label "GGCCTTGCAAGGCCGCG--CGCGAGGATCCTTCCCGGCCGGG"
  ]
  node [
    id 80
    label "GGTCCTGCGGGACCGCC--GGCGAGCTAGCTTAGCGGCCGCT"
  ]
  node [
    id 81
    label "GGGGGTGCGCCCCTGCTCGAGCTTTGATCAAGCTTGGCCAAG"
  ]
  node [
    id 82
    label "GGTGGTATACCACCGCC--GGCACGGTACCGTACGGGCCCGT"
  ]
  node [
    id 83
    label "GGTGCCGCGGCACCCCC--GGGAAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 84
    label "GGTGCGGTCGCACCGCC--GGCATGGATCCATGTGGGCCCAC"
  ]
  node [
    id 85
    label "GGCGACATGTCGCCGCC--GGCAGGGTACCCTCCCGGCCGGG"
  ]
  node [
    id 86
    label "GCCGTG--CACGGCGCTCGAGCGCAGATCTGTCCCGGCCGGG"
  ]
  node [
    id 87
    label "GGGGGTATGCCCCCGTTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 88
    label "GGCGCTATGGCGCCGCC--GGCGAGGCGCCTTCCCAGCTGGG"
  ]
  node [
    id 89
    label "GGCGGCGCGCCGCCGCC--GGCGAGGCGCCTTAGCGGCCGCT"
  ]
  node [
    id 90
    label "GCCAGGGCCCTGGCGCA--TGCGTGGATCCACCCCGGCCGGG"
  ]
  node [
    id 91
    label "GGGGGTATGTTCCCGCTCGAGCTTTGATCAAGCCTAGCTGGG"
  ]
  node [
    id 92
    label "GGTGCGGCCGCACCGCC--GGCGCAGTACTGCGCGGGCCCGC"
  ]
  node [
    id 93
    label "TTCCTGGCCGGGAAGCT--AGTTCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 94
    label "GGCGCCGCGGTGCCGCC--GGCGAGCTAGCTCAGCGGCCGCT"
  ]
  node [
    id 95
    label "CCTTCGATCGAAGGGCTCGAGCGAGGATCCTTGCCGGCTGGC"
  ]
  node [
    id 96
    label "TCCCTA--TAGGGAGCT--AGCTCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 97
    label "GGGGGTATACCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 98
    label "TCCGTG--TACGGAGCT--AGCTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 99
    label "GGTGACGCGTCACCGCC--GGCAGGCTAGCTTGGGGGCCCTC"
  ]
  node [
    id 100
    label "GGGGGCATGTCCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 101
    label "TCCCTG--TGGGGAGCT--AGCTCTGCGTGGACCAGGCCTGG"
  ]
  node [
    id 102
    label "CCTGGC--GTCGGGGCTCGAGCTCTGATCAGGGTGGGCCCGC"
  ]
  node [
    id 103
    label "GTCCTG--TAGGGCGCTCGAGTCTCGCGCGAGCTGGGCTCGG"
  ]
  node [
    id 104
    label "GGGTCCATGGGCCCGCTCGAGCATTGATCAATTCCGGCCGGA"
  ]
  node [
    id 105
    label "GCCGGTGCGCCGGCGCA--TGCTTCGCGCGAAGGGGGCCCTC"
  ]
  node [
    id 106
    label "GGCTGGATCCAGCCGCA--TGCGCGGATCCGTATCGGCCGAT"
  ]
  node [
    id 107
    label "TCCCTG--TGGGGAGCT--AGCTCTGCGCAGACCAGGCCTGG"
  ]
  node [
    id 108
    label "TCCCTG--TGGGGAGCT--AGCTCTGTACGGGCCAGGCCTGG"
  ]
  node [
    id 109
    label "TCCCTG--CAGGGAGCT--AGCTCTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 110
    label "GCCGGGATCCCGGCGCCTAGGCGCGGATCCGCGGGGGCCCCC"
  ]
  node [
    id 111
    label "GGGGGTATGCCCCCGCTCGAGCCTTGATCAAGCTTGGCCAGG"
  ]
  node [
    id 112
    label "GGCGCCATGGCGCCGCC--GGCGAGGTACCTTACCGGCCGGT"
  ]
  node [
    id 113
    label "GGCGCGTACGTGCCGCA--TGCGCGGATCCGTTCCGGCCGGA"
  ]
  node [
    id 114
    label "GGCTGGATCCGGCCGCA--TGCGAGGATCCTTACCGGCCGGT"
  ]
  node [
    id 115
    label "GGCGCTATGGCGCCGCC--GGCGAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 116
    label "GGCGGGGCCCCGCCGCA--TGCGCGGCGCCGTGACGGCCGTC"
  ]
  node [
    id 117
    label "GGACTGGTCAGTCCGCTCGAGCTGCGATCGCAAGTGGCCGCT"
  ]
  node [
    id 118
    label "GGCGGTGCGCCGCCGCC--GGCACGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 119
    label "GGAACCATGGTTCCGCC--GGCGCAGCGCTGCGCCGGCCGGC"
  ]
  node [
    id 120
    label "GGTCGCGCGCGACCGCC--GGCGAGGTACCTTGGCGGCCGCC"
  ]
  node [
    id 121
    label "TCCCGG--TTGGGAGCT--AGTTCTGTGCAGGCCAGGCCTGG"
  ]
  node [
    id 122
    label "GGGGGTATGCCCCCGTC--GACTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 123
    label "GGCCGAGCTCGGCCGCA--TGCGCGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 124
    label "GTACACATGTGTACCCG--CGGTTAGATCTAAGTGAGCTCAC"
  ]
  node [
    id 125
    label "GCCAAGGCCTTGGCGCG--CGCATCGCGCGATCCCGGCCGGG"
  ]
  node [
    id 126
    label "GGGGGA--TCCCCCGCTTGAGCTTTGATCAAGTCTGGCCAGG"
  ]
  node [
    id 127
    label "GGCGGCATGCCGCCGCC--GGCGAGGTACCTTTCCAGCTGGA"
  ]
  node [
    id 128
    label "TCCCTG--TGGGGAGCT--AGCTCTGCGCAGGCCAGGCTTGG"
  ]
  node [
    id 129
    label "GACCGTGCACGGTCCCC--GGGCTCGTGCGAGGCGGGCCCGC"
  ]
  node [
    id 130
    label "TCCTTGGTCAAGGAGTC--GACCGTGCGCACGCTGGGCCTGG"
  ]
  node [
    id 131
    label "GGCGACGCGTCGCCGCC--GGCGTGGTACCATAGCGGCCGCT"
  ]
  node [
    id 132
    label "GGCCGTGCACGGCCCCC--GGGCTCGCGCGAGGTGGGCCCGC"
  ]
  node [
    id 133
    label "TCCCAAGCTTGGGACTT--AAGTCTGTGCAGGCCAGGCCTGG"
  ]
  node [
    id 134
    label "GGCGACATGTCGCCGCC--GGCGTGGTACCGCATGGGCCCAT"
  ]
  node [
    id 135
    label "GGTTCCGCGGAACCGCC--GGCATGGATCCGTGCCGGCCGGC"
  ]
  node [
    id 136
    label "GACCAAATTTGGTTACATATGTGTGGGCCCATACTGGCCAGT"
  ]
  node [
    id 137
    label "GCCAAGATCTTGGCGCG--CGCATCGCGCGATTCCAGCTGGA"
  ]
  node [
    id 138
    label "GGCGGG--CCCGCCGCC--GGCGAGGTACCTTGTCGGCCGAT"
  ]
  node [
    id 139
    label "GGCGACGCGTCGCCGCC--GGCGCGGCGCCGTCCCGGCCGGG"
  ]
  node [
    id 140
    label "GGCTAAATTTAGCCACATATGTGTGGGCCCATACTGGCCAGT"
  ]
  node [
    id 141
    label "GGGGGTATGCCCCCGCTCGAGCATCGGCCGATAGCGGCCGCT"
  ]
  node [
    id 142
    label "GGCCCCGCGGGGCCGCC--GGCTGGGTACCTGGTCGGCCGAT"
  ]
  node [
    id 143
    label "GCCGGG--CCCGGCGTC--GGCGAGATATCTTGATGGCCATC"
  ]
  node [
    id 144
    label "GGCGCCGCGGCGCCGCC--GGCGAGGTACCTCGCCGGCCGGC"
  ]
  node [
    id 145
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAACCTGGCCGGG"
  ]
  node [
    id 146
    label "GGGTCCATGGGCCCGCTCGAGCATTGATCAATACCGGCCGGT"
  ]
  node [
    id 147
    label "GGCGACATGTCGCCGCC--GGCAGGGTACCTTCCCGGCCGGG"
  ]
  node [
    id 148
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 149
    label "GAGGTCGCGACCTCGCA--TGCTCAGTACTGAGCGGGCCCGC"
  ]
  node [
    id 150
    label "GGGCAAGCTTGCCCGCG--CGCGCGGATCCGCACCGGCCGGT"
  ]
  node [
    id 151
    label "GGCTGAGCTCAGCCGCA--TGCGAGGCGCCTTGCCGGCCGGC"
  ]
  node [
    id 152
    label "GGGGTA--TGCCCCGCTCGAGCTTCGATCGAGCCTGGCCGGG"
  ]
  node [
    id 153
    label "GGCGGG--CCCGCCGCC--GGCGAGGTACCTTGTCGGCCGAC"
  ]
  node [
    id 154
    label "GGCGCGGCCGCGCCGCA--TGCGCGGATCCGTGGCGGCCGCC"
  ]
  node [
    id 155
    label "TCCCAG--TTGGGAGCT--AGCTCTGCGCAGGCTGGGCCTAG"
  ]
  node [
    id 156
    label "GGCGGCATGCCGCCGCC--GGCAAGGTACCTTACCGGCCGGT"
  ]
  node [
    id 157
    label "GGGGGTATGTCCCCGCTCGAGCCTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 158
    label "GGCGACATGTCGCCGCC--GGCGAAGCGCTTTCCCAGCTGGG"
  ]
  node [
    id 159
    label "GCACCGATCGGTGCGCG--CGCCTGGTACCAGATGGGCCCAT"
  ]
  node [
    id 160
    label "GGCGCCATGGCGCCGCC--GGCGAGGTACCTCACCGGCCGGT"
  ]
  node [
    id 161
    label "GGCATA--TGTGCCGCTCGAGCTTTGATTAAGACCGGCTGGT"
  ]
  node [
    id 162
    label "TCCCTA--TAGGGACTT--GAGTCTGCGCAGACCAGGCTTGG"
  ]
  node [
    id 163
    label "GCCAAGGCCTTGGCGCTTAAGCGTGGATCCATGGGAGCTCTC"
  ]
  node [
    id 164
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCGGGCCGGGCCCGG"
  ]
  node [
    id 165
    label "GGTCGCGCGCGACCGCC--GGCGGGGTACCTCGGTGGCCACT"
  ]
  node [
    id 166
    label "GGGGGT--GCCTCTGCTCGAGCTTTGATCAAACCTGGCCAGG"
  ]
  node [
    id 167
    label "GCAGAAGCTTCTGCGCA--TGCACTGGCCAGTGAGAGCTCTC"
  ]
  node [
    id 168
    label "TTCCTG--TAGGGAGCT--AGTTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 169
    label "GGTGATGCGTCACCGCC--GGCCAGCTAGCTGAGCGGCCGCT"
  ]
  node [
    id 170
    label "GGCCACGCGTGGCCGCG--CGCGCGGATCCGCCCCGGCCGGG"
  ]
  node [
    id 171
    label "GGCTAGGCCTAGCCGCA--TGCGCGGCGCCGTGCCGGCCGGC"
  ]
  node [
    id 172
    label "GGCGGCATGCCGCCGCC--GGCGGAGATCTCCCCCGGCCGGG"
  ]
  node [
    id 173
    label "GGTGGTGCACCACCGCC--GGCGTGGTACCGTGCGGGCCCGT"
  ]
  node [
    id 174
    label "GGGGCCGCGGCCCCGCACGTGCCCGCATGCGGGTCGGCCGAC"
  ]
  node [
    id 175
    label "GGTCGGGTCCGACCGCC--GGCGAGGTACCTCAGCGGCCGCT"
  ]
  node [
    id 176
    label "GGGGGTATGTCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 177
    label "GGCGACGCGTCGCCGCC--GGCACGGCGCCGTATGGGCCCAT"
  ]
  node [
    id 178
    label "GGGCCAGCTGGCTCGTG--CGCTCTGATCAGACCAGGCCTGG"
  ]
  node [
    id 179
    label "GGCATCGCGATGCCGCC--GGCGAGCTAGCTTAGCGGCCGCT"
  ]
  node [
    id 180
    label "GGCGCCATGGCGCCGCC--GGCAGGGTACCCTCCCGGCCGGG"
  ]
  node [
    id 181
    label "GGTGGGGTCCCACCGCC--GGCGCGGCGCCGCACGGGCCCGT"
  ]
  node [
    id 182
    label "GGTGCGGCCGCACCCCC--GGGGCAGTACTGTGCCGGCCGGC"
  ]
  node [
    id 183
    label "GGTCACGCGTGACCGCC--GGCGTGGTACTATAGCGGCCGCT"
  ]
  node [
    id 184
    label "TCCCTG--TAGGGAGCT--GGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 185
    label "GGCCACGCGTGGCCGCG--CGCACGGTACCGTTCCGGCCGGA"
  ]
  node [
    id 186
    label "GGTGGGTACCCACCGCC--GGCGCGGCGCCGTACGAGCTCGT"
  ]
  node [
    id 187
    label "GCCAGGGCCCTGGCGTCTAGGCGCGGATCCGCAAGGGCCCTT"
  ]
  node [
    id 188
    label "GGGGGA--TCCCCCGCTCGAGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 189
    label "GGACGAGCTCGTCCGCTCGAGCACCGGCCGGTACGCGCGCGT"
  ]
  node [
    id 190
    label "GGCGTCATGACGCCGCC--GGCAAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 191
    label "GGGGTA--TGCCCCGCTCGAGCTTTGATCAAACCTGGCCGGG"
  ]
  node [
    id 192
    label "GCCTGG--TCGGGCGCTCGAGCTCTGATCAGGGTGGGCCCGC"
  ]
  node [
    id 193
    label "GGCCTCGCGAGGCCGCG--CGCGAGGATCCTTGGGGGCCCTC"
  ]
  node [
    id 194
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGTCTGGCCGGG"
  ]
  node [
    id 195
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGTCTGGCCGGA"
  ]
  node [
    id 196
    label "TCCTGG--TCAGGAGCT--AGCTCTGCGCAGGCCGGGCCCGG"
  ]
  node [
    id 197
    label "GGTCGAGCTCGACCGCC--GGCGAGGTACCTCAGCGGCCGCT"
  ]
  node [
    id 198
    label "GGCGATATATCGCCGTC--GGCGAGGTACCTTATCAGCTGAT"
  ]
  node [
    id 199
    label "GGCTGAGCTCAGCCGCA--TGCGTGGCGCCGCGGGGGCCCTC"
  ]
  node [
    id 200
    label "GGTGGAATTCCACCGCT--GGCACGGTACCGTACGGGCCCGT"
  ]
  node [
    id 201
    label "GGGGTA--TGCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 202
    label "GGTATCGCGATACCGCC--GGCGTGGTACCATAGCGGCCGCT"
  ]
  node [
    id 203
    label "GGTTTCGCGAGACCGCC--GGCGAGCTAGCTCAGCGGCCGCT"
  ]
  node [
    id 204
    label "GGGGGTGTGCCCCTGCTCGAGCTTCGATCGAGCCCGGCCGGG"
  ]
  node [
    id 205
    label "GGCTGGGCTCAGCCGCA--TGCGAGGCGCCTTGCCGGCCGGC"
  ]
  node [
    id 206
    label "GGGGGTATGCCCCTGTTCGAGCTTTGATCAAGCCCGGCTGGG"
  ]
  node [
    id 207
    label "TCCCTG--TGGGGAGCT--AGCTCTGCGCAGGCTGGGCCCAG"
  ]
  node [
    id 208
    label "GGTTCCTAGGAACCGCC--GGCGCGGTACCGTGGCGGCCGCC"
  ]
  node [
    id 209
    label "GGCTGCGCGCAGCCGCA--TGCGTGGCGCCATGCCGGCCGGC"
  ]
  node [
    id 210
    label "TTCTGG--TCAGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 211
    label "TCCCTG--TAGGGAGCTTAAGCCCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 212
    label "GACGCCGCGGCGTCCCC--GGGGAAGTACTTTAATGGCCGTT"
  ]
  node [
    id 213
    label "GGCTGAGCTCAGCCGCC--GGCTTGGTACCGAGTGAGCTCAC"
  ]
  node [
    id 214
    label "GGCTGAGCTCAGCCGCA--TGCGCGGCGCCGTAGCGGCCGCT"
  ]
  node [
    id 215
    label "GGCGCGCGCGCGCCGCA--TGCACGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 216
    label "GCCGAGGCCTCGGCGCTTAAGCGCGGATCCGCGTGAGCTCAC"
  ]
  node [
    id 217
    label "TCCCTG--TAGGGAGCT--AGCCCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 218
    label "GGGGGTGCGCTCCCGCC--GGCTTTGATCAAGCTTGGCCAAG"
  ]
  node [
    id 219
    label "GGCAACGCGTTGCCGCC--GGCGCGGTACCGTGAGGGCCCTC"
  ]
  node [
    id 220
    label "GGGGGTATGCCCCCGCTCGAGCTTCGATCGAGTTTGGCCGGG"
  ]
  node [
    id 221
    label "GCGGGTGCACTCGCGCT--GGCGCGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 222
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 223
    label "GGGGGTATGCCCCCGCTCGAGCTTCGATCGAGCCCGGCCGGG"
  ]
  node [
    id 224
    label "GGCGGGTACCCGCCGCC--GGCGCGGCGCCGTACCGGCCGGT"
  ]
  node [
    id 225
    label "GGCGACGCGTCGCCGCC--GGCGGGGATCCCCGGCGGCCGCC"
  ]
  node [
    id 226
    label "GGGGATATGTCCCCGCTCGAGCTTCGATCGAGCCCGGCCGGG"
  ]
  node [
    id 227
    label "GGGTCCTAGGGCCCGCTCGAGCATTGATCAATACCGGCCGGT"
  ]
  node [
    id 228
    label "GGCGCCATGGCGCCGCC--GGCGAGGTACCTTTCCAGCTGGA"
  ]
  node [
    id 229
    label "GGGGGTATGCCCCTCTC--GAGTTTGATCAAACCTGGCCAGG"
  ]
  node [
    id 230
    label "TCCCGG--TTGGGAGCT--AGCTCTGCGCAGGTCAGGCCTGG"
  ]
  node [
    id 231
    label "GGTGCCATGGCACCGCC--GGCAAGCTAGCTTCCCAGCTGGG"
  ]
  node [
    id 232
    label "GGGGGTATGCTTCCGCTCGAGCTTTGATCAAGCCTGGCTGGG"
  ]
  node [
    id 233
    label "GGCCCGATCGGGCCGCG--CGCGCGGATCCGTGCCGGCCGGC"
  ]
  node [
    id 234
    label "GGCGAAGCTTCGCCGCC--GGCGAGGTACCTCAGCGGCCGCT"
  ]
  node [
    id 235
    label "GGCGGCATGCCGCCGCC--GGCAGGGTACCCTCCCAGCTGGG"
  ]
  node [
    id 236
    label "GCCGGGATCCCGGCGCCTAGGCGGGGATCCCCCCGGGCCCGG"
  ]
  node [
    id 237
    label "GGCGGAGCTCCGCCGCC--GGCAGGGCGCCCTGCGGGCCCGC"
  ]
  node [
    id 238
    label "GGGTCCATGGGCCCGCTCGAGCATCGATCGATTCCGGCCGGA"
  ]
  node [
    id 239
    label "TCCCTG--TAGGGAGCT--AGTTCTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 240
    label "GGCGGCATGCCGCCGCC--GGCGAGGTACCTCTCCGGCCGGA"
  ]
  node [
    id 241
    label "GGGGGT--GCCCCCGCTCGAGCTTTGATCAAGCTTGGCCAAG"
  ]
  node [
    id 242
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 243
    label "GACCGTGCACGGTCCCC--GGGCTCGATCGAGACCGGCCGGT"
  ]
  node [
    id 244
    label "GGCGGCATGCCGCCGCC--GGCGCGGTACCGCTCCGGCCGGA"
  ]
  node [
    id 245
    label "GGACCGATCGGTCCGCG--CGCCTGGTACCAGATGGGCCCAT"
  ]
  node [
    id 246
    label "GGGGGTATGCCCCCGTTCGAGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 247
    label "TCCCGT--GTGGGAGCTCGAGCTTTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 248
    label "TCCCTG--TGGGGAGCT--AGTTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 249
    label "GGGGGT--GCCCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 250
    label "GGAGTA--TGCTTCGCTCGAGTTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 251
    label "GGCGCGATCGCGCCGCA--TGCGCGGATCCGCCTCGGCCGGG"
  ]
  node [
    id 252
    label "GGCGGCATGCCGCCGCC--GGCGAGGTATCTCCCCGGCCGGG"
  ]
  node [
    id 253
    label "GGTGGGGTCCCACCGCC--GGCACGGATCCGTACGGGCCCGT"
  ]
  node [
    id 254
    label "GGCCGGGCCCGGCCGCA--TGCGAGGATCCTTGTCGGCCGGT"
  ]
  node [
    id 255
    label "GCCAACGCGTTGGCGCA--TGCATTGCGCAATTCCGGCCGGA"
  ]
  node [
    id 256
    label "GGCGGGGCCCCGCCGCA--TGCACGGCGCCGTGGCGGCCGTC"
  ]
  node [
    id 257
    label "GGCGGCATGTCGCCGCC--GGCGAGGTACCTTCCCGGCCGGG"
  ]
  node [
    id 258
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGTCCGGCCGGG"
  ]
  node [
    id 259
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCAGACCGGGCCTGG"
  ]
  node [
    id 260
    label "GGACCGGTCGGTCCGCTCGAGCTGCGATCGCAGCTGGCCGGC"
  ]
  node [
    id 261
    label "GGGGTA--TGCCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 262
    label "GGGGTA--TGCCCCGCT--AGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 263
    label "GCCGGGATCCCGGCGCCTAGGCGGGGATCCCCGGGGGCCCCC"
  ]
  node [
    id 264
    label "GGTTCCTAGGAACCGAT--GTCGCGGTACCGTGGCGGCCGCC"
  ]
  node [
    id 265
    label "GGCGCTGCAGCGCCGCC--GGCGAGCTAGCTCACCGGCCGGT"
  ]
  node [
    id 266
    label "GGCCTCGCGAGGCCGCG--CGCGAGGATCCTTCCCGGCCGGG"
  ]
  node [
    id 267
    label "GGCTGG--CCAGCCGCA--TGCGCGGCGCCGTGCCGGCCGGC"
  ]
  node [
    id 268
    label "GGGGTG--TGCCTCGCTCGAGCTTTGGTCAAGTCTGGCCAGG"
  ]
  node [
    id 269
    label "GGCGACGCGTCGCCGCC--GGCGAGGCGCCTTCCCAGCTGGG"
  ]
  node [
    id 270
    label "GGCGGGGTCCCGCCGCC--GGCACGGTATCGTGCGGGCCCGC"
  ]
  node [
    id 271
    label "GGCGGCGCGCCGCCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 272
    label "GGTAGTGTACTACCGCC--GGCACGGTACCGTGCCGGCCGGT"
  ]
  node [
    id 273
    label "GCCAGGATCCTGGCGCG--CGCGCTGATCAGCCCCGGCCGGG"
  ]
  node [
    id 274
    label "TCCCGG--CTGGGAGCT--AGCTCTGCGTAGGCCAGGCCTGG"
  ]
  node [
    id 275
    label "GGGGTG--TGTCCCGCTCGAGTTTTGATCAAGCTTGGTCAAG"
  ]
  node [
    id 276
    label "GGGGGTATGTCCCCGCTCGAGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 277
    label "GGTCCTGCGGGACCGCC--GGCGAGCTAGCTCAGCGGCCGCT"
  ]
  node [
    id 278
    label "GGCGACATGTCGCCGCC--GGCGAGGTACCTTCCCGGCCGGG"
  ]
  node [
    id 279
    label "GGGGTA--TGCCCCGCTCGAGCTTTGATCAAGCCTAGCTGGG"
  ]
  node [
    id 280
    label "GGCGGCATGCCGCCGCC--GGCGCGGTACCGTTCCGGCCGGA"
  ]
  node [
    id 281
    label "GGCGCTGCGGCGCCCCC--GGGAAGGTACCTTGTCGGCCGAC"
  ]
  node [
    id 282
    label "GGCGGCATGCCGCCGCC--GGCGGGGATCCTTCCTAGCTAGG"
  ]
  node [
    id 283
    label "GGCGCGTACGCGCCACA--TGTGCGGATCCGTTCCGGCCGGA"
  ]
  node [
    id 284
    label "GACTCCTAGGGGTCGCTATAGCTGCGATCGCACCGTGCACGG"
  ]
  node [
    id 285
    label "AGTGTGGCCATACTACATATGTACGGTACCGTATTGGCCAAT"
  ]
  node [
    id 286
    label "GGGGGCATGCCCCCGTC--GACTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 287
    label "GGTGGAGCTCCACCGCC--GGCGCGGCGCCGCATAGGCCTGT"
  ]
  node [
    id 288
    label "GGTGACGCGTCACCACC--GGTGAGGTACCTCAGCGGCCGCT"
  ]
  node [
    id 289
    label "GGCGTGTACGCGCCGCA--TGCGCGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 290
    label "GGGGGTATGCTCCCGCTCGAGCTTTGATCAAGTCTGGCCAGA"
  ]
  node [
    id 291
    label "GGCTGGGCCCAGCCGTA--TGCGCGGATCCGCGCCGGCCGGC"
  ]
  node [
    id 292
    label "GGACCGGTCGGTCCGCTCGAGCTTCGGCCGAAACGCGCGCGT"
  ]
  node [
    id 293
    label "GGCGGTGCACCGCCGCC--GGCCGGCTAGCTGCCCAGCTGGG"
  ]
  node [
    id 294
    label "TCCCTG--TGGGGAGCT--AGTTCTGTGCAGGCCAGGCCTGG"
  ]
  node [
    id 295
    label "GGCGGGGCCCCGCCGCC--GGCGGGCTAGCCCGTGGGCCCAC"
  ]
  node [
    id 296
    label "TCCCGG--TTGGGAGCT--AGTTCTGTGTAGACCAGGCCTGG"
  ]
  node [
    id 297
    label "TCCCTG--TGGGGACTC--GAGTCTGCGCAGACCGGGCCTGG"
  ]
  node [
    id 298
    label "GGTGGAGCTCCACCGCT--AGCACAGCGCTGTACGGGCCCGT"
  ]
  node [
    id 299
    label "TCCCTA--TGGGGAGCT--AGCTCTGTACAGGCCGGGCCTGG"
  ]
  node [
    id 300
    label "GGCCGGGCCCGGCCGCG--CGCGAGGTACCTTGTGGGCCCAC"
  ]
  node [
    id 301
    label "GCTGAGATCTTAGCGCG--CGCATGGATCCATCCCGGCCGGG"
  ]
  node [
    id 302
    label "GGGGGTATGCCCCCCTC--GAGTTTGATCAAGCTCAGCTGGG"
  ]
  node [
    id 303
    label "GGCGCAATTGCGCCGCA--TGCGCGGATCCGTGGCGGCCGTC"
  ]
  node [
    id 304
    label "GCTCGTATGCGAGTGCGCGCGCGCAGATCTGTCTTAGCTGAG"
  ]
  node [
    id 305
    label "GGGGTA--TGCTCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 306
    label "GGGGGTATGCCCCCGCTTAAGCTTCGATCGAGCCCGGCCGGG"
  ]
  node [
    id 307
    label "GGGGGTATACCCCCCTC--GAGTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 308
    label "GGAGGTATACCTCCGCA--TGCTCGGATCCGAGTTGGCCGAC"
  ]
  node [
    id 309
    label "GGAGGTATGCCTCCGCTCGAGCATCGGCCGATAGCGGCCGCT"
  ]
  node [
    id 310
    label "GGCGCCTAGGCGCCGCA--TGCGCGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 311
    label "GGCGCGATCGCGCCGCA--TGCGCGGCGCCGTATCGGCCGGT"
  ]
  node [
    id 312
    label "GGCGCTATGGCGCCGCC--GGCAGGGTACCCTCCCAGCTGGG"
  ]
  node [
    id 313
    label "GGCGTCGCGACGCCCCC--GGGAAAGTACTTTGCCGGCCGGT"
  ]
  node [
    id 314
    label "TCCCGC--GTGGGAGCT--AGTTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 315
    label "GGCAGCATGCTGCCGTC--GGCGAGGTACCTTATCAGCTGAT"
  ]
  node [
    id 316
    label "GGCCGGGCCCGGCCGCA--TGCACCGATCGGTGTGAGCTCAC"
  ]
  node [
    id 317
    label "GGCGACGCGTCGCCGCC--GGCGAGGTATCTCGCCGGCCGGC"
  ]
  node [
    id 318
    label "GGGGGTATGCCCCCGCT--AGCTTTGATCAAGTCTGGCCGGA"
  ]
  node [
    id 319
    label "GGCCTTGCGAGGCCGCG--CGCGAGGATCCTTCCCGGCCGGG"
  ]
  node [
    id 320
    label "GGCCCTATGGGGCCGCG--CGCGCGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 321
    label "GGCTGGGCCCAGCCGCA--TGCGCGGCGCCGTGCCGGCCGGC"
  ]
  node [
    id 322
    label "GGCGGCGCGCCGCCGCC--GGCGCGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 323
    label "GGCGCGATCGCGCCGCA--TGCCCGGATCCGGACCAGCTGGT"
  ]
  node [
    id 324
    label "GGTACTTAGGTACCGCC--GGCGTGGTACCATAGCGGCCGCT"
  ]
  node [
    id 325
    label "TCCCTG--TAGGGAGCT--AGCTCTGTGCAGACCGGGCCTGG"
  ]
  node [
    id 326
    label "GGCCGTGCACGGCCCCC--GGGCTCGATCGAGGTGGGCCCGC"
  ]
  node [
    id 327
    label "GCCAAGATCTTGGCGCG--CGCGTGGATCCATCCCGGCCGGG"
  ]
  node [
    id 328
    label "GGCGACGCGTCGCCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 329
    label "GCCAGGTACCTGGCGCG--CGCACTGCGCAGTGCCTGCAGGC"
  ]
  node [
    id 330
    label "GGTGGGATCCCACCGCC--GGCACGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 331
    label "GGCGACGCGTCGCCGCC--GGCGGGGTACCCCAGCGGCCGCT"
  ]
  node [
    id 332
    label "TCCCTG--TAGGGAGCTTAAGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 333
    label "GGCACCATGGTGCCGCC--GGCTGGGTACCCAACCGGCCGGT"
  ]
  node [
    id 334
    label "GGCCCGGCCGGGCCGCG--CGCGCGGATCCGTGCCGGCCGGC"
  ]
  node [
    id 335
    label "GGGGTG--TGTCCCGCTCGAGCTTTGATCAAGCCTGGCTGGG"
  ]
  node [
    id 336
    label "GGGGGCATGTCCCCGCTCGAGCTTTGATCAAGCCTAGCTAGG"
  ]
  node [
    id 337
    label "GGACGGATTCGTCCGCTCGAGCACCGGCCGGTACGCGCGCGT"
  ]
  node [
    id 338
    label "GGCGACATGTCGCCGCC--GGCGGGGTACCCTCCCAGCTGGG"
  ]
  node [
    id 339
    label "GGAGTGGCCACTCCGTTTAAACGCGGGCCCGCACAGGCCTGT"
  ]
  node [
    id 340
    label "GCCAAGGCCTTGGCGCG--CGCGTTGATCAACTCCGGCCGGA"
  ]
  node [
    id 341
    label "GGCGCCATGGCGCCGCC--GGCAAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 342
    label "GGGGGTATGCCCCCGCTCGAGCTTCGATCGAGCCTGGCCGGG"
  ]
  node [
    id 343
    label "TCCCAC--GTGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 344
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 345
    label "GGCGGCGCGCCGCCGCC--GGCACGGCGCCGTCGGGGCCCCG"
  ]
  node [
    id 346
    label "GGCGAGGCCTCGCCGCA--TGCGCGGCGCCGTATGGGCCCGT"
  ]
  node [
    id 347
    label "GGCGTGTATGCGCCGCA--TGCGCGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 348
    label "GCACCGGCCGGTGCGCG--CGCCTGGTACCAGGTGGGCCCAC"
  ]
  node [
    id 349
    label "TCCTGGCGTCAGGAGCT--AGCTCTGTGTGGGCCAGGTCTGG"
  ]
  node [
    id 350
    label "GGTTCTTAGGAACCGCC--GGCATGGTACCATAGCGGCCGCT"
  ]
  node [
    id 351
    label "GGGGGTGTGCCCCCGCTCGAGCTTTGATCAAGCCTAGCTGGG"
  ]
  node [
    id 352
    label "TTCTGG--TCGGAAGCT--AGCCCTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 353
    label "TCCTGG--TCAGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 354
    label "GGCGACATGTCGCCGCC--GGCGAGGTACCTCGGCGGCCGCC"
  ]
  node [
    id 355
    label "GGCCACGCGTGGCCGCG--CGCGCGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 356
    label "GGCGGCATGCCGCCGCC--GGCGAGGATCCTTACCGGCCGGT"
  ]
  node [
    id 357
    label "GTATCTATAGATACGCG--CGCCTAGTACTAGGTGGGCCCAC"
  ]
  node [
    id 358
    label "TCCCTGGTCAGGGACTT--AGGTCTGCGTAGGCCAGGCCTGG"
  ]
  node [
    id 359
    label "TCTTGT--ACAAGAGTC--GACATGCTAGCATACAGGCCTGT"
  ]
  node [
    id 360
    label "GGGGTG--TGCCCCGCTCGAGCTTTGATCAAGTCTGGCCAGA"
  ]
  node [
    id 361
    label "TCCCTG--CAGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 362
    label "GGGTCG--CGGCCCGCTCGAGCATTGATCAATACAGGCCTGT"
  ]
  node [
    id 363
    label "GGCGGGTATCCGCCGCA--TGCGCGGATCCGTACCAGCTGGT"
  ]
  node [
    id 364
    label "GGGGGTGTGCCCCCGCTCGAGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 365
    label "GGGGGTGTGCCCCCGCTCGAGCTTTGATCAAGTCCGGCCGGA"
  ]
  node [
    id 366
    label "GGGGGTATGCCCCCGCTCGAGCTTTGGTCAAGTCTGGCCGGA"
  ]
  node [
    id 367
    label "GCCAAGGCCTTGGCGTCTAGGCGCGGATCCGCAGGGGCCCTT"
  ]
  node [
    id 368
    label "GGTTCGTACGAACCGCC--GGCACGGTACCGTGGCGGCCGCC"
  ]
  node [
    id 369
    label "GTCGGGGTCCCGACACA--TGTGCGGATCCGCGGGAGCTCCC"
  ]
  node [
    id 370
    label "GGCGCCGCGGCGCCCCC--GGGGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 371
    label "TCCCGG--TTGGGAGCT--AGCTCTGCGCAGGCTAGGCCTGG"
  ]
  node [
    id 372
    label "GGCGACATGTCGCCGCC--GGCGAGGATCCTTATCGGCCGGT"
  ]
  node [
    id 373
    label "TTCTTGGCTGGGAAGCT--AGTTCTGCGCAGACCAGGCCTGG"
  ]
  node [
    id 374
    label "GGCGCAGCTGCGCCGCA--TGCGCGGATCCGTAGCGGCCGCT"
  ]
  node [
    id 375
    label "GGCGGCGCGCCGCCGCC--GGCAAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 376
    label "GGGGGA--TCCCCCGCT--AGCTTTTATAAAGCCCAGCTGGG"
  ]
  node [
    id 377
    label "GGTCTGATCAGACCGCC--GGCAAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 378
    label "GCTCGG--CCGAGCGCGCGCGCGCAGATCTGTCCCAGCTGGG"
  ]
  node [
    id 379
    label "GGTCGGTACCGACCGCC--GGCGCGGTACCGTAGCAGCTGCT"
  ]
  node [
    id 380
    label "TCCTTGGCTAGGGACTC--GAGTCTGCGCAGGCCAGGTCTGG"
  ]
  node [
    id 381
    label "GGTCGGGCTCGACCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 382
    label "GGCACGTACGTGCCGCA--TGCGCGGATCCGTTTCGGCCGAA"
  ]
  node [
    id 383
    label "GGTGTCTAGACACCGCC--GGCATGGTACCATAGCGGCCGCT"
  ]
  node [
    id 384
    label "GGGGGTGTGCCCCTGCTCGAGCTTTGATCAAACCTGGCCAGG"
  ]
  node [
    id 385
    label "GGCGACATGTCGCCGCC--GGCGAGGATCCTTCCCGGCCGGG"
  ]
  node [
    id 386
    label "GGGGGCATGCCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 387
    label "GGTTCCGCGGAACCGCC--GGCGAGGTACCTTAGCAGCTGCT"
  ]
  node [
    id 388
    label "GGCCTGATCAGGCCGCG--CGCGCGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 389
    label "GGCGGCATGCCGCCGCC--GGCGAGGTACCTCTCCAGCTGGA"
  ]
  node [
    id 390
    label "GGCGGCGCGCCGCCGCC--GGCGGGGTATCCCGTGGGCCCAC"
  ]
  node [
    id 391
    label "GGTTCCGCGGAACCGCC--GGCATAGATCTGTACCGGCCGGT"
  ]
  node [
    id 392
    label "TCCCTG--TGGGGAGCT--AGTTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 393
    label "GGCGCCATGGCGCCGCC--GGCAAGGTACCTTCCCGGCCGGG"
  ]
  node [
    id 394
    label "GGCGCGTACGTGCCGCG--CGCGAGGTACCTTACGAGCTCGT"
  ]
  node [
    id 395
    label "GGCGCGGCCGCGCCGCA--TGCGCGGATCCGCGTTGGCCAGC"
  ]
  node [
    id 396
    label "GGCGACATGTCGCCGCC--GGCAGGGCGCCTTCCCAGCTGGG"
  ]
  node [
    id 397
    label "GTCCAGGCCTGGACGCC--GGCTCGGTATCGAGTGGGCCCAC"
  ]
  node [
    id 398
    label "TCCCGG--TTGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 399
    label "GGCGACGCGTCGCCGCC--GGCGAGGTACCTCCTCGGCCGGG"
  ]
  node [
    id 400
    label "TCCCGG--CTGGGAGCT--AGCTCTGTGCAGGCCGGGCCTGG"
  ]
  node [
    id 401
    label "GGTGGAGCTCCACCGCC--GGCGCGGCGCCGTGTGGGCCCAT"
  ]
  node [
    id 402
    label "TCCCTG--TAGGGAGCTCGAGCTCTGCGTGGGCTAGGCCTGG"
  ]
  node [
    id 403
    label "TTTCAG--TTGGAAGCT--AGCTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 404
    label "GCCAAGGCCTTGGCACC--GGTTGTGGCCATATTGGGCCCAA"
  ]
  node [
    id 405
    label "GGTGGTATACCACCGCC--GGCGAGGTACCTTGTCGGCCGAT"
  ]
  node [
    id 406
    label "GGGGGTATGCCCCCGCTCGAGCCTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 407
    label "GGCGGCGCGCCGCCGCC--GGCGTGGTACCATACCGGCCGGT"
  ]
  node [
    id 408
    label "GGCGACGCGTCGCCCCC--GGGGCGGTACCGCGCCGGCCGGC"
  ]
  node [
    id 409
    label "GGTATCGCGATACCGCC--GGCGAGCTAGCTCAGCGGCCGCT"
  ]
  node [
    id 410
    label "GGCGCGGCCGCGCCGCA--TGCGCGGATCCGTGGTGGCCACT"
  ]
  node [
    id 411
    label "GCCCCGGCCGGGGCGCTCGAGCGCGGGCCCGTCCGGGCCCGG"
  ]
  node [
    id 412
    label "GGTCGAGCTCGACCGCA--TGCGAGGCGCCTTGCCGGCCGGC"
  ]
  node [
    id 413
    label "GGCATCGCGATGCCGCG--CGCGAGGATCCTTCCCAGCTGGG"
  ]
  node [
    id 414
    label "GGCGGCGCGCCGCCGCC--GGCGAGGTACCTTGGCGGCCGCC"
  ]
  node [
    id 415
    label "GGGGGTGTGCCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 416
    label "GGTGGATATCCACCGTC--GGCACGGTACCGTACGGGCCCGT"
  ]
  node [
    id 417
    label "TCCCAG--TTGGGAGCT--AGTTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 418
    label "GGTGGGGCCCCACCGCC--GGCACGGCGCCGTGCGGGCCCGT"
  ]
  node [
    id 419
    label "GGCCTGATCAGGCCGCG--CGCGCGGATCCGCCCGGGCCCGG"
  ]
  node [
    id 420
    label "GGATCGATCGGTCCGCTCGAGCAGGGATCCCTACGTGCACGT"
  ]
  node [
    id 421
    label "GGCGGCATGCCGCCGCC--GGCGAGGTACCTTACCGGCCGGT"
  ]
  node [
    id 422
    label "GGCGGTGCGCCGCCGCC--GGCAAGGTACCTTGTCGGCCGAT"
  ]
  node [
    id 423
    label "GGCGTGATCACGCCGCA--TGCGTGGATCCATCCCGGCCGGG"
  ]
  node [
    id 424
    label "GGCCTGATCAGGCCGCG--CGCGAGGATCCTTCCGGGCCCGG"
  ]
  node [
    id 425
    label "TCCTTG--TAGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 426
    label "GGTTTCGCGAAACCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 427
    label "GGTTTCGCGAAACCGCC--GGCGAGGTACCTTACCAGCTGGT"
  ]
  node [
    id 428
    label "GGTGGCGCGCCACCGCC--GGCACGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 429
    label "GGGGGTATACCCCTGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 430
    label "ATCTTG--CAAGATGTA--TGTTTTGGCTGAAGGTGGCCACC"
  ]
  node [
    id 431
    label "GGTCGGATCCGACCGCC--GGCGAGCTAGCTCAGCGGCCGCT"
  ]
  node [
    id 432
    label "GGGGGTGCGCCCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 433
    label "GGCGCCTAGGTGCCGCA--TGCGCGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 434
    label "GGTGCCATGGCACCGCC--GGCGCAGCGCTGCCCCAGCTGGG"
  ]
  node [
    id 435
    label "GGCCGGGCCCGGCCGCC--GGCGGGGATCCCTGTGGGCCCAC"
  ]
  node [
    id 436
    label "GGCGGCGCGCCGCCGCC--GGCAAGGTACCTTACCGGCCGGT"
  ]
  node [
    id 437
    label "GGCGACATGTCGCCGTC--GGCGAGGTACCTTACCGGCCGGT"
  ]
  node [
    id 438
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGTCCGGCCGGA"
  ]
  node [
    id 439
    label "GGTGGGGCCCCACCGCC--GGCGCGGCGCCGTGCGGGCCCGT"
  ]
  node [
    id 440
    label "GGGGGTGCGCCCCCGCTCGAGCTTTGATCAAGCTTGGCCAAG"
  ]
  node [
    id 441
    label "GGCGCCATGGCGCCGCC--GGCGGGGCGCCCTCCCGGCCGGG"
  ]
  node [
    id 442
    label "GGCGCTGCGGCGCCCCC--GGGGAAGTACTTTGCCGGCCGGT"
  ]
  node [
    id 443
    label "GGCGGCATGCCGCCGCC--GGCGAGGATCCTTCCCAGCTGGG"
  ]
  node [
    id 444
    label "TTCCTGGTCGGGAAGCT--AGCTCTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 445
    label "GGTCAGATCTGACCCCA--TGGGCAGTACTGTATCGGCCGAT"
  ]
  node [
    id 446
    label "GGCACTATGGTGCCGCC--GGCGAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 447
    label "TTCCTGGTTGGGAAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 448
    label "GGGGGTGTGCCCCCGTC--GACTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 449
    label "GGCTAGGCCTAGCCGCA--TGCGCGGCGCCGTCTCGGCCGGG"
  ]
  node [
    id 450
    label "GCCAGAGCTCTGGCGCG--CGCGCTGATCAGCCCCGGCCGGG"
  ]
  node [
    id 451
    label "GGGGGA--TCCCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 452
    label "GGCCGTGCACGGCCCCC--GGGCCCGCGCGGGGTGGGCCCGC"
  ]
  node [
    id 453
    label "GGCGACATGTCGCCGCC--GGCGAGGTACCTTCCTAGCTAGG"
  ]
  node [
    id 454
    label "GGTGAAGCTTCACCGCC--GGCGAGGTACCTCAGCGGCCGCT"
  ]
  node [
    id 455
    label "TCCCAG--TTGGGAGCT--AGCTCCACGTGGGCCGGGCCTGG"
  ]
  node [
    id 456
    label "GGCGGAATTCCGCCGCA--TGCGCGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 457
    label "GGTCGGATCCGACCGCC--GGCGAGGTACCTCAGCGGCCGCT"
  ]
  node [
    id 458
    label "GGCGCGATCGCGCCGCA--TGCGCGGATCCGCGCCGGCCGGC"
  ]
  node [
    id 459
    label "GCACCGGCCGGTGCGCG--CGCCTGGTACCAGGCCGGCCGGC"
  ]
  node [
    id 460
    label "GGTGGGTACCCACTGCC--GGCGCGGCGCCGTACCGGCCGGT"
  ]
  node [
    id 461
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCGAGCCCGGCCGGG"
  ]
  node [
    id 462
    label "GGCCACGCGTGGCCGCG--CGCACGGTACCGTACCAGCTGGT"
  ]
  node [
    id 463
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCTTGGCCAGG"
  ]
  node [
    id 464
    label "GGCGGCATGCCGCCGCC--GGCGGGGATCCTTCCCAGCTGGG"
  ]
  node [
    id 465
    label "GGCGAGGCCTCGCCGCA--TGCGCGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 466
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCCTGGCTGGG"
  ]
  node [
    id 467
    label "GGCGCTATGGCGCCGCC--GGCGAGGTACCTTCCCGGCCGGG"
  ]
  node [
    id 468
    label "GGGTTCATGGGCCCGCTCGAGCATTGATCAATACCGGCCGGT"
  ]
  node [
    id 469
    label "GGTGGAGCTCCACCGCC--GGCGCGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 470
    label "GGCAACGCGTTGCCGCC--GGCGCGGTATCGCGAGGGCCCTC"
  ]
  node [
    id 471
    label "GGGGGCATGCCCCCGCTCGAGCTTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 472
    label "GGCGCCGCGGCGCCCCC--GGGGCAGTACTGCGGCGGCCGCC"
  ]
  node [
    id 473
    label "GGCGCGATCGCGCCGCA--TGCCTGGATCCAGTCCGGCCGGA"
  ]
  node [
    id 474
    label "GCCTGG--TCAGGTGCTCGAGCTCTGATCAGGGTGGGCCCGT"
  ]
  node [
    id 475
    label "GGCCCGGCCGGGCCGCG--CGCGCGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 476
    label "GGCCCCGCGGGGCCGCG--CGCAAGGATCCTTGCTGGCCAGC"
  ]
  node [
    id 477
    label "GGGGGTATGCCCCCGCTTGAGCTTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 478
    label "GGCGGCGCGCCGCCGCC--GGCGCAGTACTGCGGCGGCCGCC"
  ]
  node [
    id 479
    label "GGTCCA--TGGGCCGCTCGAGCATTGATCAATACCGGCTGGT"
  ]
  node [
    id 480
    label "GGCGCGTACGCGCCACA--TGTGCGGATCCGTCTCGGCCGAG"
  ]
  node [
    id 481
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCCTAGCTAGG"
  ]
  node [
    id 482
    label "GGTTGCGCGCAACCGCC--GGCATGCTAGCATAGCGGCCGCT"
  ]
  node [
    id 483
    label "GGCGCCGCGGCGCCCCC--GGGGAGGTACCTTATCGGCCGAT"
  ]
  node [
    id 484
    label "GGGCGAGCTCGCCCGCG--CGCGCGGTACCGCACCGGCCGGT"
  ]
  node [
    id 485
    label "GGTGCCTAGGCACCGCC--GGCTGGAGCTCCAGTCAGCTGAC"
  ]
  node [
    id 486
    label "GGCACG--CGTGCCGCC--GGCAAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 487
    label "GCACGGTACCGTGCGCT--GGCACGGTACCGTACCGGCCGGT"
  ]
  node [
    id 488
    label "GGTGGATATCCACCGCC--GGCGCGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 489
    label "GGGGGTATGCCCCCCTC--GAGTTTGATCAAGTCTGGCCAGG"
  ]
  node [
    id 490
    label "GGTCCGTACGGACCGCC--GGCTGGCTAGCCACCCGGCCGGG"
  ]
  node [
    id 491
    label "GGCGCGTACGCGCCACA--TGTGCGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 492
    label "GGGGGTATACCCCCGCTCGAGCTTTGATTAAGCCTGGCCAGG"
  ]
  node [
    id 493
    label "GGGTCCTAGGGCCCGCTCGAGCTTTGATCAAGACCGGCCGGT"
  ]
  node [
    id 494
    label "TCCTGA--TCAGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 495
    label "GGCGACGCGTCGCCGCC--GGCGGGGTACCTCAGCGGCCGCT"
  ]
  node [
    id 496
    label "GGTACCATGGTACCGCC--GGCTGGGTACCTAAGCGGCCGCT"
  ]
  node [
    id 497
    label "GGGGTA--TGCCCCGCTCGAGCTTTGATCAGGCCCGGCCGGG"
  ]
  node [
    id 498
    label "GGGGGCATGTCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 499
    label "TCCTGG--TCAGGAGCT--AGCTCTGCGCAGGTCAGGCCTGG"
  ]
  node [
    id 500
    label "GGTGCCGCGGCACCCCC--GGGACGGTACCGTGGCGGCCGCC"
  ]
  node [
    id 501
    label "GCCGAGGCCTCGGCACA--TGTACCGCGCGGTGGGAGCTTCC"
  ]
  node [
    id 502
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCTTGGCCGGG"
  ]
  node [
    id 503
    label "GGTTCCGCGGAACCGCC--GGCGTGGTACCATAGCGGCCGCT"
  ]
  node [
    id 504
    label "GGGGTA--TGCCCTGCTCGAGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 505
    label "GGGGGTGTGCCCCCGCTTGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 506
    label "GGCCTCTAGAGGCCGCG--CGCGCGGATCCGTGCCGGCCGGC"
  ]
  node [
    id 507
    label "GGGGGTATACCCCCGCTCGAGCTTTGGTCAAGTCCGGCCGGA"
  ]
  node [
    id 508
    label "GGCTGGGCCCGGCCGCA--TGCGAGGATCCTTATCGGCCGGT"
  ]
  node [
    id 509
    label "GGGGGTATGCTTCCGCTCGAGCTTTGATCAAGCCTAGCTGGG"
  ]
  node [
    id 510
    label "GGCGGCATGCCGCCGCC--GGCAGGGTATCCTCCCAGCTGGG"
  ]
  node [
    id 511
    label "GACCGCGCGCGGTCCCC--GGGCTCGCGCGAGGCGGGCCCGC"
  ]
  node [
    id 512
    label "GGCGACGCGTCGCCGCC--GGCGAGGTATCTCGAGGGCCCTC"
  ]
  node [
    id 513
    label "GGCGGCATGCCGCCGCC--GGCTCGGTACCGATCCGGCCGGA"
  ]
  node [
    id 514
    label "GGACTGGTTAGTCCGCTCGAGCTGAGATCTTAGCGTGCACGC"
  ]
  node [
    id 515
    label "GATCGCATGCGGTCCCC--GGGACCGCGCGGTGCCGGCCGGC"
  ]
  node [
    id 516
    label "GGTGCCTAGGCACCGCC--GGTAGGAGCTCCTGTCAGCTGAC"
  ]
  node [
    id 517
    label "GGTCTGATCAGACTGCG--CGCTTGGTACCGAATGGGCCCAT"
  ]
  node [
    id 518
    label "CGTGGTGCACCACGCCC--GGGGCTGCGCAGCGCGGGCCCGC"
  ]
  node [
    id 519
    label "GGCGGAGCTCCGCCGCC--GGCAGGGCGCCCTACGGGCCCGT"
  ]
  node [
    id 520
    label "GCGGGCGCGCTCGCGCT--GGCACGGTGCCGTGCGGGCCCGC"
  ]
  node [
    id 521
    label "GGCTGGGCTCAGCCGCA--TGCGCGGCGCCGCGCCGGCCGGC"
  ]
  node [
    id 522
    label "GGCGGCATGCCGCCGCC--GGCAAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 523
    label "GGCCTCGCGAGGCCGCG--CGCGCGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 524
    label "GGATCGATCGGTCCGCTCGAGCAGGGATCCCTGCGTGCACGC"
  ]
  node [
    id 525
    label "GGCCCGATCGGGCCGCG--CGCGAGGATCCTTCCGGGCCCGG"
  ]
  node [
    id 526
    label "GGCGCGGCCGCGCCGCG--CGCGCGGCGCCGTACCGGCCGGT"
  ]
  node [
    id 527
    label "GGGGTG--CACCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 528
    label "GGCGCCATGGCGCCGCC--GGCGAGGATCCTCGTCAGCTGAC"
  ]
  node [
    id 529
    label "GGGATA--TGTCCCGCTCGAGCTTCGATCGAGCCCGGCCGGG"
  ]
  node [
    id 530
    label "GGGGGA--TTCCCTGCTCGAGCTTTGATCAAGCCTGGCTGGG"
  ]
  node [
    id 531
    label "GGCGCCATGGCGCCGCC--GGCGAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 532
    label "GGCACCGCGGTGCCGCC--GGCGCGGTACCGCGCGGGCCCGC"
  ]
  node [
    id 533
    label "TTCCGC--GTGGAAGCT--AGCTCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 534
    label "GGGGTA--TGCCCCGCTCGAGCTTCGATCGAGTTTGGCCGGG"
  ]
  node [
    id 535
    label "GGCGATGCGTCGCCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 536
    label "GGTCTCGCGAGACCGCC--GGCACGGTACCGTTCCGGCCGGA"
  ]
  node [
    id 537
    label "GGCTGGGCCCGGCCGCA--TGCGAGGATCCTTACCGGCCGGT"
  ]
  node [
    id 538
    label "TCCCTG--TGGGGAGCTTAAGCTCTGCGCAGGCCAGGCTTGG"
  ]
  node [
    id 539
    label "GGCAAGGTCTTGCCACC--GGTCGTGGCCATGTGGGGCCCTA"
  ]
  node [
    id 540
    label "GGCAACGCGTTGCCGCC--GGCAGGGATCCCTGGCGGCCGCC"
  ]
  node [
    id 541
    label "TCCCGT--GTGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 542
    label "GGTACCTAGGTACCGCC--GGCTCGGTACCGGGGCGGCCGCC"
  ]
  node [
    id 543
    label "GGCTGGGCCCGGCCGCA--TGCGGGGATCCCCACCGGCCGGT"
  ]
  node [
    id 544
    label "GAGCCTATGGGCTCGCTCGAGCATTGATCAATACCGGCCGGT"
  ]
  node [
    id 545
    label "TCCTGG--TCAGGAGCT--AGCTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 546
    label "TCCCTG--TAGGGAGCTCGAGTTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 547
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCAGGCTGGGCCTAG"
  ]
  node [
    id 548
    label "TCCCTG--TAGGGAGCT--AGCTCTGTGCAGACCAGGCCTGG"
  ]
  node [
    id 549
    label "GGGGGTATGCCCCCGCTCGAGTTTTGGTCAAGCCTGGCCAGG"
  ]
  node [
    id 550
    label "GGCGCGGCCGCGCCGCA--TGCACGGATCCGTGTTGGCCAGC"
  ]
  node [
    id 551
    label "GGCGGTATACCGCCGCC--GGCAAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 552
    label "GGCGCTATAGCGCCGCC--GGCGAGGCGCCTTCCCAGCTGGG"
  ]
  node [
    id 553
    label "GGTGGGTACCCACCGCC--GGCACGGATCCGTACGGGCCCGT"
  ]
  node [
    id 554
    label "GGGGGTATGCCTCCGCT--AGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 555
    label "GGGGGTATGCCCCCGCT--AGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 556
    label "TCCTGG--TCGGGAGCT--AGCTCTGCGCGGACCAGGCCTGG"
  ]
  node [
    id 557
    label "GGGGTG--TACCCCGCTCGAGCTTTGATCAAGTCTGGCTAGG"
  ]
  node [
    id 558
    label "GGTGCCATGGCACCGCC--GGTAGGAGCTCCTGTCAGCTGAC"
  ]
  node [
    id 559
    label "GGTGACGCGTCACCGCC--GGCAGGGTACCCTACCAGCTGGT"
  ]
  node [
    id 560
    label "GGCTGGGCCCAGCCGCA--TGCGCGGCGCCGCCTCGGCCGGG"
  ]
  node [
    id 561
    label "GGTGGAGCTCCACCGCC--GGCGCGGCGCCGCACGGGCCCGT"
  ]
  node [
    id 562
    label "GGGAGTATGCTCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 563
    label "GGTGACGCGTCACCGCC--GGCGAGGCGCCTCGGCGGCCGCC"
  ]
  node [
    id 564
    label "GCCTGG--TTGGGTGCTTAAGCTCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 565
    label "GACAAGATCTTGTCGCC--GGCACGGATCCGTATGAGCTCAT"
  ]
  node [
    id 566
    label "GGCGACATGTCGCCGCC--GGCGAGGATCCTCCTCAGCTGAG"
  ]
  node [
    id 567
    label "GGAGGTATACCTCCGCA--TGCGTGGATCCACGTCGGCCGGC"
  ]
  node [
    id 568
    label "GGCGCGATCGCGCCGCG--CGCGAGGATCCTTGCCGGCCGGC"
  ]
  node [
    id 569
    label "GGTGGGTACCCACCGCC--GGCGCGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 570
    label "GGGGATATGTCCCCCTC--GAGTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 571
    label "TCCCTG--TAGGGAGCT--AGTTCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 572
    label "GGGGGTGTGTCCCCGCC--GGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 573
    label "GGCCCGCGTGGGCCGCA--TGCGAGGATCCTTCTCGGCCGGG"
  ]
  node [
    id 574
    label "GGCGGTATACCGCCGCC--GGCGAGGTACCTTGTCGGCCGAT"
  ]
  node [
    id 575
    label "GGGGGCATGCCCCTGCTCGAGCTTTGATCAAACCTGGCCAGG"
  ]
  node [
    id 576
    label "TCCCGC--GTGGGAGCTTGAGTTCTGCGTGGGCTAGGCCTGG"
  ]
  node [
    id 577
    label "GGTCGAGCTCGACCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 578
    label "GCCAGGGCCCTGGCGCA--TGCGGGGATCCCCCCCGGCCGGG"
  ]
  node [
    id 579
    label "GGCGCGGCCGCGCCGCC--GGCGAGCTAGCTCGTCGGCCGAC"
  ]
  node [
    id 580
    label "GGCGCGATCGCGCCGCA--TGCACGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 581
    label "GGGGGTATGCCCCTGCTTGAGCTTTGATCAAACCTGGCCAGG"
  ]
  node [
    id 582
    label "GACTGTGCACAGTCGCC--GGCGTCGGCCGACGTAGGCCTAT"
  ]
  node [
    id 583
    label "GGCCTGGCCAGGCCGTA--TGCGCGGATCCGCGCCGGCCGGC"
  ]
  node [
    id 584
    label "GGCGGTATACCGCCGCC--GGCGAGGTACCTTGTCGGCCGAC"
  ]
  node [
    id 585
    label "GGCGGTATACCGCCGCC--GGCGAGGTACCTTACCGGCCGGT"
  ]
  node [
    id 586
    label "GGTGCGTACGCACCGCA--TGCCCGGATCCGGCCCAGCTGGG"
  ]
  node [
    id 587
    label "TCCCGG--CTGGGAGCT--AGCCCTGTGCAGGCCAGGCCTGG"
  ]
  node [
    id 588
    label "GGGGGTATGCCCCCGCTCGAGCCTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 589
    label "GGCGCAATTGCGCCGCA--TGCGCGGATCCGTGTCGGCCGGC"
  ]
  node [
    id 590
    label "GGTGCCTAGGCACCGAT--GTCACGGTACCGTGGCGGCCGCC"
  ]
  node [
    id 591
    label "GGCTGGATCCAGCCGCA--TGTACGGCGCCGTGCCGGCCGGC"
  ]
  node [
    id 592
    label "GGGGGTGTGCCCCCGCTCGAGCTTTGATCAAGTCTGGCCAGA"
  ]
  node [
    id 593
    label "TCCCGG--TTGGGAGCT--AGCTCCGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 594
    label "GGCACCATGGTGCCGCC--GGCTAGGTACCTAACCGGCCGGT"
  ]
  node [
    id 595
    label "GGGGGCATGCCCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 596
    label "GGCGCGTACGCGCCGCA--TGTGCGGATCCGTTCTGGCCAGA"
  ]
  node [
    id 597
    label "TCCTGG--TCAGGAGCT--AGCTCTGCGCAGGCTAGGCCTGG"
  ]
  node [
    id 598
    label "TCCCTG--TGGGGACTC--GAGTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 599
    label "GCACCGGCCGGTGCGCG--CGCCTGGTACCAGATGGGCCCAT"
  ]
  node [
    id 600
    label "TCCTGG--TCAGGAGCTTAAGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 601
    label "GCGGGTGCATCCGCGCC--GGCGCGGTACCGTGCAGGCCTGC"
  ]
  node [
    id 602
    label "GGCGCGATCGCGCCGCA--TGCGCGGATCCGTAGCGGCCGCT"
  ]
  node [
    id 603
    label "GGTTCCTAGGAACCGAT--GTCGTGGTACCATGGCGGCCGCC"
  ]
  node [
    id 604
    label "GGTCTGGCCAGACCGCA--TGCGCGGATCCGCGTGGGCCCGC"
  ]
  node [
    id 605
    label "GGCGATATATCGCCGCC--GGCAAGGTACCTTGCCGGCCGGC"
  ]
  node [
    id 606
    label "GGCGCCATGGCGCCGCC--GGCGAGGATCCTTGTCGGCCGAC"
  ]
  node [
    id 607
    label "GGCGCGATCGCGCCGCA--TGCGCGGCGCCGTACCAGCTGGT"
  ]
  node [
    id 608
    label "GACCGCTAGTGGTCGCGCGCGCTTCTCGAGAAGAGCGCGCTC"
  ]
  node [
    id 609
    label "TCCCGG--TTGGGAGCT--AGTTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 610
    label "GGATTCATGGGTCCGCTCGAGCTTCGGCCGAACCCGGCCGGG"
  ]
  node [
    id 611
    label "GGCGGCATGCCGCCGCC--GGCGAGGATCCTCCCCAGCTGGG"
  ]
  node [
    id 612
    label "GGTGCCATGGCACCCCC--GGGAAGGTACCTTATCGGCCGAT"
  ]
  node [
    id 613
    label "GGCGGTATACCGCCGCC--GGCGGGGTACCCTATCGGCCGGT"
  ]
  node [
    id 614
    label "GGCGCCGCGGCGCCCCC--GGGGGGGCGCCCTGCCGGCCGGC"
  ]
  node [
    id 615
    label "GGTGGTATACCACCGCC--GGCGAGGTACCTCCCCAGCTGGG"
  ]
  node [
    id 616
    label "GGCGGCGCGCCGCCGCC--GGCACGGCGCCGTCAGGGCCCTG"
  ]
  node [
    id 617
    label "GGCGACGCGTCGCCGCC--GGCGCGGTATCGCCCCGGCCGGG"
  ]
  node [
    id 618
    label "GGTGTCTAGACACCGCC--GGCTGGAGCTCCAATCAGCTGAT"
  ]
  node [
    id 619
    label "GGCGCTATGGCGCCGCC--GGCGAGGTACCTCCCCGGCCGGG"
  ]
  node [
    id 620
    label "GGGGGTATGCCCCCGTC--GACTTTGATCAAGTCTGGCCAGG"
  ]
  node [
    id 621
    label "GGGGATATGTCCCCGCTCGAGCTTCGATCGAGCCTGGCCGGG"
  ]
  node [
    id 622
    label "ACCTGG--TCGGGTGCT--AGCTCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 623
    label "GGCTGGATCCGGCCGCA--TGCGAGGATCCTTGTCGGCCGGC"
  ]
  node [
    id 624
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCGGACCGGGCCTGG"
  ]
  node [
    id 625
    label "GGGCCAGCTGGCTCGCG--CGTCCTGATTAGGCCAGGTCTGG"
  ]
  node [
    id 626
    label "GGGGGA--TCCCCCGCT--AGCTTTGATCAAGCTTGGCCAGG"
  ]
  node [
    id 627
    label "GGGGGTGTGCCCCCGTTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 628
    label "GGCTGGGCCTGGCCGCA--TGCGTGGATCCGCGTCGGCCGAC"
  ]
  node [
    id 629
    label "GGCGGGGCTCCGCCGCA--TGCGCGGCGCCGTGCCGGCCGGC"
  ]
  node [
    id 630
    label "GCCGGTGTGCCGGCGCA--TGCTTCGTGCGAAGGAGGCCTCC"
  ]
  node [
    id 631
    label "TCCCTG--TGGGGAGCT--AGCTCTGTGCAGGCCAGGCCTGG"
  ]
  node [
    id 632
    label "GGTCGAGCTCGACCGCC--GGCTCAGTACTGAGTGGGCCCAC"
  ]
  node [
    id 633
    label "GGGGTA--TACCCCGCTCGAGCTTTGATCAAACCTGGCCAGG"
  ]
  node [
    id 634
    label "GGGGATGCGTCCCCGCTCGAGCTTTGATCAAGTCTGGCCAGG"
  ]
  node [
    id 635
    label "GGCAGCATGCTGCCGCC--GGCGAGGTACCTTCCCGGCCGGG"
  ]
  node [
    id 636
    label "GGTGGTATACCACCGCC--GGCATGGTACCGTACGGGCCCGT"
  ]
  node [
    id 637
    label "GGTGACATGTCACCGCC--GGCAAGGTACCTTCCCGGCCGGG"
  ]
  node [
    id 638
    label "GGGGGTATGCCCCTGCTCGAGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 639
    label "GGCGCGGCCGTGCCGCA--TGCGCGGATCCGTGTGGGCCCGC"
  ]
  node [
    id 640
    label "GCCTGG--CTGGGCGCT--AGCTCTGATCAGGGTGGGCCCAT"
  ]
  node [
    id 641
    label "GCAGAG--CTCTGCGCG--CGCATTGGCCAATGCAGGCCTGT"
  ]
  node [
    id 642
    label "GGCGGCTAGCCGCCGCC--GGCACGGCGCCGTTCCGGCCGGA"
  ]
  node [
    id 643
    label "GGGGGTATGCCCTCGCTCGAGTTTTGATCAAGCTTGGCCAAG"
  ]
  node [
    id 644
    label "GGCACCGCGGTGCCGCC--GGCCGGGTACCCGGGCGGCCGCC"
  ]
  node [
    id 645
    label "GGTGTCGCGACACCGCC--GGCGAGCTAGCTCCCCGGCCGGG"
  ]
  node [
    id 646
    label "GGCGACGCGTCGCCGCC--GGCGAGGTATCTCACCAGCTGGT"
  ]
  node [
    id 647
    label "GGGGGTGTGCTCCCGCTCGAGCTTTGATCAAGTCTGGCTGGA"
  ]
  node [
    id 648
    label "TCCCTGGTCAGGGAGCT--AGTTCTGCGCGGACCAGGCCTGG"
  ]
  node [
    id 649
    label "TCCCGC--GTGGGAGCT--AGCTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 650
    label "TCTGGC--GTTGGAGCT--AGCTCTGCGCAGACTGGGCCTGG"
  ]
  node [
    id 651
    label "GGCGGCGCGCCGCCGCC--GGCGGGGATCCCTGGCGGCCGCC"
  ]
  node [
    id 652
    label "GGGTCCATGGGCCCGCTCGAGCATTGATCAATACCGGCTGGT"
  ]
  node [
    id 653
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAACCTGGCCAGG"
  ]
  node [
    id 654
    label "TCCCGG--CTGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 655
    label "GCTCGTATGCGAGCGCC--GGTGTAGATCTATCTCAGCTGAG"
  ]
  node [
    id 656
    label "GGGAGTATGCTCCCGCTCGAGCTTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 657
    label "GGGGTG--CGCCCCGCT--AGCTTTGATCAAGCTTGGCCAAG"
  ]
  node [
    id 658
    label "GGCGACGCGTCGCCGCC--GGCAGGGCGCCCTCCCAGCTGGG"
  ]
  node [
    id 659
    label "GGCGACGCGTCGCCGCC--GGCAGGGTACCCTATGGGCCCAT"
  ]
  node [
    id 660
    label "TCCCCG--TGGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 661
    label "GGCGGCATGCCGCCGCC--GGCGAGGTACCTCCTCAGCTGAG"
  ]
  node [
    id 662
    label "GGCCGTGCACGGCCCCC--GGGCTCGATCGAGACCGGCCGGT"
  ]
  node [
    id 663
    label "GGCGCGTACGTGCCGCA--TGCACGGATCCGTCTCAGCTGAG"
  ]
  node [
    id 664
    label "GGCGCGGCCGTGCCGCA--TGCACGGATCCGTCCGGGCCCGG"
  ]
  node [
    id 665
    label "GGCCGTGCGCGGCCCCC--GGGGCGCATGCGCGTGGGCCCAC"
  ]
  node [
    id 666
    label "GGCGGGTACCCGCCGCA--TGCGCGGATCCGTCTCGATCGGG"
  ]
  node [
    id 667
    label "GGCGTCGCGACGCCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 668
    label "GGCGAGATCTCGCCGCC--GGCGAGGCGCCTTCCCGGCCGGG"
  ]
  node [
    id 669
    label "GGCGGCGCGCCGCCGCC--GGCGAGGTACCTCTCCGGCCGGA"
  ]
  node [
    id 670
    label "GGTCAGGCCTGACCGCC--GGCTTGGTACCGAGCGGGCCCGC"
  ]
  node [
    id 671
    label "GGTGGAGCTCCACCGCC--GGCACGGATCCGTACGGGCCCGT"
  ]
  node [
    id 672
    label "GGTGGGTACCCACCGCC--GGCACGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 673
    label "GGCGCGGCCGCGCCCCC--GGGGAGGTACCTTGTCGGCCGAC"
  ]
  node [
    id 674
    label "GGCGACGCGTCGCCGCC--GGCGGGGTATCCCGTGGGCCCAC"
  ]
  node [
    id 675
    label "GGCATTGCGATGCCGCC--GGCGAGCTAGCTTAGCGGCCGCT"
  ]
  node [
    id 676
    label "TCCCTG--TAGGGAGCT--AGTTCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 677
    label "GGCCACGCGTGGCCGCG--CGCGAGGATCCTTTCCAGCTGGA"
  ]
  node [
    id 678
    label "GGCGACGCGTCGCCGCC--GGCGAGGTATCTCGTGGGCCCAC"
  ]
  node [
    id 679
    label "GGGTCCATGGGCCCGCTCGAGCTTTGATCAAGACCGGCCGGT"
  ]
  node [
    id 680
    label "GGTTCCTAGGAACCACC--GGTGCGGTACCGTAGCGGCCGCT"
  ]
  node [
    id 681
    label "GGCATCGCGATGCCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 682
    label "GGCGCGTACGCGCCGCA--TGCGCGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 683
    label "GCTCGTATGCGAGCGCGCGCGCGCAGATCTGTCCCAGCTGGG"
  ]
  node [
    id 684
    label "GGCGCGGCCGCGCCGCA--TGCGCGGATCCGTAGCGGCCGCT"
  ]
  node [
    id 685
    label "GGTGAGGCCTCACCGCC--GGCACGGTACCGTGCGGGCCCGT"
  ]
  node [
    id 686
    label "GGCCGGATCCGGCCGCA--TGCGCGGATCCGCGTCGGCCGGC"
  ]
  node [
    id 687
    label "GGGGTA--TGCCCCGCTCGAGCTTTGATCAAGCCTGGTTAGG"
  ]
  node [
    id 688
    label "GGGGGTGCACCCCCGCTCGAGCTTTGATCAAGCTTGGCCAAG"
  ]
  node [
    id 689
    label "GGGGGCATGCCCCCGCTCGAGCTTTGATCAAGCCTAGCTGGG"
  ]
  node [
    id 690
    label "GGTGAGGCCTCACCGTC--GGCGCGGCGCCGTGCGGGCCCGT"
  ]
  node [
    id 691
    label "GGGGGTATGCCCCCGCT--AGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 692
    label "GGGAGTATGCTCCCGCTCGAGCTTCGATCGAGCCTGGCCGGG"
  ]
  node [
    id 693
    label "GCCAAGATCTTGGCGCTTAAGCGTTGGCCAATGGGAGCTCTC"
  ]
  node [
    id 694
    label "TCCCGG--CTGGGAGCT--AGCTCTGCGCAGGCTGGGCCTAG"
  ]
  node [
    id 695
    label "GGCGGCATGCCGCCGCC--GGCAGGGTACCCTGGCAGCTGCC"
  ]
  node [
    id 696
    label "GGCGCGTACGCGCCGCC--GGCGGAGCGCTTCGGGGGCCCTC"
  ]
  node [
    id 697
    label "TTCCTGATTGGGAAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 698
    label "GGTTAGGCCTAACCGCC--GGCTCGGTACCGAGCGGGCCCGC"
  ]
  node [
    id 699
    label "GATGATGCATCATCGCC--GGCCTTGTACAAGGTAGGCCTAT"
  ]
  node [
    id 700
    label "GGGAGTATGCTCCCGCTCGAGCTTTGATCAAGTCTGGCCAGA"
  ]
  node [
    id 701
    label "GGCGACGCGTCGCCGCC--GGCGAGGTATCTCAAGGGCCCTT"
  ]
  node [
    id 702
    label "GGCGCGTACGCGCCGCA--TGCATGGATCCATCTCGGCCGAG"
  ]
  node [
    id 703
    label "GGTGGCATGCCACCGCC--GGCGAGGCGCCTCCCCGGCCGGG"
  ]
  node [
    id 704
    label "GGTAATATATTACCGCC--GGCACGGTACCGTGCCGGCCGGT"
  ]
  node [
    id 705
    label "GGCGACGCGTCGCCGCC--GGCGCGGCGCCGTCCCAGCTGGG"
  ]
  node [
    id 706
    label "GGGGTA--TGCCCCGCTCGAGCTTTGATCAAGCCTGGCTGGG"
  ]
  node [
    id 707
    label "GGCACG--CGTGCCGTC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 708
    label "TTCCTGGTCGGGAAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 709
    label "GGCTGAGCTCAGCCGCC--GGCTTAGTACTAAGTGGGCCCAC"
  ]
  node [
    id 710
    label "GGGGCA--TGCTCCGCTTGAGTTTTGATCAAGTCTGGCTGGG"
  ]
  node [
    id 711
    label "GGCGCGGCCGCGCCACA--TGTCCGGATCCGGCCCGGCCGGG"
  ]
  node [
    id 712
    label "TCCCAT--GTGGGAGCT--AGCTCTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 713
    label "GGGGGTATGCCCCTGCTCGAGCTTTGATCAAACCTGGCCAGG"
  ]
  node [
    id 714
    label "GGCGACATGTCGCCGCC--GGCGAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 715
    label "GGCGCCATGGCGCCGCC--GGCGAGGATCCTTGTCAGCTGAC"
  ]
  node [
    id 716
    label "GGGGGTATACTCCCGTTCGAACTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 717
    label "GGGGGTGTACCCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 718
    label "GGTGGCGCGCCACCGCC--GGCGCAGCGCTGTACGGGCCCGT"
  ]
  node [
    id 719
    label "GGGCCA--TGGCCCGCTCGAGCTTCGATCGAGACCGGCCGGT"
  ]
  node [
    id 720
    label "GGCTCGATCGGGCCGCG--CGCGAGGATCCTTGCCGGCCGGC"
  ]
  node [
    id 721
    label "GGCGGCGCGCCGCCGCC--GGCACGGTACCGTGGCGGCCGCC"
  ]
  node [
    id 722
    label "GGTGGGTACCCACCGCC--GGCGCGGCGCCGTATGAGCTCGT"
  ]
  node [
    id 723
    label "GGCGGCATGCCGCCGCC--GGCGAGGCGCCTTCCCTGCAGGG"
  ]
  node [
    id 724
    label "GGCGGAATTCCGCCGCA--TGCTGAGATCTTACCTAGCTAGG"
  ]
  node [
    id 725
    label "TCCCAA--TTGGGAGCT--AGCTCTGTGCAGGCCGGGCCTGG"
  ]
  node [
    id 726
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 727
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCAGACTGGGCCTGG"
  ]
  node [
    id 728
    label "GATGAGGCCTTGTTGCC--GGCATGGATCCATATGGGCCCAT"
  ]
  node [
    id 729
    label "TCCCTGGTTAGGGAGCT--AGCTCTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 730
    label "GGTGACGCGTCACCGCC--GGCGGGGCGCCCCGGCGGCCGCC"
  ]
  node [
    id 731
    label "GGCGACGCGTCGCCGCC--GGCGGGGTACCCCACCGGCCGGT"
  ]
  node [
    id 732
    label "GGCGAGGCCTCGCCGCA--TGCCTGGTACCGGGCGGGCCCGC"
  ]
  node [
    id 733
    label "GGCGGCATGCCGCCGCC--GGCGAGGATCCTTCTCGGCCGAG"
  ]
  node [
    id 734
    label "GGTGGCATGCCACCGCC--GGCGGAGCGCTCTCCCAGCTGGG"
  ]
  node [
    id 735
    label "GGTAACGCGTTACCGCC--GGCCAGCTAGCTGAGCGGCCGCT"
  ]
  node [
    id 736
    label "GGGGTA--TGCTCCGCTCGAGCTTTGATTAAGCCTGGCCAGG"
  ]
  node [
    id 737
    label "GCCAAGGCCTTGGCGTCTAGGCGCGGATCCGCAAGGGCCCTT"
  ]
  node [
    id 738
    label "GGGGGTATGTCCCCGCTCGAGCTTTGATCAAGCTTGGCCAGG"
  ]
  node [
    id 739
    label "GGCGGTATACCGCCGCC--GGCGAGGTACCTTATCGGCCGGT"
  ]
  node [
    id 740
    label "GCAGGGATCCCTGCGCA--TGCGCAGATCTGTGGGTGCACCC"
  ]
  node [
    id 741
    label "GCCGGGATCCCGGCGCCTAGGCAGGGATCCCTCCGGGCCCGG"
  ]
  node [
    id 742
    label "GGCGCTGCAGCGCCGCC--GGCGAGGTACCTCGGCGGCCGCC"
  ]
  node [
    id 743
    label "GGCGAGTACTCGCCGCG--CGCGCGGATCCGTAGGAGCTCCT"
  ]
  node [
    id 744
    label "GGGGGTATGCCCCCGCTTGAGCTTCGATCGAGCCCGGCCGGG"
  ]
  node [
    id 745
    label "GGGGGTATGCTCCCGCC--GGCTTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 746
    label "GGCGCTATGGCGCCGCC--GGCGAGGTACCTTTCCAGCTGGA"
  ]
  node [
    id 747
    label "GGCGGCGCGCCGCCGCC--GGCGCGGATCCGTACCGGCCGGT"
  ]
  node [
    id 748
    label "GGCCCGATCGGGCCGCG--CGCGAGGATCCTTGCCGGCCGGC"
  ]
  node [
    id 749
    label "GGGGTA--TGTCCCGCTCGAGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 750
    label "GGCGACATGTCGCCGCC--GGCGAGGATCCTCCCCGGCCGGG"
  ]
  node [
    id 751
    label "TCCCGGGTTCGGGAGCT--AGTTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 752
    label "TCCCGA--TTGGGAGCT--AGCTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 753
    label "GCCAAGATCTTGGCGCG--CGCATCGCGCGATTCCGGCCGGA"
  ]
  node [
    id 754
    label "GGCGCGATCGCGCCGCC--GGCGAGCTAGCTCGCCGGCCGGC"
  ]
  node [
    id 755
    label "GGTTTTGCAAAGCCGTA--TACTGGGATCCTGCTCAGCTGAG"
  ]
  node [
    id 756
    label "GCTCGTATGCGAGCGCGCGCGCGCAGATCTGTCTTAGCTGAG"
  ]
  node [
    id 757
    label "GCCAGGGCCCTGGCGCA--TGCGCGGATCCGCCCCGGCCGGG"
  ]
  node [
    id 758
    label "GGCTAAATTTGGCTGCATATGCTTGGATCCAAATTGGCCAAT"
  ]
  node [
    id 759
    label "GGCGGCATGCCGCCCCC--GGGGCGGTACCGTAGCGGCCGCT"
  ]
  node [
    id 760
    label "GGCGGCATGCCGCCGCC--GGCGAGGATCCTTCCCGGCCGGG"
  ]
  node [
    id 761
    label "GGCGGCATGTCGCCGCC--GGCGGGGATCCTTCCCAGCTGGG"
  ]
  node [
    id 762
    label "GGCGGCATGCCGCCGCC--GGCAGGGTACCCTCCCGGCCGGG"
  ]
  node [
    id 763
    label "GGGGGTATGCTCCCGCTCGAGCTTTGATCAAGCCTAGCTGGG"
  ]
  node [
    id 764
    label "GCCGGGTACCCGGCGCC--GGCGCGGGCCCGTGGGGGCCCCC"
  ]
  node [
    id 765
    label "GGTTCCGCGGAACCGCC--GGCCAGCTAGCTGAGCGGCCGCT"
  ]
  node [
    id 766
    label "GGTGTCTAGACACCGCC--GGCTAGAGCTCTAATCAGCTGAT"
  ]
  node [
    id 767
    label "TCCCTG--TGGGGAGCT--AGTTCTGTGCAGGCCAGGCTTGG"
  ]
  node [
    id 768
    label "GCCAACGCGTTGGCGCA--TGCAACGCGCGTTCCCGGCCGGG"
  ]
  node [
    id 769
    label "GGGGGTATGCCCCTGCTCGAGCTTCGATCGAGCCCGGCCGGG"
  ]
  node [
    id 770
    label "GGCTGAGCTCAGCCGCA--TGCGCGGATTCGTGTCGGCCGGC"
  ]
  node [
    id 771
    label "GGTGGTATACCACCGCC--GGCGAGGTACCTTATCGGCCGAT"
  ]
  node [
    id 772
    label "TCCCTG--TGGGGACTT--AAGTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 773
    label "GGCGGAATTCCGCCGCA--TGCGTGGATCCATCTCGGCCGGG"
  ]
  node [
    id 774
    label "GGACGG--TCGTCCGCTCGAGCTTCGGCCGAAACGCGCGCGT"
  ]
  node [
    id 775
    label "GGGGGGATCCCTTCGCT--AGCTTTGATCAAGCCCGGTCGGG"
  ]
  node [
    id 776
    label "TCCCGC--GTGGGAGCT--AGTTCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 777
    label "GGCGCGGTCGTGCCGCC--GGCGAGGATCCTTGCCGGCCGGC"
  ]
  node [
    id 778
    label "GGGGGTATACCCCCGCTCGAGCTTTGGTCAAGCCCAGCTGGG"
  ]
  node [
    id 779
    label "GGGGATATGTCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 780
    label "GGCGCCATGGCGCCGCC--GGCAAGCTAGCTTCCCAGCTGGG"
  ]
  node [
    id 781
    label "GGCCGCGCGTGGCCGCG--CGCGCGGATCCGTTCCGGCCGGA"
  ]
  node [
    id 782
    label "TCCCAG--TTGGGAGCT--AGCTCTGCGCAGACCAGGCCTGG"
  ]
  node [
    id 783
    label "TCCCGG--CTGGGAGCTTAAGCTCTGCGTGGACTGGGCCTGG"
  ]
  node [
    id 784
    label "TTCCTGGCTGGGAAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 785
    label "GGTGCTTAGGCACCGCC--GGCGTGGTACCATAGCGGCCGCT"
  ]
  node [
    id 786
    label "GGGGGTATGCCCCCGCT--AGCTTTGATCAAGTCCGGCCGGA"
  ]
  node [
    id 787
    label "GGCGCCATGGCGCCCCC--GGGGCGGTACCGTATCAGCTGAT"
  ]
  node [
    id 788
    label "GGCGCGGCCGCGCCGCA--TGCACGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 789
    label "GGCGTGTATACGCCACA--TGTGCGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 790
    label "GGGTTCGCGGGCCCGCTCGAGCATTGATCAATACAGGCCTGT"
  ]
  node [
    id 791
    label "GGAGATATGTCTCCGCTCGAGCATCGGCCGATGGTGGCCGCC"
  ]
  node [
    id 792
    label "GGGAGCATGCTCCCGCTCGAGCTTTGATCAAACCTGGCCAGG"
  ]
  node [
    id 793
    label "TCCCAG--TTGGGAGCT--AGCTCTGCGCAGGCTGGGTCTAG"
  ]
  node [
    id 794
    label "TCTCAG--TTGGGAGCT--AGCTCTGCGCAGACCGGGCCTGG"
  ]
  node [
    id 795
    label "GGCCGCGCGCGGCCGCC--GGCGGGGCGCCCTGCCGGCCGGC"
  ]
  node [
    id 796
    label "GGTCGTGCGCGACCGCC--GGCGAGGTACCTCGGTGGCCACT"
  ]
  node [
    id 797
    label "CCTGGT--ATCAGGGCTTAAGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 798
    label "GGGGATGCGTCTCCGCTCGAGCTTTGATCAAGTCTGGCCAGG"
  ]
  node [
    id 799
    label "GGCAACGCGTTGCCGCC--GGCGCGGTATCGCGTGGGCCCAC"
  ]
  node [
    id 800
    label "GGTGGCATGCCACCGCC--GGCGAGGATCCTTCCCGGCCGGG"
  ]
  node [
    id 801
    label "GGGGGTGCGCCCCCGCC--GGCTTTGATCAAGCTTGGCCAGG"
  ]
  node [
    id 802
    label "GGCCGAGCTCGGCCGCA--TGCGCGGATCCGCGTCGGCCGGC"
  ]
  node [
    id 803
    label "GTTTCGATCGAAACGCTCGAGCATCGGCCGATAGGCGCGCCT"
  ]
  node [
    id 804
    label "GGCATCGCGATGCCGCC--GGCGTGGTACCATAGCGGCCGCT"
  ]
  node [
    id 805
    label "GGCACTATGGTGCCGCC--GGCGAGGTACCTCCCCAGCTGGG"
  ]
  node [
    id 806
    label "GGCCACGCGTGGCCGCG--CGCGCGGATCCGTGCCGGCCGGC"
  ]
  node [
    id 807
    label "GGGGGTGCACCCCCGCTCGAGCTTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 808
    label "GGCAAGCGCTTGCCACC--GGTCGTGGCCATGTGGGGCCCTA"
  ]
  node [
    id 809
    label "GGCGCTGCAGCGCCGGC--GCCGCAGTACTGCGCGGGCCCGT"
  ]
  node [
    id 810
    label "GGCGCGTATGCGCCACA--TGTGCGGATCCGCCCCGGCCGGG"
  ]
  node [
    id 811
    label "GGCGCGATCGCGCCGCA--TGCACGGATCCGTCCCAGCTGGG"
  ]
  node [
    id 812
    label "GGCGCGATCGCGCCGCA--TGCACGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 813
    label "GCCAAGGCCTTGGCGCG--CGCATCGCGCGATTCCGGCCGGA"
  ]
  node [
    id 814
    label "GGCGCGTACGCGCCGCA--TGCGCGGATCCGTTCCGGCCGGA"
  ]
  node [
    id 815
    label "GGTGGCGCGCCACCGCC--GGCGAGGTACCTCGCCAGCTGGC"
  ]
  node [
    id 816
    label "GGGGGTGTGTCCCCGCTCGAGCTTTGATCAAGCCTAGCTAGG"
  ]
  node [
    id 817
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 818
    label "GCCAAGATCTTGGCGCG--CGCGCTGATCAGCTCCGGCCGGA"
  ]
  node [
    id 819
    label "GGGGGCATGCCCCCGCT--AGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 820
    label "GGGGGTATGCCCCCCTC--GAGTTTGATCAAGCCTGGCTGGG"
  ]
  node [
    id 821
    label "GGCGCGGCCGCGCCGCC--GGCGAGGTACCTCGCCGGCCGGC"
  ]
  node [
    id 822
    label "TTTCTGGTCGGAAAGCT--AGTTCTGCGTGGACCAGGCCTGG"
  ]
  node [
    id 823
    label "TCCCGG--TTGGGAGCT--AGTTCTGTGTAGGCCAGGCCTGG"
  ]
  node [
    id 824
    label "GGGTCTATGGGCCCGCTCGAGCATTGATCAATACCGGCCGGT"
  ]
  node [
    id 825
    label "GGCGATGCATCGCCGCC--GGCGGGGCGCCTTCCCAGCTGGG"
  ]
  node [
    id 826
    label "GGCGCGATTGCGCCGCA--TGCGCGGATCCGTGGCGGCCGCC"
  ]
  node [
    id 827
    label "GGCGGGGCCCCGCCGCA--TGCACGGCGCCGTGACGGCCGTT"
  ]
  node [
    id 828
    label "GCCAAGGCCTTGGCGCG--CGCGTTGATCAACCCCGGCCGGG"
  ]
  node [
    id 829
    label "GGGGGTATACCTCCGCT--AGCTTTGATCAAGCCTGGCTGGG"
  ]
  node [
    id 830
    label "GGTCCGGCCGGACCGCA--TGCGCGGATCCGTGTGGGCCCGC"
  ]
  node [
    id 831
    label "GGCGCCGCGGTGCCGCC--GGCAGGGTACCCTGTCGGCCGAC"
  ]
  node [
    id 832
    label "GGCCACGCGTGGCCGCG--CGCGCGGTACCGTACCAGCTGGT"
  ]
  node [
    id 833
    label "GGCGCCATGGCGCCGCC--GGCGGAGCGCTCTCCCGGCCGGG"
  ]
  node [
    id 834
    label "GCAGGGATCCCTGCGCA--TGCGCAGATCTGTGGGAGCTCCC"
  ]
  node [
    id 835
    label "GGCGGCATGCCGCCGCC--GGCGCGGATCCGTTCCGGCCGGA"
  ]
  node [
    id 836
    label "TCCCTG--TGGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 837
    label "TCCCAG--TTGGGAGCT--AGCTCTGCGCAGACTGGGCCTGG"
  ]
  node [
    id 838
    label "GGCGCGATCGCGCCGCA--TGCGCGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 839
    label "TCCCTG--TAGGGAGCT--AGTTCCACGTGGGCCAGGCCTGG"
  ]
  node [
    id 840
    label "GACGCTGCGGCGTCGCC--GGCACCGGCCGGTGTGGGCCCAC"
  ]
  node [
    id 841
    label "GGGGGCATGCCCCCCTC--GAGTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 842
    label "GGCGACATGTCGCCGCC--GGCGAGGTACCTTGGCGGCCGCC"
  ]
  node [
    id 843
    label "GGCGCTGCAGCGCCGCC--GGCGAGGTACCTCACCGGCCGGT"
  ]
  node [
    id 844
    label "TCCTGG--TCAGGAGCTCGAGCTCTGCGCAGACCGGGCCTGG"
  ]
  node [
    id 845
    label "GGGGCA--TGCCCCGCTCGAGCTTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 846
    label "GGCGAAGCTTCGCCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 847
    label "GGCGCTGCAGCGCCGCC--GGCGGGCTAGCCTCCCGGCCGGG"
  ]
  node [
    id 848
    label "TCCCTGGTTGGGGAGCT--AGTTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 849
    label "GGGGGTATGCCCCCGTC--GACTTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 850
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCCCGGCTGGG"
  ]
  node [
    id 851
    label "GGACGGATTCGTCCGCTCGAGCACCGGCCGGTGCGCGCGCGC"
  ]
  node [
    id 852
    label "GGGGGTATGTCCCCGCTCGGGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 853
    label "GGTGGCATGCCACCGCC--GGCGAAGCGCTTCCCCAGCTGGG"
  ]
  node [
    id 854
    label "GGCGGCGCGCCGCCGCC--GGCGAGCTAGCTCAGCGGCCGCT"
  ]
  node [
    id 855
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAACCCAGCTGGG"
  ]
  node [
    id 856
    label "GGCTAGGCCTGGCCGCA--TGCGAGGATCCTTACCGGCCGGT"
  ]
  node [
    id 857
    label "GGTCCGGCCGGACCGCA--TGCGAGGATCCTTGTGGGCCCGC"
  ]
  node [
    id 858
    label "TCCCGG--TCGGGAGCT--AGCTCTGCGCGGACCAGGCCTGG"
  ]
  node [
    id 859
    label "GGCTGCGCGCAGCCGCA--TGCGCGGCGCCGTACCGGCCGGT"
  ]
  node [
    id 860
    label "TCCCGG--CTGGGAGCTTAAGCTCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 861
    label "GGCCCCGCGGGGCCGCA--TGCAAGGATCCTTATCGGCCGGT"
  ]
  node [
    id 862
    label "GGCGCGTACGCGCCGCA--TGCACGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 863
    label "GGGGGTATGTCCCCGCTCGAGCTTTGATCAAGCCTGGCTAGG"
  ]
  node [
    id 864
    label "GGGGTG--CGCCCCGCTCGAGCTTTGATCAAGCTTGGCCAAG"
  ]
  node [
    id 865
    label "GGCGCCATGGTGCCGCC--GGCGAGCTAGCTTCCCAGCTGGG"
  ]
  node [
    id 866
    label "GGCCGGGCCCGGCCGCA--TGCGGGGATCCCCGGCGGCCGCC"
  ]
  node [
    id 867
    label "GGCCGGGCTCGGCCGCA--TGCGCGGATCCGCGTCGGCCGGC"
  ]
  node [
    id 868
    label "GGGGGTATGCCCTCGTT--GACTTTGGTCGAACCTGGCTGGG"
  ]
  node [
    id 869
    label "TCCCAC--GTGGGAGCT--AGCTCTGTGCAGGCTGGGCCTGG"
  ]
  node [
    id 870
    label "GGGGGT--GCCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 871
    label "TCCCTG--CGGGGAGCT--AGCTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 872
    label "GACCATGCATGGTCCCC--GGGACCGCGCGGTACGGGCCCGT"
  ]
  node [
    id 873
    label "GGCTGGATCCGGCCGCA--TGCTCCGATCGGAGTGAGCTCAC"
  ]
  node [
    id 874
    label "TCCCGA--TCGGGAGCT--AGCTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 875
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCCTGGTCAGG"
  ]
  node [
    id 876
    label "GGCGAGTACTCGCCGCG--CGCGCGGATCCGTACCGGCCGGT"
  ]
  node [
    id 877
    label "GGCGACGCGTCGCCGCC--GGCACGGTATCGTCCCGGCCGGG"
  ]
  node [
    id 878
    label "GCCGAGATCTCGGCACC--GGTCGTGGCCACGTTGGGCCCAA"
  ]
  node [
    id 879
    label "GGCTGAGCTCAGCCGCA--TGCGCGGCGCCGTCTCGGCCGGG"
  ]
  node [
    id 880
    label "GGCGGCATGCCGCCGCC--GGCGGGGCGCCTTCCCAGCTGGG"
  ]
  node [
    id 881
    label "GGCGGCGCGCCGCCGCC--GGCAAGGTACCTTGTCGGCCGAC"
  ]
  node [
    id 882
    label "GGGGGTATGCCCCCCTC--GAGTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 883
    label "GGCGCCGCGGCGCCGCC--GGCGCGGATCCGCGTCGGCCGAC"
  ]
  node [
    id 884
    label "GGCGGGGCCCCGCCGCC--GGCGGGGATCCCTGCGGGCCCGC"
  ]
  node [
    id 885
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCCTAGCTGGG"
  ]
  node [
    id 886
    label "GGCCTCGCGAGGCCGCG--CGCGCGGATCCGTACCGGCCGGT"
  ]
  node [
    id 887
    label "GGCCCGGCCGGGCCGCA--TGCGCGGTACCGTATCGGCCGGT"
  ]
  node [
    id 888
    label "GGGTTCATGGGCCCGCTCGAGCATCGATCGATTCCAGCTGGA"
  ]
  node [
    id 889
    label "GGCGGCATGCCGCCGCC--GGCGGGGATCCCTCCCGGCCGGG"
  ]
  node [
    id 890
    label "GGCTAGGCCTAGCCGCA--TGCGCGGCGCCGTGTGGGCCCGC"
  ]
  node [
    id 891
    label "TCCCGG--CTGGGAGCT--AGCTCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 892
    label "GCAGGGATCCCTGCGCA--TGCACCGGCCGGTGAGAGCTCTC"
  ]
  node [
    id 893
    label "GGCGCCATGGCGCCGCC--GGCGAGCTAGCTTCCCAGCTGGG"
  ]
  node [
    id 894
    label "GGATAGGCCTATCCGCA--TGCTGGGATCCCATAGGGCCCTA"
  ]
  node [
    id 895
    label "TCCCGG--TTGGGAGCT--AGTTCTGCGCAGGTCAGGCCTGG"
  ]
  node [
    id 896
    label "GTCCGAGCTCGGACGCC--GGCTTGGTACTAAGTGGGCCCAC"
  ]
  node [
    id 897
    label "GGCTGAGCTCAGCCGTA--TACGCGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 898
    label "GGCTAGGCCTGGCCGCA--TGCGAGGATCCTTATCGGCCGGT"
  ]
  node [
    id 899
    label "TCCCAG--TTGGGAGCT--AGCTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 900
    label "GTCGGGATCCCGACACA--TGTGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 901
    label "TCCCGG--TTGGGAGCT--AGCTCTGCGCAGACCGGGCCTGG"
  ]
  node [
    id 902
    label "GGTACCCGGGTACCGCC--GGCACGGTACCGTAGCAGCTGCT"
  ]
  node [
    id 903
    label "TCCCGC--GTGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 904
    label "GGTGGTGCACCACCGCC--GGCACGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 905
    label "GGGGGTATGCTCCCGCTCGAGTTTTGATCAAGCTTGGTCAAG"
  ]
  node [
    id 906
    label "GCCGGAGCTCCGGCGCC--GGCAGGGATCCCTACGGGCCCGT"
  ]
  node [
    id 907
    label "GGCGCGATCGCGCTGCA--TGCACAGCGTTGTACCGGCCGGT"
  ]
  node [
    id 908
    label "GGCGCCGCGGCGCCGCC--GGCGGAGATCTCCGTCGGCCGAC"
  ]
  node [
    id 909
    label "GACGGCATGCCGTCGTC--GGCAAGGTGCCTTCCCGGCCGGG"
  ]
  node [
    id 910
    label "GGCGACATGTCGCCGCC--GGCGAGGTACCTTTCCAGCTGGA"
  ]
  node [
    id 911
    label "GGCAGCATGCTGCCGCC--GGCGAGGTACCTCCCCAGCTGGG"
  ]
  node [
    id 912
    label "TCCCGC--GTGGGAGCT--AGCTCTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 913
    label "GCATTGGCCAATGCGTC--GATCTCGCGCGGGCTGGGCCCGG"
  ]
  node [
    id 914
    label "GGTTCCGCGGAACCGCC--GGCGAGGTACCTCAGCGGCCGCT"
  ]
  node [
    id 915
    label "GGCGACGCGTCGCCGCC--GGCGGGGTACCCCCCCGGCCGGG"
  ]
  node [
    id 916
    label "GGGGGTATGCCCTCGCTCGAGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 917
    label "TCCTGAGCTTGGGAGCT--AGTTCTGTGCAGGCTAGGCCTGG"
  ]
  node [
    id 918
    label "GGTGGAATTCCACCGCC--GGCAAGGTACCTTTCCGGCCGGA"
  ]
  node [
    id 919
    label "GGCGACGCGTCGCCGTC--GGCGAGGTACCTTACCGGCCGGT"
  ]
  node [
    id 920
    label "AGGGCA--TGCTCTGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 921
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAACCCGGCCGGG"
  ]
  node [
    id 922
    label "GGCCCCGCGGGGCCGCC--GGCGAGGTACCTCACCAGCTGGT"
  ]
  node [
    id 923
    label "GGCGCGATCGCGCCGCC--GGCGAAGATCTTTGTCGGCCGAT"
  ]
  node [
    id 924
    label "GGTGACATGTCACCGCC--GGCGAGGATCCTCCCCGGCCGGG"
  ]
  node [
    id 925
    label "GGCGCGGTCGCGCCGCA--TGCGCGGCGCCGCGCTGGCCAGC"
  ]
  node [
    id 926
    label "GGGGGTATGCCCCCGCTCGAGTTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 927
    label "GCTCGTGTGCGAGCGCGCGCGCGCAGATCTGTCTTAGCTGAG"
  ]
  node [
    id 928
    label "GGCACCGCGGTGCCGCG--CGCGCGGATCCGTCCCGGCCGGG"
  ]
  node [
    id 929
    label "GCCTGG--TTGGGCGCTCGAGTTCTGATCAGGATGGGCCCGT"
  ]
  node [
    id 930
    label "TCCCTG--TGGGGAGCT--AGCTCTGCGCAGGCCAGGTCTGG"
  ]
  node [
    id 931
    label "GCCAAGGCCTTGGCGCG--CGCGCTGATCAGCCCCAGCTGGG"
  ]
  node [
    id 932
    label "GGGGGTGTGCCCCTGCTTGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 933
    label "GGGGTA--TGCCCCGCTCGAGCCTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 934
    label "GGCGCCGCGGCGCCGCC--GGCGTGGATCCACCCCGGCCGGG"
  ]
  node [
    id 935
    label "GGGCCA--TGGCCCGCT--AGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 936
    label "TCCCAGTGTTGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 937
    label "GGTGCCTAGGCACCGCC--GGTCGAAGCTTCGGTCAGCTGAC"
  ]
  node [
    id 938
    label "GGTGAAGCTTCACCGCC--GGCACGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 939
    label "GGTGGAATTCCACCGCC--GGCACGGCGCCGTACGGGCCCGT"
  ]
  node [
    id 940
    label "GGCAACGCGTTGCCGCG--CGCGAGGATCCTTCCCGGCCGGG"
  ]
  node [
    id 941
    label "GGCGAGATCTCGCCGCC--GGCGGGGCGCCCTACCGGCCGGT"
  ]
  node [
    id 942
    label "GGGGGTATGCCTCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 943
    label "GGCGCGGCCGCGCCGCA--TGCCCGGATCCGGCCCGGCCGGG"
  ]
  node [
    id 944
    label "GGCGACATGTCGCCGCC--GGCGGGGTACCCCCCCGGCCGGG"
  ]
  node [
    id 945
    label "TCCCGG--CTGGGAGCT--AGTTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 946
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 947
    label "GGCGACATGTCGCCGCC--GGCGAGGTACCTCTCCGGCCGGA"
  ]
  node [
    id 948
    label "TCCCGT--GTGGGAGCTTAAGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 949
    label "TCCTGG--TTGGGAGCT--AGTTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 950
    label "GGCGGCATGCCGCCGCC--GGCGAGGTACCTCACCGGCCGGT"
  ]
  node [
    id 951
    label "TCCCGC--GTGGGAGCT--AGTTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 952
    label "GGGGTA--TGCCCCGTC--GACTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 953
    label "TTCCTGGTTAGGGAGTCCGGACCTGCATGCAGCCGGGCCTGG"
  ]
  node [
    id 954
    label "GACTCCATGGGGTCGCTATAGCTGCGATCGCACCGTGCACGG"
  ]
  node [
    id 955
    label "GGCGCCATGGCGCCGCC--GGCGAGGATCCTCACCGGCCGGT"
  ]
  node [
    id 956
    label "TCCCTG--TAGGGAGCT--AGTTCTGTGCGGGCCAGGCCTGG"
  ]
  node [
    id 957
    label "GGCGCGGTCGCGCCGCA--TGCGCGGCGCCGCGTCGGCCGGC"
  ]
  node [
    id 958
    label "TCCTGG--TTGGGAGCTCGAGCTCTGCGCAGGCCTGGTTAGG"
  ]
  node [
    id 959
    label "GGCGGCATGCCGCCGCC--GGCGGGGTATCCTCCCAGCTGGG"
  ]
  node [
    id 960
    label "TCCCGC--GTGGGAGCT--AGTTCTGTGCAGGCCGGGCCTGG"
  ]
  node [
    id 961
    label "TCCCGC--GTGGGAGCT--AGCTCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 962
    label "GGGGGTGTGCCCCCGCTCGAGCTTTGATCAAGCTTGGCCAAG"
  ]
  node [
    id 963
    label "GGCACTGCAGTGCCGCC--GGCGAGGTACCTTAACGGCCGTT"
  ]
  node [
    id 964
    label "GGCGGCGCGCCGCCGCC--GGCAGGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 965
    label "GGCGTATATACGCCGCA--TGCTCGGATCCGACTCGGCCGGG"
  ]
  node [
    id 966
    label "GGCGCTGCGGCGCCCCC--GGGAAAGTACTTTGCCGGCCGGT"
  ]
  node [
    id 967
    label "GGCGGCGCGCCGCCGCC--GGCACGGTATCGTCGGGGCCCCG"
  ]
  node [
    id 968
    label "GGTTCCGCGGAACCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 969
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCAGGCTAGGCCTGG"
  ]
  node [
    id 970
    label "GGCGGCTAGCCGCCGCC--GGCACGGCGCCGTTCCAGCTGGA"
  ]
  node [
    id 971
    label "GGGGCCGCGGCCCCCCC--GGGGCGGTACCGCACCAGCTGGT"
  ]
  node [
    id 972
    label "GGCCGTGCACGGCCCCC--GGGCCAGATCTGGGCGGGCCCGC"
  ]
  node [
    id 973
    label "GGGCAGGCCTGCCCGCA--TGCCGGGATCCCGTCGGGCCCGA"
  ]
  node [
    id 974
    label "GCAGAATATTCTGCGCA--TGCACCGATCGGTGGGAGCTCTC"
  ]
  node [
    id 975
    label "GGGGCA--TGCCCTGCTCGGGCTTTGATCAAACCTGGCCAGG"
  ]
  node [
    id 976
    label "GGGGGTGTGCCCCCGCTCGAGCTTTGATCAAATCTGGCCAGG"
  ]
  node [
    id 977
    label "GGGGTA--TGCCCCGCTCGAGCTTTGATCAAGCCTGGCCGGG"
  ]
  node [
    id 978
    label "GGCGGCATGCCGCCGCC--GGCGAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 979
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATCAAGCTCGGCCGGG"
  ]
  node [
    id 980
    label "TCCTGG--TCAGGAGCT--AGCCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 981
    label "GGCGCCGCGGCGCCGCC--GGCGAGGTACCTTGCCGGCCGGC"
  ]
  node [
    id 982
    label "GGGTTCATGGGCCCGCTCGAGCATTGATCAATTCCGGCCGGA"
  ]
  node [
    id 983
    label "GGTGGGGCTCCACCGCC--GGCGCGGCGCCGTGCGGGCCCGT"
  ]
  node [
    id 984
    label "GGCGGCGCGTCGCCGCC--GGCGAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 985
    label "GGTGGGATCCCACCGCG--CGCGCGGATCCGTGCGGGCCCGC"
  ]
  node [
    id 986
    label "GGGGGT--GCCCCCGCTCGAGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 987
    label "GGGGTA--TGCCCCGCTCGAGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 988
    label "GGCCTCGCGAGGCCGCG--CGCGGAGATCTCTCTCGGCCGAG"
  ]
  node [
    id 989
    label "GGCGCCGCGGCGCCGCC--GGCGGAGTACTCTGGCGGCCGCC"
  ]
  node [
    id 990
    label "GGTCCTATGGGACCGCC--GGCTGAGATCTTACCGAGCTCGG"
  ]
  node [
    id 991
    label "GCCGGGGCCCCGGCGCT--GGCGCGGATCCGCGTGGGCCCAC"
  ]
  node [
    id 992
    label "GGTGGAATTCCACCGCC--GGCACGGTACCGTACGGGCCCGT"
  ]
  node [
    id 993
    label "GGCGCGGCCGCGCCGCG--CGCGCGGTACCGCGCCGGCCGGC"
  ]
  node [
    id 994
    label "GGCTGGATCCAGCCGCA--TGCGCGGATTCGCAACGGCCGTT"
  ]
  node [
    id 995
    label "GCCAAGGCCTTGGCGCG--CGCAATGCGCATTTCCGGCCGGA"
  ]
  node [
    id 996
    label "GGGGGTATGCCCCCGTC--GACTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 997
    label "GGCGACGCGTCGCCGCC--GGCGGGGTACCCCGCCGGCCGGC"
  ]
  node [
    id 998
    label "GCCAAGGCCTTGGCGCG--CGCGCTGATCAGCTCCGGCCGGA"
  ]
  node [
    id 999
    label "GGGCGGGCCCGCCCGCG--CGCGTGGTATCACACCGGCCGGT"
  ]
  node [
    id 1000
    label "GGCGCCGCGGCGCCCCC--GGGGAGGTACCTTATCAGCTGAT"
  ]
  node [
    id 1001
    label "GGCAAG--CTTGCCGCC--GGCGGGGTACCTCAGCGGCCGCT"
  ]
  node [
    id 1002
    label "TCCCAC--GTGGGAGCT--AGCTCTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 1003
    label "GGTCCGGCCGGACCGCA--TGTGCGGATCCGCGTGGGCCCGC"
  ]
  node [
    id 1004
    label "GGTTTCGCGAAACCGCC--GGCGAGCTAGCTCAGCGGCCGCT"
  ]
  node [
    id 1005
    label "GACCGTGCACGGTCCCC--GGGCTCGCGCGAGGCGGGCCCGC"
  ]
  node [
    id 1006
    label "GGCCTGGCCAGGCCGCC--GGCAGGGTACCCTGCGGGCCCGC"
  ]
  node [
    id 1007
    label "TCCCGC--GTGGGAGCT--AGCTTTGCGCAGACCGGGCCTGG"
  ]
  node [
    id 1008
    label "GGCGGGGCCCCGCCGCC--GGCGGGCGCGCCCGCTGGCCAGC"
  ]
  node [
    id 1009
    label "GGCCTCGCGAGGCCGCG--CGCGAGGATCCTTCCCAGCTGGG"
  ]
  node [
    id 1010
    label "GGGGGTATGCTCCCGCTCGAGTTTTGATCAAGCTTGGCCAAG"
  ]
  node [
    id 1011
    label "GGTGGGATCTCACCGCC--GGCACGGTACCGTACGGGCCCGT"
  ]
  node [
    id 1012
    label "GGCGGGTACCCGCCGCA--TGCGCGGATCCGTCTCGGCCGGG"
  ]
  node [
    id 1013
    label "GTCAGGATCCTGACGCA--TGCTCCGGCCGGAGTGAGCTCAC"
  ]
  node [
    id 1014
    label "GGTGTCGCGACACCGCC--GGCGTGGTACCATAGCGGCCGCT"
  ]
  node [
    id 1015
    label "GGGGGTATGCCCCCGCTTGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 1016
    label "GCCAATGCATTGGCGCG--CGCGCTGATCAGCCCCGGCCGGG"
  ]
  node [
    id 1017
    label "GGGGTA--TGCCCCGCT--AGCTTTGATCAGGCCTGGCCAGG"
  ]
  node [
    id 1018
    label "GGGGGCATGCTCCCGCTCGAGCTTTGATCAAGCCTAGCTAGG"
  ]
  node [
    id 1019
    label "GGCGCCGCGGCGCCGCC--GGCGAGGTACCTCCCCGGCCGGG"
  ]
  node [
    id 1020
    label "GGTACTCGGGTACCGCA--TGCTGGGCGCCTAGGGGGCCCTC"
  ]
  node [
    id 1021
    label "GGCGGAGCTCCGCCGCC--GGCAGGGATCCCTACGGGCCCGT"
  ]
  node [
    id 1022
    label "GGGGGTATGCCCCCGCC--GGCTTTGATCAAGCCCAGCTGGG"
  ]
  node [
    id 1023
    label "GGCGCGTACGCGCCGCA--TGTGCGGATCCGTTCCGGCCGGA"
  ]
  node [
    id 1024
    label "GGCGGCATGCCGCCGCC--GGCACGGCGCCGTCCCGGCCGGG"
  ]
  node [
    id 1025
    label "GGCGCGATCGCGCCGCA--TGCGCGGCGCCGTGCCGGCCGGC"
  ]
  node [
    id 1026
    label "GGGGAA--TTCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 1027
    label "GGGCCAGCTGGCTCGCG--CGCTCTGATCAGACTAGGCCTGG"
  ]
  node [
    id 1028
    label "GGCGGCTAGCCGCCGCC--GGCACGGTACCGTGGCGGCCGCC"
  ]
  node [
    id 1029
    label "TCCCGG--TTGGGAGCT--AGCTCTGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 1030
    label "GGCGGCATGTCGCCGCC--GGCCAGGTACCTGATCGGCCGAT"
  ]
  node [
    id 1031
    label "GCCGAGATCTCGGCACC--GGTCATGGCCATGTTGGGCCCAA"
  ]
  node [
    id 1032
    label "GGCTGGGCCCAGCCGCA--TGCGGGGCGCCTTACCGGCCGGT"
  ]
  node [
    id 1033
    label "GCTGAGATCTCAGCGCG--CGCGTGGATCCATCCCGGCCGGG"
  ]
  node [
    id 1034
    label "TCCCGG--TCGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 1035
    label "GGCGCGATCGCGCCGCA--TGCACGGATCCGTTCCGGCCGGA"
  ]
  node [
    id 1036
    label "GGCGCGATCGCGCCGCA--TGCGCGGCGCCGTCTCGGCCGGG"
  ]
  node [
    id 1037
    label "GGCGGCATGTCGCCGCC--GGCGAGGTACCTTCCCAGCTGGG"
  ]
  node [
    id 1038
    label "GCCAGGATCCTGGCGCG--CGCATCGCGCGATCCCGGCCGGG"
  ]
  node [
    id 1039
    label "TCCTGG--TCAGGAGCT--AGCTCTACGTGGGCCAGGCCTGG"
  ]
  node [
    id 1040
    label "GGCGCGGCCGCGCCGCC--GGCGAGGATCCTTGTCGGCCGAC"
  ]
  node [
    id 1041
    label "GTGTGG--CCACACGCTCGAGCCCAGGCCTGGACGGGCCCGT"
  ]
  node [
    id 1042
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCGGACCAGGCCTGG"
  ]
  node [
    id 1043
    label "GGGGGTGTGCCCCCGCTCGAGCTTCGATCGAGTTTGGCCGGG"
  ]
  node [
    id 1044
    label "GTCAGAATTCTGACGCA--TGCTCCGGCCGGAGTGAGCTCAC"
  ]
  node [
    id 1045
    label "GGTGGGTACCCACCGCG--CGCGCGGTACCGTGTGGGCCCAC"
  ]
  node [
    id 1046
    label "GGCGGGTACCCGCCGTA--TGCGCGGATCCGTACCGGCCGGT"
  ]
  node [
    id 1047
    label "TCCCAG--TTGGGAGCT--AGTTCTGCGCAGACTGGGCCTGG"
  ]
  node [
    id 1048
    label "GGTGGTATACCACCGCC--GGCGAGGTACCTTACCGGCCGGT"
  ]
  node [
    id 1049
    label "TCCCGG--CTGGGAGCT--AGTTCTGCGTGGGTCAGGCCTGG"
  ]
  node [
    id 1050
    label "GGCTGAGCTCAGCCGTA--TACGCGGATCCGTGTCGGCCGGC"
  ]
  node [
    id 1051
    label "GGCACTGCAGTGCCGCC--GGCGAGGTACCTTAGCGGCCGCT"
  ]
  node [
    id 1052
    label "GCCAGG--CCTGGCGCG--CGCGCTGATCAGCCCCGGCCGGG"
  ]
  node [
    id 1053
    label "GTCCAGGCCTGGACGCCTGGGTTTGGTACCGAGCGAGCTCGC"
  ]
  node [
    id 1054
    label "GGACGGGTTCGTCCGCTCGAGCACCGGCCGGTACGCGCGCGT"
  ]
  node [
    id 1055
    label "GGGGGTGTGCCCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 1056
    label "GGTGACATGTCACCGCC--GGCAGGGTACCCTCCCGGCCGGG"
  ]
  node [
    id 1057
    label "GGCGCCATGGCGCCGCC--GGCGAGGTACCTTCTCAGCTGAG"
  ]
  node [
    id 1058
    label "GGCGCCATGGCGCCGCC--GGCGAGGTACCTTCCCGGCCGGG"
  ]
  node [
    id 1059
    label "GGGCTCATGGGCCCGCTCGAGCTTCGATCGAGACCGGCCGGT"
  ]
  node [
    id 1060
    label "GGCGGCATGCCGCCGCC--GGCGAGGTACCTTCCCGGCCGGG"
  ]
  node [
    id 1061
    label "GCAGGGATCCCTGCGCA--TGCGCGGATCCGTGGGAGCTCTC"
  ]
  node [
    id 1062
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATTAAGCCCAGCTGGG"
  ]
  node [
    id 1063
    label "GGCGCCGCGGCGCCCCC--GGGGAGGTACCTTGTTGGCCAAT"
  ]
  node [
    id 1064
    label "GGTCGGGCCCGACCGCC--GGCGCGGCGCCGTGCGGGCCCGT"
  ]
  node [
    id 1065
    label "GGGGGTATGCCCCCGCTCGAGCTTTGATTAAGCCTGGCCAGG"
  ]
  node [
    id 1066
    label "GGCGGCATGCCGCCGCC--GGCGAGGTACCTTTCCGGCCGGA"
  ]
  node [
    id 1067
    label "GGGGGT--GCCCCCGCTTGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  node [
    id 1068
    label "GGGGGA--TCCCCCGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 1069
    label "GGCGCTGCAGTGCCGCC--GGCACGGATCCGTACCGGCCGGT"
  ]
  node [
    id 1070
    label "GGCGACATGTCGCCGCC--GGCCGAGTACTCGCCCGGCCGGG"
  ]
  node [
    id 1071
    label "GGCAGCATGCTGCCGCC--GGCAAGGTACCTTCCCGGCCGGG"
  ]
  node [
    id 1072
    label "GGGTCCATGGGCCCGCTCGAGCTTTGATCAAGTCCGGCCGGA"
  ]
  node [
    id 1073
    label "GGCGCGGCCGCGCCGCA--TGCCCGGATCCGGTCCGGCCGGA"
  ]
  node [
    id 1074
    label "GGGGGTATACCCCCGCTCGAGCTTTGATCAAGCCCGGCCGGG"
  ]
  edge [
    source 1
    target 1014
  ]
  edge [
    source 3
    target 442
  ]
  edge [
    source 4
    target 984
  ]
  edge [
    source 7
    target 278
  ]
  edge [
    source 9
    target 830
  ]
  edge [
    source 9
    target 1003
  ]
  edge [
    source 10
    target 242
  ]
  edge [
    source 10
    target 18
  ]
  edge [
    source 11
    target 311
  ]
  edge [
    source 12
    target 432
  ]
  edge [
    source 12
    target 32
  ]
  edge [
    source 12
    target 807
  ]
  edge [
    source 13
    target 252
  ]
  edge [
    source 13
    target 1060
  ]
  edge [
    source 15
    target 415
  ]
  edge [
    source 15
    target 97
  ]
  edge [
    source 17
    target 301
  ]
  edge [
    source 17
    target 1033
  ]
  edge [
    source 18
    target 148
  ]
  edge [
    source 18
    target 429
  ]
  edge [
    source 18
    target 713
  ]
  edge [
    source 20
    target 148
  ]
  edge [
    source 20
    target 549
  ]
  edge [
    source 23
    target 904
  ]
  edge [
    source 23
    target 428
  ]
  edge [
    source 24
    target 1027
  ]
  edge [
    source 27
    target 190
  ]
  edge [
    source 29
    target 595
  ]
  edge [
    source 31
    target 469
  ]
  edge [
    source 32
    target 415
  ]
  edge [
    source 36
    target 222
  ]
  edge [
    source 36
    target 239
  ]
  edge [
    source 36
    target 109
  ]
  edge [
    source 38
    target 978
  ]
  edge [
    source 39
    target 180
  ]
  edge [
    source 41
    target 132
  ]
  edge [
    source 45
    target 689
  ]
  edge [
    source 45
    target 336
  ]
  edge [
    source 46
    target 163
  ]
  edge [
    source 49
    target 671
  ]
  edge [
    source 57
    target 422
  ]
  edge [
    source 61
    target 481
  ]
  edge [
    source 62
    target 654
  ]
  edge [
    source 63
    target 485
  ]
  edge [
    source 68
    target 148
  ]
  edge [
    source 68
    target 194
  ]
  edge [
    source 68
    target 72
  ]
  edge [
    source 71
    target 110
  ]
  edge [
    source 72
    target 290
  ]
  edge [
    source 72
    target 195
  ]
  edge [
    source 72
    target 592
  ]
  edge [
    source 74
    target 978
  ]
  edge [
    source 77
    target 486
  ]
  edge [
    source 77
    target 707
  ]
  edge [
    source 79
    target 319
  ]
  edge [
    source 80
    target 277
  ]
  edge [
    source 81
    target 440
  ]
  edge [
    source 82
    target 636
  ]
  edge [
    source 85
    target 147
  ]
  edge [
    source 87
    target 148
  ]
  edge [
    source 87
    target 627
  ]
  edge [
    source 88
    target 552
  ]
  edge [
    source 91
    target 763
  ]
  edge [
    source 97
    target 148
  ]
  edge [
    source 97
    target 492
  ]
  edge [
    source 97
    target 429
  ]
  edge [
    source 100
    target 595
  ]
  edge [
    source 104
    target 982
  ]
  edge [
    source 107
    target 836
  ]
  edge [
    source 111
    target 588
  ]
  edge [
    source 111
    target 463
  ]
  edge [
    source 112
    target 160
  ]
  edge [
    source 113
    target 814
  ]
  edge [
    source 115
    target 531
  ]
  edge [
    source 121
    target 609
  ]
  edge [
    source 121
    target 823
  ]
  edge [
    source 127
    target 389
  ]
  edge [
    source 128
    target 836
  ]
  edge [
    source 129
    target 1005
  ]
  edge [
    source 138
    target 153
  ]
  edge [
    source 144
    target 981
  ]
  edge [
    source 145
    target 242
  ]
  edge [
    source 145
    target 921
  ]
  edge [
    source 145
    target 653
  ]
  edge [
    source 146
    target 468
  ]
  edge [
    source 146
    target 824
  ]
  edge [
    source 146
    target 652
  ]
  edge [
    source 148
    target 463
  ]
  edge [
    source 148
    target 415
  ]
  edge [
    source 148
    target 588
  ]
  edge [
    source 148
    target 242
  ]
  edge [
    source 148
    target 386
  ]
  edge [
    source 148
    target 942
  ]
  edge [
    source 148
    target 653
  ]
  edge [
    source 148
    target 875
  ]
  edge [
    source 148
    target 1065
  ]
  edge [
    source 148
    target 176
  ]
  edge [
    source 151
    target 205
  ]
  edge [
    source 155
    target 793
  ]
  edge [
    source 156
    target 421
  ]
  edge [
    source 157
    target 588
  ]
  edge [
    source 157
    target 176
  ]
  edge [
    source 170
    target 355
  ]
  edge [
    source 175
    target 457
  ]
  edge [
    source 176
    target 779
  ]
  edge [
    source 176
    target 863
  ]
  edge [
    source 176
    target 498
  ]
  edge [
    source 176
    target 852
  ]
  edge [
    source 176
    target 738
  ]
  edge [
    source 179
    target 675
  ]
  edge [
    source 184
    target 817
  ]
  edge [
    source 186
    target 722
  ]
  edge [
    source 191
    target 977
  ]
  edge [
    source 194
    target 242
  ]
  edge [
    source 194
    target 195
  ]
  edge [
    source 194
    target 258
  ]
  edge [
    source 195
    target 438
  ]
  edge [
    source 195
    target 366
  ]
  edge [
    source 197
    target 577
  ]
  edge [
    source 200
    target 992
  ]
  edge [
    source 201
    target 977
  ]
  edge [
    source 201
    target 305
  ]
  edge [
    source 203
    target 1004
  ]
  edge [
    source 204
    target 769
  ]
  edge [
    source 210
    target 353
  ]
  edge [
    source 220
    target 1043
  ]
  edge [
    source 222
    target 817
  ]
  edge [
    source 222
    target 1042
  ]
  edge [
    source 223
    target 342
  ]
  edge [
    source 223
    target 744
  ]
  edge [
    source 223
    target 461
  ]
  edge [
    source 223
    target 769
  ]
  edge [
    source 226
    target 621
  ]
  edge [
    source 228
    target 746
  ]
  edge [
    source 230
    target 398
  ]
  edge [
    source 230
    target 895
  ]
  edge [
    source 232
    target 509
  ]
  edge [
    source 234
    target 846
  ]
  edge [
    source 235
    target 510
  ]
  edge [
    source 240
    target 1066
  ]
  edge [
    source 242
    target 477
  ]
  edge [
    source 242
    target 406
  ]
  edge [
    source 242
    target 466
  ]
  edge [
    source 242
    target 502
  ]
  edge [
    source 242
    target 726
  ]
  edge [
    source 242
    target 471
  ]
  edge [
    source 244
    target 280
  ]
  edge [
    source 246
    target 344
  ]
  edge [
    source 248
    target 294
  ]
  edge [
    source 248
    target 836
  ]
  edge [
    source 248
    target 392
  ]
  edge [
    source 249
    target 1067
  ]
  edge [
    source 251
    target 838
  ]
  edge [
    source 257
    target 278
  ]
  edge [
    source 257
    target 1060
  ]
  edge [
    source 258
    target 438
  ]
  edge [
    source 258
    target 726
  ]
  edge [
    source 259
    target 946
  ]
  edge [
    source 259
    target 325
  ]
  edge [
    source 259
    target 727
  ]
  edge [
    source 259
    target 624
  ]
  edge [
    source 261
    target 497
  ]
  edge [
    source 261
    target 977
  ]
  edge [
    source 261
    target 933
  ]
  edge [
    source 266
    target 319
  ]
  edge [
    source 274
    target 654
  ]
  edge [
    source 276
    target 344
  ]
  edge [
    source 279
    target 987
  ]
  edge [
    source 279
    target 706
  ]
  edge [
    source 283
    target 1023
  ]
  edge [
    source 286
    target 996
  ]
  edge [
    source 289
    target 347
  ]
  edge [
    source 289
    target 682
  ]
  edge [
    source 290
    target 700
  ]
  edge [
    source 294
    target 767
  ]
  edge [
    source 294
    target 631
  ]
  edge [
    source 296
    target 823
  ]
  edge [
    source 304
    target 756
  ]
  edge [
    source 305
    target 736
  ]
  edge [
    source 306
    target 744
  ]
  edge [
    source 307
    target 882
  ]
  edge [
    source 310
    target 433
  ]
  edge [
    source 314
    target 951
  ]
  edge [
    source 314
    target 903
  ]
  edge [
    source 318
    target 786
  ]
  edge [
    source 325
    target 548
  ]
  edge [
    source 328
    target 535
  ]
  edge [
    source 331
    target 495
  ]
  edge [
    source 337
    target 1054
  ]
  edge [
    source 341
    target 531
  ]
  edge [
    source 343
    target 903
  ]
  edge [
    source 344
    target 364
  ]
  edge [
    source 344
    target 638
  ]
  edge [
    source 344
    target 1062
  ]
  edge [
    source 344
    target 885
  ]
  edge [
    source 344
    target 850
  ]
  edge [
    source 344
    target 855
  ]
  edge [
    source 344
    target 916
  ]
  edge [
    source 346
    target 465
  ]
  edge [
    source 351
    target 885
  ]
  edge [
    source 351
    target 364
  ]
  edge [
    source 353
    target 494
  ]
  edge [
    source 353
    target 499
  ]
  edge [
    source 353
    target 545
  ]
  edge [
    source 353
    target 980
  ]
  edge [
    source 353
    target 597
  ]
  edge [
    source 354
    target 842
  ]
  edge [
    source 361
    target 817
  ]
  edge [
    source 365
    target 438
  ]
  edge [
    source 367
    target 737
  ]
  edge [
    source 371
    target 398
  ]
  edge [
    source 375
    target 964
  ]
  edge [
    source 381
    target 577
  ]
  edge [
    source 384
    target 713
  ]
  edge [
    source 385
    target 750
  ]
  edge [
    source 386
    target 471
  ]
  edge [
    source 386
    target 498
  ]
  edge [
    source 393
    target 1058
  ]
  edge [
    source 398
    target 609
  ]
  edge [
    source 398
    target 654
  ]
  edge [
    source 398
    target 1029
  ]
  edge [
    source 398
    target 1034
  ]
  edge [
    source 400
    target 891
  ]
  edge [
    source 405
    target 771
  ]
  edge [
    source 406
    target 588
  ]
  edge [
    source 415
    target 627
  ]
  edge [
    source 415
    target 505
  ]
  edge [
    source 417
    target 609
  ]
  edge [
    source 418
    target 439
  ]
  edge [
    source 421
    target 950
  ]
  edge [
    source 425
    target 817
  ]
  edge [
    source 432
    target 1055
  ]
  edge [
    source 439
    target 983
  ]
  edge [
    source 440
    target 688
  ]
  edge [
    source 440
    target 962
  ]
  edge [
    source 442
    target 966
  ]
  edge [
    source 443
    target 611
  ]
  edge [
    source 443
    target 464
  ]
  edge [
    source 446
    target 805
  ]
  edge [
    source 447
    target 708
  ]
  edge [
    source 447
    target 784
  ]
  edge [
    source 447
    target 697
  ]
  edge [
    source 461
    target 726
  ]
  edge [
    source 462
    target 832
  ]
  edge [
    source 463
    target 502
  ]
  edge [
    source 463
    target 738
  ]
  edge [
    source 464
    target 761
  ]
  edge [
    source 466
    target 885
  ]
  edge [
    source 466
    target 850
  ]
  edge [
    source 467
    target 619
  ]
  edge [
    source 467
    target 1058
  ]
  edge [
    source 469
    target 561
  ]
  edge [
    source 471
    target 595
  ]
  edge [
    source 477
    target 1015
  ]
  edge [
    source 481
    target 885
  ]
  edge [
    source 489
    target 882
  ]
  edge [
    source 492
    target 1065
  ]
  edge [
    source 502
    target 979
  ]
  edge [
    source 504
    target 987
  ]
  edge [
    source 505
    target 932
  ]
  edge [
    source 508
    target 537
  ]
  edge [
    source 509
    target 763
  ]
  edge [
    source 510
    target 959
  ]
  edge [
    source 522
    target 978
  ]
  edge [
    source 528
    target 715
  ]
  edge [
    source 541
    target 903
  ]
  edge [
    source 554
    target 555
  ]
  edge [
    source 555
    target 819
  ]
  edge [
    source 556
    target 858
  ]
  edge [
    source 562
    target 656
  ]
  edge [
    source 569
    target 672
  ]
  edge [
    source 571
    target 946
  ]
  edge [
    source 571
    target 676
  ]
  edge [
    source 574
    target 584
  ]
  edge [
    source 575
    target 713
  ]
  edge [
    source 580
    target 812
  ]
  edge [
    source 580
    target 838
  ]
  edge [
    source 581
    target 713
  ]
  edge [
    source 585
    target 739
  ]
  edge [
    source 593
    target 1029
  ]
  edge [
    source 595
    target 726
  ]
  edge [
    source 609
    target 895
  ]
  edge [
    source 609
    target 949
  ]
  edge [
    source 624
    target 1042
  ]
  edge [
    source 631
    target 836
  ]
  edge [
    source 634
    target 798
  ]
  edge [
    source 635
    target 1071
  ]
  edge [
    source 649
    target 951
  ]
  edge [
    source 649
    target 903
  ]
  edge [
    source 649
    target 912
  ]
  edge [
    source 653
    target 713
  ]
  edge [
    source 654
    target 891
  ]
  edge [
    source 660
    target 836
  ]
  edge [
    source 682
    target 862
  ]
  edge [
    source 689
    target 885
  ]
  edge [
    source 706
    target 977
  ]
  edge [
    source 712
    target 1002
  ]
  edge [
    source 714
    target 1037
  ]
  edge [
    source 717
    target 1074
  ]
  edge [
    source 717
    target 1055
  ]
  edge [
    source 720
    target 748
  ]
  edge [
    source 726
    target 1015
  ]
  edge [
    source 726
    target 979
  ]
  edge [
    source 726
    target 926
  ]
  edge [
    source 726
    target 850
  ]
  edge [
    source 726
    target 1074
  ]
  edge [
    source 726
    target 1055
  ]
  edge [
    source 726
    target 921
  ]
  edge [
    source 749
    target 987
  ]
  edge [
    source 752
    target 874
  ]
  edge [
    source 752
    target 1029
  ]
  edge [
    source 756
    target 927
  ]
  edge [
    source 763
    target 885
  ]
  edge [
    source 776
    target 961
  ]
  edge [
    source 780
    target 893
  ]
  edge [
    source 802
    target 867
  ]
  edge [
    source 814
    target 1023
  ]
  edge [
    source 817
    target 969
  ]
  edge [
    source 817
    target 836
  ]
  edge [
    source 817
    target 946
  ]
  edge [
    source 836
    target 930
  ]
  edge [
    source 837
    target 1047
  ]
  edge [
    source 845
    target 977
  ]
  edge [
    source 849
    target 996
  ]
  edge [
    source 856
    target 898
  ]
  edge [
    source 865
    target 893
  ]
  edge [
    source 899
    target 1029
  ]
  edge [
    source 905
    target 1010
  ]
  edge [
    source 912
    target 1002
  ]
  edge [
    source 914
    target 968
  ]
  edge [
    source 978
    target 1037
  ]
]
