graph [
  node [
    id 0
    label "GTGATG--CGTTGCGCC--GGCGTGGATCCACGCGGGCCCGT"
  ]
  node [
    id 1
    label "GTCCCTATAGGGACGTC--GACTCACATGTGGGCCTGCAGGC"
  ]
  node [
    id 2
    label "GCCCATGCATGGGCGTATGTACCCACGCGTGGGGTGGCCACC"
  ]
  node [
    id 3
    label "GTGGCTATAGCCACGCTCGAGTCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 4
    label "GCGGGG--CCTCGCGTG--CACTCAGATCTGAGTGGGCCCAT"
  ]
  node [
    id 5
    label "GCCGCCTAGGCGGTGCTCGAGCCTGGATCCAGCCCTGCAGGG"
  ]
  node [
    id 6
    label "GCGAGCGCGTTCGCGCC--GGCGTGGGCCCGCGTGGGCCCAT"
  ]
  node [
    id 7
    label "GTGGACGCGTCCACGCTCGAGCCAGGATCCTGGAGGGCCCTT"
  ]
  node [
    id 8
    label "GCGGGTGCACTCGCGTG--CACCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 9
    label "GCCCGGATCCGGGCGGG--CCTTGGGATCCCACCGGGCCCGG"
  ]
  node [
    id 10
    label "GCTGTGGTCACAGCGTT--GACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 11
    label "CCGTGA--TCACGGGTATGTACCTGCGCGCAGCCTGGCTGGG"
  ]
  node [
    id 12
    label "GTGAGTGCACTCACGCTCGAGCTCAGGTCTGAGTGGGCCCAT"
  ]
  node [
    id 13
    label "GCGATG--CGTTGCGCC--GGCGTGGATCCACGCGGGCCCGT"
  ]
  node [
    id 14
    label "GCGGTTGCAGTCGCGCG--CGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 15
    label "GTGGGTTAATCCACGCTCGAGCCCGCTAGCGGGGGGGCCCCT"
  ]
  node [
    id 16
    label "GTGGGTGCACTCACGCTCGAGCCCGGGCCCGGGCGGGCCCGT"
  ]
  node [
    id 17
    label "GTGCAGGTCTGCACGCTTAAGCCCAGGCCTGGGGCGGCCGCT"
  ]
  node [
    id 18
    label "GTGGGATATCTCACGCTTAAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 19
    label "GTGGTTGCAGCCACGCTCGAGTGCGGTGCCGCGCCGGCCGGT"
  ]
  node [
    id 20
    label "GTGGTG--CACCACGCTCGAGCCTGGTGCCGGGCCGGCCGGT"
  ]
  node [
    id 21
    label "GCCGTG--CACGGTGTATGTACCTGCGTGCAGCCCGGCCGGG"
  ]
  node [
    id 22
    label "GTGGCTGCAGCCACGTTTGAATCTACGCGTAGCTGGGCCCAG"
  ]
  node [
    id 23
    label "GTGCCTGCAGGCACGCTCGAGCCCTGATCAGGGTGGGCCCAT"
  ]
  node [
    id 24
    label "GTGGGTGCACTCACGCTCGAGCCCAGGCCTGGGCGGGCCCGT"
  ]
  node [
    id 25
    label "GCGGGCGCGCTCGCGCTCGAGCCAAGGTCTTGGCGGATCCGT"
  ]
  node [
    id 26
    label "GAGGGTGCACCCTCGCTCGAGCGTGGATCCACGCGGGCCCGT"
  ]
  node [
    id 27
    label "GCCATTTAAATGGCGTATGTACCATCGCGATGCCAGGCTTGG"
  ]
  node [
    id 28
    label "GTGGGCGCGTCCACGCTCGAGCATGGATCCATGTGGGCCCAT"
  ]
  node [
    id 29
    label "GTGGCTGCAGCCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 30
    label "GAGAACATGTTCTCCGC--GCGGCCGATCGGCGCGGGCCCGC"
  ]
  node [
    id 31
    label "GTGGGCGCGCTCACGCTCGAGCCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 32
    label "GTGGGTGCACTCACGCTCGAGCCCGCGCGCGGGCGGGCCCGT"
  ]
  node [
    id 33
    label "GGGTCAGCTGGCTTGCG--TGCTCTGATCAGATCAGGCCTGG"
  ]
  node [
    id 34
    label "GCCGGGATCCCGGCGGG--CCTAGGGATCCCTCTGGGCCCGG"
  ]
  node [
    id 35
    label "GTGGGTGCACCCACGCCCGGGCCATGATCATGGTGGGCCCAT"
  ]
  node [
    id 36
    label "GTGATTGCAGTCACGCTCGAGCCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 37
    label "GTGGGTGCACTCACGCTCGAGCCCTGGCCAGGGCGCGCGCGT"
  ]
  node [
    id 38
    label "GCGGCTGCAGCCGCGCG--CGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 39
    label "GTGGCTGCAGCCACGCTCGAGCTTGGTGCCAAGGGGGCCCCT"
  ]
  node [
    id 40
    label "GTGCGCGCGTGCACGCTCGAGCGCTGGCCAGCGACGGCCGTT"
  ]
  node [
    id 41
    label "GTGGGTGCACTCACGCTCGAGCCCTGGCCAGGGCAGGCCTGT"
  ]
  node [
    id 42
    label "GCGGATGCGTTCGCGCC--GGCGTGGATTCACGCGGGCCCGT"
  ]
  node [
    id 43
    label "GCGGTTGCAGTCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 44
    label "GTGGGTGCACTCACGCTCGAGCCCAGGCCTGGGGGGGCCCCT"
  ]
  node [
    id 45
    label "GCCCACGCGTGGGCGAT--GTCCCACGCGTGGGCTGGCCAGC"
  ]
  node [
    id 46
    label "GTGGTG--CACCACGCTCGAGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 47
    label "GTGGGTATACCCACGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 48
    label "GCCGTG--CATGGCGTATGTACCTGTGTGCAGCCCGGCTGGG"
  ]
  node [
    id 49
    label "GTGGCTATAGCCACGCTCGAGCCTGGATCCGGGCGAGCTCGT"
  ]
  node [
    id 50
    label "GTGGCCGCGGCCACGCTCGAGTCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 51
    label "GTGGCTGCAGTCACGCTCGAGCCCAGGCCTGGGGGGGCCCCT"
  ]
  node [
    id 52
    label "GCCTGA--TCAGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 53
    label "GTGGCCGCGGTCACGCTCGAGTCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 54
    label "GCGGTTGCAGCCGCGTG--CACCCGGATCCGGGAGGGCCCTT"
  ]
  node [
    id 55
    label "GTGGTG--CACCACGTTCGAACCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 56
    label "GTGGCTATAGCCACGCTCGAGCCCGCGCGCGGGCGGGCCCGT"
  ]
  node [
    id 57
    label "GCGGCTGCAGCCGCGTG--CACTCGGATCCGAGAGGGCCCTT"
  ]
  node [
    id 58
    label "GCCATCTAGGTGGCGTA--TACCAACATGTTGCCTGGCTAGG"
  ]
  node [
    id 59
    label "GTGAGCGCGTTCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 60
    label "GCCGTCTAGACGGTGCTCGAGCCCAGATCTGGGCTGGCCAGC"
  ]
  node [
    id 61
    label "GAGGATGCATCCTCGCTCGAGCCAAGGCCTTGGCGGGCCCGT"
  ]
  node [
    id 62
    label "GCGGCCGCGGTCGCGCTCGAGCCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 63
    label "GCCGGGGCCCCGGCGTGTGCACGGGGATCCCCCCGGGCCCGG"
  ]
  node [
    id 64
    label "GCCGTGATCACGGCGAT--GTCCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 65
    label "GCCGTGATCACGGCGTATGTGCCTGTGCGCAGCCCGGCCGGG"
  ]
  node [
    id 66
    label "GTGGGTGCACTCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 67
    label "GCGAAAGCTTTCGCGTG--CACCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 68
    label "GTGACTGCAGTCACGTTCGAGCCCAGGCCTGGGCGGGCCCGT"
  ]
  node [
    id 69
    label "GTGACCGCGGTCACGCTCGAGCCCAGGCCTGGGGGGGCCCCT"
  ]
  node [
    id 70
    label "GCTGTGATCACGGCGTATGTACCTGTGTGCAGCCCGGCTGGG"
  ]
  node [
    id 71
    label "GCGGTTGCAGTCGCGCTCGAGCCCGGGCTCGGGTGGGCCCAT"
  ]
  node [
    id 72
    label "GTGGGTGCACCCACGCTCGAGTCCGGATCCGGGGGAGCTCCT"
  ]
  node [
    id 73
    label "GTAGGCATGCTTACGCTCGAGCTCAGATCTGAGTGGGCCCAT"
  ]
  node [
    id 74
    label "GCGGTCGCGATCGCGCG--CGCTCGGATCCGAGGGGGCCCCT"
  ]
  node [
    id 75
    label "GCCTGG--TTGGGCGCT--AGCTCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 76
    label "GCGATCGCGATCGCGCTCGAGCCCGGTACCGGGTGGGCCCAT"
  ]
  node [
    id 77
    label "GTGTTTGCAGACACGCC--GGCCTGGTACCAGGCGGGCCCGT"
  ]
  node [
    id 78
    label "GTGGCTATAGCCACGCTCGAGCCCTGGCCAGGGCCGGCCGGT"
  ]
  node [
    id 79
    label "GTGGGTGCATCCACGCTCGAGCCCAGATCTGGGCCGGCCGGT"
  ]
  node [
    id 80
    label "GTGGCTATAGCCACGCTCGAGCCTGGATCCAGGTGAGCTCAT"
  ]
  node [
    id 81
    label "GCGGCCGCGGCCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 82
    label "GTGGGTGTACCCACGCC--GGCTCGGATCCGAGAGGGCCCTC"
  ]
  node [
    id 83
    label "GCGAGTGCACTCGCGCTCGAGCTCAGGTCTGAACGGGCCCGT"
  ]
  node [
    id 84
    label "CCTGTT--AGCAGGGTATGTACCCACGCGTGGGCTGGCCAGC"
  ]
  node [
    id 85
    label "GTGGGTGCACTCACGCT--AGCCCTGGCCAGGGTGGGCCCAT"
  ]
  node [
    id 86
    label "GGGCTG--CAGCCCGTTTGAATCCACGCGTGGCTGGGCCCAG"
  ]
  node [
    id 87
    label "GCGGTATATACCGCGTG--CACCCGGTACCGGGTGGGCCCAC"
  ]
  node [
    id 88
    label "GTGGATATATCCACGTTCGAGCCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 89
    label "GTGGTTGCAATCACGCTCGAGCTCGGGTCCGAGCGGGCCCGT"
  ]
  node [
    id 90
    label "GGCCAG--CTGGTCGCG--TGCTCTGATCAGACCAGGCCTGG"
  ]
  node [
    id 91
    label "GTGGGTATATCCACGCC--GGCCAAGATCTTGGTGGGCCCAC"
  ]
  node [
    id 92
    label "GCGAATATATTCGCGCG--CGCCCGGATCCGGGTGGGCCCAC"
  ]
  node [
    id 93
    label "GCGGTCGCGACCGTGCTCGAGCCAGGATCCTGGTTGGCCAAC"
  ]
  node [
    id 94
    label "GCGATCGCGATCGCGTG--CACTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 95
    label "GTGGGTATATCCACGTG--CACAACGATCGTTGTGGGCCCAC"
  ]
  node [
    id 96
    label "GCGGTTATAATCGCGTG--CACCCTGATCAGGGCGGGCCCGT"
  ]
  node [
    id 97
    label "GCGGATGTGTTCGCGCC--GGCGTGGATCCACGCGGGCCCGT"
  ]
  node [
    id 98
    label "GTGGGTGCATCCACGCCTAGGCCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 99
    label "GTGGGCGCGCTCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 100
    label "GCGAGTGCACTCGCGCG--CGCTCGGATCCGAGAGGGCCCTT"
  ]
  node [
    id 101
    label "GCGACTGCAGTCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 102
    label "GCGGATGCATTCGCGCG--CGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 103
    label "GCGGGTGCACTCGCGCTCGAGCCCAGTACTGGGTCGGCCGAT"
  ]
  node [
    id 104
    label "GTGATTGCAGTCACGCTCGAGCCTGGATCCAGGGGGGCCCCT"
  ]
  node [
    id 105
    label "GCCGGGGTCCCGGCGGG--CCTTAGCCGGCTACCGAGCTCGG"
  ]
  node [
    id 106
    label "GTGCCCATGGGCACGCGTACGCCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 107
    label "GTGATTGCAGTCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 108
    label "GTGGGATATCTCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 109
    label "GTGGGG--CCCCACGCTCGAGCTCAGGTCTGAGTGGGCCCAT"
  ]
  node [
    id 110
    label "GTGAGTATACTCACGCTCGAGCCTGGATCCGGAAGGGCCCTT"
  ]
  node [
    id 111
    label "GTGGGTGCACTCACGCTCGAGCTCAGGCCTGAGTGGGCCCAT"
  ]
  node [
    id 112
    label "GCGAATGCATTCGCGCTCGAGCCACGGCCGTGGCGGGCCCGT"
  ]
  node [
    id 113
    label "GTGGCTATAGCCACGTG--CACAACGATCGTTGTGGGCCCAC"
  ]
  node [
    id 114
    label "GCTGTA--TACGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 115
    label "GTGGGTGCACTCACGCTCGAGCCTGGGCCCAGATGGGCCCAT"
  ]
  node [
    id 116
    label "GTGGCTGCAGTCACGCTCGAGTCCAGGCCTGGGTGGGCCCAT"
  ]
  node [
    id 117
    label "GCCATCATGATGGCGTATGTACCCACGCGTGGCTCAGCTGGG"
  ]
  node [
    id 118
    label "GTGGGTGCATCCACGCCTGGGCTCAGATCTGAATGGGCCCAT"
  ]
  node [
    id 119
    label "GTGGGCGCGCTCACGTTCGAGCCCAGATCTGGGCGAGCTCGT"
  ]
  node [
    id 120
    label "GCGGGCGCGCTCGCGCTCGAGCTCAGTACTGAGCCAGCTGGT"
  ]
  node [
    id 121
    label "GCGGACGCGTTCGCGCTCGAGCCCAGGCCTGGGTGGGCCCAT"
  ]
  node [
    id 122
    label "GCTGTGATCACAGCGTATGTACCTGCGTGCAGCCCGGCCGGG"
  ]
  node [
    id 123
    label "GGGGAAATTTCCCCGTTCGAACTCAGATCTGACCGGGCCCGG"
  ]
  node [
    id 124
    label "GTGGCCGCGGTCACGCTCGAGCTCGGATCCGAGCGGGCCCGT"
  ]
  node [
    id 125
    label "GCGATCGCGGTCGCGTG--CACTCGGATCCGAGTGGGCCCAC"
  ]
  node [
    id 126
    label "GCCATTCGAATGGCGTATGTACCGTCGCGACGCTTGGCCAGG"
  ]
  node [
    id 127
    label "GCGGACGCGTTCGCGCTCGAGTCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 128
    label "GTCTCTGCAGGGATGCC--GGCTTTGGCTGAAGGTGGCCACC"
  ]
  node [
    id 129
    label "GTGAACGCGTTCACGTTCGAGCCCAGATCTGGGAGGGCCCTT"
  ]
  node [
    id 130
    label "GTGGGTATATCCACGCGCGCGCCCAGATCTGGAAGGGCCCTT"
  ]
  node [
    id 131
    label "GCGATCGCGGTCGCGTG--CACCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 132
    label "GCGGGTGCATCCGCGCG--CGCCCTGATCAGGGTGGGCCCAT"
  ]
  node [
    id 133
    label "GCGGTTGCAATCGCGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 134
    label "GTGGGATATTCCACGCGTACGCCCAGTACTGGGCCGGCCGGC"
  ]
  node [
    id 135
    label "GTGGTCATGACCACGCTTAAGCCTGGATCCAGATGGGCCCAT"
  ]
  node [
    id 136
    label "GTGGGTTAATCCACGCTCGAGCCCGCTAGCGGGTGGGCCCAT"
  ]
  node [
    id 137
    label "GCGGTTATAGCCGCGCG--CGCGCGGCGCCGTGTGGGCCCAC"
  ]
  node [
    id 138
    label "GCGGTTGCAACCGTGCTCGAGCCAGGTACCTGGGCGGCCGCC"
  ]
  node [
    id 139
    label "GTGGCTGCAGCCACGTTTGAATCCACGCGTGGCTGGGCCCAG"
  ]
  node [
    id 140
    label "GCGGGTGCACTCGCGCTCGAGCTCAGTACTGAGCCAGCTGGT"
  ]
  node [
    id 141
    label "GCGAACGCGTTCGCGTG--CACGCGGGTCCGTGCGGGCCCGT"
  ]
  node [
    id 142
    label "GCGGGTGCACTCGCGTG--CACTCAGATCTGAGTGGGCCCAT"
  ]
  node [
    id 143
    label "GCGTATATATACGCGCG--CGCCCGGATCCGGGAGGGCCCTT"
  ]
  node [
    id 144
    label "GTGAGCGCGTTCACGCTCGAGCTCGGGCCCGAGCGGGCCCGT"
  ]
  node [
    id 145
    label "GTGGCG--CGCCACGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 146
    label "GCGAATATATTCGCGCTCGAGCTCAGATCTGAGCCGGCCGGT"
  ]
  node [
    id 147
    label "GTGGCTATAGCCACGCTCGAGCCCGGATCCGGGAGGGCCCTT"
  ]
  node [
    id 148
    label "GCGGTTATAACCGCGTG--CACTCTGATCAGAGCGGGCCCGT"
  ]
  node [
    id 149
    label "GCCATCTAGGTGGCGTA--TACCATCGCGATGCCAGGCCTGG"
  ]
  node [
    id 150
    label "GTGGAG--CTCCACGCTCGAGCTCAGATCTGAGCCGGCCGGT"
  ]
  node [
    id 151
    label "GTCGTGATCACGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 152
    label "GTGAATGCATTCACGCTCGAGCTTAGATCTAAGCCGGCCGGT"
  ]
  node [
    id 153
    label "GTAGGCATGCCTACGTGTACACCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 154
    label "GCGGCG--CGCCGCGCTCGAGCCCTGGCCAGGGTGGGCCCAT"
  ]
  node [
    id 155
    label "GCGAGCGCGTTCGCGCC--GGCGTGGATCCACGCGGGCCCGT"
  ]
  node [
    id 156
    label "GCCACGGCCGTGGCGCC--GGCTGAGCGCTCAGCAGGCCTGC"
  ]
  node [
    id 157
    label "GTGGCTGCAGTCACGTTTGAATCCACGCGTGGCTGGGCCCAG"
  ]
  node [
    id 158
    label "GTGGTCGCGGCCACGCTCGAGTCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 159
    label "GCCGTGATCACGGCGTT--GACCTGCGTGCAGCCTGGCCAGG"
  ]
  node [
    id 160
    label "GCTGTGATCACAGCGTATGTACCTGCGCGCAGCCTGGCCGGG"
  ]
  node [
    id 161
    label "GCCCACTAGTGGGCGTATGTACCCACGCGTGGGCTGGCCAGC"
  ]
  node [
    id 162
    label "GCGACCGCGGTCGCGCTCGAGCCCGGTACCGGGTGGGCCCAT"
  ]
  node [
    id 163
    label "GTGGGCGCGTCCACGCTCGAGCCTGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 164
    label "GCTCAGGCCTGAGCGCTCGAGCCTGGGCCCAGCCGGGCCCGG"
  ]
  node [
    id 165
    label "GCGGCTGCAGCCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 166
    label "TCCCTG--TGGGGAGTT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 167
    label "GGGGAAATTTCCCCGCTCGAGTCTGGTGCCAGACGGGCCCGT"
  ]
  node [
    id 168
    label "GTGGCTGCAGCCACGCTCGAGTCTGGATCCAGGGGGGCCCCT"
  ]
  node [
    id 169
    label "GCGATTGCAGTCGCGCG--CGCTCGGATCCGAGAGGGCCCTT"
  ]
  node [
    id 170
    label "GTGGCCGCGGCCACGTTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 171
    label "GCCGTTCGGACGGCGTATGTACCTTGTACAAGCCAGGCCTGG"
  ]
  node [
    id 172
    label "GCCGTGATCACGGCGTATGTACTTGCGTGCAGCCCGGCCGGG"
  ]
  node [
    id 173
    label "GCCGTGATCACGGCGTATGTACTTGCGCGCAACCCGGCCGGG"
  ]
  node [
    id 174
    label "GTGGGCGCGTCCACGCTCGAGCCGGGATCCCGGTGGGCCCAT"
  ]
  node [
    id 175
    label "GTGGTCATGATCACGCTCGAGCCTGGATCCAGATGGGCCCAT"
  ]
  node [
    id 176
    label "GTGGGTGCACTCACGCTCGAGCCTGGATCCAGGAGGGCCCTT"
  ]
  node [
    id 177
    label "GCGGTAGCTACCGCGTG--CACTCGGTACCGAGTGGGCCCAT"
  ]
  node [
    id 178
    label "GTGGGTGCATCCACGCTCGAGCCCTGATCAGGGAGGGCCCTT"
  ]
  node [
    id 179
    label "GCCGCGGCCGCGGCGCTCGAGCCCGGCGCCGGCCGGGCCCGG"
  ]
  node [
    id 180
    label "GTGGTTGCAATCACGCTCGAGCCCGGGTCCGGGCGGGCCCGT"
  ]
  node [
    id 181
    label "GCGGACGCGTCCGCGTG--CACGCGGGCCCGTGCGGGCCCGT"
  ]
  node [
    id 182
    label "GCCGCCTAGGCGGTGCTCGAGCCTGGATCCAGCCCCGCGGGG"
  ]
  node [
    id 183
    label "GCCGGGATCCCGGCGGG--CCTTGGGATCCCACCGGGCCCGG"
  ]
  node [
    id 184
    label "GTGTCTGCAGACACGTC--GACCTAGCGTTAGGCGGGCCCGT"
  ]
  node [
    id 185
    label "GTGGATATATTCACGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 186
    label "GTGGGTATACCCACGCC--GGCTCAGGCCTGAGTGGGCCCAC"
  ]
  node [
    id 187
    label "GCGGGAGCTCTCGCGCTCGAGCCACGGCCGTGGTGGGCCCAT"
  ]
  node [
    id 188
    label "GTGGCTGCAGCCACGTG--CACGCGGATCCGTGAGGGCCCTT"
  ]
  node [
    id 189
    label "GCGAGCGCGTTCGCGCC--GGCGCGGATCCGCGGGGGCCCCT"
  ]
  node [
    id 190
    label "GCCGTGATTACGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 191
    label "GTGGGTGCACTCACGCTCGAGTCCGGGCCCGGGAGGGCCCTT"
  ]
  node [
    id 192
    label "GTGGATGCATCCACGTTCGAGCCCGGTACCGGGCGGGCCCGT"
  ]
  node [
    id 193
    label "GCCACG--CGTGGCGTATGTACCCACGCGTGGGCTGGCCAGC"
  ]
  node [
    id 194
    label "GCCTGGGCTCGGGCGCC--GGCTCTGATCAGGGTGAGCTCAC"
  ]
  node [
    id 195
    label "GCCGTGATCACGGCGTATGTACCTGCGTGCAGCCCGGCTGGG"
  ]
  node [
    id 196
    label "GTGGGTATATCCACGTTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 197
    label "GTGGCCGCGGCCACGCTCGAGTCAGGATCCTGGCGGGCCCGT"
  ]
  node [
    id 198
    label "GTGAGCGCGCTCACGTTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 199
    label "GTGGGTGCATCCACGTTCGAACCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 200
    label "GTGGTCATGGCCACGCTCGAGCCCAGGCCTGGGGGGGCCCCT"
  ]
  node [
    id 201
    label "GCCGGGGTCCCGGCGGG--CCTTGGCCGGCCACCGAGCTCGG"
  ]
  node [
    id 202
    label "GTGGATATATCCACGTTCGAACCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 203
    label "GCCGGGGCTCCGGCGGG--CCTTGGGATCCCACCGGGCCCGG"
  ]
  node [
    id 204
    label "GTGGATGCATCCACGCTCGAGCCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 205
    label "GTAGGCATGCCTACGTGTGCACGCAGATCTGCGTGGGCCCAC"
  ]
  node [
    id 206
    label "GTGGGTATATCCACGTTCGAGCCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 207
    label "GCCGCCGCGGCGGCGTCTGGATGTGGGCCCATCCGGGCCCGG"
  ]
  node [
    id 208
    label "GTGGTTATAGCCACGCTCGAGCCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 209
    label "GTGGACGCGTTCACGCTCGAGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 210
    label "GTGGCTATAGCCACGCTCGAGCCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 211
    label "GCCTGA--TCAGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 212
    label "GTGGAATATTCCACGCTCGAGCTCAGGTCTGAGTGGGCCCAT"
  ]
  node [
    id 213
    label "GTGGGTATACCCACGCGCGCGCCCAGATCTGGTAGGGCCCTA"
  ]
  node [
    id 214
    label "GCGGGAATTCTCGCGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 215
    label "GCCTGA--TCAGGCGTATGTACCTGTGCGCAGCCTGGCCGGG"
  ]
  node [
    id 216
    label "GCGGATATATCCGCGCG--CGCCCTGATCAGGGTGGGCCCAT"
  ]
  node [
    id 217
    label "GTGGGAGCTCTCACGTTCGAGCCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 218
    label "GTGAGCGCGCTCACGCTCGAGTCTGGATCCAGGGGGGCCCCT"
  ]
  node [
    id 219
    label "GTGACTGCAGTCACGCATATGCCCTGATCAGGGAGAGCTCTT"
  ]
  node [
    id 220
    label "GCTGTGATCACGGCGTATGTGTCTGCATGCAGCCTGGCCGGG"
  ]
  node [
    id 221
    label "GCGAGCGCGTTCGCGCC--GGCGAGGTACCTCGTGGGCCCAT"
  ]
  node [
    id 222
    label "GTGGGCGCGCTCACGCTCGAGCTCTGGCCAGAGCGGGCCCGT"
  ]
  node [
    id 223
    label "GTGGGTATACTCACGCGATCGCCCAGATCTGGCAGGGCCCTG"
  ]
  node [
    id 224
    label "GCCGTGGCCACGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 225
    label "GCCATGATCATGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 226
    label "GCCTGA--TCAGGCGTACGTACCTGCATGCAGCTTGGCCAAG"
  ]
  node [
    id 227
    label "GCCCACGCGTGGGCGTATATACCCACGCGTGGGCTGGCCAGC"
  ]
  node [
    id 228
    label "GCGAACGCGTTCGCGCG--CGCTCGGATCCGAGGGGGCCCCT"
  ]
  node [
    id 229
    label "GTGGGTGCACTCACGCTCGAGCCTTGGCCAAGGTGGGCCCAT"
  ]
  node [
    id 230
    label "GTGGTG--CACCACGTTCGAGCTCAGATCTGAGTGGGCCCAT"
  ]
  node [
    id 231
    label "GTCGTGATCACGGTGTATGTACCTGCGCGCAGCCCGGCTGGG"
  ]
  node [
    id 232
    label "GTGAGCGCGCTCACGCTCGAGCCCGGTACCGGGTGGGCCCAT"
  ]
  node [
    id 233
    label "TCCGGGTACCCGGAGGG--CCTCAGCCGGCTGGTGGGCCCGC"
  ]
  node [
    id 234
    label "GCGGTCGCGGCCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 235
    label "GTAAATATATTTACGCTCGAGCATAGTACTATATGGGCCCAT"
  ]
  node [
    id 236
    label "GTGGCTGCAGCCACGTTCGAGCCAGGATCCTGGCGGGCCCGT"
  ]
  node [
    id 237
    label "GCGGATGCGTTCGCGCTCGAGCCCAGTACTGGGCCAGCTGGT"
  ]
  node [
    id 238
    label "GTGGGTATACCCACGTTCGAACCCGGATCCGGGTGGGCCCAC"
  ]
  node [
    id 239
    label "GTGGCTTAAGCCACGCTCGAGCCTGGATCCAGACGGGCCCGT"
  ]
  node [
    id 240
    label "GTGGGTATACTCACGCTCGAGCCCTGGCTAGGGCGGGCCCGT"
  ]
  node [
    id 241
    label "GTGGGTATACTCACGCTCGAGCCCAGGCCTGGGTGGGCCCAC"
  ]
  node [
    id 242
    label "GTGAATATATTCACGTTCGAGCCCAGTACTGGGAGGGCCCTT"
  ]
  node [
    id 243
    label "GCCATGATCATGGCGTATGTACCTGCATGCAGCTTGGCCAAG"
  ]
  node [
    id 244
    label "GCCGGGGCCCCGGCGGG--CCTCGGGATCCCGTCGGGCTCGG"
  ]
  node [
    id 245
    label "GCCGTTGCAACGGTGCTCGAGCCCGGATCCGGGCTGGCCAGC"
  ]
  node [
    id 246
    label "GCGGTTGCAGTCGCGCG--CGCCCTGATCAGGGTGGGCCCAT"
  ]
  node [
    id 247
    label "GTGAGCGCGCTCACGCTCGAGCCCAGATCTGGGGGGGCCCCT"
  ]
  node [
    id 248
    label "GCTGGG--TCCAGCGTATGTACCTGCGTGCAGCCCGGCCGGG"
  ]
  node [
    id 249
    label "GCCATCTAGATGGCGTATGTACCAACGCGTTGCCTGGCCAGG"
  ]
  node [
    id 250
    label "GTGACTATAGTCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 251
    label "GCGAGCGCGTTCGCGCC--GGCGCGGATCCGCGTGGGCCCAT"
  ]
  node [
    id 252
    label "GCAGCCGCGGCTGTGCTCGAGCCTAGATCTAGCCCCGCGGGG"
  ]
  node [
    id 253
    label "GCGGTTGCAGCCGCGTG--CACTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 254
    label "GTGGCTGCAGCCACGCTCGAGTCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 255
    label "GTGAGTGCACTCACGTTCGAGCCCAGGCCTGGGCGGGCCCGT"
  ]
  node [
    id 256
    label "GTGACCGCGGTCACGCTCGAGCCCAGATCTGGGGGGGCCCCT"
  ]
  node [
    id 257
    label "GCGACTGCAGTCGCGTG--CACTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 258
    label "GCGGCTGCAGTCGCGCTCGAGCCCGGGCTCGGGTGGGCCCAT"
  ]
  node [
    id 259
    label "GCCGGCTAGCTGGTGCTCGAGCCTAGATCTAGCTCGGCCGAG"
  ]
  node [
    id 260
    label "GCGGGTGCACTCGCGCTCGAGCTCAGGTCTGAACGGGCCCGT"
  ]
  node [
    id 261
    label "GCGGTGTACATCGCGCTCGAGCCTGGATCCAGACGGGCCCGT"
  ]
  node [
    id 262
    label "GTGGGTGCATCCACGCCTAGGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 263
    label "GCCGCTGCAGCGGTGCTCGAGCCTTGATCAAGACTGGCCAGT"
  ]
  node [
    id 264
    label "GTGGCTGCAGCCACGTTCGAGCCCAGGCCTGGGCGGGCCCGT"
  ]
  node [
    id 265
    label "GCGGATGCATTCGCGCTCGAGCCCTGGCCAGGGTGGGCCCAT"
  ]
  node [
    id 266
    label "GTGGATGCATCCACGCCTGGGCTCAGTACTGAGAGAGCTCTT"
  ]
  node [
    id 267
    label "GCGACCGCGGTCGCGTTCGAGCTCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 268
    label "GCGATTGCAGTCGCGTG--CACCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 269
    label "GTGGCTGCAGCCACGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 270
    label "GTGGTCGCGGTCACGCTCGAGCCCGGGCCCGGGCGGGCCCGT"
  ]
  node [
    id 271
    label "GCCGTGATCACGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 272
    label "GCCATCTAGATGGCGTATGTACCAACGTGTTGCCTGGCCAGG"
  ]
  node [
    id 273
    label "GTGGGTGCACCCACGCG--CGCCCGGGTCCGGGTGGGCCCAT"
  ]
  node [
    id 274
    label "GTGGGTGCATCCACGCTCGAGCCCAGGCCTGGGCCGGCCGGT"
  ]
  node [
    id 275
    label "GTGAGCGCGTTCACGCTCGAGCCCGGGCCCGGGTGGGCCCAT"
  ]
  node [
    id 276
    label "GCTGTGATCATGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 277
    label "GCGGCCATGGCCGCGCTCGAGCCTGGATCCAGACCGGCCGGT"
  ]
  node [
    id 278
    label "GTGGCTATAGCCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 279
    label "GTGGTCGCGATCACGCTCGAGCCCGGGCCCGGGCGGGCCCGT"
  ]
  node [
    id 280
    label "GCCGGTGCACCGGCGGG--CCTAAGGATCCTTCCGGGCTCGG"
  ]
  node [
    id 281
    label "GTGGTTGCAATCACGCTCGAGTCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 282
    label "GCGGTG--CACCGCGCG--CGCCCGGATCCGGATGGGCCCAT"
  ]
  node [
    id 283
    label "GCCTGG--TTGGGCGCTCGAGCTCTGATCAGGGTGGGCCCGC"
  ]
  node [
    id 284
    label "GGTGAGGCCTCACCGTTCGAGCCCAGGCCTGGGCGGGCCCGT"
  ]
  node [
    id 285
    label "GCGGGCGCGTCCGCGCC--GGCGTGGATCCACGTGGGCCCAT"
  ]
  node [
    id 286
    label "GCGATCGCGATCGCGCTCGAGCCCGGTACCGGGCGGGCCCGT"
  ]
  node [
    id 287
    label "GTGGGCGCGTCCACGTTCGAGCACGGATCCGTGTGGGCCCAT"
  ]
  node [
    id 288
    label "GTGGACGCGTCCACGCTCGAGCTCAGATCTGAGCCGGCCGGT"
  ]
  node [
    id 289
    label "TCCGGGTACCCGGAGGG--CCTCAGCCGGCTGGCGGATTCGC"
  ]
  node [
    id 290
    label "GCGGGTGCACCCGCGCTCGAGCTCAGGTCTGAGCGGGCCCGT"
  ]
  node [
    id 291
    label "GTGGATGTATCCACGTTCGAACCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 292
    label "GTGGGCTAGCTCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 293
    label "GCCGTGATCACGGCGTCTGGACCCACGCGTGGCCAGGCCTGG"
  ]
  node [
    id 294
    label "GCGGTCGCGATCGCGCG--CGCCCGGATCCGGATGGGCCCAT"
  ]
  node [
    id 295
    label "GCGGTTGCAACCGCGCG--CGCTCGGATCCGAGAGGGCCCTT"
  ]
  node [
    id 296
    label "GCCGCCTAGGCGGTGCTCGAGCCTGGTACCAGCCCCGCGGGG"
  ]
  node [
    id 297
    label "GCGGGCGCGCTCGCGCC--GGCGCGGCGCCGCGGGGGCCCCT"
  ]
  node [
    id 298
    label "GCGGGTGCACTCGCGCTCGAGCCCAGGCCTGGGTCGGCCGAT"
  ]
  node [
    id 299
    label "GTGGGTATACTCACGCTCGAGCTCTGGCCAGAGCGGGCCCGT"
  ]
  node [
    id 300
    label "GCGGTTGCAGCCGCGTG--CACTCGGATCCGAGAGGGCCCTT"
  ]
  node [
    id 301
    label "GCCATTTAAATGGCGTATGTACCGTCGCGACGCCTGGCTAGG"
  ]
  node [
    id 302
    label "GCGGCCATGGCCGCGCTCGAGCCTGGATCCAGGCCGGCCGGT"
  ]
  node [
    id 303
    label "GTGCCG--CGGCACGCTCGAGCCAGGATCCTGGCGGGCCCGT"
  ]
  node [
    id 304
    label "GCGATGGCCATCGCGCTCGAGCCTCGGCCGAGGTGGGCCCAT"
  ]
  node [
    id 305
    label "GCGGGCGCGCTCGCGCTCGAGCCGTGGCCATGGTCGGCCGAT"
  ]
  node [
    id 306
    label "GCTGTGATCATGGCGTATGTACCTGTGCGCAGCCCGGCCGGG"
  ]
  node [
    id 307
    label "ATAGCTATGGTTATGTTCGAACATTGTGCAATCTGAGCTCAG"
  ]
  node [
    id 308
    label "GCGGCTATAGTCGCGCTCGAGCCCGGGCTCGGGTGGGCCCAT"
  ]
  node [
    id 309
    label "GCCGCCGCGGCGGCGTCTGGATGCGGGCCCGTCCGGGCCCGG"
  ]
  node [
    id 310
    label "GCCTGCGCGCAGGCGTATGTACCCACGCGTGGGCTGGCCAGC"
  ]
  node [
    id 311
    label "GTGATCATGATCACATGTGCATCAGCCGGCTGGCGGGCCCGT"
  ]
  node [
    id 312
    label "GCCCACGCGTGGGCGTATGTACCCACGCGTGGGCTGGCCAGC"
  ]
  node [
    id 313
    label "GCGGTATATACCGCGTG--CACCCGGATCCGGGTGGGCCCAC"
  ]
  node [
    id 314
    label "GCTCGGGCCCGAGCGCTCGAGCATGGGCCCATCCGGGCCCGG"
  ]
  node [
    id 315
    label "GCGGATGCATCCGCGCG--CGCCCTGATCAGGGTGGGCCCAT"
  ]
  node [
    id 316
    label "GTGGGTGCACCCACGCTCGAGCCCGGGCCCGGGCGGGCCCGT"
  ]
  node [
    id 317
    label "GCCGTGATCACGGCGTATGTACCTGTGCGCAGCTCGGCCGAG"
  ]
  node [
    id 318
    label "GTGATCATGGTCACGCTCGAGCTCAGATCTGAGTGGGCCCAC"
  ]
  node [
    id 319
    label "GTGGCTGCAGCCACGCTCGAGCCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 320
    label "GTGTCTGCAGGCACGTTCGAGCCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 321
    label "GCGCCGGTCGGCGCGTG--CACTCAGGTCTGAGCGGGCCCGT"
  ]
  node [
    id 322
    label "GCGTGA--TCACGCGTATGTACCTGCGCGCAGCCCGGCTGGG"
  ]
  node [
    id 323
    label "GTGGCTGCAGCCACGCTCGAGTCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 324
    label "GTGGATGCATCCACGTTCGAATCTGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 325
    label "GCTCGGGCCCGAGCGCTCGAGCACGGGCCCGTCCGGGCCCGG"
  ]
  node [
    id 326
    label "GTGGGTGCACTCACGCTCGAGCCTGGGCCCAGGCGGGCCCGT"
  ]
  node [
    id 327
    label "GCCGTGATCACGGCGTATGTACCTGTGTGCAGCCCGGCTGGG"
  ]
  node [
    id 328
    label "GTGGGTGCATCCACGTTCGAGCCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 329
    label "GTGGAG--CTCCACGCTCGAGTTCGGTACCGAGCCGGCCGGT"
  ]
  node [
    id 330
    label "GTGAAG--CTTCACGCTCGAGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 331
    label "GCGAGCGCGTTCGCGCC--GGCGTGGTACCACGCGGGCCCGT"
  ]
  node [
    id 332
    label "GCGGACGCGTTCGCGCTCGAGCCCGGTACCGGGCGGGCCCGT"
  ]
  node [
    id 333
    label "GCCCCCGCGGGGGCGCTTGAGCCCGGGCCCGGCCGGGCCCGG"
  ]
  node [
    id 334
    label "GCGAATGCATTCGCGTG--CACTCAGATCTGAGGGGGCCCCT"
  ]
  node [
    id 335
    label "GCGAACGCGTTCGCGCTCGAGCTCGGTACCGAGTGGGCCCAT"
  ]
  node [
    id 336
    label "GTGGGTGCACTCACGCTCGAGCCTGGATCCAGGCGGGCCCGT"
  ]
  node [
    id 337
    label "GCCGCCTAGGCGGTGCTCGAGCCTAGATCTAGCCCCGCGGGG"
  ]
  node [
    id 338
    label "GTGGCTGCAGCCACGTTCGAGCCTAGGCCTAGGCGGGCCCGT"
  ]
  node [
    id 339
    label "GCGGCCATGGCCGCGCTCGAGCCTAGATCTAGGCGGGCCCGT"
  ]
  node [
    id 340
    label "GTGGCTATAGCCACGTG--CACTACGATCGTAGAGGGCCCTC"
  ]
  node [
    id 341
    label "GCGGACGCGTTCGCGCTCGAGCCAAGATCTTGGAGGGCCCTC"
  ]
  node [
    id 342
    label "GCTGTGATCATGGCGTATGTACCTGCGCGCAGCTCGGCTGAG"
  ]
  node [
    id 343
    label "GCCGGGATCCCGGCGGG--CCTTGGGATCCTACCGGGCCCGG"
  ]
  node [
    id 344
    label "GTGGCTGCAGCCACGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 345
    label "GCGGAAGCTTTCGCGCTCGAGCCCTGGCCAGGGTGGGCCCAT"
  ]
  node [
    id 346
    label "GTGGTTATAACCACGCTCGAGCCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 347
    label "GCGGGTGCACTCGCGCTCGAGCCCAGTACTGGGCCGGCCGGT"
  ]
  node [
    id 348
    label "GTGACG--CGTCACGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 349
    label "GTGGATGCATCCACGCTCGAGCCTGCATGCAGGGGGGCCCCT"
  ]
  node [
    id 350
    label "GCTGAATATTCAGCGCTTGAGCTGGCGCGCCAGCGAGCTCGC"
  ]
  node [
    id 351
    label "GTGGGTATACCCACGCGCGCGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 352
    label "GCTGTGATCACGGCGTATGTACCTGCGCGCAGCCTGGCCGGG"
  ]
  node [
    id 353
    label "GCCAGGGCCCTGGCGTGTGCACGGGGATCCCCCCGGGCCCGG"
  ]
  node [
    id 354
    label "GCGGTTGCAATCGCGCG--CGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 355
    label "GCGGTGGCCATCGCGCTCGAGCCTCGGCCGAGGTGGGCCCAT"
  ]
  node [
    id 356
    label "GCGTTCGCGAACGCGTGTGCACCCAGATCTGGCTCGGCCGGG"
  ]
  node [
    id 357
    label "GTGGCTGCGGCCACGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 358
    label "GTGGGTGCACCCACGTTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 359
    label "GCGGAG--CTCCGCGTTCGAACTCGGGTCCGAGAGGGCCCTT"
  ]
  node [
    id 360
    label "GTAGGTATACCTACGCTCGAGCTCGGGTCCGAGTGGGCCCAT"
  ]
  node [
    id 361
    label "GCCGCCTAGGCGGTGCTCGAGCCTTGATCAAGCCCCGCGGGG"
  ]
  node [
    id 362
    label "GTGGGTGCACTCACGCTCGAGCCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 363
    label "CCGTGA--TCACGGGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 364
    label "GTGGGTATATCCACGCGCGCGCCCAGATCTGGCAGGGCCCTG"
  ]
  node [
    id 365
    label "GTGGATGCATTCACGCTCGAGCTCAGATCTGAGTGGGCCCAC"
  ]
  node [
    id 366
    label "GTGGGTATATCCACGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 367
    label "GTGAATGCATTCACGTTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 368
    label "GCGTGA--TCACGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 369
    label "GTGATTGCAGTCACGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 370
    label "GTGGATGCATCCACGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 371
    label "GCGTGTATACACGCGCG--CGCCCGGATCCGGGAGGGCCCTT"
  ]
  node [
    id 372
    label "GCGGGCGCGTTCGCGCC--GGCGAGGATCCTCGTGGGCCCAT"
  ]
  node [
    id 373
    label "GTGGGTGCACTCACGCTCGAGCCTGGGCCCAGGCCGGCCGGT"
  ]
  node [
    id 374
    label "GTGCGTGCACGCACGCCTAGGCCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 375
    label "CTGTGA--TCACGGGTATGTACCTGCGTGCAGCTTGGCCGAG"
  ]
  node [
    id 376
    label "GCTGGA--TCCAGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 377
    label "GTGACCATGGTCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 378
    label "GCCGGA--TCTGGCGTATGTACCTGCGCGCAGCCCGGCTGGG"
  ]
  node [
    id 379
    label "GCTGTGATCACAGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 380
    label "GCCTGA--TTAGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 381
    label "GCCGCCGCGGTGGTGCTCGAGCCCAGATCTGGCCCCGCGGGG"
  ]
  node [
    id 382
    label "GTGGCTGCAGTCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 383
    label "GTGGAG--CTCCACGCTCGAGCCTGGATCCAGGCCGGCCGGT"
  ]
  node [
    id 384
    label "GCGAATGCATTCGCGCTCGAGCTCGGATCCGAGCGGGCCCGT"
  ]
  node [
    id 385
    label "GTGATG--CATCACGCTCGAGCCCAGGCCTGGGGGGGCCCCT"
  ]
  node [
    id 386
    label "GTGACTGCAGTCACGTTCGAGCCTAGGCCTAGGCGGGCCCGT"
  ]
  node [
    id 387
    label "GCCGTGATCACGGCGTGTGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 388
    label "GTGGATGCATCCACGCTCGAGTCGAGATCTCGGCGGGCCCGT"
  ]
  node [
    id 389
    label "GCGGCG--CGCCGCGCG--CGCCCGGATCCGGGGGGGCCCCT"
  ]
  node [
    id 390
    label "GTGGGTGCATCCACGTTCGAACCCAGATCTGGGTCGGCCGAT"
  ]
  node [
    id 391
    label "GCGTGA--TCACGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 392
    label "GTGGCTATAGCCACGCTCGAGCTCAGATCTGAGCCGGCCGGT"
  ]
  node [
    id 393
    label "CCTTCTGCAGAGGGGCTCGAGCCCCGATCGGGGGCGGCCGCC"
  ]
  node [
    id 394
    label "GTGGCTGCAGCCACGTTCGAGCCCTGATCAGGGCGAGCTCGT"
  ]
  node [
    id 395
    label "GTAGGCATGCCTACGTGTGCACGAAGGCCTTCGCGGGCCCGC"
  ]
  node [
    id 396
    label "GCGGGTGCATTCGCGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 397
    label "GTGGGCGCGTCCACGCTCGAGCCAGGATCCTGGAGGGCCCTT"
  ]
  node [
    id 398
    label "GCTGGT--ACCAGCGCTTGAGCTGGCGCGCCAGCGGGCCCGC"
  ]
  node [
    id 399
    label "GTGGATGCATCCACGCTCGAGCCCTGGCCAGGGCGAGCTCGT"
  ]
  node [
    id 400
    label "GTGAGATATCTCACGCTCGAGCCTGGTGCCGGGCGGGCCCGT"
  ]
  node [
    id 401
    label "GTGGGATATCTCACGCTCGAGCTCTGATCAGAGCGGGCCCGT"
  ]
  node [
    id 402
    label "GTGGTG--CACCACGCG--CGCCCGGATCCGGGGGGGCCCCT"
  ]
  node [
    id 403
    label "GCGGCATATGTCGCGCTCGAGCCTGGATCCAGACCGGCCGGT"
  ]
  node [
    id 404
    label "GCGATCGCGGTCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 405
    label "GTGATG--CATCACGCTCGAGCCCAGATCTGGGCCGGCCGGT"
  ]
  node [
    id 406
    label "GCGAATGCATTCGCGTG--CACCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 407
    label "GCGGTG--CACCGCGTG--CACGCGGATCCGTGCGCGCGCGT"
  ]
  node [
    id 408
    label "GCCTGCTAGCAGGCGTATGTACCCACGCGTGGGCTGGCCAGC"
  ]
  node [
    id 409
    label "GCCGCCTAGGTGGTGCTCGAGCCCAGATCTGGCCCCGCGGGG"
  ]
  node [
    id 410
    label "GCCGGGGCCCCGGCGGG--CCTCGGGATCCTGTCGGGCTCGG"
  ]
  node [
    id 411
    label "GTGGGTTAACCCACGCTCGAGCCCGCTAGCGGGTGGGCCCAT"
  ]
  node [
    id 412
    label "GTGATG--CATCACGCTCGAGCTCGGATCCGAGGGGGCCCCT"
  ]
  node [
    id 413
    label "GCCGTGATCATGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 414
    label "GCCGTA--TACGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 415
    label "GCGGGCGCGTCCGCGCC--GGCGAGGATCCTCGTGGGCCCAT"
  ]
  node [
    id 416
    label "GCGGTAGCTACCGCGCG--CGCCCGGATCCGGGTGGGCCCAC"
  ]
  node [
    id 417
    label "GTGAGTGCACTCACGCCTAGGCCCAGGCCTGGGTGGGCCCAT"
  ]
  node [
    id 418
    label "GCGGGTGCATCCGCGCTCGAGCCCTGATCAGGGTGGGCTCAT"
  ]
  node [
    id 419
    label "GCGGATGCATCCGCGTG--CACCCGGCGCCGGGCGAGCTCGT"
  ]
  node [
    id 420
    label "GCCTGA--TCAGGCGTATGTATCTGTGTGCAGCTCGGCCGAG"
  ]
  node [
    id 421
    label "GTGGCCGCGGTCACGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 422
    label "GCAGGTGCACCTGTGCTCGAGCCCGGTACCGGGGTGGCCACC"
  ]
  node [
    id 423
    label "GTGCCTCGAGGCACGCTCGAGCCTGGATCCAGACGGGCCCGT"
  ]
  node [
    id 424
    label "GTGGGTGCATCCACGTTCGAGCCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 425
    label "GTGCCTGCAGGCACGTTCGAGCCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 426
    label "GTGAATATATTCACGTTCGAGCCCAGTACTGGAAGGGCCCTT"
  ]
  node [
    id 427
    label "GCGGGTGCATTCGCGCTCGAGCTCAGTACTGAGCCAGCTGGT"
  ]
  node [
    id 428
    label "GTGGTCGCGATCACGCTCGAGCCAGGATCCTGGCGGGCCCGT"
  ]
  node [
    id 429
    label "GTGGCTATAGCCACGCTCGAGCCCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 430
    label "GCTCACATGTGGGCGTC--GACCATCGCGATGCCAGGCCTGG"
  ]
  node [
    id 431
    label "GCGGATGCATTCGCGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 432
    label "GTGGCTGCAGCCACGCTCGAGCCTGGATCCAGGTCGGCCGAT"
  ]
  node [
    id 433
    label "GCGACTATAGTCGCGCG--CGCCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 434
    label "GTGGATGCATCCACGCTCGAGTCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 435
    label "GTGGGTGCACTCACGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 436
    label "GCGGGCGCGTTCGCGCC--GGCGTGGATCCACGGGGGCCCCT"
  ]
  node [
    id 437
    label "TCCGGGTACCCGGAGGG--CCTCAGCCGGCTGGCGGGCTCGC"
  ]
  node [
    id 438
    label "GCGAACGCGTTCGCGCTCGAGCTCGGATCCGAGCGGGCCCGT"
  ]
  node [
    id 439
    label "GTGGGAGTTCCCACGCTCGAGCACGGATCCGTGAGGGCCCTT"
  ]
  node [
    id 440
    label "GCGAATGCATTCGCGCTCGAGCCCGGATCCGGGCCGGCCGGT"
  ]
  node [
    id 441
    label "GTGGGCGCGCTCACGCTCGAGCCTGGATCCAGGGGGGCCCCT"
  ]
  node [
    id 442
    label "GTGAGCGCGCTCACGCTCGAGCCTGGATCCAGGGGGGCCCCT"
  ]
  node [
    id 443
    label "GAGGTTATAGCCTCGCTCGAGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 444
    label "GTGGCTATAGCCACGCTCGAGCCCGGATCCGGGCGAGCTCGT"
  ]
  node [
    id 445
    label "GTGGACGCGTTCACGTTCGAGCCCAGATCTGGGAGGGCCCTT"
  ]
  node [
    id 446
    label "GTGGGTATATTCACGCTCGAGCCCAGATCTGGTAGGGCCCTA"
  ]
  node [
    id 447
    label "GTGGCTATAGCCACGCTCGAGCCCGGATCCGGGCGAGCTCGC"
  ]
  node [
    id 448
    label "GTGACG--CGTCACGCTCGAGCTTAGATCTAAGCCGGCCGGT"
  ]
  node [
    id 449
    label "GCCGTG--CACGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 450
    label "GCGGTCGCGATCGCGCTCGAGCCCGGTACCGGGCGGGCCCGT"
  ]
  node [
    id 451
    label "GCCGTGATCACGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 452
    label "GTGACTATAGTCACGCTCGAGCCTGGATCCGGGTGGGCCCAC"
  ]
  node [
    id 453
    label "GTGTGA--TCACGCGTGTGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 454
    label "GTGGGTGCATCCACGTTCGAACCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 455
    label "GTGGGTGCACTCACGCTCGAGCCTTGGCCAAGGCGGGCCCGT"
  ]
  node [
    id 456
    label "GCGGCTGCAGCCGTGCTTGAGCTAAGATCTTAGGCGATCGCC"
  ]
  node [
    id 457
    label "GCGGTGGCCATCGCGCTCGAGCCCGGATCCGGGCGAGCTCGT"
  ]
  node [
    id 458
    label "GTGGCTGCAGCCACGTC--GACCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 459
    label "GCCGTGATCACGGCGTATGTACCTGCGCGTAGCCCGGCCGGG"
  ]
  node [
    id 460
    label "GTGGCTGCAGCCACGTTCGAACCCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 461
    label "GCGGTACGTACCGCGCG--CGCCCGGATCCGGGTGGGCCCAC"
  ]
  node [
    id 462
    label "GCCATGGTCATGGCGTATGTGCCTGTGTACAGCTCAGCTGAG"
  ]
  node [
    id 463
    label "GCGGGTGCACTCGCGTG--CACTCAGATCTGAGGGGGCCCCT"
  ]
  node [
    id 464
    label "GCCCGGGCCCGGGCGCTCGAGCCCGGATCCGGCCGGGCCCGG"
  ]
  node [
    id 465
    label "GTGACCGCGGTCACGTTCGAGCCCAGGCCTGGGCGGGCCCGT"
  ]
  node [
    id 466
    label "GCCGTG--CACGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 467
    label "GCGGTTGCAGCCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 468
    label "GCGGTTGCAATCGCGCG--CGCCCTGATCAGGACGGGCCCGT"
  ]
  node [
    id 469
    label "GTGGCTATAGCCACGTTCGAACCCAGATCTGGGTCGGCCGAT"
  ]
  node [
    id 470
    label "GCCGCCTAGGCGGTGCTCGAGCCCGGTACCGGCTCAGCTGAG"
  ]
  node [
    id 471
    label "GCGTTTATAAACGCGTG--CACGCTGATCAGTATGAGCTCAT"
  ]
  node [
    id 472
    label "GCGGGTGCGCTCGCGCTCGAGCCCAGGCTTGGGCGGGCCCGT"
  ]
  node [
    id 473
    label "GAGAACGCGTTCTCGCTCGAGCCCAGTACTGGGCGGGCCCGT"
  ]
  node [
    id 474
    label "GTGGGCGCGTCCACGCTCGAGCCGGGATCCCGGAGGGCCCTT"
  ]
  node [
    id 475
    label "GCGGTTGCAACCGTGCTCGAGCCAGGTACCTGGGTGGCCACT"
  ]
  node [
    id 476
    label "GTGGAG--CTCCACGTTCGAGCTCAGATCTGAGCCGGCCGGT"
  ]
  node [
    id 477
    label "GCCGTGATCACGGCGTCTGGACCTACGCGTAGCCAGGCCTGG"
  ]
  node [
    id 478
    label "GCGGGTGTACTCGCGCTCGAGCCCGGTACCGGGGGGGCCCCT"
  ]
  node [
    id 479
    label "GCGATTGCAGTCGCGCG--CGCCCGGATCCGGGAGGGCCCTT"
  ]
  node [
    id 480
    label "GCCGTGATCACGGTGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 481
    label "GTGGTTGCAGCCACGCTCGAGCTCGGTGCCGAGCGGGCCCGT"
  ]
  node [
    id 482
    label "GCGGTTGCAACCGCGCG--CGCCCGGATCCGGGGGGGCCCCT"
  ]
  node [
    id 483
    label "GCCCTGGCCGGGGCGCC--GGCTGAGATCTCAGCGGGCCCGT"
  ]
  node [
    id 484
    label "GTGACCGCGGTCACGTTCGAGCCCAGTACTGGGCGGGCCCGT"
  ]
  node [
    id 485
    label "GCGGTTGCAACCGTGCTCGAGCCAGGTACCTGGGTGGCCACC"
  ]
  node [
    id 486
    label "CTGTGA--TCACGGGTATGTACCTGCGTGCAGCTTGGCCAAG"
  ]
  node [
    id 487
    label "GCCCGGATCCGGGCGCTCGAGCCAGGATCCTGCCGGGCCCGG"
  ]
  node [
    id 488
    label "GCTGTGATCACAGCGTATGTACTTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 489
    label "GTAGATGCATTTACGCTCGAGCTCGGTACCGAGTGGGCCCAT"
  ]
  node [
    id 490
    label "GTGGTCGCGATCACGCTCGAGCTCAGATCTGAGCGGGCCCGT"
  ]
  node [
    id 491
    label "GCCGTG--CACGGCGTATGTACCTGCGTGCAGCCCGGCCGGG"
  ]
  node [
    id 492
    label "GCCCGGGCCCGGGCGCTCGAGCCCGGGCCCGGCCGGGCCCGG"
  ]
  node [
    id 493
    label "GTGGATGCATCCACGCTCGAGTCCAGATCTGGGCCGGCCGGT"
  ]
  node [
    id 494
    label "GTGGAG--CTCCACGCTCGAGCTCGGATCCGAGTCGGCCGAT"
  ]
  node [
    id 495
    label "GAGGGTGCATCCTCGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 496
    label "GCCGTG--CATGGCGTATGTACCTGCGCGCAGTTCGGCTGAG"
  ]
  node [
    id 497
    label "GCCGTGATCACGGCGTATGTACCTGCGCGCAGCTTGGCCAAG"
  ]
  node [
    id 498
    label "ATCCCG--CGGGATGCGCGCGCTTCGGCTGGAGGTGGCTACC"
  ]
  node [
    id 499
    label "GAGGGTGCATCCTCGCTCGAGCCGAGGCCTCGGCGGGCCCGT"
  ]
  node [
    id 500
    label "GTGGCTATAGCCACGCTCGAGCCCTGATCAGGGCGCGCGCGT"
  ]
  node [
    id 501
    label "GTGGGTATACTCACGCTCGAGCCTGGATCCAGGCGGGCCCGT"
  ]
  node [
    id 502
    label "GTGAGTGCACTCACGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 503
    label "GCTGTGATCACGGCGTATGTACCTGCGCGCAGCTCGGCTGAG"
  ]
  node [
    id 504
    label "GTGGCG--CGCCACGCTCGAGCTCAGATCTGAGCCGGCCGGT"
  ]
  node [
    id 505
    label "GCAGCTGCAGCTGTGCTCGAGCCTGGTACCAGGGTGGCCACC"
  ]
  node [
    id 506
    label "GCTGGGATCCCGGCGGG--CCTGGAGATCTCTTCGGGCTCGG"
  ]
  node [
    id 507
    label "GTGGGCGCGCCCACGCTCGAGCTCGGATCCGAATGGGCCCAT"
  ]
  node [
    id 508
    label "GTAAATATATTTACACTCGAGTATGATATCATAAGGGCCCTT"
  ]
  node [
    id 509
    label "GTGGAG--CTCCACGTTCGAGCTCAGATCTGAGTGGGCCCAC"
  ]
  node [
    id 510
    label "GCTGTGGTTATAGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 511
    label "GCGAGCGCGTTCGCGCC--GGCGCGGTACCGCGTGGGCCCAT"
  ]
  node [
    id 512
    label "GCTGTGATCACAGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 513
    label "GCCGTGATCACGGCGTCTGGACCCATGCGTGGCCAGGCCTGG"
  ]
  node [
    id 514
    label "GCCGCCTAGGCGGTGCTCGAGCCTGGTACCAGCTCCGCGGAG"
  ]
  node [
    id 515
    label "GTGGGTGCACTCACGCTCGAGCCCTGGCCAGGGTGGGCCCAT"
  ]
  node [
    id 516
    label "GTGGATGCGTCCACGCTCGAGCCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 517
    label "GCCGTGATCACGGCGTATGTACCTGCGCGCAGCCCGGCTGGG"
  ]
  node [
    id 518
    label "TGGGCTATAGCCCAGCC--GGCACGGATCCGTGTTGGCCAGC"
  ]
  node [
    id 519
    label "GCTGTGATCATGGCGTA--TATCTGTGCACAGCTCCGCGGAG"
  ]
  node [
    id 520
    label "GCGAATGCATTCGCGTG--CACGCGGGCCCGTGCGGGCCCGT"
  ]
  node [
    id 521
    label "GCGGTTGCAACCGTGCTCGAGCCAGGTACCTGAGTGGCCACT"
  ]
  node [
    id 522
    label "GCGGGTGCACCCGCGCTCGAGCCCAGATCTGGGCCGGCCGGT"
  ]
  node [
    id 523
    label "GCCGTGATCACGGCGTA--TACCTGTGCGCGGCTCGGCCGAG"
  ]
  node [
    id 524
    label "GCGATCGCGGTCGCGTTCGAGCTCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 525
    label "GTGGGTGCACTCACGCTCGAGCCTAGGCCTGGGCGGGCCCGT"
  ]
  node [
    id 526
    label "GCGGTTGCAACCGTGCTCGAGCCAGGTACCTGGCTGGCCAGC"
  ]
  node [
    id 527
    label "GCAGACGCGTCTGTGCTCGAGCTCGGATCCGAGGTGGCCACT"
  ]
  node [
    id 528
    label "GCCATCTAGATGGCGTATGTACCAACGCGTTGCCTGGCTAGG"
  ]
  node [
    id 529
    label "GCCATTTAAATGGCGTATGTACCATCGCGATGCCTGGCTAGG"
  ]
  node [
    id 530
    label "GTGGGTATACCCACGTTCGAGCCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 531
    label "GTGGGCGCGTCCACGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 532
    label "GCGGTCGCGGTCGCGCTCGAGCCTGGATCCAGGAGGGCCCTT"
  ]
  node [
    id 533
    label "GCCGTGATCACGGCGTATGTACTTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 534
    label "GCAGACGCGTCTGTGCTCGAGCTCGGATCCGAGGTGGCCACC"
  ]
  node [
    id 535
    label "GTAGATATATTTACGCTCGAGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 536
    label "CATGGGGCCCCATGGATCGATCCCCGGCCGGGGCCGGCCGGC"
  ]
  node [
    id 537
    label "GTGGGAGCTCCCACGCTCGAGCCCGGGCCCGGGCGGGCCCGT"
  ]
  node [
    id 538
    label "GCGGGTGCACTCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 539
    label "GCGTGA--TCACGCGTCTGGACCTACGCGTAGCCAGGCCTGG"
  ]
  node [
    id 540
    label "GTGGGTATACTCACGCTCGAGCCCGCGCGCGGGCGGGCCCGT"
  ]
  node [
    id 541
    label "GTGGCCGCGGTCACGTTCGAGCCCAGTACTGGGCGGGCCCGT"
  ]
  node [
    id 542
    label "GCGGTCGCGGTCGCGCG--CGCCCGGATCCGGGTGGGCCCAC"
  ]
  node [
    id 543
    label "GCGATTGCAGTCGCGTG--CACGCGGATCCGCGTGGGCCCAT"
  ]
  node [
    id 544
    label "GTGCCCGCGGGCACGTTCGAGCTCAGATCTGAGTGGGCCCAC"
  ]
  node [
    id 545
    label "GTGGATGCATCCACGCTCGAGTCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 546
    label "GCTGTGATCACAGCGTATGTACCTGCGCGTAGCCCGGCCGGG"
  ]
  node [
    id 547
    label "GCGACCATGGTCGCGCTCGAGCCCGGTACCGGGCGGGCCCGT"
  ]
  node [
    id 548
    label "GTGGTTGCAGCCACGTATGTATCCACGCGTGGCCGGGCCCGG"
  ]
  node [
    id 549
    label "GCCCATGCATGGGCGTATGTACCCACGCGTGGGCTGGCCAGC"
  ]
  node [
    id 550
    label "GCCGGGGCCCTGGCGGG--CCTCGGGATCCCGTCGGGCCCGG"
  ]
  node [
    id 551
    label "GCTGTGATCACGGCGTGTGTACCTGCGCGCAGTTCGGCCGAG"
  ]
  node [
    id 552
    label "GTGGTTGCAACCACATG--CATTTGCATGCAAGTGGGCCCAC"
  ]
  node [
    id 553
    label "GTGAGTGCACTCACGCTCGAGCCTGGATCCAGGGGGGCCCCT"
  ]
  node [
    id 554
    label "GTGGATGCATCCACGTTCGAGCCCAGGCCTGGGCGGGCCCGT"
  ]
  node [
    id 555
    label "GTGGGTATATCCACGCTCGAGCCCAGATCTGGATGGGCCCAT"
  ]
  node [
    id 556
    label "GCGGCCATGGTCGCGTTCGAACCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 557
    label "GCGGGTGCACTCGCGCTCGAGCCCAGATCTGGATGGGCCCAT"
  ]
  node [
    id 558
    label "GCCGGCTAGTCGGTGCTCGAGCCCAGATCTGGCCCCGCGGGG"
  ]
  node [
    id 559
    label "GCTGTGATCACGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 560
    label "GTGGTTGCAGTCACGCTCGAGCCCGGGTCCGGGCGGGCCCGT"
  ]
  node [
    id 561
    label "GTGAGTGCACTCACGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 562
    label "GTGGCTATAGCCACGCTCGAGCCTGGATCCAGGCGAGCTCGT"
  ]
  node [
    id 563
    label "GCGGCTGCAGCCGCGCTCGAGCCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 564
    label "GTGGGTATATCCACGCTCGAGCCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 565
    label "GCCGTGATCACGGCGTATGTACCTGTGTGCAGTCCGGCCGGG"
  ]
  node [
    id 566
    label "GTGACCGCGGTCACGTTCGAGCCCAGTACTGGGCGAGCTCGT"
  ]
  node [
    id 567
    label "GCGGACGCGTCCGCGCTCGAGCCTGGATCCAGGCGGGCCCGT"
  ]
  node [
    id 568
    label "GTGGGTGCATCCACGTC--GACCAGGATCCTGATGGGCCCAT"
  ]
  node [
    id 569
    label "GCGACA--TGTCGCGCTCGAGTTCGGTACCGAGTGGGCCCAC"
  ]
  node [
    id 570
    label "GTGGCTATAGCCACGCTCGAGTCTGGATCCAGATGGGCCCAT"
  ]
  node [
    id 571
    label "GTGGGTGCACCCACGCCTAGGCCCAGATCTGGGGGGGCCCCT"
  ]
  node [
    id 572
    label "CCTGCT--AGCAGGGTATGTACCCACGCGTGGGCTGGCCAGC"
  ]
  node [
    id 573
    label "GTGAACGCGTTCACGCT--AGCCCGGGCTCGGGTGGGCCCAT"
  ]
  node [
    id 574
    label "GCCGTGATCACGGCGTATGTACCTGCGTGCAGCTCGGCCGAG"
  ]
  node [
    id 575
    label "GCCCCGATCGGGGCGCC--GGCTGAGGTCTCAGCGGGCCCGC"
  ]
  node [
    id 576
    label "GGGTGTGCACGCCCGTATGTACCTTCGCGAAGGCAAGCTTGC"
  ]
  node [
    id 577
    label "GCGTGCGCGCACGCGCG--CGCTCGGGTCCGAGTGGGCCCAT"
  ]
  node [
    id 578
    label "GTGACCGCGGTCACGCTCGAGTCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 579
    label "GTGGGTATACCCACGTTCGAGCCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 580
    label "GCGTATATATACGCGCG--CGCCCGGGCCCGGGAGGGCCCTT"
  ]
  node [
    id 581
    label "GCCGTGATTACGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 582
    label "CTGACCGCGGTCAGGCTCGAGCCCAGATCTGGGCCGGCCGGT"
  ]
  node [
    id 583
    label "GTGGCTGCAGCCACGTTTGAATCCACGCGTGGTTGGGCCCAG"
  ]
  node [
    id 584
    label "GCGGCCATGGCCGCGCTCGAGCCCGGATCCGGGCCGGCCGGT"
  ]
  node [
    id 585
    label "GTGGGTATATCCACGTGCGCGCCCAGATCTGGGCCGGCCGGC"
  ]
  node [
    id 586
    label "GTGGGCGCGCTCACGCTCGAGCCCGGGCCCGGGTGGGCCCAT"
  ]
  node [
    id 587
    label "GCTGTGATCACGGCGTATGTACCTGCGCGCAGCTCGGTCGAG"
  ]
  node [
    id 588
    label "GCGGTTGCAACCGCGCG--CGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 589
    label "GCGGTCGCGATCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 590
    label "GCCGCTGCAGCGGTGCTCGAGCCCAGATCTGGCCCCGCGGGG"
  ]
  node [
    id 591
    label "GTCGTGATCACGGCGTATGTACCTGCGTGCAGCCCGGCCGGG"
  ]
  node [
    id 592
    label "GCTGTGATCACGGCGTATGTACCTGTGTGCAGCCTGGCTGGG"
  ]
  node [
    id 593
    label "GCTGCT--AGCAGCGTATGTACCCACGCGTGGGCTGGCCAGC"
  ]
  node [
    id 594
    label "GCGGGTGCACTCGCGCTCGAGCTCAGGTCTGAGCGGGCCCGT"
  ]
  node [
    id 595
    label "GTGGGTGCACTCACGCTCGAGCTCAGGTCTGAGTGGGCCCAT"
  ]
  node [
    id 596
    label "GCGGGTGCACCCGCGTC--GACCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 597
    label "GAGGCTATAGTCTCGCGTACGCCTTCATGAAGTCGGGCCCGA"
  ]
  node [
    id 598
    label "GTGGATGCATTCACGTTCGAGCCCAGGCCTGGGTGGGCCCAC"
  ]
  node [
    id 599
    label "GTGGGCGCGCTCACGCTCGAGCCCGCGCGCGGGCGGGCCCGT"
  ]
  node [
    id 600
    label "GCAGATGCATCTGCGCG--CGCTCGGGTCCGAGCGGGCCCGT"
  ]
  node [
    id 601
    label "GTGGCTGCAGCCACGCTCGAGCCCAGATCTGGGGGGGCCCCT"
  ]
  node [
    id 602
    label "GCGGGG--CCTCGCGCTCGAGCCGTGGCCATGGTGGGCCCAT"
  ]
  node [
    id 603
    label "GTGGAG--CTCCACGCTCGAGCCCAGGCCTGGGTGGGCCCAT"
  ]
  node [
    id 604
    label "GCCGTGATCACGGCGTATGTATCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 605
    label "GCCGGA--TCCGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 606
    label "GTGGCTGCAGCCACGCTCGAGCCAGGATCCTGGAGGGCCCTT"
  ]
  node [
    id 607
    label "GTGGCCGCGGTCACGCTCGAGTCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 608
    label "GCTGTGATCACAGCGTGTGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 609
    label "GTGGGCGCGTCCACGCTCGAGCCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 610
    label "GCCATATATATGGCGTATGTACTAACGCGTTGCCTGGCCAGG"
  ]
  node [
    id 611
    label "GTGAGCGCGCTCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 612
    label "GCGATTGCAGTCGCGCG--CGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 613
    label "GTGGTG--CACCACGCTCGAGCTCGGATCCGAGGGGGCCCCT"
  ]
  node [
    id 614
    label "GCGAAG--CTTCGCGCTCGAGCCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 615
    label "GCGGGTGCATCCGCGCC--GGCGCGGCGCCGCGGGGGCCCCT"
  ]
  node [
    id 616
    label "GTGGGATATTCCACGCTCGAGCCCGCTAGCGGGTGGGCCCAT"
  ]
  node [
    id 617
    label "GCGGAG--CTCCGCATC--GATTTGAATTCAAGCCGGCCGGC"
  ]
  node [
    id 618
    label "GTGGACGCGTCCACGTTCGAGCCCTGTACAGGGCGGGCCCGT"
  ]
  node [
    id 619
    label "GCGGATGCGTTCGCGCC--GGCGTGGATCCACGCGGGCCCGT"
  ]
  node [
    id 620
    label "CAGTCGTACGGCTGATC--GATTCGCATGCGATCGGGCCCGG"
  ]
  node [
    id 621
    label "GTGATG--CATCACGCTCGAGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 622
    label "GCCGGGGCCCCGGCGGA--TCTCGGGATCCCGTCGGGCTCGG"
  ]
  node [
    id 623
    label "GCGGGTGCGCTCGCGCTCGAGCCTTGATCAAGGTGGGCCCAT"
  ]
  node [
    id 624
    label "GCGGCTATAGTCGCGCG--CGCTCGGATCCGAGTGGGCCCAC"
  ]
  node [
    id 625
    label "GCCGTGATCACGGCGTT--GACCTGCGCGCAGCCTGGCCAGG"
  ]
  node [
    id 626
    label "GCGGGTATACTCGCGTG--CACGCGGATCCGTTAGGGCCCTA"
  ]
  node [
    id 627
    label "GTGTCTGCAGACACGCC--GGCCTGGTACCAGGCGAGCTCGT"
  ]
  node [
    id 628
    label "GTGGGTATATCCACGCTCGAGCCCAGATCTGGGTGAGCTCAT"
  ]
  node [
    id 629
    label "GCGGATGCATCCGCGTG--CACCCAGCGCTGGGCGGGCCCGT"
  ]
  node [
    id 630
    label "GCTGTGATCACGGCGTATGTACTTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 631
    label "GCCAGGGCCCTGGCGGG--CCTAGGGGTCCCTCCGGGCTCGG"
  ]
  node [
    id 632
    label "GTGGCTATAGCCACGCGTACGCCCAGATCTGGGAGGGCCCTC"
  ]
  node [
    id 633
    label "GCGGTCGCGATCGCGCG--CGCCCGGATCCGGGGGGGCCCCT"
  ]
  node [
    id 634
    label "GTGGGCGCGCCCACGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 635
    label "GTGGACGCGTCCACGCTCGAGCCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 636
    label "GTGGCTGCAGCCACGCTCGAGTCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 637
    label "GTGGGTGCATCCACGCC--GGCGAGGATCCTCGCGGGCCCGT"
  ]
  node [
    id 638
    label "GTGGGCGCGTCCACGCTCGAGCCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 639
    label "GCCCGGGCCCGGGTGTGTGCACGAAGTACTTTTTGAGCTCAG"
  ]
  node [
    id 640
    label "GTAAATATGTTTACGCTCGAGCATAGTACTATGCGGGCCCGT"
  ]
  node [
    id 641
    label "GTGGATATATCCACGCTCGAGCTCTGATCAGAGCGCGCGCGT"
  ]
  node [
    id 642
    label "GCCGGCGCGCTGGTGCTCGAGCCCTGATCAGGCCCCGCGGGG"
  ]
  node [
    id 643
    label "GTGAGCGCGCTCACGTTCGAGCCCGGGCCCGGGGGGGCCCCT"
  ]
  node [
    id 644
    label "GTGGATGCATCCACGCTCGAGCCAGGATCCTGGTGGGCCCGT"
  ]
  node [
    id 645
    label "GCGGTCGCGATCGCGCTCGAGCTTGGATCCAAGCGGGCCCGT"
  ]
  node [
    id 646
    label "GTGGCTGCAGCCACGCTCGAGTCCGGATCCGGGGGGGCCCCT"
  ]
  node [
    id 647
    label "GTGGCCATGGCCACGCTCGAGCTCTGATCAGAGCGCGCGCGT"
  ]
  node [
    id 648
    label "GTGGATGCATCCACGCTCGAGCCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 649
    label "GCGGGTGCACTCGCGCTCGAGTTCAGTACTGAGCCAGCTGGT"
  ]
  node [
    id 650
    label "GCCGGGGCTCCGGCGGG--CCTCGGGATCCTGTCGGGCTCGG"
  ]
  node [
    id 651
    label "GTGCGCGCGCGCACGCTCGAGCGCGGGCCCGCGACGGCCGTT"
  ]
  node [
    id 652
    label "GTGAACGCGTTCACGTTCGAGCCCAGTACTGGGTGGGCCCAT"
  ]
  node [
    id 653
    label "GTGGGTATACTCACGTC--GACCCTGGCCAGGGTGAGCTCAC"
  ]
  node [
    id 654
    label "GCCATCTAGGTGGCGTA--TACCAACGCGTTGCCTGGCTAGG"
  ]
  node [
    id 655
    label "GTCTGCCGGCAGACGTATGTACCTTCGCGAAGCCATGCATGG"
  ]
  node [
    id 656
    label "GCCGTGATCACGGCGTACGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 657
    label "GCGTGA--TCATGTGTATGTACCTGCGTGCAGCCCGGCCGGG"
  ]
  node [
    id 658
    label "GCGGATGCATCCGCGTG--CACGCGGGCCCGTGAGGGCCCTT"
  ]
  node [
    id 659
    label "GTGGATGCATTCACGCTCGAGCCTGGATCCAGGCGGGCCCGT"
  ]
  node [
    id 660
    label "GTGGGTGCATCCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 661
    label "GCCGTGATCACGGCGTATGTACCTGCGCGCAGCCTGGCCGGG"
  ]
  node [
    id 662
    label "GTGGGTATACCCACGCC--GGCTCAGATCTGACAGGGCCCTG"
  ]
  node [
    id 663
    label "GCCCGGGTCCGGGCGGG--CCTTGGGATCCCACCGGGCCCGG"
  ]
  node [
    id 664
    label "GTGGGTGCACTCACGCTCGAGCCTAGGCCTAGGTGGGCCCAC"
  ]
  node [
    id 665
    label "GTGACCGCGGTCACGCTCGAGCCCGGGCCCGGGTGGGCCCAC"
  ]
  node [
    id 666
    label "CTGTGA--TCACAGGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 667
    label "GTGAGCGCGCTCACGCTCGAGCCCGGCGCCGGGCGGGCCCGT"
  ]
  node [
    id 668
    label "GCCATCGTGATGGCGTATGTACCCACGCGTGGCTCAGCTGGG"
  ]
  node [
    id 669
    label "GCGATG--CATCGCGTG--CACGCGGGCCCGTGAGGGCCCTT"
  ]
  node [
    id 670
    label "GTCCCTATAGGGACGTC--GACTAACATGTTGGCCTGCAGGC"
  ]
  node [
    id 671
    label "GTGGGTATATTCACGCTCGAGCCCAGATCTGGGTGGATCCAC"
  ]
  node [
    id 672
    label "GTGATTATAATCACGTTCGAGCTCAGATCTGAGTGGGCCCAC"
  ]
  node [
    id 673
    label "GCCGTGATCACGGCGTATGTACCTGCGCGCAGCCTGGCCAGG"
  ]
  node [
    id 674
    label "GCCGCCATGGCGGTGCTCGAGCCTAGATCTAGCCCCGCGGGG"
  ]
  node [
    id 675
    label "GCCGTGGTCACGGCGTCTGGACTTGCGCGCAACCAGGCCTGG"
  ]
  node [
    id 676
    label "GCCGGGGTCCCGGCGGG--CCTTGGCCGGCTACCGAGCTCGG"
  ]
  node [
    id 677
    label "GCCGTCGCGACGGTGCTCGAGCCTAGATCTAGCCCCGCGGGG"
  ]
  node [
    id 678
    label "GTGGGCGCGTCCACGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 679
    label "GCGGGCGCGCTCGCGCTCGAGCTCAGTACTGGGCCAGCTGGT"
  ]
  node [
    id 680
    label "GCGAGCGCGTTCGCGCC--GGCGTGGATCCACGGGGGCCCCT"
  ]
  node [
    id 681
    label "GCGAATGCATTCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 682
    label "GCGGATGCATTCGCGCTCGAGCCCGGTACCGGGCGGGCCCGT"
  ]
  node [
    id 683
    label "GCGATTGCAGTCGCGCG--CGCCCTGATCAGGGTGGGCCCAT"
  ]
  node [
    id 684
    label "GCCGGGGTCCCGGCGGG--CCTTGGCCGGCTATCGAGCTCGA"
  ]
  node [
    id 685
    label "GTGGGTGCACTCACGCTCGAGCCTTGGCCAAGGGGGGCCCCT"
  ]
  node [
    id 686
    label "GTGGTCGCGATCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 687
    label "GTGATG--CATCACGCTCGAGCCCGGATCCGGGGGGGCCCCT"
  ]
  node [
    id 688
    label "GCCGTGATCACGGCGTCTGGACTTGCGCGCAACCAGGCCTGG"
  ]
  node [
    id 689
    label "GCTGTGGTCACAGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 690
    label "GTGGGATATCCCACGCTCGAGCCTGGTGCCGGGCGGGCCCGT"
  ]
  node [
    id 691
    label "GTGGCCGCGGTCACGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 692
    label "GCGGATGCATTCGCGCTCGAGCCCAGTACTGGGCCAGCTGGT"
  ]
  node [
    id 693
    label "GCGGGCGCGCTCGCGCC--GGCGTGGCGCCACGGGGGCCCCT"
  ]
  node [
    id 694
    label "GCGTGA--TCACGCGTATGTACCTGCGCGCAGTCTGGCCGGG"
  ]
  node [
    id 695
    label "GTGAAG--CTTCACGCTCGAGCTTGGTACCAAGCGGGCCCGT"
  ]
  node [
    id 696
    label "GCGATTGCAGTCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 697
    label "GCCTGA--TCAGGCGTATGTACCTGTGCGCAGCCCGGCCGGG"
  ]
  node [
    id 698
    label "GCTGTGATCATGGCGTATGTACCTGTGTGCAGCTTGGCTGAG"
  ]
  node [
    id 699
    label "GTGGATGCATCCACGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 700
    label "GTGGCTATAGTCACGTG--CACGCGGATCCGTGAGGGCCCTC"
  ]
  node [
    id 701
    label "GTCGTGATCACGGCGTATGTACCTGCGCGCAGCCCGGCTGGG"
  ]
  node [
    id 702
    label "GCGGTCGCGGCCGCGCG--CGCTCGGCGCCGAGTGGGCCCAT"
  ]
  node [
    id 703
    label "GCCAGGGCCCTGGCGGG--CCTGGGGATCCCCCCGGGCTCGG"
  ]
  node [
    id 704
    label "GCGGATGCATTCGCGCTCGAGCCTGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 705
    label "GCCGTGATCACGGCGTATGTACCTGCGTGCAGCCCGGCCGGG"
  ]
  node [
    id 706
    label "GCGGATGCATTCGCGCTCGAGCCCGGATCCGGGCGAGCTCGT"
  ]
  node [
    id 707
    label "GCGTGA--TCACGCGTCTGGACCCACGCGTGGCCAGGCCTGG"
  ]
  node [
    id 708
    label "GCGGTTGCAGCCGCGCG--CGCTCGGATCCGAGAGGGCCCTT"
  ]
  node [
    id 709
    label "GTGGGTATACCCACGCG--CGCCCGGATCCGGGAGGGCCCTC"
  ]
  node [
    id 710
    label "GTGGCTGCAGCCACGCTCGAGCCCTCATGAGGGAGGGCCCTT"
  ]
  node [
    id 711
    label "GTGGGTATATCCACGCTCGAGCCCAGATCTGGAAGGGCCCTT"
  ]
  node [
    id 712
    label "GTGACTGCAGTCACGCTCGAGCCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 713
    label "GCGTGA--TCATGCGTATGTACTTGCGCGCAGCTCAGCTGAG"
  ]
  node [
    id 714
    label "GCGGCTGCAGTCGCGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 715
    label "GTGGGTGCACCCACGCTCGAGCTCAGGTCTGAGTGGGCCCAT"
  ]
  node [
    id 716
    label "GTGGCCATGGCCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 717
    label "GCGAGCGCGTTCGCGCC--GGCGTGGTACCACGTGGGCCCAT"
  ]
  node [
    id 718
    label "GCGGCTATAGTCGCGTG--CACGCGGATCCGTGTGGGCCCAC"
  ]
  node [
    id 719
    label "GCGGTTGCAATCGTGCTCGAGCCAGGTACCTGGGTGGCCACC"
  ]
  node [
    id 720
    label "GCCATTTAAGTGGCGTATGTACCATCGCGATGCCTGGCTAGG"
  ]
  node [
    id 721
    label "GCGGCTGCAGTCGCGCTCGAGCCTGGATCCGGGCGAGCTCGT"
  ]
  node [
    id 722
    label "GTGGATGCATCCACGTTCGAGCCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 723
    label "TCCGGGTACCCGGAGGG--CCTCAGCCGGCTGGCGAGCTCGC"
  ]
  node [
    id 724
    label "GCGGCTATAGCCGCGTTCGAACCCGCTAGCGGGTGGGCCCAC"
  ]
  node [
    id 725
    label "GCGTCGGTCGACGCGTG--CACTCAGGTCTGAGCGGGCCCGT"
  ]
  node [
    id 726
    label "GCGGTG--CACCGCGCG--CGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 727
    label "GTGGATATATCCACGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 728
    label "GTGGAAGCTTCCACGTTCGAGCCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 729
    label "GCCGCCGCGGCGGCGTCTGGATGCGGGCCCGCCCGGGCCCGG"
  ]
  node [
    id 730
    label "GTGGCTATAGCCACGCTCGAGCCCGGATCCGGGTGAGCTCAT"
  ]
  node [
    id 731
    label "GCCGCCGCGGTGGTGCTCGAGCCCTGATCAGGCCCCGCGGGG"
  ]
  node [
    id 732
    label "GCCGCCGCGGCGGCGTCTGGATGAGGGCCCTTCCGGGCCCGG"
  ]
  node [
    id 733
    label "GTGCCCATGGGCACGCTCGAGCTCGGATCCGAGCGGGCCCGT"
  ]
  node [
    id 734
    label "GCGTGA--TCACGCGTATGTACCTGCGTGCAGTCCAGCTGGG"
  ]
  node [
    id 735
    label "GCGGTTGCAACCGCGCG--CGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 736
    label "GTGGGTGCACTCACGTTCGAGCCCAGGCCTGGGCGGGCCCGT"
  ]
  node [
    id 737
    label "GTGGATGCATCCGCGCG--CGCTCGGGTCCGAGCGGGCCCGT"
  ]
  node [
    id 738
    label "GGGTCAGCTGGTTTGTG--CGTTCTGATCAGACCAGGCCTGG"
  ]
  node [
    id 739
    label "GCCGCCGCGGCGGCGCTCGAGCCGGGGCCCCGCCGGGCCCGG"
  ]
  node [
    id 740
    label "GTGGGCGCGCTCACGCTCGAGCCTAGGCCTAGGGGGGCCCCT"
  ]
  node [
    id 741
    label "GTGGCTATAGCCACGTG--CACCCGGATCCGGGTGAGCTCAC"
  ]
  node [
    id 742
    label "GCCTGA--TCAGGCGTATGTACCTGCGCGCAGCTCGGCCGGG"
  ]
  node [
    id 743
    label "GAGAACATGTTCTCGCGCGCGCGCCGATCGGCGCGGGCCCGC"
  ]
  node [
    id 744
    label "GCGGGTGCACTCGCGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 745
    label "GCGGGTGCATTCGCGTG--CACTCAGATCTGAGTGGGCCCAT"
  ]
  node [
    id 746
    label "GCCGCCTAGGTGGTGCTCGAGCCCTGATCAGGCCCCGCGGGG"
  ]
  node [
    id 747
    label "GCCATATATATGGCGTATGTACCAACGCGTTGCCTGGCTAGG"
  ]
  node [
    id 748
    label "GTCGTGATCATGGCGTATGTACCTGCGCGCAGCCCGGCTGGG"
  ]
  node [
    id 749
    label "CGGATG--CGTTCGGCC--GGCGTGGATCCACGCGGGCCCGT"
  ]
  node [
    id 750
    label "GTGTCTGCAGACACGTC--GACCTGGTGCCAGGCGGGCCCGT"
  ]
  node [
    id 751
    label "GCCATCTAGATGGCGTATGTACCATTGCGATGCCTGGCTAGG"
  ]
  node [
    id 752
    label "GCCTGGGTCCAGGCGGG--CCTAGGGATCCCTCTGGGCCCGG"
  ]
  node [
    id 753
    label "GCGGCCATGGCCGCGCTCGAGCCCGGATCCGGACCGGCCGGT"
  ]
  node [
    id 754
    label "GCGGTTGCAACCGTGCTCGAGCCAGGATCCTGGGTGGCCACC"
  ]
  node [
    id 755
    label "TCCGGGTACCTGGAGGG--CCTCAGCCGGCTGGCGGGCTCGC"
  ]
  node [
    id 756
    label "GCCGTGGTCACGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 757
    label "GCGAGCGCGTTCGCGCC--GGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 758
    label "GCGGTTGCGGCCGCGCG--CGCTCGGCGCCGAGGGGGCCCCT"
  ]
  node [
    id 759
    label "GCGTATGCATACGCGTG--CACGCGGTACCGTGCGGGCCCGT"
  ]
  node [
    id 760
    label "GGGCCAGCTGGCTTGTG--CGCTCTGATCAGACTAGGCCTGG"
  ]
  node [
    id 761
    label "TCCGGGGCCCTGGAGGG--CCTCAGCCGGCTGGCGGGCTCGC"
  ]
  node [
    id 762
    label "GTGGATGCGTCCACGCTCGAGTCAGGATCCTGGCGGGCCCGT"
  ]
  node [
    id 763
    label "GCCGTGATCACGGCGTT--GACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 764
    label "GTGGCTGCAGCCACGCTCGAGCCCAGGCCTGGGTGGGCCCAT"
  ]
  node [
    id 765
    label "GTGGATGCATTCACGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 766
    label "GCGAGCGCGTTCGCGCC--GGCGAGGATCCTCGTGGGCCCAT"
  ]
  node [
    id 767
    label "GTGAACGCGTTCACGTTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 768
    label "GCGGTTGCAGCCGCGCG--CGCGCGGCGCCGTGTGGGCCCAT"
  ]
  node [
    id 769
    label "GCCATCTAGATGGCGTATGTACCATCGCGATGCCTGGCTAGG"
  ]
  node [
    id 770
    label "GCCGCCTAGGCGGTGCTCGAGCCTAGATCTAGCCCTGCAGGG"
  ]
  node [
    id 771
    label "GCCGTGATCATGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 772
    label "GTGGGCGCGCTCACGTTCGAGCCCAGGCCTGGGCGGGCCCGT"
  ]
  node [
    id 773
    label "GCTGTGATCACGGCGTATATATTTGCGTGCAGCTCGGCCGAG"
  ]
  node [
    id 774
    label "GTGGATGCATCCACGCTCGAGTCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 775
    label "GTGACTGCAGTCACGTTCGAGCTCAGATCTGAGAGGGCCCTT"
  ]
  node [
    id 776
    label "GCGACTGCAGTCGCGCTCGAGTCCAGGCCTGGGTCGGCCGAC"
  ]
  node [
    id 777
    label "GTAGATGCATCTACGCG--CGCTCGGGTCCGAGCGGGCCCGT"
  ]
  node [
    id 778
    label "GCCTGA--TCAGGCGTATGTGTCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 779
    label "GCCGAGATCTCGGCGTATGTACCTGCATGCAGCTCGGCCGAG"
  ]
  node [
    id 780
    label "GTGAACGCGTTCACGCTCGAGCCTGGGCCCAGGCGGGCCCGC"
  ]
  node [
    id 781
    label "GCCGAGGTCTCGGCGGG--CCTAGGGATCCCTCCGGGCTCGG"
  ]
  node [
    id 782
    label "GTGGTTGCAATCACGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 783
    label "GTGGGTATACCCACGCTCGAGTCCAGGCCTGGATCGGCCGAT"
  ]
  node [
    id 784
    label "GTGACCGCGGTCACGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 785
    label "GTAGCTATAGTTACGCTCGAGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 786
    label "GCCGCCATGGCGGTGCTCGAGCCCAGATCTGGCCCCGCGGGG"
  ]
  node [
    id 787
    label "GGTGCTGCAGCGCCGTG--CATATTCGCGAATCTGGGCCCAG"
  ]
  node [
    id 788
    label "GCGGTTGCAGTCGCGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 789
    label "GCCGGGGCCCCGGCGTGCGCATCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 790
    label "GGGCAG--CTGCTTGCG--CGCTCTGATCAGACCAGGCCTGG"
  ]
  node [
    id 791
    label "GTGGTCATGATCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 792
    label "GTGGGTATACTCACGTG--CACGCGGATCCGTGTGGGCCCAC"
  ]
  node [
    id 793
    label "GTGGATATATCCACGTG--CACAACGATCGTTGTGGGCCCAC"
  ]
  node [
    id 794
    label "GTGGCATATGCCACGTTCGAACCCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 795
    label "GTGGTTGCAGTCACGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 796
    label "TCCCTG--TGGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 797
    label "GCGGCTATAGTCGCGCG--CGCCCAGATCTGGGTGGGCCCAC"
  ]
  node [
    id 798
    label "GCCACTTAAGTGGCGTATGTACCATCGCGATGCCTGGCTAGG"
  ]
  node [
    id 799
    label "GTGGGTATACTCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 800
    label "GCGTATATATACGCGCG--CGCCTGGGTCCAGGAGGGCCCTT"
  ]
  node [
    id 801
    label "GCCGGGGCCCCGGCGTGTGCACCGGGATCCCGCCGGGCCCGG"
  ]
  node [
    id 802
    label "GTGGAG--CTCCACGCTCGAGCCTGGTATCAGGTGGGCCCAT"
  ]
  node [
    id 803
    label "GCCGGGGCCCCGGCGGG--CCTAGGGATCCCTTCGGGCTCGG"
  ]
  node [
    id 804
    label "GTGGCG--CGCCACGTTCGAGCTCAGATCTGAGTGGGCCCAT"
  ]
  node [
    id 805
    label "GTGGATATATCCACGTG--CACCCGGATCCGGGTGGGCCCAC"
  ]
  node [
    id 806
    label "GTGAGCGCGTTCACGTTCGAGCCCAGTACTGGGCGGGCCCGT"
  ]
  node [
    id 807
    label "GTGGTAGTTATCACGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 808
    label "GTGGCTGCAGTCACGCTCGAGTCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 809
    label "GCCGTGATCATGGCGTATGTACCTGCGCGCAGCCTGGCCGGG"
  ]
  node [
    id 810
    label "GTGGATGCGTCCACGCTCGAGCTTAGATCTAAGCGGGCCCGT"
  ]
  node [
    id 811
    label "GTGGAATATTCCACGCTCGAGCCCGCTAGCGGGTGGGCCCAT"
  ]
  node [
    id 812
    label "GCGGTG--CACCGCGCG--CGCCCGGATCCGGGTGGGCCCAC"
  ]
  node [
    id 813
    label "GCGTTCGCGAACGCGCG--CGCCCGGGTCCGGGAGGGCCCTT"
  ]
  node [
    id 814
    label "GCGGATGCATTCGCGCTCGAGCTCAGTACTGAGCCAGCTGGT"
  ]
  node [
    id 815
    label "GCTCGGGCCCGAGCGCTCGAGCCCGGGCCCGGCCGGGCCCGG"
  ]
  node [
    id 816
    label "GCGTTTGCAAACGCGCG--CGCCCGGGTCCGGGTGGGCCCAT"
  ]
  node [
    id 817
    label "GTGGACGCGTCCACGTTCGAGCCCAGATCTGGGAGGGCCCTT"
  ]
  node [
    id 818
    label "GCGACTGCAGTCGCGCTCGAGCCTCGGCCGGGGCGGGCCCGT"
  ]
  node [
    id 819
    label "GTGGATGCATCCACGCTCGAGCTCAGGTCTGAGTGGGCCCAT"
  ]
  node [
    id 820
    label "GCCGTGATTACGGCGTATGTACCTGCGTGCAGCCTGGTCGGG"
  ]
  node [
    id 821
    label "GCCGCCTAGGTGGTGCTCGAGCCTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 822
    label "GTGGGCGCGCTCACGCTCGAGCCCTGGCCAGGGGGGGCCCCT"
  ]
  node [
    id 823
    label "GCGGATGCATTCGCGCTCGAGCCAGGATCCTGGCGGGCCCGT"
  ]
  node [
    id 824
    label "GTAAAA--TTTTACATTCGAATACTGCGCAGTCTGAGCTCAG"
  ]
  node [
    id 825
    label "GCGGGTATGCTCGCGCTCGAGCCAAGTACTTGGCGGATCCGT"
  ]
  node [
    id 826
    label "GCCATCTAGATGGCGTATGTACCATCGCGATGCCAGGCTTGG"
  ]
  node [
    id 827
    label "GTGGGTGCATCCACGCTCGAGCCAGGATCCTGGTGGGCCCGT"
  ]
  node [
    id 828
    label "GCCATGATCATGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 829
    label "GTGACTATAGTCACGTTCGAGCTCAGATCTGAGTGGGCCCAC"
  ]
  node [
    id 830
    label "GTGGCTTAAGCCACGCTCGAGCCCGCTAGCGGGGGGGCCCCT"
  ]
  node [
    id 831
    label "GCGGATGCATCCGCGTG--CACTCGGTACCGAGTGGGCCCAT"
  ]
  node [
    id 832
    label "GTGAGAGCTTTCACGCTCGAGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 833
    label "GGAGTG--CACTCCGTTCGAGCCCAGGCCTGGGCGGGCCCGT"
  ]
  node [
    id 834
    label "GTGGTCGCGACCACGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 835
    label "GCGAATGCGTTCGCGTG--CACGCGGGTCCGTGCGGGCCCGT"
  ]
  node [
    id 836
    label "GTGACCATGGTCACGCTCGAGCCCTGATCAGGGCGGGCCCGC"
  ]
  node [
    id 837
    label "GCGATCGCGATCGCGCTCGAGCCCGGTACCGGGGGGGCCCCT"
  ]
  node [
    id 838
    label "GTGGGTGCACTCACGTTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 839
    label "GCCGTGATTATGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 840
    label "GCGGCTATAGCCGCGTTCGAACCCTGATCAGGGCGGGCCCGC"
  ]
  node [
    id 841
    label "GTGGGTGCACCCACGCTCGAGCCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 842
    label "GTGGTTGCAACCACGCTCGAGTCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 843
    label "GTGGATGCATTCACGCTTGAGCCCGGATCCGGATGGGCCCAT"
  ]
  node [
    id 844
    label "GTGGATATATCCACGCTCGAGCCCAGGCCTGGATGGGCCCAT"
  ]
  node [
    id 845
    label "GTGGGTTAACTCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 846
    label "TCCGGGTACCCGGAGGG--CCTCAGCCGGCTGGCGGATCCGC"
  ]
  node [
    id 847
    label "GTGGAG--CTCCACGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 848
    label "TCACGG--CCGTGAACC--GGTTGGGTACCCAGCGGGCCCGC"
  ]
  node [
    id 849
    label "GCGACG--CGTCGCGCTCGAGCCTGGATCCAGGCGGGCCCGT"
  ]
  node [
    id 850
    label "GCCCCGGCCGGGGCGTGTACACCGGGCGCCCGCCGGGCCCGG"
  ]
  node [
    id 851
    label "GTGAGCGCGTTCACGCTCGAGCCTGGATCCAGGAGGGCCCTT"
  ]
  node [
    id 852
    label "GCAGCTGCAGCTGTGCTCGAGCCCGGTACCGGGGTGGCCACC"
  ]
  node [
    id 853
    label "GCCGGGGTCCCGGCGGG--CCTTAGCCGGCTATCGAGCTCGG"
  ]
  node [
    id 854
    label "GAGGATGCATCCTCGCTCGAGCAGGGATCCCTGCGGGCCCGT"
  ]
  node [
    id 855
    label "GCCGGGGTCCCGGCGGG--CCTTAGCCGGCTATCGAGCTCGA"
  ]
  node [
    id 856
    label "GCGGCCGCGGTCGCGCTCGAGCTCGGGCCCGAGCGGGCCCGT"
  ]
  node [
    id 857
    label "GTGGACGCGTTCACGTTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 858
    label "GTGGGTGCACCCACGTTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 859
    label "GTGGGTGCACTCACGCTCGAGCCCTGGCCAGGGAGGGCCCTT"
  ]
  node [
    id 860
    label "GCCGTGATCATGGCGTATGTACCTGCGTGCAGCCCGGCCGGG"
  ]
  node [
    id 861
    label "GCGTGA--TCATGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 862
    label "GCAGTTGCAACTGTGCTCGAGCCCTGTACAGGGGTGGCCACC"
  ]
  node [
    id 863
    label "GCGGGCGCGTTCGCGCC--GGCGTGGATCCACGCCGGCCGGT"
  ]
  node [
    id 864
    label "GTGGCTATAGCCACGCTCGAGCCCTGATCAGGGAGGGCCCTC"
  ]
  node [
    id 865
    label "GTGCCTCGAGGCACGCTCGAGCCTGGTACCAGACGGGCCCGT"
  ]
  node [
    id 866
    label "GCCGTGATCACGGCGTATGTACCTGCGCGCAGTCCGGCCGGG"
  ]
  node [
    id 867
    label "GCGGTATATACCGCGCG--CGCCCGGATCCGGGTGGGCCCAC"
  ]
  node [
    id 868
    label "GCCGGTCGACCGGCGTATGTACCTTCGCGAAGCCAGGCCTGG"
  ]
  node [
    id 869
    label "GCCGCCTAGGCGGTGCTCGAGCCCAGATCTGGCTCCGCGGAG"
  ]
  node [
    id 870
    label "GTGGCCATGGCCACGTG--CACTACGATCGTAGAGGGCCCTC"
  ]
  node [
    id 871
    label "GTGGATGCATCCACGCG--CGCCCGGGTCCGGGTGGGCCCAT"
  ]
  node [
    id 872
    label "GCCGAGGTCTCGGCGGG--CCTAAGGATCCTTCCGGGCCCGG"
  ]
  node [
    id 873
    label "GCGAGCGCGTTCGCGCC--GGCGAGGTACCTCGCGGGCCCGT"
  ]
  node [
    id 874
    label "GTGGCTATAGCCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 875
    label "GTGGGCGCGTCCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 876
    label "GCTGTGATCATGGCGTATGTACCTGTGTGCAGCCCGGCCGGG"
  ]
  node [
    id 877
    label "GCTGTA--TACAGCGTATGTACCTGCGCGCGGCCCGGCCGGG"
  ]
  node [
    id 878
    label "GCCGGGGTCCCGGCGGG--CCTTAGCCGGCTACTGAGCTCGG"
  ]
  node [
    id 879
    label "GCCGGGGTCCCGGCGGG--CCTGGGGATCCCCCCGGGCCCGG"
  ]
  node [
    id 880
    label "GTGGCTATAGCCACGCTCGAGCCTGGATCCAGGCGGGCCCGT"
  ]
  node [
    id 881
    label "GCGGACGCGTTCGCGCTCGAGCTCAGTACTGAGCCAGCTGGT"
  ]
  node [
    id 882
    label "GTGGATATATCCACGCTCGAGCCCTGGCCAGGGCGGGCCCGT"
  ]
  node [
    id 883
    label "GCGGATGCATCTGCGCG--CGCTCGGGTCCGAGCGGGCCCGT"
  ]
  node [
    id 884
    label "GCGTGA--TCACGCGTCTAGACTTACATGTAACCAGGCCTGG"
  ]
  node [
    id 885
    label "GTGGGCGCGCTCACGCTCGAGCCTGGGCCCAGGCGGGCCCGT"
  ]
  node [
    id 886
    label "GTGGCTATAGCCACGCTCGAGCCTGGATCCAGATGGGCCCAT"
  ]
  node [
    id 887
    label "GCGGTTGCAGCCGCGCC--GGCGAGGTATCTCGTGGGCCCAT"
  ]
  node [
    id 888
    label "GTGGCTATAGCCACGCTCGAGCTCTGATCAGAGCGCGCGCGT"
  ]
  node [
    id 889
    label "GTCATGATCATGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 890
    label "GCGGCCGCGGTCGCGCG--CGCCCGGATCCGGGTGGGCCCAC"
  ]
  node [
    id 891
    label "GCGAGCGCGTTCGCGCC--GGCGTGGATCCACGTGGGCCCAT"
  ]
  node [
    id 892
    label "GTGGCTGCAGTCACGCTCGAGCCCGGGCCCGGGTGGGCCCAT"
  ]
  node [
    id 893
    label "GTGGTTGCAGCCACGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 894
    label "GCGACG--CGTCGCGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 895
    label "GCCGGC--GCCGGCGTATGTACGTTCGCGAACCCAGGCCTGG"
  ]
  node [
    id 896
    label "GTGGCCGCGGCCACGCTCGAGTCAGGATCCTGGTGGGCCCAT"
  ]
  node [
    id 897
    label "GTGGCTGCAGCCACGCTCGAGTCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 898
    label "GTGGGTATACCCACGCGTACGCTCAGTACTGAGTGAGCTCAC"
  ]
  node [
    id 899
    label "GTAGGTATACTTACGCTCGAGCTCGGGTCCGAGTGGGCCCAT"
  ]
  node [
    id 900
    label "GTGAGCATGCTCACGCTCGAGCCCTGGCCAGGGTGGGCCCAT"
  ]
  node [
    id 901
    label "GCTGTGATCATGGCGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 902
    label "GTGGTTGCAATCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 903
    label "GCCGTGGCCACGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 904
    label "GCGAGCGCGCTCGCGCC--GGCGTGGATCCACGTGGGCCCAT"
  ]
  node [
    id 905
    label "GTGGATATATCCACGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 906
    label "GTGGAG--CTCCACGCTCGAGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 907
    label "GCGGGCGCGTTCGCGCTCGAGCCCTGATCAGGGCGGGCCCGT"
  ]
  node [
    id 908
    label "GTGACTATAGTCACGCTCGAGCCCGGATCCGGGCGGGCCCGT"
  ]
  node [
    id 909
    label "GTGGTG--CACCACGTTCGAGCTCAGATCTGAGTGGGCCCAC"
  ]
  node [
    id 910
    label "GTGAGTGCACTCACGCG--CGCCCGGATCCGGATGGGCCCAT"
  ]
  node [
    id 911
    label "GAGGGTGCACCCTCGCTCGAGCGGGGATCCCCGCGGGCCCGT"
  ]
  node [
    id 912
    label "GCGGTCGCGATCGCGCG--CGCTCGGATCCGAGAGGGCCCTT"
  ]
  node [
    id 913
    label "GAGGGTGCACCCTCGCTCGAGCCAAGGCCTTGGCGGGCCCGT"
  ]
  node [
    id 914
    label "GCGGCTGCAGCCGCGCTCGAGCCTTGCGCAGGGCGAGCTCGT"
  ]
  node [
    id 915
    label "GTGGATGCATCCGCGCG--CGCTCGGGCCCGAGCGGGCCCGT"
  ]
  node [
    id 916
    label "GCCGTGATCACGGCGTGTGTACCTGCGCGCAGTTCGGCCGAG"
  ]
  node [
    id 917
    label "GCCGGG--TCCGGCGGG--CCTAGGGATCCCTCCGGGCCCGG"
  ]
  node [
    id 918
    label "GTGGGG--CCCCACGCTCGAGCCCAGGCCTGGGTGGGCCCAT"
  ]
  node [
    id 919
    label "GCGGTTGCAATCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 920
    label "GTGCGCGCGTGCACGCTCGAGCGCGGGCCCGCGACGGCCGTT"
  ]
  node [
    id 921
    label "GCGGTTGCAGCCGCGTG--CACCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 922
    label "GCCGTGATCACGGCGTATGTACCTGCGCGCAGCTCGGCCGGG"
  ]
  node [
    id 923
    label "GTGGATATATCCACGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 924
    label "GTGAACGCGTTCACGCTCGAGCTTAGATCTAAGCCGGCCGGT"
  ]
  node [
    id 925
    label "GTGGATGCGTTCGCGCC--GGCGTGGATCCACGCGGGCCCGT"
  ]
  node [
    id 926
    label "GCGTAGGTCTACGCGTG--CACTCAGGTCTGAGCGGGCCCGT"
  ]
  node [
    id 927
    label "GTGAGTATACTCACGCTCGAGCCCAGGCCTGGGTGGGCCCAC"
  ]
  node [
    id 928
    label "GCGTGA--TCACGCGTA--TACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 929
    label "GCGATCGCGGTCGCGCTCGAGCCTGGTACCAGGTGGGCCCAT"
  ]
  node [
    id 930
    label "GCCGTGATCACGGCGTATGTACCTGTGCGCAGCCCGGCCGGG"
  ]
  node [
    id 931
    label "GCGACCGCGGTCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 932
    label "GTGTCGGCCGACACGTTCGAGCCCAGATCTGGGCGGGCCCGT"
  ]
  node [
    id 933
    label "GCAGTTGCAACTGTGCTCGAGCCCGGATCCGGGGTGGCCACC"
  ]
  node [
    id 934
    label "ATGGAC--GTCCATGCTTGAGCTCAGTATTGAGCGGGCCCGT"
  ]
  node [
    id 935
    label "GCCGTGATCACGGTGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 936
    label "GTGGGCGCGCTCACGCTCGAGCCCGGGCCCGGGCGGGCCCGT"
  ]
  node [
    id 937
    label "GCGGCTTAAGTCGCGTG--CACCTGGATCCAGATGGGCCCAT"
  ]
  node [
    id 938
    label "GCGAACGCGTTCGCGCTTGAGCTCGGATCCGAGCGGGCCCGT"
  ]
  node [
    id 939
    label "GTGGGCGCGTCCACGTTCGAGCTCAGATCTGAGTGGGCCCAC"
  ]
  node [
    id 940
    label "GCGGGAATTCTCGCGCTCGAGCCGAGGTCTCGGCCGGCCGGT"
  ]
  node [
    id 941
    label "GTGGTTTAAGCCACGCTCGAGCCCAGATCTGGGCCGGCCGGT"
  ]
  node [
    id 942
    label "GCGGTG--CGTCGCGCC--GGCGTGGATCCACGCGGGCCCGT"
  ]
  node [
    id 943
    label "GCGGCTATAGCCGCGTTCGAACCGGGTACCCGGAGGGCCCTC"
  ]
  node [
    id 944
    label "GCCGCCTAGGTGGTGCTCGAGCCCTGATCAGGCCTGGCCAGG"
  ]
  node [
    id 945
    label "GCCGTGATCACGGCGTACGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 946
    label "CAGACCGCGGTCTGGCTCGAGCCCAGATCTGGGCCGGCCGGT"
  ]
  node [
    id 947
    label "GCGTGA--TTACGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 948
    label "GTGGTTGCAGCCACGCTCGAGCCCTGATCAGGGCGGGCCCGC"
  ]
  node [
    id 949
    label "GCGGTCGCGATCGCGCG--CGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 950
    label "GTGGGTGTACCCACGCTCGAGCACGGATCCGTGAGGGCCCTC"
  ]
  node [
    id 951
    label "GCGATCGCGGTCGCGTG--CACCCGGTACCGGGCGGGCCCGT"
  ]
  node [
    id 952
    label "GCGGCTGCAGTCGCGTG--CACCTGGATCCAGGTGGGCCCAC"
  ]
  node [
    id 953
    label "GTGGGTATATTCACGCTCGAGCCTAGATCTAGGTGGGCCCAC"
  ]
  node [
    id 954
    label "GCGAGCGCGTTCGCGCC--GGCGCGGTACCGCGGGGGCCCCT"
  ]
  node [
    id 955
    label "GCTGTGATCACGGCGTA--TACCTGCGTGCAGCCCGGCCGGG"
  ]
  node [
    id 956
    label "GCGGTCGCGACCGCGTG--CACGCGGGCCCGTGCGGGCCCGT"
  ]
  node [
    id 957
    label "GTGACTGCAGTCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 958
    label "GTGGGCGCGCTCACGCTCGAGTCTGGGCCCAGGCGGGCCCGT"
  ]
  node [
    id 959
    label "GTGGGTGTACCCACGCTCGAGCACGGATCCGTGAGGGCCCTT"
  ]
  node [
    id 960
    label "GTGGGTATACCCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 961
    label "GCTGTGATCATGGCGTA--TATCTGTGCGCAGCTCCGCGGAG"
  ]
  node [
    id 962
    label "GTGGGCGCGCTCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 963
    label "GTGGAG--CTCCACGCTCGAGCTCGGATCCGAGAGGGCCCTT"
  ]
  node [
    id 964
    label "GTGGGCATGTTCACGTTCGAGCCCAGATCTGGAAGGGCCCTT"
  ]
  node [
    id 965
    label "GCCGTGATCACGGCGTATGTACCTGCGCGCAGCTCAGCTGAG"
  ]
  node [
    id 966
    label "GCTGGATATTCAGCGCTTGAGCTGGCGCGCCAGCGGGCCCGC"
  ]
  node [
    id 967
    label "GTGGCTATAGCCACGCTCGAGCCCTGATCAGGGCGGGCCCGC"
  ]
  node [
    id 968
    label "GAGGGCGCGCTCTCGCTCGAGCCAGGGCCCTGGCGGGCCCGC"
  ]
  node [
    id 969
    label "GTGGGTGCACTCACGCTCGAGCCTAGGCCTGGGAGGGCCCTT"
  ]
  node [
    id 970
    label "GTGGGTGCACTCACGCTCGAGCCCAGGCCTGGGTGGGCCCAT"
  ]
  node [
    id 971
    label "GAGGCCGCGGCCTCGCTCGAGCCCGGGCCCGGGCGGGCCCGT"
  ]
  node [
    id 972
    label "GAGGTG--CACCTCGCTCGAGCCTAGATCTAGGTGGGCCCAT"
  ]
  node [
    id 973
    label "GCCTGCGCGCGGGTGTATGTACATAGTACTATTTTGGCCAAG"
  ]
  node [
    id 974
    label "GGGCCAGCTGGCTCGCG--CGCTCTGATCAGACTAGGCCTGG"
  ]
  node [
    id 975
    label "GTGGATGCATTCACGCTCGAGCCCAGGCCTGGGGGGGCCCCT"
  ]
  node [
    id 976
    label "GCCGCCTAGGCGGTGCTCGAGCCTAGATCTAGCCCGGCTGGG"
  ]
  node [
    id 977
    label "GCGGCCATGGCCGCGCTCGAGCCAAGATCTTGGCGGGCCCGT"
  ]
  node [
    id 978
    label "GCCGTGATCACGGCGTATGTATCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 979
    label "GTGGGTATATCCACGCTCGAGTCCAGGCCTGGATCGGCCGAT"
  ]
  node [
    id 980
    label "GTGGCTGCAGCCACGTTCGAGCCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 981
    label "GTGAATGCGTTCACGTTCGAGCCCAGTACTGGGTGGGCCCAT"
  ]
  node [
    id 982
    label "GTGGCTGCAGCCACGCTCGAGTCAGGATCCTGGCGGGCCCGT"
  ]
  node [
    id 983
    label "GTGGCTATAGCCACGTG--CACCATGATCATGGTGGGCCCAC"
  ]
  node [
    id 984
    label "GCGGTTGCAGCCGCGCG--CGCCCGGATCCGGGAGGGCCCTT"
  ]
  node [
    id 985
    label "GTGGCTGCAGCCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 986
    label "GCCGCCGCGGTGGTGCTCGAGCCTAGATCTAGCCCCGCGGGG"
  ]
  node [
    id 987
    label "GTGGTTGCAATCACGCTCGAGCTCAGATCTGAGGGGGCCCCT"
  ]
  node [
    id 988
    label "GCTGTGATCACGGCGTATGTACCTGCGCGCAGCTCGGCCGAG"
  ]
  node [
    id 989
    label "GTGTCTGCGGACACGTC--GACCTAGCGCTAGGCGGGCCCGT"
  ]
  node [
    id 990
    label "CCGTGA--TCATGGGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 991
    label "GTGGCTGCAGCCACGCTCGAGCCTGGATCCAGGCGGGCCCGT"
  ]
  node [
    id 992
    label "GTGATTGCAATCACGCTCGAGCCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 993
    label "GTGGCTATAGCCACGCTCGAGTCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 994
    label "GCGATTGCAGTCGCGTG--CACCCGGCGCCGGGTGGGCCCAT"
  ]
  node [
    id 995
    label "GTGGATGCATCCACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 996
    label "GCGGATGCATTCGCGCC--GGCGTGGATCCACGCGGGCCCGT"
  ]
  node [
    id 997
    label "GCGGATGCGTTTGCGCC--GGCGTGGATCCACGCGGGCCCGT"
  ]
  node [
    id 998
    label "GCCAGGGCCCTGGCGGG--CCTAGGGATCCCTCCGGGCTCGG"
  ]
  node [
    id 999
    label "GCGGTCGCGATCGCGCG--CGCTCGGATCCGAGTGGGCCCAT"
  ]
  node [
    id 1000
    label "GTGGGTGCACTCACGCTCGAGCCTGGATCCAGGTGGGCCCAT"
  ]
  node [
    id 1001
    label "GCGGGCGCGCTCGCGCC--GGCGTGGCGCCGCGGGGGCCCCT"
  ]
  node [
    id 1002
    label "GCCGTA--TACGGCGTCTGGACCTACGCGTAGCCAGGCCTGG"
  ]
  node [
    id 1003
    label "GGGCAG--CTGCTTGTG--TGCTCTGATCAGACTAGGCCTAG"
  ]
  node [
    id 1004
    label "GTGGGTGCACCCACGCTCGAGCTCAGGCCTGAGTGGGCCCAT"
  ]
  node [
    id 1005
    label "GTGTGA--TCACACGTATGTACCTGCGCGCAGCCCGGCCGGG"
  ]
  node [
    id 1006
    label "GTGGCTGCAGCCACGCTCGAGCTCTGTACAGAGTGGGCCCAT"
  ]
  node [
    id 1007
    label "GTGGGTATACTCACGCTCGAGCTCGGATCCGAGCGGGCCCGT"
  ]
  node [
    id 1008
    label "GTAGCTATAGTTACGCTCGAGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 1009
    label "GTGGATGCATTCACGCTCGAGCCCAGATCTGGGTGGGCCCAT"
  ]
  node [
    id 1010
    label "GTGGAAGCTTCCACGTTCGAGCTCAGGCCTGAGCGGGCCCGT"
  ]
  node [
    id 1011
    label "GCCGTGATCATGGCGTATGTACCTGCGCGCAGCTCGGCCGGG"
  ]
  node [
    id 1012
    label "GCCGGGGCCCCGGCAGGTACCTGGGGCGCCCTCCGGGCCCGG"
  ]
  node [
    id 1013
    label "GGGCCAGCTGGCTCGCG--TGCTCTGATCAGACTAGGCCTGG"
  ]
  node [
    id 1014
    label "GCGGCTGCAGTCGCGCG--CGCCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 1015
    label "GTGACTGCAGTCACGCTCGAGTCCGGATCCGGGTGGGCCCAT"
  ]
  node [
    id 1016
    label "GCGGTTGCAGTCGCGCTCGAGCCCGGATCCGGGAGGGCCCTT"
  ]
  node [
    id 1017
    label "GTGGGTGCACTCACGTTCGAGCTCAGGCCTGAGCGGGCCCGT"
  ]
  edge [
    source 0
    target 13
  ]
  edge [
    source 7
    target 397
  ]
  edge [
    source 9
    target 663
  ]
  edge [
    source 12
    target 595
  ]
  edge [
    source 14
    target 612
  ]
  edge [
    source 16
    target 316
  ]
  edge [
    source 21
    target 491
  ]
  edge [
    source 24
    target 525
  ]
  edge [
    source 24
    target 736
  ]
  edge [
    source 29
    target 382
  ]
  edge [
    source 36
    target 992
  ]
  edge [
    source 36
    target 712
  ]
  edge [
    source 42
    target 619
  ]
  edge [
    source 43
    target 696
  ]
  edge [
    source 43
    target 919
  ]
  edge [
    source 43
    target 1014
  ]
  edge [
    source 43
    target 467
  ]
  edge [
    source 47
    target 366
  ]
  edge [
    source 49
    target 562
  ]
  edge [
    source 49
    target 444
  ]
  edge [
    source 52
    target 742
  ]
  edge [
    source 57
    target 300
  ]
  edge [
    source 59
    target 611
  ]
  edge [
    source 65
    target 930
  ]
  edge [
    source 70
    target 327
  ]
  edge [
    source 70
    target 592
  ]
  edge [
    source 71
    target 258
  ]
  edge [
    source 81
    target 234
  ]
  edge [
    source 83
    target 260
  ]
  edge [
    source 84
    target 572
  ]
  edge [
    source 88
    target 206
  ]
  edge [
    source 88
    target 202
  ]
  edge [
    source 95
    target 793
  ]
  edge [
    source 97
    target 619
  ]
  edge [
    source 101
    target 696
  ]
  edge [
    source 101
    target 1014
  ]
  edge [
    source 105
    target 853
  ]
  edge [
    source 105
    target 878
  ]
  edge [
    source 105
    target 676
  ]
  edge [
    source 107
    target 369
  ]
  edge [
    source 107
    target 957
  ]
  edge [
    source 111
    target 1004
  ]
  edge [
    source 111
    target 595
  ]
  edge [
    source 114
    target 414
  ]
  edge [
    source 117
    target 668
  ]
  edge [
    source 120
    target 679
  ]
  edge [
    source 122
    target 379
  ]
  edge [
    source 129
    target 445
  ]
  edge [
    source 132
    target 315
  ]
  edge [
    source 136
    target 411
  ]
  edge [
    source 139
    target 583
  ]
  edge [
    source 139
    target 157
  ]
  edge [
    source 140
    target 427
  ]
  edge [
    source 140
    target 649
  ]
  edge [
    source 141
    target 835
  ]
  edge [
    source 142
    target 745
  ]
  edge [
    source 150
    target 476
  ]
  edge [
    source 151
    target 451
  ]
  edge [
    source 159
    target 625
  ]
  edge [
    source 160
    target 352
  ]
  edge [
    source 160
    target 379
  ]
  edge [
    source 165
    target 1014
  ]
  edge [
    source 165
    target 467
  ]
  edge [
    source 166
    target 796
  ]
  edge [
    source 172
    target 705
  ]
  edge [
    source 180
    target 782
  ]
  edge [
    source 180
    target 560
  ]
  edge [
    source 183
    target 343
  ]
  edge [
    source 185
    target 923
  ]
  edge [
    source 190
    target 451
  ]
  edge [
    source 195
    target 327
  ]
  edge [
    source 195
    target 705
  ]
  edge [
    source 195
    target 517
  ]
  edge [
    source 196
    target 366
  ]
  edge [
    source 196
    target 206
  ]
  edge [
    source 201
    target 676
  ]
  edge [
    source 202
    target 291
  ]
  edge [
    source 204
    target 644
  ]
  edge [
    source 204
    target 774
  ]
  edge [
    source 204
    target 516
  ]
  edge [
    source 206
    target 564
  ]
  edge [
    source 206
    target 530
  ]
  edge [
    source 208
    target 210
  ]
  edge [
    source 208
    target 346
  ]
  edge [
    source 210
    target 886
  ]
  edge [
    source 210
    target 993
  ]
  edge [
    source 211
    target 742
  ]
  edge [
    source 211
    target 697
  ]
  edge [
    source 211
    target 380
  ]
  edge [
    source 215
    target 697
  ]
  edge [
    source 218
    target 442
  ]
  edge [
    source 224
    target 756
  ]
  edge [
    source 225
    target 413
  ]
  edge [
    source 225
    target 889
  ]
  edge [
    source 227
    target 312
  ]
  edge [
    source 230
    target 909
  ]
  edge [
    source 231
    target 701
  ]
  edge [
    source 237
    target 692
  ]
  edge [
    source 240
    target 799
  ]
  edge [
    source 241
    target 927
  ]
  edge [
    source 242
    target 426
  ]
  edge [
    source 244
    target 410
  ]
  edge [
    source 246
    target 683
  ]
  edge [
    source 249
    target 528
  ]
  edge [
    source 249
    target 272
  ]
  edge [
    source 254
    target 319
  ]
  edge [
    source 255
    target 736
  ]
  edge [
    source 260
    target 594
  ]
  edge [
    source 267
    target 524
  ]
  edge [
    source 269
    target 357
  ]
  edge [
    source 269
    target 985
  ]
  edge [
    source 270
    target 279
  ]
  edge [
    source 271
    target 922
  ]
  edge [
    source 271
    target 661
  ]
  edge [
    source 271
    target 935
  ]
  edge [
    source 271
    target 866
  ]
  edge [
    source 271
    target 945
  ]
  edge [
    source 271
    target 604
  ]
  edge [
    source 271
    target 559
  ]
  edge [
    source 271
    target 771
  ]
  edge [
    source 271
    target 705
  ]
  edge [
    source 271
    target 517
  ]
  edge [
    source 271
    target 756
  ]
  edge [
    source 271
    target 930
  ]
  edge [
    source 271
    target 581
  ]
  edge [
    source 271
    target 459
  ]
  edge [
    source 276
    target 342
  ]
  edge [
    source 276
    target 413
  ]
  edge [
    source 276
    target 988
  ]
  edge [
    source 277
    target 302
  ]
  edge [
    source 281
    target 842
  ]
  edge [
    source 286
    target 450
  ]
  edge [
    source 289
    target 846
  ]
  edge [
    source 290
    target 594
  ]
  edge [
    source 293
    target 513
  ]
  edge [
    source 294
    target 589
  ]
  edge [
    source 295
    target 708
  ]
  edge [
    source 297
    target 1001
  ]
  edge [
    source 304
    target 355
  ]
  edge [
    source 306
    target 876
  ]
  edge [
    source 306
    target 901
  ]
  edge [
    source 309
    target 729
  ]
  edge [
    source 317
    target 451
  ]
  edge [
    source 319
    target 980
  ]
  edge [
    source 320
    target 425
  ]
  edge [
    source 322
    target 391
  ]
  edge [
    source 342
    target 503
  ]
  edge [
    source 352
    target 559
  ]
  edge [
    source 352
    target 661
  ]
  edge [
    source 354
    target 588
  ]
  edge [
    source 360
    target 899
  ]
  edge [
    source 362
    target 841
  ]
  edge [
    source 366
    target 564
  ]
  edge [
    source 366
    target 923
  ]
  edge [
    source 366
    target 555
  ]
  edge [
    source 368
    target 947
  ]
  edge [
    source 369
    target 1015
  ]
  edge [
    source 370
    target 995
  ]
  edge [
    source 372
    target 766
  ]
  edge [
    source 372
    target 415
  ]
  edge [
    source 375
    target 486
  ]
  edge [
    source 379
    target 546
  ]
  edge [
    source 379
    target 559
  ]
  edge [
    source 379
    target 608
  ]
  edge [
    source 379
    target 689
  ]
  edge [
    source 387
    target 451
  ]
  edge [
    source 387
    target 916
  ]
  edge [
    source 391
    target 861
  ]
  edge [
    source 396
    target 744
  ]
  edge [
    source 404
    target 931
  ]
  edge [
    source 410
    target 650
  ]
  edge [
    source 413
    target 451
  ]
  edge [
    source 413
    target 1011
  ]
  edge [
    source 424
    target 722
  ]
  edge [
    source 424
    target 454
  ]
  edge [
    source 427
    target 814
  ]
  edge [
    source 433
    target 797
  ]
  edge [
    source 434
    target 699
  ]
  edge [
    source 436
    target 680
  ]
  edge [
    source 437
    target 755
  ]
  edge [
    source 437
    target 723
  ]
  edge [
    source 438
    target 938
  ]
  edge [
    source 441
    target 442
  ]
  edge [
    source 444
    target 447
  ]
  edge [
    source 445
    target 817
  ]
  edge [
    source 451
    target 978
  ]
  edge [
    source 451
    target 922
  ]
  edge [
    source 451
    target 988
  ]
  edge [
    source 451
    target 574
  ]
  edge [
    source 451
    target 480
  ]
  edge [
    source 451
    target 533
  ]
  edge [
    source 451
    target 656
  ]
  edge [
    source 466
    target 491
  ]
  edge [
    source 475
    target 521
  ]
  edge [
    source 475
    target 485
  ]
  edge [
    source 484
    target 541
  ]
  edge [
    source 485
    target 719
  ]
  edge [
    source 488
    target 512
  ]
  edge [
    source 503
    target 988
  ]
  edge [
    source 512
    target 988
  ]
  edge [
    source 516
    target 635
  ]
  edge [
    source 517
    target 701
  ]
  edge [
    source 519
    target 961
  ]
  edge [
    source 527
    target 534
  ]
  edge [
    source 529
    target 720
  ]
  edge [
    source 531
    target 875
  ]
  edge [
    source 542
    target 890
  ]
  edge [
    source 551
    target 916
  ]
  edge [
    source 557
    target 744
  ]
  edge [
    source 559
    target 630
  ]
  edge [
    source 559
    target 901
  ]
  edge [
    source 560
    target 795
  ]
  edge [
    source 570
    target 886
  ]
  edge [
    source 570
    target 993
  ]
  edge [
    source 581
    target 839
  ]
  edge [
    source 584
    target 753
  ]
  edge [
    source 587
    target 988
  ]
  edge [
    source 591
    target 705
  ]
  edge [
    source 595
    target 715
  ]
  edge [
    source 600
    target 883
  ]
  edge [
    source 609
    target 635
  ]
  edge [
    source 611
    target 962
  ]
  edge [
    source 616
    target 811
  ]
  edge [
    source 619
    target 925
  ]
  edge [
    source 619
    target 996
  ]
  edge [
    source 619
    target 997
  ]
  edge [
    source 631
    target 998
  ]
  edge [
    source 634
    target 678
  ]
  edge [
    source 644
    target 827
  ]
  edge [
    source 648
    target 722
  ]
  edge [
    source 651
    target 920
  ]
  edge [
    source 652
    target 981
  ]
  edge [
    source 660
    target 995
  ]
  edge [
    source 661
    target 809
  ]
  edge [
    source 661
    target 673
  ]
  edge [
    source 675
    target 688
  ]
  edge [
    source 684
    target 855
  ]
  edge [
    source 691
    target 784
  ]
  edge [
    source 693
    target 1001
  ]
  edge [
    source 699
    target 1009
  ]
  edge [
    source 701
    target 748
  ]
  edge [
    source 705
    target 860
  ]
  edge [
    source 715
    target 1004
  ]
  edge [
    source 720
    target 798
  ]
  edge [
    source 737
    target 915
  ]
  edge [
    source 751
    target 769
  ]
  edge [
    source 767
    target 857
  ]
  edge [
    source 771
    target 860
  ]
  edge [
    source 771
    target 901
  ]
  edge [
    source 771
    target 1011
  ]
  edge [
    source 771
    target 839
  ]
  edge [
    source 771
    target 809
  ]
  edge [
    source 771
    target 828
  ]
  edge [
    source 782
    target 795
  ]
  edge [
    source 783
    target 979
  ]
  edge [
    source 795
    target 893
  ]
  edge [
    source 808
    target 897
  ]
  edge [
    source 838
    target 858
  ]
  edge [
    source 853
    target 855
  ]
  edge [
    source 885
    target 958
  ]
  edge [
    source 891
    target 904
  ]
  edge [
    source 922
    target 1011
  ]
  edge [
    source 950
    target 959
  ]
  edge [
    source 957
    target 1015
  ]
  edge [
    source 974
    target 1013
  ]
]
