graph [
  node [
    id 0
    label "GGTCCTGCGGGGTCGCGCGCGCTCTGTACAGAGCGTGCACGT"
  ]
  node [
    id 1
    label "GACTTTGCAGGGTCGCACGTGTTTTGATCAGAGTGTGCACAC"
  ]
  node [
    id 2
    label "AGGCCAGCTGGCCTGCTCGAGCTCGGATCCGAGGGGGCCCTC"
  ]
  node [
    id 3
    label "TCCCTGATCAGGGAGTCCGGACCCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 4
    label "AGGGGTGCACCCCTGCTCGAGCCCGGTACCGGACGGGCCTGT"
  ]
  node [
    id 5
    label "TCCCTG--CAGGGAGTCCGGACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 6
    label "GGCCCCTAGGGGTCACTCGAGTTGAGATCTCAAAGTGCACTT"
  ]
  node [
    id 7
    label "AGGGGCGCGCCCCTGCTCGAGCTCGGTACCGACTCGGCCGAG"
  ]
  node [
    id 8
    label "GGGTCCTAGGGCCCGCTCGAGCTCGGTACCGAGTAGGCCTGC"
  ]
  node [
    id 9
    label "TCCTTGGTCAGGGAGTCCGGATCATGCGCATGCTGGGCCCAG"
  ]
  node [
    id 10
    label "GACTCGTACGGGTCGCGCGCGCTTCGATCGAAGGGTGCACTC"
  ]
  node [
    id 11
    label "AGGGGTGCACCCCTGTTCGAACGCGGTACCGCGTGGGCCTGC"
  ]
  node [
    id 12
    label "AAGAGCATGCTCTTGCT--AGCTCGGTACCGAGAAGGCCTTC"
  ]
  node [
    id 13
    label "TCCTGG--TCAGGAGTCCGGACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 14
    label "AGGGGTATGCCCCTGCTCGAGCACGGTACCGTGTGAGCTTAC"
  ]
  node [
    id 15
    label "ACGCCAGCTGGCGTGCTCGAGTGTGGTACCATGTGGGCCTAC"
  ]
  node [
    id 16
    label "GCGTCGTACGGCGCGTTCGAACCAGGTACCTGGGGGGCCTCC"
  ]
  node [
    id 17
    label "AGGGGATATCCCCTGTTTGAACGCGGTACCGTGCGGGCCTGC"
  ]
  node [
    id 18
    label "TCCCTGGCCAGGGAGTCCGGACCCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 19
    label "AGGTCCGCGGGCCTGCTCGAGCCTGGTACCAGGCAAGCTTGC"
  ]
  node [
    id 20
    label "TCCCTGGTCAGGGAGTCCGGATCTGGCGCCAGCTGGGCCTGG"
  ]
  node [
    id 21
    label "AGGGTAGCTACCCTGCGCGCGCGCGGTACCGCGCAGGCCTGT"
  ]
  node [
    id 22
    label "GCGTCCTAGGGCGCGTTCGAACTCGGTACCGAAGGGGCCTCT"
  ]
  node [
    id 23
    label "AGGCCAGCTGGCCTGCCCGGGCCCGGATCCGGGGGGGCCCTC"
  ]
  node [
    id 24
    label "AGGCCTATGGGCCTGCTCGAGCTCGGTACCGAGTAGGCCTAC"
  ]
  node [
    id 25
    label "GCGGACTAGTCCGCGTTCGAGCCTGGTACCAGGGGAGCTCTC"
  ]
  node [
    id 26
    label "AGGGCACGTGCCCTGCGCGCGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 27
    label "TCCCTGGTTGGGGAGTC--GACCTTGCGCAAGTCAGGCCTGG"
  ]
  node [
    id 28
    label "AGGAGTGCGCTCCTGCTCGAGTCCGGTACCGGGCGGGCCTGT"
  ]
  node [
    id 29
    label "GACTTCGCGAGGTCGCGCGTGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 30
    label "GACCTG--CGGGTCGTG--CATTTTGATCAGGGTGTGCACAT"
  ]
  node [
    id 31
    label "AGGGGTGCACCCCTGTTCGAACTCGGATCCGAGCGGGCCTGT"
  ]
  node [
    id 32
    label "CGGGGTGCGCCCCGGCGCGCGCCCGGTACCGGGTCGGCCGGC"
  ]
  node [
    id 33
    label "ACGCCAGCTGGCGTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 34
    label "AGGCCAGCTGGCCTGTTCGAGCTCGGTACCGAGTAGGCCTAT"
  ]
  node [
    id 35
    label "GTACCCGCGGGTACGCTCGAGCCCGGTACCGGGGGGGCCCCC"
  ]
  node [
    id 36
    label "AGGGACGCGTCCCTGTTCGAGCCCGGTACCGGGGGGGCCCTT"
  ]
  node [
    id 37
    label "ACGGGTGCGCCCGTGCTCGAGCGCCGTGCGGCGGGGGCCCTC"
  ]
  node [
    id 38
    label "GGGTCAGCTGGCCTGCTCGAGCTCGGTACCGAGAAGGCCTTC"
  ]
  node [
    id 39
    label "AGGGGTGCACCCCTGTTCGAACGTGGTACCACGTGGGCCTGC"
  ]
  node [
    id 40
    label "AGGGGAGCTCCCCTGTTCGAACTCGGTACCGGGCGGGCCTGT"
  ]
  node [
    id 41
    label "GGCTCT--AGAGCTGTTCGAACTGGGTACCCAGTAGGCCTAC"
  ]
  node [
    id 42
    label "GACCTTGCAGGGTCGCGCGCGCTCTGATCAGAGTGTGCACGT"
  ]
  node [
    id 43
    label "GGACCTGCAGGTTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 44
    label "GGGAGCGCGCTCCTGCTCGAGCTCAGTACTGAATGGGCCTGT"
  ]
  node [
    id 45
    label "AGGGGTATGCCCCTGCTCGAGTGCGGTACCGTGCGGGCCTGC"
  ]
  node [
    id 46
    label "GACCTTGCAGGGTCGCGCGCGCTCTGATCAGAGCGTGCATGT"
  ]
  node [
    id 47
    label "AGGGGTGCACCCCTGTTCGAACGTGGTACCACGTGGGCCTGT"
  ]
  node [
    id 48
    label "AGGCCAATTGGCCTGCTCGAGCCTGGTACCAGGGGGGCCCTC"
  ]
  node [
    id 49
    label "GGATCCTAGGGTTCGCGCGCGCTTCGATCGAAATCCGCGGGT"
  ]
  node [
    id 50
    label "TCCCTGGTCAGGGAGTC--GACCTTGTGCAGGCCAGGCCTGG"
  ]
  node [
    id 51
    label "TCCCTGGTCGGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 52
    label "TCCCTGGTCAGGGAGTC--GATCTTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 53
    label "AGGGGTATGCCCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 54
    label "AGGTCAGCTGACCTGTTCGAACACAGTACTGTGGGGGCCCTC"
  ]
  node [
    id 55
    label "ACGCCCGCGGGCGTGCTCGAGCGCGGTATCGTGGGGGCCCTC"
  ]
  node [
    id 56
    label "AGGAGTGCACTCCTGCTCGAGCTCGGTACCGAGCGGGCCTGC"
  ]
  node [
    id 57
    label "AGGCTTTAAAGCCTGTGTACACACAGTACTGTGCGGGCCTGC"
  ]
  node [
    id 58
    label "TCCCTGGTCAGGGAGTC--GACCTGCGCGCAGCCAGGCCTGG"
  ]
  node [
    id 59
    label "ACGTCCTAGGACGTGTTCGAACTCGGTACCGAAGGGGCCTCT"
  ]
  node [
    id 60
    label "GCCTGG--TTGGGCGCT--AGCTCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 61
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCCGGGCCCGG"
  ]
  node [
    id 62
    label "AGGCCAGCTGGCCTGCTCGAGTGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 63
    label "ATGCCGGTCGGCATGTGTACATATGGATCCATCTGGGCCTAG"
  ]
  node [
    id 64
    label "AGGGGTATACCCCTGTTTAAACAAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 65
    label "ACGGGCGCGCCCGTGCTCGAGCCTGGTACCAGGGGAGCTCTC"
  ]
  node [
    id 66
    label "TCCTGG--TCAGGAGTC--GACCCTGCGCAGGCCAGGTCTGG"
  ]
  node [
    id 67
    label "TCCTTGGTCAGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 68
    label "AGGCCAGCTGGCCTGCTCGAGCGCGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 69
    label "ACGGGTTAACCCGTGCTCGAGCCTGGTACCAGGGGAGCTCTC"
  ]
  node [
    id 70
    label "GCAGGGATCCCTGCGTGTACACTCGGATCCGACTAGGCCTAG"
  ]
  node [
    id 71
    label "TCCTTGGTCAGGGAGTC--GACCTTCATGAAGCTGGGCCTGG"
  ]
  node [
    id 72
    label "GGACCG--CGGTTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 73
    label "ACGGGCATGCCCGTGTTTGAACACGGTACCGTCTGGGCCTGG"
  ]
  node [
    id 74
    label "TCCCTGGTTGGGGAGTC--GATCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 75
    label "AGGAGTGCACTCCTGTTCGAACTCGGTACCGAGTGGGCCTGC"
  ]
  node [
    id 76
    label "AGGGGCATGCCCCTGTTTAAACAAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 77
    label "AGGGGTATGCCCCTGCTCGAGCACGGTACCGTGAGGGCCTTC"
  ]
  node [
    id 78
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 79
    label "TCCCTGGTTGGGGAGTCCGGACCTTGCGCAAGCTGGGCCTGG"
  ]
  node [
    id 80
    label "ACGCTCTGGAGCGTGTTCGAACCGGGTACCCGGTAGGCCTAC"
  ]
  node [
    id 81
    label "GCGTCCTAGGGCGCGTTCGAACTCGGTACCGGGGGGGCCTCC"
  ]
  node [
    id 82
    label "AGGGCAGCTGCCCTGCTCGAGTCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 83
    label "ATGCGCGCGCGTATGCTCGAGCGCGGTACCGCGTTGGCCAAC"
  ]
  node [
    id 84
    label "TTCTGG--TCAGGGGTCCGGACCTTGCGCAAGTCAGGCCTGA"
  ]
  node [
    id 85
    label "AGGCCAGCTGGCCTGCTCGAGCACGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 86
    label "AGGGGCGCGCCCTTGTTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 87
    label "AGGGGTATACCCCTGTTCGAACCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 88
    label "AGGGGTGCACCCCTGTTCGAGCCCGGTACCGGGGGAGCTCCC"
  ]
  node [
    id 89
    label "TCCCTGGTCGGGGAGTC--GACCTGCATGCAGCCAGGCCTGG"
  ]
  node [
    id 90
    label "ACGGGCATGCCCGTGTTTGAACAAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 91
    label "GGGCCCGCGGGCCCGCTCGAGCGCGGGCCCGTGGGGGCCCTC"
  ]
  node [
    id 92
    label "AGGCGTATGCGCCTGCTCGAGCGCGGTACCGCGTGGGCCTAC"
  ]
  node [
    id 93
    label "AGAGGTATACCTCTGTTCGAACTCGGTACCGAACGAGCTTGT"
  ]
  node [
    id 94
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCTGGGCCCAG"
  ]
  node [
    id 95
    label "AGGGCAGCTGCCCTGCTCGAGCACGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 96
    label "TCCCTG--TAGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 97
    label "GGCCCTGCAGGGTCGCGCGCGTTCTGATCAGAGTGTGCACAT"
  ]
  node [
    id 98
    label "GCCGGGGCCCCGGCGCC--GGCCGGGCGCCTGAGGGGCCCCT"
  ]
  node [
    id 99
    label "TCCCTGGCCGGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 100
    label "AGGGGTGCACCCCTGTTCGAACAGGGTACCTTGCGGGCCTGT"
  ]
  node [
    id 101
    label "AGGAGTGCACTCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 102
    label "TCCTGG--TCAGGAGCT--AGTTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 103
    label "AGGTCCGCGGGCCTGCTCGAGCCCGCATGCGGGAAGGCCTTC"
  ]
  node [
    id 104
    label "AGGGCACGTGCCCTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 105
    label "ACGGGTGCACCCGTGCTCGAGCTTGGTACCAAGTGAGCTTAC"
  ]
  node [
    id 106
    label "GGCCTTGCAGGGTCGCGCGCGCTCTGATCAGAACGTGCACGT"
  ]
  node [
    id 107
    label "GCGTCCTAGGGCGCGTTCGAACCAGGTACCTGGAGGGCCTTC"
  ]
  node [
    id 108
    label "AGGGATATATCCCTGTATGTACACGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 109
    label "AGGCCAGCTGGCCTGCTCGAGCCCTGTACAGGGTGGGCCTGC"
  ]
  node [
    id 110
    label "GACTCTGCAGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 111
    label "GACCTCGCGGGGTCGTGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 112
    label "AGGTCAGCTGACCTGCTCGAGCCCAGATCTGGGGGGGCCCTC"
  ]
  node [
    id 113
    label "AGGGACATGTCCCTGTTCGAACACGGTACCGTGCGGGCCTGC"
  ]
  node [
    id 114
    label "TCTCTGGTCAGGGAGTCCGGACCTGTGTGCAGCCAGGCCTGG"
  ]
  node [
    id 115
    label "GTGGTG--TATCGCGCTCGAGCCCTGCGCAGGCTGGGCCCAG"
  ]
  node [
    id 116
    label "GACTCTGCAGGGTCGCGCGCGCTCTGATCAGAGTGTGCACGT"
  ]
  node [
    id 117
    label "TCCCTGGTCAGGGAGTC--GACCTGTGTGCAGCCGGGCCTGG"
  ]
  node [
    id 118
    label "AGGGCCGCGGCCCTGCTCGAGCGGAGTGCTCCGCGGGCCTGC"
  ]
  node [
    id 119
    label "TCCCTGATCAGGGAGTC--GATCTTGCGCAAGCCAGGCCTGG"
  ]
  node [
    id 120
    label "GACTCTGCAGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGC"
  ]
  node [
    id 121
    label "AGGCCAGCTGGCCTGCTCGAGCGCGGTACCGTGGGGGCCTCC"
  ]
  node [
    id 122
    label "GGGAGCGCGCTCCTGGTTAACCCTGGTACCAGGAAGGCCTTC"
  ]
  node [
    id 123
    label "GACCTCGCGAGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 124
    label "AGGGGTGCACCCCTGCTCGAGCGCGGATCCGCGGGAGCTCTC"
  ]
  node [
    id 125
    label "AGGCGTATACGCCTGCTCGAGCCCGGATCCGGGGGAGCTCTC"
  ]
  node [
    id 126
    label "TCCCTGGTCGGGGAGTC--GACCTGTGTGCAGCCGGATCTGG"
  ]
  node [
    id 127
    label "TCCTTGGTCAAGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 128
    label "GCCTGG--TCAGGTGCT--AGCTCTGATCAGGGTGAGCTCGC"
  ]
  node [
    id 129
    label "AGGTCCGCGGGCCTGCTCGAGCCTGGTACCGGGCAGGCCTGC"
  ]
  node [
    id 130
    label "TCCCTG--TGGGGAGCT--AGCTCTGCGCAGGCCGGGCCCGG"
  ]
  node [
    id 131
    label "AGGGGATATCCCCTGTCATGACGAAGTACTTTGGGAGCTCTC"
  ]
  node [
    id 132
    label "AGGTCAGCTGGCCTGTTCGAACGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 133
    label "AAGGGTGCACCCTTGCTCGAGCGCGGTATCGTGTTGGCCAAC"
  ]
  node [
    id 134
    label "TCCCTG--TAGGGAGCT--AGCTCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 135
    label "AGGAGTGCACTCCTGTTCGAACTCAGTACTGAATGGGCCTGT"
  ]
  node [
    id 136
    label "GCGCTCTAGGGCGCGTTCGAACCAGGTACCTGGGGGGCCTCC"
  ]
  node [
    id 137
    label "AGGGGTATGCCCCTGTTCGAACTTGGTACCAAGAGGGCCTTC"
  ]
  node [
    id 138
    label "TCCCTGATCAGGGAGTCCGGACCCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 139
    label "GGCCTTGCAGGGTCGCGCGCGCTCTGATCAGAGTGTGCACGT"
  ]
  node [
    id 140
    label "TCCCTGGTCAGGGAGTC--GACTCTGCGTAGGTCAGGCCTGG"
  ]
  node [
    id 141
    label "TCCTGG--TCGGGAGTC--GACCCACCGGTGGTCAGGCCTGG"
  ]
  node [
    id 142
    label "AGGGGCATGCCCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 143
    label "AGGGGTGCGCCCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 144
    label "AGGGGTATGCCCCTGCTCGAGTGTGGTACCATCTGGGCCTAG"
  ]
  node [
    id 145
    label "TCTCTGGTCAGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 146
    label "ACGGATGCGTCCGTGCTCGAGCTCGGTACCGAGTAAGCTTAC"
  ]
  node [
    id 147
    label "TCCCTGGTTAGGGAGTC--GACCCTCATGAGGCCAGGCCTGG"
  ]
  node [
    id 148
    label "AGGTCAGCTGGCCTGCTTGAGCGCGGTATCGCGGGGGCCCTC"
  ]
  node [
    id 149
    label "GGGTCAGCTGACCTGTTCGAGCCCGGTACCGGGCAGGCCTGT"
  ]
  node [
    id 150
    label "ACCTCG--CGAGGTCGC--GCGTCTGATCAGAACGTGCACGT"
  ]
  node [
    id 151
    label "AGGTCAGCTGGCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 152
    label "AGGCCAGCTGGCCTGCTCGAGCCCGGTACCGGGCAGGCCTGC"
  ]
  node [
    id 153
    label "GATTCTGCAGGGTCGTGCGCATTCTGATCAGAGTGTGCACAT"
  ]
  node [
    id 154
    label "AGGGGTTAACCCCTGTATGTACGCAGTACTGCATGGGCCTAT"
  ]
  node [
    id 155
    label "GATCTCGCGGGATCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 156
    label "TCCCTG--CAGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 157
    label "GACCTTGCAGGGTCGCC--GGCTCTGATCAGAATGTGCACAT"
  ]
  node [
    id 158
    label "AGGCCAGCTGGCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 159
    label "AGGGGTATACCCCTGCTCGAGCGCGGTACCGCGTGGGCCTAC"
  ]
  node [
    id 160
    label "TCTTGG--TCAGGAGTCCGGACCTTGCGCAGGCTAGGCCTGG"
  ]
  node [
    id 161
    label "GGGGGTATGCCCCCGCTCGAGTGCGGTACCGTGAGGGCCTTC"
  ]
  node [
    id 162
    label "GACTGCTAGTGGTCGCGCGCGCTTCGATCGAAGGGCGCGCTC"
  ]
  node [
    id 163
    label "AGGAGG--CCTCCTGCTCGAGCCCGGTACCGGGCGGGCCTGT"
  ]
  node [
    id 164
    label "TCCCTGGTCAGGGAGTCCGGACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 165
    label "GACTCG--CGGGTCGCGCGCGCTCTGATCAGAGCATGCGTGT"
  ]
  node [
    id 166
    label "GCCGACATGTCGGTGCTCGAGTCCCGCGCGGGGGGGGCCCTC"
  ]
  node [
    id 167
    label "AGGGGTATACCCCTGTTCGAACGCAGATCTGCGTGGGCCTGT"
  ]
  node [
    id 168
    label "AGGGCACGTGCCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 169
    label "ACGGGCGCGCCCGTGTTCGAATGCGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 170
    label "AGGAGTATACTCCTGTTCGAGCACGGTACCGTCTGGGCCTAG"
  ]
  node [
    id 171
    label "GCCTTG--CAAGGTGCC--GGCTCTGATTAGAGTGTGCACAT"
  ]
  node [
    id 172
    label "ACGCTTATAAGCGTGTGTGCACTAAGTACTTATAAGGCCTTA"
  ]
  node [
    id 173
    label "AGGCTCGCGAGCCTGTGATCACTCCCTAGGGACCGGGCCTGG"
  ]
  node [
    id 174
    label "AGGGCAGCTGCCCTGCGCGCGCGCGGTACCGCGCAGGCCTGT"
  ]
  node [
    id 175
    label "ACGGGCGCGCCCGTGTACGTATGTGGTACCATGGGGGCCCTC"
  ]
  node [
    id 176
    label "TCCCTGGTCAGGGATCT--AGACCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 177
    label "AGGCTAGCTGGCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 178
    label "AGGCCCGCGGGCCTGCTCGAGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 179
    label "AGGAGTGCACTCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 180
    label "TCCCTGGTCAGGGAGTCCGGGCCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 181
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCCAGGTCTGG"
  ]
  node [
    id 182
    label "GGCTTG--CAGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 183
    label "AGGGGCATGCCCCTGTTTGAACGCGGTACCGTGTGGGCCTGC"
  ]
  node [
    id 184
    label "AGGGGTGCACCCCTGTTCGAATTCGGTACCGAGGGAGCTCTT"
  ]
  node [
    id 185
    label "CCCTGG--TCAGGGGTC--GATCTGTGTGCAGCCAGGCCTGG"
  ]
  node [
    id 186
    label "AGGGGTTAGCCCCTGCTCGAGCACGGTACCGTAAGAGCTCTT"
  ]
  node [
    id 187
    label "AGGGGAATTCCCCTGTTCGAGCGCGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 188
    label "GGGAGAGCTCTCCCGTTCGAACTCGGTACCGAGAGGGCCTTT"
  ]
  node [
    id 189
    label "TCCCTGGCTGGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 190
    label "TCCCTGGTCAGGGAGTC--GACCTGTGTGCAGCCAGGCCTGG"
  ]
  node [
    id 191
    label "GGGGCACGTGCCCCGCTCGAGCCGGGATTCCGGGGGGCCTCC"
  ]
  node [
    id 192
    label "GCGCTCTAGAGCGTGTTCGAACTGGGTACCCAGTAGGCCTAC"
  ]
  node [
    id 193
    label "GTGCCCGCGGGTACGCTCGAGCCCGGTACCGGGGGGGCCCCC"
  ]
  node [
    id 194
    label "ACGGGTTAACCCGTGCTCGAGCCTGGTACCAGGAGGGCCTTC"
  ]
  node [
    id 195
    label "AGGGGAGCTCCCCTGCTCGAGCTCGGTACCGAGGGGGCCTCT"
  ]
  node [
    id 196
    label "GTAGGTATACCTATGTGTACATATAGTACTATGTAGGCCTAC"
  ]
  node [
    id 197
    label "AGGTCAGCTGGCCTGTTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 198
    label "TCCTGG--TCAGGAGTC--GACCTGTGTGCAGCCAGGCCTGG"
  ]
  node [
    id 199
    label "GACCTCGCGAGGTCGGC--GCCTCTGATCAGAACGTGCACGT"
  ]
  node [
    id 200
    label "AGGTCCGCGGGCCTGCTCGAGCCCGGATCCGGGCAGGCCTGC"
  ]
  node [
    id 201
    label "AGGGATATATCCCTGTATGTACGCGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 202
    label "TTTTGAATTCAAAAGCTCGAGCATTGGCCAATACGGGCCTGT"
  ]
  node [
    id 203
    label "AGGGGCATGCCCCTGTTCGAATGCGGTACCGTGGGCGCGCTC"
  ]
  node [
    id 204
    label "AGGTCAGCTGGCCTGCTCGAGCTCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 205
    label "GACTCTGCAGGGTCGCGCGCGCTCTGATCAGAGTGTGCATGT"
  ]
  node [
    id 206
    label "AGGGGTATGCCCCTGCTCGAGCACGGTACCGTGCGGGCCTGC"
  ]
  node [
    id 207
    label "AGGAGTGCACTCCTGCTCGAGCTCAGTACTGAATGGGCCTAT"
  ]
  node [
    id 208
    label "TCCCTGGTCAGGGAGTCCGGATTTTGCGCAGACCAGGCCTGG"
  ]
  node [
    id 209
    label "TCCCTG--CAGGGAGTC--GACCTTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 210
    label "GACCTTGCGAGGTCGCGCGCGCTCTGATCAGAGCATGCATGT"
  ]
  node [
    id 211
    label "AGGCGATATCGCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 212
    label "AGGGGCGCGCCCCTGCTCGAGTGCGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 213
    label "AGGGGTGCGCCCCTGCTCGAGCACGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 214
    label "GCGTCGTACGACGCGTTCGAACCAGGTACCTGGGGGGCCTCC"
  ]
  node [
    id 215
    label "TCCCTGGTCAGGGAGTC--GACCTGCGCGCAGCCGGGCCTGG"
  ]
  node [
    id 216
    label "GACTTG--CAGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 217
    label "TCCCTGGTTGGGGAGTCCGGACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 218
    label "GGCCTCGCGGGGTCGCGCGCGCTACGATCGTAATCCGCGGGT"
  ]
  node [
    id 219
    label "GCGCTCTAGAGCGTGTTCGAACCGGGTACCCGGTAGGCCTAT"
  ]
  node [
    id 220
    label "TCCCTGGTCAGGGAGTC--GATCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 221
    label "GGGGTAGCTACCCCGCTTAAGCTTGGATCCAAGCAGGCCTGC"
  ]
  node [
    id 222
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGTAGGCCAGGCCTGG"
  ]
  node [
    id 223
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCGTAGGCCTGC"
  ]
  node [
    id 224
    label "GGGGCCGCGGCCCCGCTCGAGCGCGGGCCCGTGGGGGCCCTC"
  ]
  node [
    id 225
    label "AGGGATATATCCCTGTTCGAACACGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 226
    label "GGCCTTGCAAGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 227
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCGAGGGCCTTC"
  ]
  node [
    id 228
    label "AGGGGCATGTCCCTGTTTGAACGAGGTACCTCGTGGGCCTAC"
  ]
  node [
    id 229
    label "TCCCTGATCAGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 230
    label "GCGCTCTAGGGCGTGTTCGAACCAGGTACCTGGGGGGCCTCC"
  ]
  node [
    id 231
    label "AGGGTCGCGGCCCTGCTCGAGCGCGGTACCGCGCGGGCCTGC"
  ]
  node [
    id 232
    label "AGGGTCGCGGCCCTGCTCGAGCCTGGTACCAGGGGGGCCCTC"
  ]
  node [
    id 233
    label "TCCCTGGTCAGGGAGTCTAGACCGTGCGCACGCCGGGCCTGG"
  ]
  node [
    id 234
    label "AGGGGTGCACCCCTGTTTGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 235
    label "GACCTTGCAGGGTCGCC--GGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 236
    label "ACGGGCATGCCCGTGTTCGAATGAGGTACCTTCTGGGCCTAG"
  ]
  node [
    id 237
    label "AGGGGATATCCCCTGTCATGATGGGGTACCTTGGGAGCTCTC"
  ]
  node [
    id 238
    label "AGGTCAGCTGACCTGCTCGAGCCCGGATCCGGGGGGGCCCTC"
  ]
  node [
    id 239
    label "TTCTGG--CCAGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 240
    label "GCGCCGTACGGCGCGTTCGAACCAGGTACCTGGGGGGCCTCC"
  ]
  node [
    id 241
    label "TCCCTGGTCAGGGAGTC--GACCTTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 242
    label "AGGGGTATACCCCTGTTTGAACAAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 243
    label "ACGGGTGCACCCGTGCTCGAGCTCGGTACCGAGTGAGCTTAT"
  ]
  node [
    id 244
    label "ACGGGTGCACCCGTGCTCGAGCCTGGTACCAGGGGAGCTCTC"
  ]
  node [
    id 245
    label "AGGAGTGCACTCCTGCTCGAGCCTGGTACCAGGGGGGCCCTC"
  ]
  node [
    id 246
    label "ACGGATGCATCCGTGCTCGAGCTCGGTACCGAGTAAGCTTAC"
  ]
  node [
    id 247
    label "TCCCTGGTCAGGGAGTCCGGACCCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 248
    label "ACGCTCTAGAGCGTGTTCGAACCGGGTACCTGGTAGGCCTAC"
  ]
  node [
    id 249
    label "AGGGGAGCTCCCCTGCTCGAGCGCGGTACCGTGCGGGCCTGT"
  ]
  node [
    id 250
    label "TCTCTGGTCAGAGAGTC--GACCTTGCGCAGGCTGGGCCTAG"
  ]
  node [
    id 251
    label "ATGCTCTAGAGCGTGTTCGAACCGGGTACCCGGTGGGCCTAC"
  ]
  node [
    id 252
    label "AGTCCG--TGGGTTGCTTAGGTTCTGATCAGAGAGGGCCCTT"
  ]
  node [
    id 253
    label "TCCCGG--CCGGGAGTT--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 254
    label "GGCCAA--TTGGTCGCT--AGCTCTGATCAGAGAGGGCCCTT"
  ]
  node [
    id 255
    label "GACTCCGCGGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 256
    label "TCCCTGGCCAGGGAGTC--GACCCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 257
    label "TCCCTGGTCAGGGAGTC--GACCCTGTGCAGGCCGGGCCTGG"
  ]
  node [
    id 258
    label "GCCTGG--TTGGGCGCTCGAGCTCTGATCAGGGTGGGCCCGT"
  ]
  node [
    id 259
    label "AGGGGATATCCCCTGTTTGAACGCGGTACCGTGAGGGCCTTC"
  ]
  node [
    id 260
    label "AGGGGAGCTCCCCTGCTCGAGCACGGTACCGTGCGGGCCTGT"
  ]
  node [
    id 261
    label "ACGAGCGCGCTCGTGTTCGAATGTGGTACCATGGGGGCCCTC"
  ]
  node [
    id 262
    label "AGGGGTGCACCCCTGCGCGCGCACGGTACCGTGCAGGCCTGT"
  ]
  node [
    id 263
    label "GGGGGG--CCCCCCGCTCGAGCACGGTACCGTGCAGGCCTGT"
  ]
  node [
    id 264
    label "TCCCTGGTCGGGGAGTCCGGGCCTGTGTGCAGCTAGGCCTGG"
  ]
  node [
    id 265
    label "AGGCCCGCGGGCCTGCTCGAGCCCGGATCCGGGCAGGCCTGC"
  ]
  node [
    id 266
    label "AGGGGCATGCCCCTGTTCGAATGAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 267
    label "AGGTCAGCTGACCTGTTCGAACGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 268
    label "TCTCTGGTCAGGGAGTC--GACCTTGCGCAAGCCAGGCCTGG"
  ]
  node [
    id 269
    label "GCAGGGATCCCTGTGTGTACACTCGGATCCGACTAGGCCTAG"
  ]
  node [
    id 270
    label "TCCCTGGTCAGGGAGTC--GACCGTGCGCACGCCGGGCCTGG"
  ]
  node [
    id 271
    label "GGAGCTGCGGTTCTGCG--CGCCGCGTACGCGGCCGGCCGGC"
  ]
  node [
    id 272
    label "GAGTGCCGGTGCTCGTTCGAACCCGGTACCGGGAAGGCCTTC"
  ]
  node [
    id 273
    label "AGGGGTATGCCCCTGCTCGAGTGCGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 274
    label "TCCTGG--TCAGGAGTC--GACCCCGCGCGGGCCAGGCCTGG"
  ]
  node [
    id 275
    label "AGGGGTGCACCCCTGCTCGAGCACGGTACCGTGCGGGCCTGT"
  ]
  node [
    id 276
    label "AGGGGTGCGCCCCTGCTCGAGTGCGGTACCGTGCGGGCCTGC"
  ]
  node [
    id 277
    label "GGATCCGCGGGTTCGCGCGCGCTCTGATCAGAGCGTGCATGT"
  ]
  node [
    id 278
    label "TCCCTGGTCAGGGAGTC--GACTCTGCGCAGGTCAGGCCTGG"
  ]
  node [
    id 279
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCGTAAGCTTAC"
  ]
  node [
    id 280
    label "TCCCTGGTCAGGGAGTC--GATCTGCGTGCAGCTGGGCCTGG"
  ]
  node [
    id 281
    label "TCCTGG--TCAGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 282
    label "AAGGGTGCACCCTTGCTCGAGCTCTGATCAGAGTGGGCCTAT"
  ]
  node [
    id 283
    label "AAGGGCGCGCCTTTGTCTAGACGCGGTACCGCTGAGGCCTTA"
  ]
  node [
    id 284
    label "AGGGCACGTGCCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 285
    label "AGGGGATATCCCCTGTTTGAACGCGGTACCGTGTGGGCCTGC"
  ]
  node [
    id 286
    label "AGGCCAGCTGGCCTGCTCGAGCGCGGTACCGTGAGGGCCTTC"
  ]
  node [
    id 287
    label "AAGGGCGCGCCTTTGTCTAGACGCGGTACCGCTGAGGCCTTG"
  ]
  node [
    id 288
    label "AGGCCAGCTGGCCTGTTCGAACTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 289
    label "GACCTTGCGGGGTCGCC--GGCTCTGATCAGAGCGTGCACGC"
  ]
  node [
    id 290
    label "GGGCGCGCGCGCCTGTTCGAACTCGGTACCGAGATTGCGATC"
  ]
  node [
    id 291
    label "GTGCCCTAGGGTACGCGCGCGCACGGATCCGTGAAGGCCTTC"
  ]
  node [
    id 292
    label "AGGGGCGCGCCCCTGTTCGAACGCGGTACCGCGTGGGCCTGC"
  ]
  node [
    id 293
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCCAGGCTTGG"
  ]
  node [
    id 294
    label "GCCTGG--TCAGGCGCT--AGCTCTGATCAGGATGAGCTCAT"
  ]
  node [
    id 295
    label "TCTCTGGTCAGGGAGTC--GATCTTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 296
    label "AGGGGCGCGCCCCTGTT--GACGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 297
    label "AGGGGTGCGCCCCTGCTCGAGCGCGGTACCGCGCAGGCCTGT"
  ]
  node [
    id 298
    label "AGGGGTATACCCCTGTTTGAACATGGTACCATGTGGGCCTAC"
  ]
  node [
    id 299
    label "GCGTCCTAGGGCGCGTTCGAACCAGGTACCTGGGGGGCCTCC"
  ]
  node [
    id 300
    label "TCCCTGGTCAGGGAGTC--GACCCTGTGCAGGCCAGGCCTGG"
  ]
  node [
    id 301
    label "AGGTCAGCTGACCTGCTCGAGCACGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 302
    label "TCCCTGGTCAGGGAGTC--GACCTGGCGCCGGCCAGGCCTGG"
  ]
  node [
    id 303
    label "GGCCTTGCAGGGTCGGC--GCCTCTGATCAGAGTGTGCACGT"
  ]
  node [
    id 304
    label "AGGGGTATACCCCTGTTCGAACTCGGATCCGAGTGGGCCTGC"
  ]
  node [
    id 305
    label "AGGGGCGCGCCCCTGTTCGAGCTCCGTGCGGAGGGGGCCCTC"
  ]
  node [
    id 306
    label "AGGGGTGCACCCCTGTTCGAACGCGGTACCGTGTGGGCCTGT"
  ]
  node [
    id 307
    label "TCCCTGGTCAGGGAGTC--GGCCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 308
    label "AGGGGTGCACCCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 309
    label "TCCCTGGTCAGGGAGTC--GACCTTGCGCAGGCTAGGCCTGG"
  ]
  node [
    id 310
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGTTGGGTCTGG"
  ]
  node [
    id 311
    label "ACGCCAGCTGGCGTGCTCGAGCGCGGTACCGCGTGGGCCTAC"
  ]
  node [
    id 312
    label "GCCTCG--CGGGGCGTGCGTGCTCTGATCAGAGCATGCATGT"
  ]
  node [
    id 313
    label "AGGGGTATACCCCTGTATATATGAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 314
    label "AAGGGTATACCCTTGTTCGAACGCAGATCTGCGCGGGCCTGT"
  ]
  node [
    id 315
    label "GACTTCGCGAGGTCGCGCGCGCTCTGATCAGAACGTGCACGT"
  ]
  node [
    id 316
    label "GGCCCTGCAGGGTCGCC--GGCTCTGATCAGAGTGTGCACAC"
  ]
  node [
    id 317
    label "AAGGGTGCACCCTTGCTCGAGCACGGTATCGTGTTGGCCAAC"
  ]
  node [
    id 318
    label "AGGGGCATGCCCCTGTTTGAACACGGTACCGTGCGGGCCTGC"
  ]
  node [
    id 319
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCGTAGGCCTAC"
  ]
  node [
    id 320
    label "GACCTC--GGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 321
    label "TCCCTGATCGGGGAGTC--GACCCTGCGCAGGGTAGGCCTGC"
  ]
  node [
    id 322
    label "AGGACACGTGTCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 323
    label "TCCCTG--CGGGGAGTCCGGACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 324
    label "GGCCCTGCGGGGTCGCGCGCGCTCTGTACAGAGCGTGCACGT"
  ]
  node [
    id 325
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCTGGGTCCAG"
  ]
  node [
    id 326
    label "TCCCTGGTCAGGGAGTC--GACCTTGCGCAGGTCGGGCCTGG"
  ]
  node [
    id 327
    label "AGGGTAGCTACCCTGCGCGCGCTCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 328
    label "AGGGGATATCCCCTGTTTGAACGCGGTACCGTGCGAGCTTGC"
  ]
  node [
    id 329
    label "TGGGATATGTTCCGGCTTGAGCGCGGTACCGTATAGGCCTAT"
  ]
  node [
    id 330
    label "GGGGCTGCAGCCTCGCGCGCGCTGTGATCACAATCCGCGGGT"
  ]
  node [
    id 331
    label "GACCTTGCAGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 332
    label "GCCTGG--TCAGGCGCT--AGCTCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 333
    label "TCCCTGGCTGGGGAGTC--GACCCTGCGCAGGTCAGGCCTGG"
  ]
  node [
    id 334
    label "GACCTTGCAAGGTCGCGCGCGCTCTGATCAGAACGTGCACGT"
  ]
  node [
    id 335
    label "AGGGGTGCGCCCCTGCTCGAGCTCGGTACCGAGCGGGCCTGC"
  ]
  node [
    id 336
    label "AGGGCAATTGCCCTGCTCGAGCCTGGTACCAGGGGGGCCCTC"
  ]
  node [
    id 337
    label "AGGGGTATACCCCTGTTTAAACAAGGTACCTTGCGGGCCTGC"
  ]
  node [
    id 338
    label "TCCCTGGTCGGGGAGTCCGGACCTGCGTGCAGCCGGGCCTGG"
  ]
  node [
    id 339
    label "AGGGGCATGCCCCTGTTTGAACAAAGTACTTTGTGGGCCTAC"
  ]
  node [
    id 340
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGTCGGGCCTGG"
  ]
  node [
    id 341
    label "GGGGGA--TCCCCCGTGTACATACGGTACCGTCTGAGCTCAG"
  ]
  node [
    id 342
    label "AGGGCATATGCCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 343
    label "GACTCTGCAGGGTTGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 344
    label "AGGCCAGCTGGCCTGCTCGAGCCCGGATCCGGGGGGGCCCTC"
  ]
  node [
    id 345
    label "GGGCCCGCGGGCCCGCTCGAGCGCAGGCCTGTGGGGGCCCTC"
  ]
  node [
    id 346
    label "AGGGAAGCTTCCCTGCGCGCGCACGGTACCGTGTGGGCCCGC"
  ]
  node [
    id 347
    label "AGGTCAGCTGACCTGCTCGAGCTCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 348
    label "GGGTTCTAGGGCCCGCTCGAGCTCGGTACCGAGTGGGCCTAC"
  ]
  node [
    id 349
    label "AGGGGTGCACCCCTGTTCGAATGGGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 350
    label "AGGGCGGCCGCCCTGCTCGAGCGCGGTACCGCGCAGGCCTGT"
  ]
  node [
    id 351
    label "GCGCTCTGGAGCGTGTTCGAACCGGGTACCCGGTAGGCCTAC"
  ]
  node [
    id 352
    label "AGGCCAGCTGGCCTGCTCGAGCCTGGTACCGGGAGGGCCTTC"
  ]
  node [
    id 353
    label "AGGGGCGCGCCCCTGCTCGAGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 354
    label "GACTCCGCGGGGTCGGC--GCCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 355
    label "TCCTGG--TCAGGAGTC--GATCTGTGTGCAGTCAGGCTTGG"
  ]
  node [
    id 356
    label "GACCTCGCGGGGTCGCGCGCGCTCTGATCAGAATGTGCACAT"
  ]
  node [
    id 357
    label "GTGGGGATCCCCGCGTGTACATTCGATATCGACTGAGCTCAG"
  ]
  node [
    id 358
    label "AGGGGTGCACCCCTGCTCGAGCTCGGTACCGAACGGGCCTGT"
  ]
  node [
    id 359
    label "GGCCTCGCGAGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 360
    label "AGGGGTATGCCCCTGCTCGAGTACGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 361
    label "AGGGGTATACCCCTGTTTGAACGAGGTACCTCGTGGGCCTAC"
  ]
  node [
    id 362
    label "TCCCTGGTCAGGGAGTC--GACTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 363
    label "GGGATTGCGGTCTCGCGCGCGCTCCGATCGGAGGGGGCCCTT"
  ]
  node [
    id 364
    label "AGGGTAGCTGCCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 365
    label "AGGGGAATTCCCCTGTTCGAGCACGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 366
    label "ACGGGAATTCCCGTGCTCGAGCCTGGATCCAGGCGGGCCTGC"
  ]
  node [
    id 367
    label "AGGGGTGCACCCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 368
    label "GATGCGGCCGTGTCGCTCGAGCTTCGATCGAAGCAGGCCTGT"
  ]
  node [
    id 369
    label "AGGGGTGCGCCCCTGCTCGAGCTTGGTACCAAGGGGGCCCTC"
  ]
  node [
    id 370
    label "AGGGGTGCGCCCCTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 371
    label "AGGGGTGCACCCCTGCTCGAGCGCGGTACCGCGCAGGCCTGT"
  ]
  node [
    id 372
    label "AGGGGAATTCCCCTGCTCGAGCTCGGATCCGAGTAGGCCTAT"
  ]
  node [
    id 373
    label "GACCTTGCGGGGTCGCGCGCGCTCTGATCAGAGTGTGCACGT"
  ]
  node [
    id 374
    label "AGGGGAGCTCCCCTGCTCGAGCTCGGTACCGAGCGGGCCTGT"
  ]
  node [
    id 375
    label "AGGGTAGCTGCCCTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 376
    label "TCCCTGGTTGGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 377
    label "ACGCCTGCGGGCGTGCTCGAGCGCGGTATCGCGGGGGCCCTC"
  ]
  node [
    id 378
    label "TCCCTGGCCAGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 379
    label "AGGGGTATGCCCCTGCTCGAGTGTGGTACCATGTGGGCCTAC"
  ]
  node [
    id 380
    label "AGGACAGCTGTCCTGTTCGAGCCCGGTACCGGGCGGGCCTGC"
  ]
  node [
    id 381
    label "TCTCTGGTTAGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 382
    label "GGGTAATATTACCCGCTCGAGCCTACCGGTAGGTTGGCCAAC"
  ]
  node [
    id 383
    label "AGGGGCATGCCCCTGCTCGAGCTCGGTACCGAGAGAGCTCTC"
  ]
  node [
    id 384
    label "TCCCTGGTCAGGGAGTC--GACCTGCGTGCAGCTGGGCCTGG"
  ]
  node [
    id 385
    label "TCCCTG--CGGGGAGTCCGGACCCTGCGCAGGACAGGCCTGT"
  ]
  node [
    id 386
    label "ACGGGTGCGCCCGTGCTCGAGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 387
    label "GGGGCTGCAGCCTCGCGTGCGCTGAGATCTTAATCCGCGGGT"
  ]
  node [
    id 388
    label "AGGCCTGCGGGCCTGTTTGAACAGGATGTCCTGGGAGCTCTC"
  ]
  node [
    id 389
    label "AGGGATATATCCCTGTT--AATGCGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 390
    label "GGGAGTTAACTCCCGTACGTATTCGGTACCGAAAGGGCCTTT"
  ]
  node [
    id 391
    label "TCCCTG--CAGGGAGTC--GACCCTGCGTAGGCCAGGTCTGG"
  ]
  node [
    id 392
    label "AGGGGCATGCCCCTGTTTGAACAAGGTACCTTGTGGGCCTGC"
  ]
  node [
    id 393
    label "GACTCTGCAGGGTTGCGCGCGCTCTGATCAGAGTGTGCACGT"
  ]
  node [
    id 394
    label "AGGGGAGCTCCCCTGCTCGAGTGCGGTACCGCGCAGGCCTGT"
  ]
  node [
    id 395
    label "TCCCAGATCTGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 396
    label "TCCTGA--TCAGGAGTCTAGACACTGCGCAGTGCAGGCCTGC"
  ]
  node [
    id 397
    label "TCCCTGGCTGGGGAGTCCGGACCCAGCGCTGGCCAGGCCTGG"
  ]
  node [
    id 398
    label "AGGTCAGCTGACCTGTTCGAACGTGGTACCACGGGGGCCCTT"
  ]
  node [
    id 399
    label "AGGCCAGCTGGCCTGCTCGAGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 400
    label "GACCTT--AGGGTCGCGCGCGCTCTGATCAGAACGTGCACGT"
  ]
  node [
    id 401
    label "ACGGGTGCACCCGTGTTCGAATGCGGTACCGTGGGAGCTCTC"
  ]
  node [
    id 402
    label "ACGGGTGCACCCGTGCTCGAGTGTGGTACCATGGGGGCCCTC"
  ]
  node [
    id 403
    label "AGAGGATATCCTCTGTGTGCATACGGTACCGTCAAGGCCTTG"
  ]
  node [
    id 404
    label "AGGCCAGCTGGCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 405
    label "GGGGGTATGCCCTCGTTTGGACCTGGTACCAGATAGGCCTAT"
  ]
  node [
    id 406
    label "GGGGCAGCTGCCCCGCTCGAGCCGGGATCCCGGGGGGCCTCC"
  ]
  node [
    id 407
    label "AGGGGCATGCCCCTGTTTGAACGAGGTACCTCGTGGGCCTAC"
  ]
  node [
    id 408
    label "AGGGGTGCACCCCTGTTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 409
    label "AGGGGTGCATCCCTGTTCGAACACGGATCCGTGGGAGCTCTC"
  ]
  node [
    id 410
    label "TCCCTGGTCAGGGAGTC--GACCGTGCGCACGCCAGGCCTGG"
  ]
  node [
    id 411
    label "AGGGGTATGCCCCTGCTCGAGTGCGGTACCGTGAGGGCCTTC"
  ]
  node [
    id 412
    label "ACGGGTTAACCCGTGCTCGAGCCAGGTACCTGGGGAGCTCTC"
  ]
  node [
    id 413
    label "AGGTCAGCTGGCCTGCTCGAGCTCGGTACCGAGAGGGCCTTC"
  ]
  node [
    id 414
    label "ACGGGGCGCCCCGTGCTCGAGTTCGGTACCGAGGGAGCTCTC"
  ]
  node [
    id 415
    label "ACCTTG--CAAGGTGCGCGCGCTCTGATCAGAACGTGCACGT"
  ]
  node [
    id 416
    label "AGAATGGTCATTCTGTGTGCACACAGTACTGTCATGGCCATG"
  ]
  node [
    id 417
    label "AGGCTCGCGGGCCTGCTCGAGCACGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 418
    label "TCCCGG--TCGGGAGTC--GACCCTGCGCAGGGCAGGCCTGC"
  ]
  node [
    id 419
    label "GACCTCGTGGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 420
    label "ACAGGTATACCTGTGTTTGAACGCGGTACCGTCTGGGCCTAG"
  ]
  node [
    id 421
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCGCGGGCCTGC"
  ]
  node [
    id 422
    label "GGATCCGCGGGTTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 423
    label "TCCCTGGTCAGGGAGTCCGGACCCTGCGCAGGTCAGGCCTGG"
  ]
  node [
    id 424
    label "AGGGGCATGCCCCTGCTCGAGCCTGGTACCAGGTAGGCCTGC"
  ]
  node [
    id 425
    label "GGGGGTATGCCCCCGCTCGAGTGCGGTACCGTCTGGGCCTAG"
  ]
  node [
    id 426
    label "ACGAGCGCGCTCGTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 427
    label "TCCCTGGTCAGGGAGTC--GACCCCGCGCGGGCTGGGCCTGG"
  ]
  node [
    id 428
    label "ACGGGCGCGCCCGTGTTCGAATGAGGTACCTTGGGAGCTCTC"
  ]
  node [
    id 429
    label "TCCTTGGTCAGGGAGTC--GACTTGGCGCCAACAGGGCCTTG"
  ]
  node [
    id 430
    label "GACTCTGCAGGGTCGCGCGCGCTCTGATCAGAGCGTGCGCGT"
  ]
  node [
    id 431
    label "TCCTGG--TCAGGAGCT--AGCTCTGCGCAGACCAGGCCTGG"
  ]
  node [
    id 432
    label "ACGGGTGCACCCGTGTTCGAATGCGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 433
    label "GACCTCGCGAGGTCGCGCGCGCTCTGATCAGAACGTGCACGT"
  ]
  node [
    id 434
    label "TCTCTGGTCAGGGAGTC--GACCCTGCGCAGGACGGGCCTGT"
  ]
  node [
    id 435
    label "TCCCTGGTCAGGGAGCC--GGCCTGGCGCCAGCTGGGCCTGG"
  ]
  node [
    id 436
    label "GCCTTG--CGGGGCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 437
    label "TCCCTGGTTGGGGAGTC--GACCCTGCGCAGGGCAGGCCTGC"
  ]
  node [
    id 438
    label "GACTGCTAGTGGTCGCGCGCGCTTCGATCGAAGGGCGCGTTC"
  ]
  node [
    id 439
    label "GACCTTGCAGGGTCGCGCGCGTTCTGATCAGAGTGTGCACAC"
  ]
  node [
    id 440
    label "GGGTTCTAGGGCCCGCTCGAGCGCGGTACCGTGAGGGCCTTC"
  ]
  node [
    id 441
    label "AGGCGAGCTCGCCTGCTCGAGTGCGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 442
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCGTGGGCCTAC"
  ]
  node [
    id 443
    label "TCCCTGGTCAGGGAGTT--GACCTTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 444
    label "AGGGGCATGCCCCTGTTTGAACACGGTACCGTGTGGGCCTGC"
  ]
  node [
    id 445
    label "AGGGGTATACCCCTGCTCGAGCGTGGTACCACTGAGGCCTCA"
  ]
  node [
    id 446
    label "AGGGGATATCCCCTGTTCGAACTCGGTACCGGAGGGGCCTCT"
  ]
  node [
    id 447
    label "AGGGCAATTGCCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 448
    label "TCCCTGGTCAGGGAGTC--GGCCCTGCGTAGGCCAGGCCTGG"
  ]
  node [
    id 449
    label "TCCTTGGCTGGGGAGTC--GACCCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 450
    label "TCCCTGGTCAGGGAGTC--GACCTGGCGCCGGTCAGGCCTGG"
  ]
  node [
    id 451
    label "GACCTCGCGGGGTCGCGCGCGCTCTGATCAGAGTGTGCACAC"
  ]
  node [
    id 452
    label "ACGGATGCATCCGTGCTTGAGCTCGGTACCGAGTAAGCTTAC"
  ]
  node [
    id 453
    label "GGGGCAGCTGCCCCGCTCGAGCGCGGATCCGCGAGGGCCTTC"
  ]
  node [
    id 454
    label "AGGCCAGCTGGCCTGCTCGAGCTCGGTACCGAGTAGGCCTAC"
  ]
  node [
    id 455
    label "ACGGGTTAACCCGTGCTCGAGCCTGGTACCAGGAGAGCTTTC"
  ]
  node [
    id 456
    label "AGGAGTGCACTCCTGCTCGAGCCCGGTACCGGGCAGGCCTGC"
  ]
  node [
    id 457
    label "AGGGGTGCACCCCTGTTCGAATGCGGTACCGTGGGAGCTCTC"
  ]
  node [
    id 458
    label "GCGTCGGCCGACGTGCTTGAGTCCGGTACCGGGTGAGCTCAC"
  ]
  node [
    id 459
    label "ACGGGCATGCCCGTGTTCGAATGCGGTACCGTGGGAGCTCTC"
  ]
  node [
    id 460
    label "TCCCTTGTGGGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 461
    label "GACCTCGCGGGGTCGCGCGCGCTCTGATCAGAGTGTGCACGC"
  ]
  node [
    id 462
    label "AGGCTAGCTGGCCTGCTCGAGCCCGGTACCGGGGAAGCTTCT"
  ]
  node [
    id 463
    label "AGGGGCATGCCCCTGCTCGAGCTCGGTACCGAGTAGGCCTAC"
  ]
  node [
    id 464
    label "GACTCCGCGGGGTCGCGCGCGCTCCGATCGGAGCGTGCACGT"
  ]
  node [
    id 465
    label "TCCCTGGTCAGGGAGTCTAGACCTTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 466
    label "TCCCTGGTTGGGGAGTC--GATCTTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 467
    label "AGGGCTGCAGCCCTGTTTGAACAGGATGTCCTGGGAGCTCTC"
  ]
  node [
    id 468
    label "AGGGATATGTCCCTGTGCGCACGCGGTACCGTACGGGCCTGT"
  ]
  node [
    id 469
    label "AGGGGTATACCCCTGTTTGAATGAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 470
    label "ACGGGTGCACCCGTGCTCGAGTGTGGTACCATGGGAGCTCTC"
  ]
  node [
    id 471
    label "GCCTGG--TCAGGCGCC--GGCTCTGATCAGGATGGGCCCAT"
  ]
  node [
    id 472
    label "ATGCCCGCGGGTATGCC--GGCCCGGTACCGGGGAAGCTTCC"
  ]
  node [
    id 473
    label "GGCCTG--CAGGTCGCGCGTGCTCTGATCAGAATGTGCACAT"
  ]
  node [
    id 474
    label "AGGCGAGCTCGCCTGCTCGAGCACGGTATCGTGGGGGCCCTC"
  ]
  node [
    id 475
    label "GGGGCAATTGCCCCGCTCGAGCGCGGATCCGCGGGGGCCTCC"
  ]
  node [
    id 476
    label "GGCTCTGCAGGGTCGTGCGCGCTCTGATCAGAGTGTGCACAT"
  ]
  node [
    id 477
    label "TCCCTGGTCAGGGAGTC--GACCTTGCGCAAGCCGGGCCTGG"
  ]
  node [
    id 478
    label "TCCCTAGTTGGGGAGTC--GACCTTGCGCAAGCCAGGCCTGG"
  ]
  node [
    id 479
    label "AGGGCAGCTGCCCTGTTCGAACACGGTACCGTGAGGGCCTTC"
  ]
  node [
    id 480
    label "GGGCCGTACGGCCCGCTCGAGCCCGGTACCGGGGAGGCCTTC"
  ]
  node [
    id 481
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGGCAGGCTTGC"
  ]
  node [
    id 482
    label "GGCCTTGCAGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 483
    label "ACGGGCATGCCCGTGTTCGAATGCGGTACCGTCAGGGCCTTG"
  ]
  node [
    id 484
    label "TCCCGG--TCGGGAGTC--GACCTGCATGCAGCCGGGCCTGG"
  ]
  node [
    id 485
    label "AGGAGTGCACTCCTGCTCGAGCGCGGTACCGCGAGGGCCTTC"
  ]
  node [
    id 486
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 487
    label "TCCCTGGTCAGGGAGTTCGGACCCTGCGCAGGATATGCATGT"
  ]
  node [
    id 488
    label "ATGGGCGCGCCCATGCTCGAGCACGGTGCCGTGCGGGCCTGC"
  ]
  node [
    id 489
    label "AGGGGTGCACCCCTGCTCGAGTGCGGATCCGTGCGGGCCTGC"
  ]
  node [
    id 490
    label "GGGATA--TATCCCGTT--AATGCGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 491
    label "CGTGGAGCTCCATGGCTCGAGCCCCGGCCGGGGCGGGCCCGC"
  ]
  node [
    id 492
    label "AGGGGTATGCCCCTGCTCGAGCTCGGTACCGAGAGGGCCTTC"
  ]
  node [
    id 493
    label "AGGGATATATCCCTGTTATAACACGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 494
    label "AGGGCAGCTGCCCTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 495
    label "TCCCTGGTCAGGGACTC--GAGTCTGCGTAGGCTGGGCCTAG"
  ]
  node [
    id 496
    label "GGGTGTGCGCACTCGCTCGAGCACGGTGCCGTGGGGGCCCTC"
  ]
  node [
    id 497
    label "AGGTCAGCTGGCCTGTTCGAACGTGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 498
    label "AGGGGCGCGCCCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 499
    label "ACGCCAGCTGGCGTGTTCGAGCTCGGTACCGAGAGGGCCTTC"
  ]
  node [
    id 500
    label "AGGCCAGCTGGCCTGCTCGAGCTCGGATCCGGGGGGGCCCTC"
  ]
  node [
    id 501
    label "GACCTCGCGGGGTCGGC--GCCTCTGATCAGAGTGTGCACAC"
  ]
  node [
    id 502
    label "AGGGGACGTCCCCTGTCATGATGGGGTACCTTGGGAGCTCTC"
  ]
  node [
    id 503
    label "ACGGGCGCGCCCGTGTTCGAATGCGGTACCGTGGGAGCTCTC"
  ]
  node [
    id 504
    label "AGGGGCATGCCCCTTTC--GAAGAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 505
    label "AGGGATATATCCCTGTTTGAACACGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 506
    label "TGGGATATGTTCCAGCTTGAGCGTGGTACCGTATAGGCCTAT"
  ]
  node [
    id 507
    label "TCCTTGGTCAGGGAGTC--GACCCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 508
    label "AGGGGCATGCCCCTGCTCGAGCCCGGATCCGGGGGGGCCCTC"
  ]
  node [
    id 509
    label "GCGGGGATCTCCGCGTGTACACTCAGTGCTGACTGGGCCTAG"
  ]
  node [
    id 510
    label "TCCCTGGTCGGGGAGTCTAGACCCGGCGCCGGCCAGGCCTGG"
  ]
  node [
    id 511
    label "GGGTCCTAGGGCCCGCTCGAGCGCGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 512
    label "ATGGGGTGCCCTGTGTGTGCACCCAGTACTGGGCAGGCCTGT"
  ]
  node [
    id 513
    label "AGGAGTGCGCTCCTGCTCGAGTCCGGTACCGGGAGGGCCCTC"
  ]
  node [
    id 514
    label "AGGCCAGCTGGCCTGCTCGAGCTCGGTACCGAAGGGGCCCTT"
  ]
  node [
    id 515
    label "GGGAGTTAACTCCCGTATGTACGCAGTACTGCAAGGGCCTTT"
  ]
  node [
    id 516
    label "AGGGCAGCTGCCCTGCTCGAGCTCGGATCCGAGGGGGCCCTC"
  ]
  node [
    id 517
    label "GCGTCGGCCGACGCGCTTGAGTCCGGTACCGGGTGAGCTCAC"
  ]
  node [
    id 518
    label "GGCCTCGCGGGGTCGCC--GGCTCTGATCAGAGTGTGCACGT"
  ]
  node [
    id 519
    label "AGGCGTGCACGCCTGCTCGAGCCCGGATCCGGGGGGGCCCTC"
  ]
  node [
    id 520
    label "AGGGCCGCGGCCCTGCTCGAGCCCGGTACCGGGCGGGCCTGC"
  ]
  node [
    id 521
    label "TCCCTGATCGGGGAGTC--GATCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 522
    label "TCCCTGGTTGGGGAGTC--GACCTTGCGCAAGCCAGGCCTGG"
  ]
  node [
    id 523
    label "CCCTGG--TCAGGGGTC--GATCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 524
    label "CCTGGC--GTCGGGGCT--AGCTCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 525
    label "ACGGGAATTCCCGTGTTCGAATGAGGTACCTTCAGGGCCTTG"
  ]
  node [
    id 526
    label "AGGGGTGCGCCCCTGCTCGAGCGCGGTGCCGCGCGCGCGTGT"
  ]
  node [
    id 527
    label "GCCTGG--TCGGGCGCTCGAGCTCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 528
    label "GGATCTGCAGGTTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 529
    label "TGGAGCATGTTCCAGCTTGAGCGCGGTACCGTATAGGCCTAT"
  ]
  node [
    id 530
    label "GAGGGTTAGCCTTTGTGTACATACGGTACCGTGGTGGCCATC"
  ]
  node [
    id 531
    label "TCCCTGGTCGGGGAGTC--GACCTTGCGCAGGGCAGGCCTGC"
  ]
  node [
    id 532
    label "AGGGGCATGCCCCTGTC--GATGCGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 533
    label "AGGGGTGCGCCCCTGCTCGAGCCCGGCGCCGGGCAGGCCTGC"
  ]
  node [
    id 534
    label "AGGGGCGCGCCCCTGCGCGCGCACGGTACCGTGCAGGCCTGT"
  ]
  node [
    id 535
    label "GCCTTG--CAGGGCGGC--GCCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 536
    label "ACGGGCATGCCCGTGCTCGAGCCTGGATCCAGGGGGGCCTCC"
  ]
  node [
    id 537
    label "GACCTCGCGGGGTCGCGTGCGCTTCGATCGAAATCCGCGGGT"
  ]
  node [
    id 538
    label "ACGGGAATTCCCGTGCTCGAGCTCGGTACCGAGGGAGCTCTC"
  ]
  node [
    id 539
    label "AGGGGTATACCCCTGTTCGAGCACGGTACCGTGTGGGCCTGC"
  ]
  node [
    id 540
    label "AGGGTGGCCGCCCTGCTCGAGCTCGGTACCGAGCAGGCCTGT"
  ]
  node [
    id 541
    label "AGGTCGATCGACCTGCTCGAGTACGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 542
    label "AGGGGCATGCCCCTGCTCGAGCACGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 543
    label "GACCTTGCGGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 544
    label "GACTCTGCAGGGTCGCC--GGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 545
    label "AGGGTCGCGGCCCTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 546
    label "TTCCTGGTCAGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 547
    label "GACTCTGCAGAGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 548
    label "GCGTCCTAGGGCGCGTTCGAACTCGGTACCGAGGGGGCCTCC"
  ]
  node [
    id 549
    label "AGGGGCATGTCCCTGTTTGAACACGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 550
    label "GACCTTGCGGGGTCGCC--GGTTCTGATCAGAGTGTGCATGT"
  ]
  node [
    id 551
    label "AGGGGTATACCCCTGCTCGAGCGCGGTACCGCGTGAGCTTAC"
  ]
  node [
    id 552
    label "GACCCCGCGGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGC"
  ]
  node [
    id 553
    label "AGGAGAGCTCTCCTGTTCGAACTCGGTACCGAGAGGGCCTTT"
  ]
  node [
    id 554
    label "GCTCTG--CAGGGCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 555
    label "AGGCCAGCTGGCCTGCTCGAGCGCGGTACCGCGTAGGCCTGC"
  ]
  node [
    id 556
    label "TCTCTGGTCAGGGAGTCCGGACCTGGCGCCAGCCAGGCCTGG"
  ]
  node [
    id 557
    label "GGCCCG--CGGGTCGCCTAGGTTCTGATCAGAGAGGGCCCTT"
  ]
  node [
    id 558
    label "GACTCG--CGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 559
    label "AGGAGTGCGCTCCTGCTCGAGCTCGGTACCGGGGGGGCCCTT"
  ]
  node [
    id 560
    label "AGGGGCGCGCCCCTGCTCGAGCACGGTACCGTGCAGGCCTGT"
  ]
  node [
    id 561
    label "AGGGGTGCACCCCTGCTCGAGTGCGGTACCGTGCGGGCCTGC"
  ]
  node [
    id 562
    label "AGGGGTATGCCCCTGCTCGAGCTCGGTACCGAGTAGGCCTAC"
  ]
  node [
    id 563
    label "AGGGACGCGTCCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 564
    label "AGGGGAGCTCCCCTGCTCGAGTGCGGATCCGTGCGGGCCTGC"
  ]
  node [
    id 565
    label "GCGTGGTACCACGCGTTCGAACCAGGTACCTGGAGGGCCTTC"
  ]
  node [
    id 566
    label "AGGGGCGCGCCCCTGCTCGAGCGCGGTACCGCGCAGGCCTGT"
  ]
  node [
    id 567
    label "TCCCTGATCAGGGAGTC--GATCCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 568
    label "AGGCCAATTGGCCTGCTCGAGCCTGGTACCGGGAGGGCCTTC"
  ]
  node [
    id 569
    label "GGGTGTGCGCACTCGCTTGAGCGTGGCGCCGCGGGGGCCCTC"
  ]
  node [
    id 570
    label "GACCCAGCTGGGTTGCCTAGGCTCAGCGTTGGGTGGGCCCAT"
  ]
  node [
    id 571
    label "GGCCTCGCGGGGTCGCGCGCGCTCTGATCAGAGCGTGCATGC"
  ]
  node [
    id 572
    label "AGGTCAGCTGACCTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 573
    label "AGGGGAGCTCCCCTGTTCGAGCACGGTACCGTGCGGGCCTGT"
  ]
  node [
    id 574
    label "GGGTGTGCGCACTCGCTCGAGCACGATGTCGTGGGGGCCCTC"
  ]
  node [
    id 575
    label "ACGGGCATGCCCGTGCTCGAGCGCGGTACCGCGTAGGCCTGC"
  ]
  node [
    id 576
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCTGGGCCCGG"
  ]
  node [
    id 577
    label "AGGGGTATGCCCCTGCTCGAGCGCGGATCCGCGGGAGCTCTC"
  ]
  node [
    id 578
    label "GGGGCTGCAGCCCCGCTCGAGCCGGGATCCCGGGGGGCCTCC"
  ]
  node [
    id 579
    label "AGGCCAGCTGGCCTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 580
    label "AGGGGTATGCCCCTGCTCGAGCTTGGTACCAAGGCGGCCGTC"
  ]
  node [
    id 581
    label "GGCCTCGCGGGGTCGCGCGCGCTTCGATCGAAATCCGCGGGT"
  ]
  node [
    id 582
    label "AGGGGTATACCCCTGTTTAAACACGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 583
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGTGCGGGCCTGC"
  ]
  node [
    id 584
    label "ACGGGCGCGCCCGTGCTCGAGTGTGGTACCATGTGGGCCTAC"
  ]
  node [
    id 585
    label "TCCCTGGCTGGGGAGTC--GACCCTGCGCAGGCCAGGTCTGG"
  ]
  node [
    id 586
    label "TTCCTGGTCGGGAAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 587
    label "AGGGTCGCGGCCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 588
    label "GGGTGTGCGCACTCGCTCGAGCGCGGTGCCGCGGGGGCCCTC"
  ]
  node [
    id 589
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCCCGAGCTTGG"
  ]
  node [
    id 590
    label "GATGCT--AGCGTCGCGCGCGCTTTGATCGAAGGGCGCGCTC"
  ]
  node [
    id 591
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGTCAGGCCTGG"
  ]
  node [
    id 592
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCTAGGCCTGG"
  ]
  node [
    id 593
    label "AGGAGTGCACTCCTGCTCGAGCCTGGTACCAGGTAGGCCTAT"
  ]
  node [
    id 594
    label "AGGGGTATACCCCTGTTCGAACCTGGTACCAGGTGGGCCTGC"
  ]
  node [
    id 595
    label "ACGCCTGCGGGCGTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 596
    label "AGGTCAGCTGGCCTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 597
    label "AGGGACATGTCCCTGTTTAAACACGGTACCGTCTGGGCCTAG"
  ]
  node [
    id 598
    label "AGGGGCATGCCCCTGTTTGAACGAGGTATCTCGTGGGCCTAC"
  ]
  node [
    id 599
    label "GGGAGTGCGCTCCTGCTCGAGCTCAGTACTGAATGGGCCTGT"
  ]
  node [
    id 600
    label "GGCCTCGCGGGGCCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 601
    label "GGACCT--AGGTTCGCGCGCGCTCTGATCAGAGTGTGCACGT"
  ]
  node [
    id 602
    label "AGGCCACGTGGCCTGTTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 603
    label "TCCCTGGTCAGGGAGTC--GACTCTGCGCAGGCCAGGTCTGG"
  ]
  node [
    id 604
    label "GGGTGTGCGCACCCGCTTGAGCGTGGCGCCGCGGGGGCCCTT"
  ]
  node [
    id 605
    label "GAAGATATATCTTCGTTTGAATCTTGGCCAAGGAGAGCTTTC"
  ]
  node [
    id 606
    label "TCCCTG--TGGGGAGTCCGGACCCTGCGCAGGACAGGCCTGT"
  ]
  node [
    id 607
    label "AGGAGTGCGCTCCTGCTCGAGCCCGGTACCGGGAGGGCCCTC"
  ]
  node [
    id 608
    label "AGGGCAGCTGCCCTGCGCGCGCCCGGTACCGGGTGGGCCCGC"
  ]
  node [
    id 609
    label "TTCCTGGTCAGGGAGTCCGGATCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 610
    label "GGGGCACGTGCCCCGCTCGAGCCGGGATCCCGGGGGGCCTCC"
  ]
  node [
    id 611
    label "AGGAGTGCGCTCCTGCTCGAGCCTGGTACCAGGTAGGCCTAT"
  ]
  node [
    id 612
    label "TCCCGG--TCGGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 613
    label "AGGAGCATGCTCCTGTTCGAATGCGGTACCGTGGGAGCTCTC"
  ]
  node [
    id 614
    label "AGGGGAGCTCCCCTGCC--GGTGCGGTACCGTGCGGGCCTGT"
  ]
  node [
    id 615
    label "GGCCTCATGGGGTCGCGCGCGCTTCGATCGAAATCCGCGGGT"
  ]
  node [
    id 616
    label "TCCCTGGTCAGGGAGTC--GACCCTACGTAGGGTGGGTCTGT"
  ]
  node [
    id 617
    label "AGGGGCGCGCCCCTGCA--TGCGCGGTACCGTGGGAGCTCTC"
  ]
  node [
    id 618
    label "GACCTCGCGAGGTCGCGTGCGCTCTGATCAGAACGTGCACGT"
  ]
  node [
    id 619
    label "GCCTGGGTTCAGGCGCT--AGCTCTGATCAGGGTGGGCCCGC"
  ]
  node [
    id 620
    label "AGGGGCATGCCCCTGTGCGCACTCGGTACCGACTAGGCCTAG"
  ]
  node [
    id 621
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 622
    label "AGGTCCGCGGGCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 623
    label "AGGGGTGCACCCCTGTTCGAACACGGATCCGTGGGAGCTCTC"
  ]
  node [
    id 624
    label "AGGGTGGCCGCCCTGCTCGAGCGCGGTACCGCGCAGGCCTGT"
  ]
  node [
    id 625
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCGGGGCCCTG"
  ]
  node [
    id 626
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCCGGGCTTGG"
  ]
  node [
    id 627
    label "TCCCTGGCCAGGGAGTC--GACCTGTGTGCAGCTGGGCCTGG"
  ]
  node [
    id 628
    label "AGGCCAGCTGGCCTGCTCGAGCCCGGTACCGGGTGGGCCTAC"
  ]
  node [
    id 629
    label "GCCTGG--TCAGGCGCTCGAGCTCTGATCAGGGTGGGCCCGC"
  ]
  node [
    id 630
    label "GGGGGAGCTCCCCCGCTCGAGCGCGGCGCCGCGTGGGCCTGC"
  ]
  node [
    id 631
    label "AGGCAAGCTTGCCTGCTCGAGTATGGTACCATGGGGGCCCTC"
  ]
  node [
    id 632
    label "ACGGGCATGCCCGTGTATGTACAAGGTACCTTGTGGGCCTGC"
  ]
  node [
    id 633
    label "TCCCTGGTTGGGGAGTC--GACCCTGCGCAGGCCAGGTCTGG"
  ]
  node [
    id 634
    label "TCTTGG--TCAGGAGTC--GACCTGCGCGCAGCCGGGCCTGG"
  ]
  node [
    id 635
    label "GGCCTCGCGGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 636
    label "AGGGGTGCGCCCCTGCTCGAGCGCGGTACCGCGCGGGCCTGT"
  ]
  node [
    id 637
    label "TTCCTGGTCAGGAAGTC--GACCCTGTGCAGGCCAGGCCTGG"
  ]
  node [
    id 638
    label "TCCCTGGTTGGGGAGTCCGGACCCTGCGCAGGCCAGGTCTGG"
  ]
  node [
    id 639
    label "AGGGGCGCGCCCCTGCTCGAGCCCGGTATCGGGCGGGCCTGC"
  ]
  node [
    id 640
    label "AGGGATATATCCCTGTGCGCACGCGGTACCGTTCGGGCCTGA"
  ]
  node [
    id 641
    label "TCCCTGGTCAGGGAGTCTAGACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 642
    label "AGGAGTGCACTCCTGCTCGAGCGTGGTACCACGAGGGCCTTC"
  ]
  node [
    id 643
    label "TCCCTG--CAGGGAGTC--GACCCTGCGCAGGCCAGGCTTGG"
  ]
  node [
    id 644
    label "GACCTTGCGGGGTCGCGCGCGCTCTGATCAGAGTGTGCACAC"
  ]
  node [
    id 645
    label "AGGGGCATGCCCCTGTTTGAACAAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 646
    label "TCCTGG--TCAGGAGTC--GACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 647
    label "GGCCTTGCAGGGTCGCGCGTGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 648
    label "ACTCTG--CAGGGTGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 649
    label "AGGGGTGCGCCCCTGCTCGAGCCCGGTACCGGGCGGGCCTGC"
  ]
  node [
    id 650
    label "GCCTGG--TCAGGCGCTCGAGTTCTGATCAGGATGGGCCCGT"
  ]
  node [
    id 651
    label "TCCCTGTATAGGGAGCT--AGCTCCGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 652
    label "AGGGGCGCGCCCCTGTTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 653
    label "GCGCCATATGGCGCGGC--GCCACGGTACCGTGGAGGCCTCC"
  ]
  node [
    id 654
    label "AGGGGTATACCCCTGCTCGAGCGCGGATCCGCGGGAGCTCTC"
  ]
  node [
    id 655
    label "AGGGGTATGCCCCTGCTCGAGTGTGGTACCATGAGGGCCTTC"
  ]
  node [
    id 656
    label "GCAGGGATCTCTGCGTGTGCATAGGGTACCTTCTGGGCCTAG"
  ]
  node [
    id 657
    label "TCCCTGGTCAGGGAGTC--GACCTGTGTGCAGCTGGGCCTGG"
  ]
  node [
    id 658
    label "GGGGCTATGGCCTCGCTCGAGCTTCGATCGAAGCAGGCCTGT"
  ]
  node [
    id 659
    label "AGGCCAGCTGGCCTGTTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 660
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCCCGGGCCTGG"
  ]
  node [
    id 661
    label "AGGGCAGCTGCCCTGCTCGAGTGCGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 662
    label "ACTTCG--CGAGGTGCGCGCGCTCTGATCAGAACGTGCACGT"
  ]
  node [
    id 663
    label "TCCTGG--TCAGGAGTC--GATCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 664
    label "AGAGGATATCCTCTATGTGCATACGGTACCGTCAAGGCCTTG"
  ]
  node [
    id 665
    label "GGGGGCTAGCTCTCGCTCGAGCTTGGATCCAGGTAGGCCTGC"
  ]
  node [
    id 666
    label "GGCCTT--AAGGTCGCGCGCGTTCTGATCAGAGTGTGCACAT"
  ]
  node [
    id 667
    label "AGGGGTGCGCCCCTGCTCGAGCTCGGATCCGAGGGGGCCCTC"
  ]
  node [
    id 668
    label "TCCCTGATCAGGGAGTCCGGACCTTGCGCAAGCCAGGCCTGG"
  ]
  node [
    id 669
    label "GGGTGTATGCACCCGCTCGAGCGCTGATCAGTGGGGGCCCTC"
  ]
  node [
    id 670
    label "AGGGGTATGCCCCTGCTCGAGCACGGTACCGTTCGGGCCTGA"
  ]
  node [
    id 671
    label "AGGGGCATGCCCCTGTTTGAATGAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 672
    label "TCCTTGGTTGGGGAGTC--GACCTGCATGCAGCCAGGCCTGG"
  ]
  node [
    id 673
    label "ACGGGCGCGCCCGTGCTCGAGCGCGGATCCGCGGGGGCCCTC"
  ]
  node [
    id 674
    label "GGGCCACGTGGCCCGTGTACACACGGTACCGTCGAGGCCTCG"
  ]
  node [
    id 675
    label "GACCTTGCAAGGTCGCC--GGCTCTGATCAGAGTATGCATAC"
  ]
  node [
    id 676
    label "AGGAGTGCGCTCCTGCTCGAGCCCGGTACCGGGGGGGCCTCT"
  ]
  node [
    id 677
    label "GCGTCCTAGGACGCGTTCGAACTCGGTACCGGGGGGGCCTCC"
  ]
  node [
    id 678
    label "AGGGGAGCTCCCCTGCTCGAGCGCGGTACCGCGCGTGCGCGT"
  ]
  node [
    id 679
    label "AGGGGAGCTCCCCTGCTCGAGCGCGGTACCGTGCGAGCTTGT"
  ]
  node [
    id 680
    label "GGGTCCTAGGGCCCGCTCGAGCGCGGTACCGTGTAGGCCTGC"
  ]
  node [
    id 681
    label "ACGGGTGCACCCGTGCTCGAGCCTGGATCCAGGCGGGCCTGC"
  ]
  node [
    id 682
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCGTGAGCTTAC"
  ]
  node [
    id 683
    label "AGGGGTGCACCCCTGCTCGAGCGCGGCGCCGCGCAGGCCTGT"
  ]
  node [
    id 684
    label "AGGGGTATGCCCCTGCTCGAGCTCGGTACCGAGTGGGCCTAC"
  ]
  node [
    id 685
    label "GGGGGTTAACCCCCGTATGTACGCAGTACTGTAAGGGCCTTT"
  ]
  node [
    id 686
    label "TCCCTGATCAGGGAGTC--GACCTTGCGCAAGCCGGGCCTGG"
  ]
  node [
    id 687
    label "TCCCTG--CAGGGAGTC--GATCTTGCGCAAGCCAGGCCTGG"
  ]
  node [
    id 688
    label "AGGGGTATACCCCTGCTCGAGTGCGGTACCGTGCGGGCCTGC"
  ]
  node [
    id 689
    label "ATGAGCTAGCTCATGTTTAAACATGGTACCATAAGGGCCTTT"
  ]
  node [
    id 690
    label "TTCCTA--TAGGGAGTC--GACTGTGCGCACACCAGGCCTGG"
  ]
  node [
    id 691
    label "AGGGATGCGTCCCTGCGCGCGCACGGTACCGTGTGGGCCCGC"
  ]
  node [
    id 692
    label "AGGGGCGCGCCCCTGCTCGAGCCCGGTACCGGGCAGGCCTGT"
  ]
  node [
    id 693
    label "GGCTACGCGTGGTCGCCTAGGCTCTGATCAGAGAGGGCCCTT"
  ]
  node [
    id 694
    label "TCCCTGGTCAGGGAGTCTAGACCTTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 695
    label "AGGGGTATACCCCTGCTCGAGCCTGGTACCGGGAGAGCTCTC"
  ]
  node [
    id 696
    label "TCTCTGGTCAGGGAGTCTAGACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 697
    label "AGGGGTGCGCCCCTGTTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 698
    label "TCCTGG--TTGGGAGTCCGGACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 699
    label "GACCTT--AGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 700
    label "GACCTCGCGGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 701
    label "CATTGG--CCAATGGTTCGAATCTCGCGTGGGCCGGGCCTGG"
  ]
  node [
    id 702
    label "ACGGGCGCGCCCGTGTTCGAGCCTGGTACCAGGGGAGCTCTC"
  ]
  node [
    id 703
    label "AGGCGTGCGCGCCTGCTCGAGTGCGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 704
    label "AGGTCAGCTGACCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 705
    label "TCCCTGGTCAGGGAGTCCGGACCTTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 706
    label "AAGGGTGCACCCTTGCTCGAGCACGGTATCGTGTTGGCCAGC"
  ]
  node [
    id 707
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCGTCGGCCGGC"
  ]
  node [
    id 708
    label "GACCTCGCGGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGC"
  ]
  node [
    id 709
    label "CCCTGA--TCGGGGGTT--GACCCTGCGCAGGTCAGGCCTGG"
  ]
  node [
    id 710
    label "TCCCTGGTTGGGGAGTC--GACCTTGCGCAGGACAGGCTTGT"
  ]
  node [
    id 711
    label "GACCTCGCGGGGTCGCGCGTGTTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 712
    label "AGGGGTATGCCCCTGCTCGAGCTCGGTACCGAGCGGGCCTGC"
  ]
  node [
    id 713
    label "AGGGGCGCGCCCCTGTTCGAGCACGGTACCGTGCAGGCCTGT"
  ]
  node [
    id 714
    label "TCCCTGGTTGGGGAGTC--GACCTTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 715
    label "AGGGGAGCTCCCCTGCTCGAGTGTGGATCCATGCAGGCCTGT"
  ]
  node [
    id 716
    label "GGGTGTGCGCACCCGCTTGAGCGTGGCGCCGCAGGGGCCCTT"
  ]
  node [
    id 717
    label "AGGTCAATTGGCTTACTTAAGTTTGGTATCAAAGAGGCCTCT"
  ]
  node [
    id 718
    label "GACCTTGCGAGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 719
    label "AGGAGTGCACTCCTGCTCGAGCCCGGTACCGGGGGAGCTCTC"
  ]
  node [
    id 720
    label "TCCCCGGTCGGGGAGTC--GACCTTGCGCAAGCCAGGCCTGG"
  ]
  node [
    id 721
    label "TCCCTGGTCAGGGAGTCCGGATCCTGTGCAGGCTGGGCCCGG"
  ]
  node [
    id 722
    label "ACGGGCGTGCCCGTGCTCGAGCCTGGTACCAGGGGAGCTCTC"
  ]
  node [
    id 723
    label "AGGTCAGCTGGCCTGTTCGAGCTCGGTACCGAGCGGGCCTGC"
  ]
  node [
    id 724
    label "AGGGGAGCTCCCCTGCTCGAGTGCGGTACCGTGCGGGCCTGC"
  ]
  node [
    id 725
    label "AGGGGTGCACCCCTGTTCGAGCCCGGTACCGGGGGAGCTCTC"
  ]
  node [
    id 726
    label "AGGTCAGCTGACCTGTTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 727
    label "TCCCTG--TAGGGAGCT--AGTTCTGCGCAGGTCGGGCCTGG"
  ]
  node [
    id 728
    label "GGACCGCGTGGTTCGCGCGCGCTTCGATCGAAATCCGCGGGT"
  ]
  node [
    id 729
    label "AGGTCAGCTGGCCTGTTTAAACGCGGTACCGCAGGGGCCCTT"
  ]
  node [
    id 730
    label "AGGGCCGCGGCCCTGCTCGAGCCCGGTATCGGGCGGGCCTGC"
  ]
  node [
    id 731
    label "AGGTTTGCAGACCTGCTCGAGCTCGGATCCGAGGGGGCCCTC"
  ]
  node [
    id 732
    label "GCAGATATATCTGTATCTAGATGCGGTACCGTGTTGGCCAGC"
  ]
  node [
    id 733
    label "AGGCCAGCTGGCCTGTTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 734
    label "GACCCTGCAGGGTCGCGCGCGCTCTGATCAGGGCGTGCACGC"
  ]
  node [
    id 735
    label "GGATTCGCGGGTTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 736
    label "AGGGGTATACCCCTGCTCGAGCCCGGATCCGGGGGGGCCCTC"
  ]
  node [
    id 737
    label "GATCCAGTTGGGTCGCCTAGGCTCAGCGCTGGGTGGGCCCAT"
  ]
  node [
    id 738
    label "AGGCCAATTGGCCTGCTCGAGTTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 739
    label "TCCCTGATCAGGGAGTC--GACCTTGCGCAAGTCGGGCCTGG"
  ]
  node [
    id 740
    label "AGGAGAATTCTCCTGTTCGAATACGGTACCGTCTCAGCTGAG"
  ]
  node [
    id 741
    label "TCCCTGGTTGGGGAGTCCGGACCTGGCGCCAGCCAGGCCTGG"
  ]
  node [
    id 742
    label "AGGGACATGTCCCTGTTCGAATGAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 743
    label "AGGCGATATCGCCTGCTCGAGCTCGGTACCGAGTAGGCCTAC"
  ]
  node [
    id 744
    label "AGGCCAATTGGCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 745
    label "GGCTTG--CAGGTCGCGCGCGCTCTGATCAGAACGTGCACGT"
  ]
  node [
    id 746
    label "AGGGGCATGCCCCTGTTCGAACCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 747
    label "ACGTCAGCTGACGTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 748
    label "AGGGGG--CCCCCTGCTCGAGCCCGGTACCGGGCAGGCCTGT"
  ]
  node [
    id 749
    label "TCCCTGATCAGGGAGTC--GACCTGCATGCAGCCAGGCCTGG"
  ]
  node [
    id 750
    label "TCCCGC--GTGGGAGCT--AGCTCTGCGTGGGCCAGGCCTGG"
  ]
  node [
    id 751
    label "AGGGGAGCTCCCCTGCTCGAGTGCGGTACCGTGCGGGCCTGT"
  ]
  node [
    id 752
    label "ACGGGCATGCCCGTGCTCGAGCACGGTACCGTGAGGGCCTTC"
  ]
  node [
    id 753
    label "TCCCTGATCGGGGAGTC--GACCCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 754
    label "GATCCTGCAGGGTCGTGCGCGTTCTGATTGGAATGTGCACAT"
  ]
  node [
    id 755
    label "ATGGCATATGCTGTGTGCGCATGCGGTACCGTGTTGGCCAAC"
  ]
  node [
    id 756
    label "AGGGGAGCTCCCCTGCTCGAGTGCGGTACCGTGCAGGCCTGT"
  ]
  node [
    id 757
    label "AGGGCAGCTGCCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 758
    label "AGGCGATATCGCCTGCTCGAGCTCGGATCCGAGGGGGCCCTC"
  ]
  node [
    id 759
    label "ACGGGG--CCCCGTGCTCGAGCCTGGTACCAGGGGAGCTCTC"
  ]
  node [
    id 760
    label "TCCCTGGTCAGGGAGTC--GACCTTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 761
    label "AGGAGTGCACTCCTGCTCGAGCCCGGTACCGGGCGGGCCTGC"
  ]
  node [
    id 762
    label "GCGCTCTAGAGCGTGTTCGAACCGGGTACCCGGTAGGCCTAC"
  ]
  node [
    id 763
    label "GACCTTGCAGGGTCGGC--GCTTTTGATCAGGGTGTGCACAT"
  ]
  node [
    id 764
    label "AGGGCAGCTGCCCTGCTCGAGCCCGGTACCGGGGGGGCCCTT"
  ]
  node [
    id 765
    label "TCCCTAGTTGGGGAGTCTAGACCCTGCGCAGGGCAGGCCTGC"
  ]
  node [
    id 766
    label "AGGTCAGCTGGCCTGTTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 767
    label "AGGGGTGCGCCCCTGTTCGAGCCCGGTACCGGGGGAGCTCTC"
  ]
  node [
    id 768
    label "GCCCTG--CAGGGTGCACGTGCTCTGATCAGAGTGTGCACAC"
  ]
  node [
    id 769
    label "TCCCTGGTCAGGGAGTC--GACCTTGCGCAAGCCAAGCTTGG"
  ]
  node [
    id 770
    label "ACGGGTTAACCCGTGCTCGAGCTTGGTACCAAGGGAGCTCTC"
  ]
  node [
    id 771
    label "AGGGTAGCTGCCCTGCGCGCGCGCGGTACCGCGCAGGCCTGT"
  ]
  node [
    id 772
    label "ACCTTG--CAGGGTGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 773
    label "TTCCTGGTCAGGGAGTC--GATCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 774
    label "AAGGGTATACCCTTGTTCGAACACAGATCTGTAGGGGCCCTT"
  ]
  node [
    id 775
    label "TCCCTGATCAGGGAGTT--GACTCTGCGTAGACCAGGCCTGG"
  ]
  node [
    id 776
    label "AGGGGATATCCCCTGTTTGAACGCGGTACCGTGGGAGCTCTC"
  ]
  node [
    id 777
    label "AGGTCAGCTGGCCTGCTCGAGTCCGGTACCGGGCGGGCCTGC"
  ]
  node [
    id 778
    label "AGGAGTGCGCTCCTGCTCGAGCCCGGTACCGGGCGGGCCTGT"
  ]
  node [
    id 779
    label "TCCCTGGTTGGGGAGTC--GACCCTGCGCAGGTCAGGCCTGG"
  ]
  node [
    id 780
    label "AGGAGTGCACTCCTGTTCGAACATAGTACTATGTGGGCCTGC"
  ]
  node [
    id 781
    label "TCCCTGGTTGGGGAGTC--GACCCTGCGCAGGTCAGGCCTGA"
  ]
  node [
    id 782
    label "AGGGGTATACCCCTGTGCGCACTCGGTACCGAACGGGCCTGT"
  ]
  node [
    id 783
    label "TTCCTGGTCAGGGAGTC--GACCTTGTGCAGGCCAGGCCTGG"
  ]
  node [
    id 784
    label "AGGGGTGCGCCCCTGCTCGAGCGCGGTACCGCGTCGGCCGGC"
  ]
  node [
    id 785
    label "TCCCTG--CAGGGAGTC--GACCCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 786
    label "TGGGATATGTTCCAGCTTGAGCGCGGTACCGTATAGGCCTAT"
  ]
  node [
    id 787
    label "TCCCTG--CAGGGAGTC--GACCTTGCGTAGGCCAGGCCTGG"
  ]
  node [
    id 788
    label "AGGGGTTAACCCCTGTATGTACGCAGTACTGCGAGGGCCTTT"
  ]
  node [
    id 789
    label "GCCTAG--TTGGGCGCT--AGCTCTGATCAGGGTGGGCCCAC"
  ]
  node [
    id 790
    label "AGGGGTATGCCCCTGCTCGAGCGCGGTACCGCGGGAGCTCTC"
  ]
  node [
    id 791
    label "AGGGGCGCGCCCCTGCTCGAGTTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 792
    label "GGGGTA--TGTCCTGCTCGAGCTTTGATCAAGCCTGGCCAGG"
  ]
  node [
    id 793
    label "TCCCTGGTCAGGGAGTC--GACCTTGCGCAAGCCAGGCCTGG"
  ]
  node [
    id 794
    label "AGGAGTGCACTCCTGCTCGAGCTCGGTACCGACACGGCCGTG"
  ]
  node [
    id 795
    label "AGGCCAATTGGCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 796
    label "GCGCTCTAGGGCGCGTTCGAACTCGGTACCGGGGGGGCCTCC"
  ]
  node [
    id 797
    label "AGGAGG--CCTCCTGCTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 798
    label "GCGCCTTAGGGCGCGTTCGAACCAGGTACCTGGGGGGCCTCC"
  ]
  node [
    id 799
    label "GCGCTTTAGGGCGCGTTCGAACTCGGTACCGAGGGGGCCTCC"
  ]
  node [
    id 800
    label "AGGCCAATTGGCCTGTTCGAGCCCGGTACCGGGGGGGCCCTC"
  ]
  node [
    id 801
    label "ACGGAAGCTTCCGTGCTCGAGCCTGGTACCAGGGGAGCTCTC"
  ]
  node [
    id 802
    label "GGCCTTCGAGGGTCGCGTGCGCTTCGATCGAAATCCGCGGGT"
  ]
  node [
    id 803
    label "ACCTCG--CGGGGTGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 804
    label "AGGGGCGCGCCCCTGTTCGAGCCCGGTATCGGGGGAGCTCTC"
  ]
  node [
    id 805
    label "AGGGGTATACCCCTGTTTAAACGAGGTACCTTGTGGGCCTAC"
  ]
  node [
    id 806
    label "TCCTTGGTCAGGGAGTC--GATCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 807
    label "TCCCAG--TTGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 808
    label "AGGCCAGCTGGCCTGCTCGAGCCCGGTACCGGGGGGGCCCTT"
  ]
  node [
    id 809
    label "GGCCTCGTGGGGTCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 810
    label "AGGAGTGCGCTCCTGCTTGAGCCTGGTACCAGGTAGGCCTAC"
  ]
  node [
    id 811
    label "GACCTCGCGGGGTCGCGCGCGCTCTGATTAGAGCGTGCACGT"
  ]
  node [
    id 812
    label "GACCCCGCGGGGTCGCGCGCGCTCTGATCAGAGTGTGCACGC"
  ]
  node [
    id 813
    label "GATTGCTAGTGGTCGCGCGCGCTTCGATCGAAGGGCGCGCTC"
  ]
  node [
    id 814
    label "ACGGGTCGACCCGTGCTCGAGCCTGGTACCAGGGGAGCTCTC"
  ]
  node [
    id 815
    label "AGGGAAGCTTCCCTGCGCGCGCACGGTACCGTGCAGGCCTGT"
  ]
  node [
    id 816
    label "AGGGCCGCGGCCCTGCTCGAGCCCGGTATCGGGCAGGCCTGC"
  ]
  node [
    id 817
    label "AGGGGTGCGCCCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 818
    label "TCCCTGGTCAGGGAGCC--GGCCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 819
    label "GACCTTGTGGGGTCGTGTGCATTCTGATCAGAGTGTGCACAT"
  ]
  node [
    id 820
    label "AGGGGCGCGCCCCTGCTCGAGCACGGTACCGTGCGGGCCTGC"
  ]
  node [
    id 821
    label "AGGGATATATCCCTGTTTGAACATGGTACCATGTGGGCCTAC"
  ]
  node [
    id 822
    label "ACGTCAGCTGACGTGCTTGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 823
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCCGAGCTTGG"
  ]
  node [
    id 824
    label "ACGGGCATGCCCGTGTTCGAATGAGGTACCTTCAGGGCCTTG"
  ]
  node [
    id 825
    label "AGGTCAGCTGGCCTGCTCGAGCACGGTACCGTGGGGGCCCTC"
  ]
  node [
    id 826
    label "ACGGGCATGCCCGTGTTTGAACAAGGTACCTTCTGGGCCTGG"
  ]
  node [
    id 827
    label "GGTGCG--CGCACCGTTTAAACATGGTACCATGAGGGCCTTC"
  ]
  node [
    id 828
    label "AGGTCAGCTGGCCTGTTCGAGCGCGGTACTGCGGGGGCCCTC"
  ]
  node [
    id 829
    label "GGTGCG--CGCACCGTTTAAACATAGTACTATGAGGGCCTTC"
  ]
  node [
    id 830
    label "GCGGACGCGTCCGTGCTCGAGCGCGGATCCGCGGGGGCCTCC"
  ]
  node [
    id 831
    label "AGGGGCGCGCCCCTGCTCGAGCGCGGTATCGTGCAGGCCTGC"
  ]
  node [
    id 832
    label "GCCTGG--TCGGGCGCT--AGCTCTGATCAGGCTGGGCCCAG"
  ]
  node [
    id 833
    label "TCCCTGGTCAGGGAGTC--GACCCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 834
    label "GGGCCCGCGGGCCCGCTCGAGCGCGGGCCCGTGTGGGCCCAC"
  ]
  node [
    id 835
    label "AGGGGTATGCCCCTGCTCGAGCGTGGTACCACGAGGGCCTTC"
  ]
  node [
    id 836
    label "AGGGGTATACCCCTGTTTGAACGTGGTACCATGTGGGCCTGC"
  ]
  node [
    id 837
    label "GACCGG--CTGGTTGCCTAGGCTCTGATCAGAGAGGGCCCTT"
  ]
  node [
    id 838
    label "TCCCTGGTTAGGGAGTCTAGACCCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 839
    label "AGGCGAGCTCGCCTGCTCGAGCGCGGTACCGCGCGGGCCTGC"
  ]
  node [
    id 840
    label "AGGGGTATGCCCCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 841
    label "ACGGGAGCTCCCGTGCTCGAGCCCGGTACCGGGGGAGCTCTC"
  ]
  node [
    id 842
    label "AGGCCAGCTGGCCTGCTCGAGCCCGGTACCGGGTAGGCCTAC"
  ]
  node [
    id 843
    label "TCCCTGGTCGGGGAGTC--GACCTTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 844
    label "AGGGGCATGCCCCTGTTTGAACACGGTACCGTGTGGGCCTAC"
  ]
  node [
    id 845
    label "TCCCCGGTTGGGGAGTC--GACCCTGCGCAGGCCGGGCCCGG"
  ]
  node [
    id 846
    label "AGGTCAATTGACCTGCTCGAGCTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 847
    label "GACCTG--CGGGTCGCGCGCGCTCTGATCAGAGCGTGCATGT"
  ]
  node [
    id 848
    label "TCCCGG--TCGGGAGCT--AGCTCTGCGCAGGCCAGGCCTGG"
  ]
  node [
    id 849
    label "TCCCTGGTCGGGGAGTCCGGATCCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 850
    label "ACGGGCGCGCCCGTGCTCGAGCGCGGTACCGCGCAGGCCTGC"
  ]
  node [
    id 851
    label "GACCTCGCGGGGTCGCGCGCGTTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 852
    label "GCTCTG--CAGGGCGCC--GGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 853
    label "AGGGATGCATCCCTGCTCGAGTTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 854
    label "AGGAGTGCACTCCTGCTCGAGCCCGGTACCGGGTAGGCCTAC"
  ]
  node [
    id 855
    label "AGGGGCGCGCCCCTGTTCGAGCCCGGTACCGGGGGAGCTCTC"
  ]
  node [
    id 856
    label "AGGGGTATACCCCTGCTCGAGTGTGGTACCATCTAGGCCTAG"
  ]
  node [
    id 857
    label "AGGGGATATCCCCTGTCATGATGGAGTACTTTGGGAGCTCTC"
  ]
  node [
    id 858
    label "GGCCCG--TGGGTTGCCTAGGCTCAGCGCTGGGTGGGCCCAC"
  ]
  node [
    id 859
    label "TCCCTG--CAGGGAGTC--GACCTTGCGCAAGCCAGGCCTGG"
  ]
  node [
    id 860
    label "AGGAGTGCACTCCTGCTCGAGCCCAGTACTGGATAGGCCTAT"
  ]
  node [
    id 861
    label "AGGAGCGCGCTCCTGCTCGAGTTCGGTACCGAGTAGGCCTAT"
  ]
  node [
    id 862
    label "AGGGGCGCGCCCCTGTTCGAACTCGGTACCGAGTGGGCCTGC"
  ]
  node [
    id 863
    label "AGGGGCGCGCCCCTGCTCGAGCACGGTACCGTGCGTGCGCGT"
  ]
  node [
    id 864
    label "AGGTCAGCTGACCTGTTCGAGCTTGGTACCAAGGGGGCCCTC"
  ]
  node [
    id 865
    label "TCCCTGGTCAGGGAGTC--GATTCTGCGCAGGACTGGCCAGT"
  ]
  node [
    id 866
    label "TCCTTGGTCAGGGAGTC--GACCTGCATGCAGCCGGGCCTGG"
  ]
  node [
    id 867
    label "GGGCCTCGGGGCTCGCGCGCGCTTCGATCGAAATCCGCGGGT"
  ]
  node [
    id 868
    label "AGGCCAGCTGGCCTGCTCGAGTTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 869
    label "GGGGGTATGCCCCCAGT--ACTCTGGTACCAGGGAGGCCTTC"
  ]
  node [
    id 870
    label "AGGGGTATGCCCCTGTTTAAACGAGGTACCTCGTGGGCCTAC"
  ]
  node [
    id 871
    label "GCGTCAGCTGGCGCGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 872
    label "GATTCCGCGGGATCGCGCGCGCTCTGATCAGAGCGTGCACGT"
  ]
  node [
    id 873
    label "GGCCCTATGGGGTCGCGCGCGCTTCGATCGAAATCCGCGGGT"
  ]
  node [
    id 874
    label "ACGCTCTAGAGCGTGTTCGAACTGGGTACCCAGTAGGCCTAC"
  ]
  node [
    id 875
    label "AGGGCAATTGCCCTGTTCGAACTCGGTACCGAGGGGGCCCTC"
  ]
  node [
    id 876
    label "TCCCTGGTCAGGGAGTC--GATCCTGCGCAGGCCGGGCCTGG"
  ]
  node [
    id 877
    label "AGGGGTGCACCCCTGTTCGAACACGGTACCGTGTGGGCCTGT"
  ]
  node [
    id 878
    label "GGGGGA--TCCCCCGTTTAAACTTGGTACCAATGAGGCCTTG"
  ]
  node [
    id 879
    label "TCCCTGATCAGGGAGTC--GACCTTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 880
    label "TCCCTGGTCAGGGAGCCCGGGCCTGTGCGCAGCTGGGCCTGG"
  ]
  node [
    id 881
    label "AAGGGCGCGCCCTTATTCGAATTCGGTACCGAAAGAGCTCTT"
  ]
  node [
    id 882
    label "GACTCCTAGGGGTCGCGCGCGCTTCGATCGAAATCCGCGGGT"
  ]
  node [
    id 883
    label "AGGGGTATACCCTTGTTCGAACTCGGATCCGAGTGGGCCTGC"
  ]
  node [
    id 884
    label "TCCCTGGTCAGGGAGTCCGGACCCTGCGCAGGCTGGGCCTGG"
  ]
  node [
    id 885
    label "AGGGGTGCACCCCTGTTCGAACTCGGTACCGGAGGAGCTCTT"
  ]
  node [
    id 886
    label "TCTCTG--CAGGGAGCT--AGCTCTACGTGGGTTGGGCCCAG"
  ]
  node [
    id 887
    label "ACGGGTGCGCCCGTGCTCGAGCGCGGTACCGCGGGGGCCCTC"
  ]
  node [
    id 888
    label "TCCTGG--TCAGGAGCT--AGCTCTGCGCAGACCGGGCCTGG"
  ]
  edge [
    source 0
    target 324
  ]
  edge [
    source 2
    target 500
  ]
  edge [
    source 3
    target 247
  ]
  edge [
    source 3
    target 138
  ]
  edge [
    source 5
    target 323
  ]
  edge [
    source 16
    target 240
  ]
  edge [
    source 16
    target 214
  ]
  edge [
    source 17
    target 285
  ]
  edge [
    source 18
    target 884
  ]
  edge [
    source 21
    target 771
  ]
  edge [
    source 27
    target 522
  ]
  edge [
    source 28
    target 778
  ]
  edge [
    source 35
    target 193
  ]
  edge [
    source 39
    target 47
  ]
  edge [
    source 42
    target 139
  ]
  edge [
    source 42
    target 331
  ]
  edge [
    source 42
    target 373
  ]
  edge [
    source 43
    target 528
  ]
  edge [
    source 44
    target 599
  ]
  edge [
    source 45
    target 688
  ]
  edge [
    source 45
    target 583
  ]
  edge [
    source 46
    target 331
  ]
  edge [
    source 50
    target 300
  ]
  edge [
    source 50
    target 760
  ]
  edge [
    source 50
    target 783
  ]
  edge [
    source 51
    target 486
  ]
  edge [
    source 51
    target 99
  ]
  edge [
    source 51
    target 843
  ]
  edge [
    source 51
    target 376
  ]
  edge [
    source 52
    target 295
  ]
  edge [
    source 52
    target 760
  ]
  edge [
    source 52
    target 220
  ]
  edge [
    source 58
    target 215
  ]
  edge [
    source 60
    target 789
  ]
  edge [
    source 61
    target 576
  ]
  edge [
    source 61
    target 833
  ]
  edge [
    source 62
    target 579
  ]
  edge [
    source 64
    target 805
  ]
  edge [
    source 64
    target 242
  ]
  edge [
    source 65
    target 702
  ]
  edge [
    source 65
    target 722
  ]
  edge [
    source 66
    target 646
  ]
  edge [
    source 67
    target 486
  ]
  edge [
    source 67
    target 127
  ]
  edge [
    source 67
    target 507
  ]
  edge [
    source 67
    target 806
  ]
  edge [
    source 70
    target 269
  ]
  edge [
    source 74
    target 466
  ]
  edge [
    source 74
    target 376
  ]
  edge [
    source 76
    target 645
  ]
  edge [
    source 78
    target 576
  ]
  edge [
    source 78
    target 592
  ]
  edge [
    source 78
    target 833
  ]
  edge [
    source 80
    target 351
  ]
  edge [
    source 81
    target 677
  ]
  edge [
    source 81
    target 548
  ]
  edge [
    source 82
    target 757
  ]
  edge [
    source 85
    target 825
  ]
  edge [
    source 86
    target 652
  ]
  edge [
    source 88
    target 725
  ]
  edge [
    source 94
    target 576
  ]
  edge [
    source 94
    target 325
  ]
  edge [
    source 96
    target 156
  ]
  edge [
    source 99
    target 189
  ]
  edge [
    source 99
    target 378
  ]
  edge [
    source 102
    target 281
  ]
  edge [
    source 106
    target 482
  ]
  edge [
    source 110
    target 547
  ]
  edge [
    source 110
    target 116
  ]
  edge [
    source 110
    target 430
  ]
  edge [
    source 110
    target 120
  ]
  edge [
    source 110
    target 343
  ]
  edge [
    source 111
    target 700
  ]
  edge [
    source 116
    target 205
  ]
  edge [
    source 116
    target 393
  ]
  edge [
    source 117
    target 190
  ]
  edge [
    source 117
    target 657
  ]
  edge [
    source 123
    target 359
  ]
  edge [
    source 123
    target 718
  ]
  edge [
    source 123
    target 433
  ]
  edge [
    source 123
    target 700
  ]
  edge [
    source 132
    target 497
  ]
  edge [
    source 132
    target 766
  ]
  edge [
    source 132
    target 267
  ]
  edge [
    source 133
    target 317
  ]
  edge [
    source 136
    target 230
  ]
  edge [
    source 138
    target 884
  ]
  edge [
    source 139
    target 482
  ]
  edge [
    source 140
    target 278
  ]
  edge [
    source 142
    target 840
  ]
  edge [
    source 143
    target 697
  ]
  edge [
    source 143
    target 367
  ]
  edge [
    source 145
    target 381
  ]
  edge [
    source 145
    target 486
  ]
  edge [
    source 146
    target 246
  ]
  edge [
    source 151
    target 158
  ]
  edge [
    source 151
    target 204
  ]
  edge [
    source 151
    target 197
  ]
  edge [
    source 151
    target 704
  ]
  edge [
    source 156
    target 209
  ]
  edge [
    source 156
    target 643
  ]
  edge [
    source 156
    target 785
  ]
  edge [
    source 158
    target 659
  ]
  edge [
    source 158
    target 868
  ]
  edge [
    source 159
    target 442
  ]
  edge [
    source 162
    target 438
  ]
  edge [
    source 162
    target 813
  ]
  edge [
    source 164
    target 423
  ]
  edge [
    source 164
    target 180
  ]
  edge [
    source 164
    target 247
  ]
  edge [
    source 174
    target 771
  ]
  edge [
    source 177
    target 404
  ]
  edge [
    source 181
    target 486
  ]
  edge [
    source 181
    target 603
  ]
  edge [
    source 182
    target 216
  ]
  edge [
    source 182
    target 745
  ]
  edge [
    source 183
    target 444
  ]
  edge [
    source 187
    target 365
  ]
  edge [
    source 189
    target 376
  ]
  edge [
    source 189
    target 333
  ]
  edge [
    source 189
    target 585
  ]
  edge [
    source 191
    target 610
  ]
  edge [
    source 192
    target 874
  ]
  edge [
    source 197
    target 659
  ]
  edge [
    source 197
    target 726
  ]
  edge [
    source 200
    target 265
  ]
  edge [
    source 204
    target 347
  ]
  edge [
    source 206
    target 583
  ]
  edge [
    source 209
    target 787
  ]
  edge [
    source 209
    target 859
  ]
  edge [
    source 217
    target 638
  ]
  edge [
    source 219
    target 762
  ]
  edge [
    source 220
    target 486
  ]
  edge [
    source 220
    target 773
  ]
  edge [
    source 220
    target 876
  ]
  edge [
    source 220
    target 806
  ]
  edge [
    source 222
    target 486
  ]
  edge [
    source 222
    target 448
  ]
  edge [
    source 223
    target 319
  ]
  edge [
    source 225
    target 505
  ]
  edge [
    source 226
    target 482
  ]
  edge [
    source 228
    target 407
  ]
  edge [
    source 229
    target 486
  ]
  edge [
    source 234
    target 408
  ]
  edge [
    source 241
    target 326
  ]
  edge [
    source 241
    target 477
  ]
  edge [
    source 241
    target 833
  ]
  edge [
    source 241
    target 760
  ]
  edge [
    source 246
    target 452
  ]
  edge [
    source 247
    target 884
  ]
  edge [
    source 249
    target 751
  ]
  edge [
    source 249
    target 260
  ]
  edge [
    source 256
    target 378
  ]
  edge [
    source 256
    target 833
  ]
  edge [
    source 257
    target 300
  ]
  edge [
    source 257
    target 833
  ]
  edge [
    source 260
    target 573
  ]
  edge [
    source 266
    target 671
  ]
  edge [
    source 268
    target 793
  ]
  edge [
    source 270
    target 410
  ]
  edge [
    source 273
    target 360
  ]
  edge [
    source 276
    target 561
  ]
  edge [
    source 277
    target 422
  ]
  edge [
    source 278
    target 591
  ]
  edge [
    source 278
    target 362
  ]
  edge [
    source 279
    target 682
  ]
  edge [
    source 280
    target 384
  ]
  edge [
    source 281
    target 431
  ]
  edge [
    source 283
    target 287
  ]
  edge [
    source 288
    target 659
  ]
  edge [
    source 293
    target 486
  ]
  edge [
    source 293
    target 626
  ]
  edge [
    source 297
    target 636
  ]
  edge [
    source 297
    target 371
  ]
  edge [
    source 297
    target 566
  ]
  edge [
    source 300
    target 486
  ]
  edge [
    source 301
    target 825
  ]
  edge [
    source 302
    target 450
  ]
  edge [
    source 304
    target 883
  ]
  edge [
    source 306
    target 877
  ]
  edge [
    source 307
    target 486
  ]
  edge [
    source 307
    target 448
  ]
  edge [
    source 307
    target 818
  ]
  edge [
    source 308
    target 817
  ]
  edge [
    source 308
    target 408
  ]
  edge [
    source 309
    target 592
  ]
  edge [
    source 309
    target 760
  ]
  edge [
    source 315
    target 433
  ]
  edge [
    source 317
    target 706
  ]
  edge [
    source 318
    target 444
  ]
  edge [
    source 319
    target 442
  ]
  edge [
    source 326
    target 340
  ]
  edge [
    source 329
    target 786
  ]
  edge [
    source 331
    target 482
  ]
  edge [
    source 331
    target 543
  ]
  edge [
    source 333
    target 779
  ]
  edge [
    source 340
    target 591
  ]
  edge [
    source 340
    target 833
  ]
  edge [
    source 343
    target 393
  ]
  edge [
    source 344
    target 500
  ]
  edge [
    source 347
    target 704
  ]
  edge [
    source 350
    target 624
  ]
  edge [
    source 351
    target 762
  ]
  edge [
    source 359
    target 635
  ]
  edge [
    source 362
    target 486
  ]
  edge [
    source 362
    target 603
  ]
  edge [
    source 364
    target 757
  ]
  edge [
    source 373
    target 543
  ]
  edge [
    source 375
    target 494
  ]
  edge [
    source 376
    target 714
  ]
  edge [
    source 376
    target 633
  ]
  edge [
    source 376
    target 779
  ]
  edge [
    source 377
    target 595
  ]
  edge [
    source 378
    target 486
  ]
  edge [
    source 384
    target 657
  ]
  edge [
    source 385
    target 606
  ]
  edge [
    source 386
    target 673
  ]
  edge [
    source 392
    target 645
  ]
  edge [
    source 394
    target 756
  ]
  edge [
    source 400
    target 699
  ]
  edge [
    source 403
    target 664
  ]
  edge [
    source 404
    target 733
  ]
  edge [
    source 404
    target 808
  ]
  edge [
    source 407
    target 598
  ]
  edge [
    source 409
    target 623
  ]
  edge [
    source 419
    target 809
  ]
  edge [
    source 419
    target 700
  ]
  edge [
    source 421
    target 583
  ]
  edge [
    source 422
    target 735
  ]
  edge [
    source 431
    target 888
  ]
  edge [
    source 433
    target 618
  ]
  edge [
    source 443
    target 760
  ]
  edge [
    source 444
    target 844
  ]
  edge [
    source 451
    target 461
  ]
  edge [
    source 451
    target 644
  ]
  edge [
    source 456
    target 761
  ]
  edge [
    source 458
    target 517
  ]
  edge [
    source 461
    target 812
  ]
  edge [
    source 461
    target 708
  ]
  edge [
    source 463
    target 562
  ]
  edge [
    source 465
    target 641
  ]
  edge [
    source 465
    target 694
  ]
  edge [
    source 466
    target 714
  ]
  edge [
    source 477
    target 686
  ]
  edge [
    source 477
    target 793
  ]
  edge [
    source 478
    target 522
  ]
  edge [
    source 482
    target 647
  ]
  edge [
    source 486
    target 546
  ]
  edge [
    source 486
    target 833
  ]
  edge [
    source 486
    target 760
  ]
  edge [
    source 486
    target 591
  ]
  edge [
    source 486
    target 592
  ]
  edge [
    source 498
    target 791
  ]
  edge [
    source 498
    target 817
  ]
  edge [
    source 506
    target 786
  ]
  edge [
    source 507
    target 833
  ]
  edge [
    source 513
    target 607
  ]
  edge [
    source 520
    target 730
  ]
  edge [
    source 522
    target 714
  ]
  edge [
    source 543
    target 718
  ]
  edge [
    source 543
    target 700
  ]
  edge [
    source 546
    target 773
  ]
  edge [
    source 549
    target 844
  ]
  edge [
    source 551
    target 682
  ]
  edge [
    source 552
    target 812
  ]
  edge [
    source 552
    target 708
  ]
  edge [
    source 560
    target 713
  ]
  edge [
    source 562
    target 684
  ]
  edge [
    source 572
    target 596
  ]
  edge [
    source 577
    target 654
  ]
  edge [
    source 579
    target 596
  ]
  edge [
    source 585
    target 633
  ]
  edge [
    source 593
    target 611
  ]
  edge [
    source 596
    target 766
  ]
  edge [
    source 600
    target 635
  ]
  edge [
    source 604
    target 716
  ]
  edge [
    source 626
    target 823
  ]
  edge [
    source 626
    target 833
  ]
  edge [
    source 627
    target 657
  ]
  edge [
    source 628
    target 842
  ]
  edge [
    source 635
    target 809
  ]
  edge [
    source 635
    target 700
  ]
  edge [
    source 641
    target 838
  ]
  edge [
    source 641
    target 696
  ]
  edge [
    source 646
    target 663
  ]
  edge [
    source 652
    target 697
  ]
  edge [
    source 686
    target 739
  ]
  edge [
    source 687
    target 859
  ]
  edge [
    source 700
    target 811
  ]
  edge [
    source 700
    target 851
  ]
  edge [
    source 700
    target 708
  ]
  edge [
    source 704
    target 726
  ]
  edge [
    source 705
    target 884
  ]
  edge [
    source 711
    target 851
  ]
  edge [
    source 714
    target 843
  ]
  edge [
    source 724
    target 751
  ]
  edge [
    source 725
    target 767
  ]
  edge [
    source 730
    target 816
  ]
  edge [
    source 738
    target 795
  ]
  edge [
    source 744
    target 800
  ]
  edge [
    source 747
    target 822
  ]
  edge [
    source 751
    target 756
  ]
  edge [
    source 757
    target 764
  ]
  edge [
    source 760
    target 793
  ]
  edge [
    source 760
    target 843
  ]
  edge [
    source 766
    target 828
  ]
  edge [
    source 767
    target 855
  ]
  edge [
    source 779
    target 781
  ]
  edge [
    source 804
    target 855
  ]
  edge [
    source 833
    target 876
  ]
]
